### ISSUE TITLE
on mac os x 10.11: bad formated local forwarding specification

### ISSUE THREAD

**Issue by axmue** [sequelpro/sequelpro#2215] opened 2015-09-03 10:18 UTC
sequel pro 1.0.2, build 4096
on mac os x 10.11 el capitano beta

The parameter of the -L option looks like 12345/127.0.0.1/3306 instead of 12345:127.0.0.1:3306

**Comment by dmoagx** [comment] 2015-09-03 13:04
Duplicate of #2050 
This has already been fixed since 1.1rc1: http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/
Please search for existing issues, before creating a new one.

**Closed by dmoagx** 2015-09-03 13:04 UTC
