### ISSUE TITLE
Bug after trying to export data to an invalid filename

### ISSUE THREAD

**Issue by Erin-Boehmer** [sequelpro/sequelpro#2531] opened 2016-07-10 22:31 UTC
I am trying to export data from a query. Within the export data dialog, I selected the correct folder to export the data to, but accidentally pasted the entire query into the filename text box and hit "export" before I realized the filename was wrong. When trying to redo the export, I enter the correct filename into the box (my_intended_filename.csv), but still get a popup box saying "[my really long sql code] my_intended_filename.csv could not be created". I cannot find a way to reset the default export filename which is now set to the really long query text and which is preventing me from exporting any data. I have uninstalled Sequel Pro and reinstalled several times and have deleted the sequel pro files in ~/Library/Application Settings, ~/Library/Preferences and ~/Library/Applications but I don't know where this default export filename is being stored.

<img width="510" alt="screen shot 2016-07-11 at 12 57 18 am" src="https://cloud.githubusercontent.com/assets/3460589/16716493/7d42f812-4706-11e6-9527-c571b79c21ad.png">

**Comment by dmoagx** [comment] 2016-07-10 22:36
Click on the triangle, put the cursor in the custom filename field, press cmd+A, press delete.
Duplicate of #2325

**Closed by dmoagx** 2016-07-10 22:36 UTC
