### ISSUE TITLE
unexpected close

### ISSUE THREAD

**Issue by lorenzobattelli** [sequelpro/sequelpro#3435] opened 2019-03-31 17:00 UTC
every time I normally close sequel pro by clicking Red Cross button in the upper left angle of the window, a message which tells me that "an error occurred, Sequel pro has closed  unexpectedly, send a comment to Apple" always appears
<img width="999" alt="Schermata 2019-03-31 alle 18 59 48" src="https://user-images.githubusercontent.com/26606040/55292131-339d2c00-53e7-11e9-849d-2cad9d739fce.png">
.

**Comment by dmoagx** [comment] 2019-03-31 17:10
Duplicate of #3116

**Closed by dmoagx** 2019-03-31 17:10 UTC
