### ISSUE TITLE
high CPU

### ISSUE THREAD

**Issue by al404** [sequelpro/sequelpro#2017] opened 2014-11-12 11:52 UTC
with 10.10 upgrade sequel pro some times gets stuck with 99% cpu usage
on this upgrade i switch from OS X system apache / mysql to MAMP pro

not sure if CPU usage is due to 10.10 or MAMP 
but sequel pro get unusable i need to force exit

**Comment by alexdrag** [comment] 2015-01-02 12:56
I have similar problems with several tables - CPU goes to 99%.

https://gist.github.com/alexdrag/485de934ae65e7fbed36

**Comment by alexdrag** [comment] 2015-01-02 12:59
Btw I tried with stable version and with Nightly build of SequalPro. And I didn't have this problems on Mountain lion, just on Yosemite. Also I installed MySql using brew (http://brew.sh)

**Comment by alexdrag** [comment] 2015-01-27 22:11
I've updated SequalPro to the latest Nightly Build, and I do not have issues anymore.

**Comment by ischemic** [comment] 2015-01-29 14:30
I've just had this again adding fields to a table.

Sample here: https://gist.github.com/anonymous/7f58478e7da5c67fc8a0

**Comment by messageagency** [comment] 2015-02-05 20:08
Here's another sample during adding a column: 
https://gist.github.com/messageagency/56cc14895b748590c1e0

Clicked the "+" button on fields list.
Existing table with about 25 fields, and about 1000 rows.
Database with 2 tables total.
Localhost connection.
CPU still redlined at 100% as i'm writing this.

**Comment by dmoagx** [comment] 2015-02-05 22:10
I believe you, but there isn't much I can do.
The samples are not really helpful for this issue (to me at least).

What we really need is some way to reliably reproduce this (I've not yet been able to personally).

**Comment by lucascepeda** [comment] 2015-11-24 09:49
Got here because I had a similar problem, with high CPU times using Sequel Pro 1.1. 
It got even high CPU times right after starting it, before connecting to a database.

The problem was the huge dumps on the query history. **Clearing the query history** solved the problem, and working with the dumped database (+500MB) works like a charm, again.

Just in case this solves someone else's problem!

**Comment by lalop** [comment] 2017-12-14 19:17
I have the same issue, @lucascepeda  how did you clear the query history ?

**Comment by lucascepeda** [comment] 2017-12-15 08:59
@lalop Go to "Query" (icon tab) -> "Query History" (dropwdown) -> "Clear Global History".

I hope that helps!

**Comment by lalop** [comment] 2017-12-15 09:49
@lucascepeda this helps a lot :)

**Comment by dmoagx** [comment] 2018-10-14 17:53
I'll close this.
Apart from the large query history (which is already discussed in other issues) we have not been able to identify any problem.

**Closed by dmoagx** 2018-10-14 17:53 UTC
Labels: OSXVersion-10.10, WaitingOnUser
