### ISSUE TITLE
Crashes when adding Schema Privileges

### ISSUE THREAD

**Issue by yaykyle** [sequelpro/sequelpro#2167] opened 2015-07-06 14:46 UTC
Sequel Pro consistently crashes for me when I am trying to add assign schema privileges to a new user on a new db.

I'm running Sequel Pro v1.0.2, Build 4096 on OS X v10.10.4 (14E46)

Steps to Reproduce:

1. Connect over SSH to MySQL (5.5.43-0ubuntu0.12.04.1)
2. Select "Choose Database..." > "Add Database..."
3. Add a new Database, choosing UTF-8 from "Database Encoding"
4. Select Database > User Accounts...
5. Click the Plus (+) to add a new user.
6. Enter a Username and Password.
7. Click Schema Privileges
8. Select the new database from Schemas.
9. Double-click alter, create, delete, drop, index, insert, select, update.
10. Click Apply and Sequel Pro will crash.

**Comment by dmoagx** [comment] 2015-07-06 18:18
Duplicate of #1961.
This is already fixed in 1.1rc1 http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/
Please search for existing issues before creating a new one!

**Closed by dmoagx** 2015-07-06 18:18 UTC

**Comment by yaykyle** [comment] 2015-07-06 18:36
Apologies, I searched but didn't see it!
