### ISSUE TITLE
I tried to create a table called procedures in a hospital_pricing database and I get an NSInvalidArgumentException

### ISSUE THREAD

**Issue by andytriboletti** [sequelpro/sequelpro#3448] opened 2019-04-13 16:45 UTC
I created a database and tried to login. I tried various names for the database and tables.

I get this error consistently:

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6000003149e0

(
	0   CoreFoundation                      0x00007fff37471cf9 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff62005a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff374ebb06 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff374140ef ___forwarding___ + 1485
	4   CoreFoundation                      0x00007fff37413a98 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff3960787e __NSThread__start__ + 1194
	8   libsystem_pthread.dylib             0x00007fff63a212eb _pthread_body + 126
	9   libsystem_pthread.dylib             0x00007fff63a24249 _pthread_start + 66
	10  libsystem_pthread.dylib             0x00007fff63a2040d thread_start + 13
)

Has anyone else experienced this error?

**Comment by dmoagx** [comment] 2019-04-13 19:12
Invalid issue description.

Duplicate of #2699 anyway...

**Closed by dmoagx** 2019-04-13 19:12 UTC
