### ISSUE TITLE
Follow foreign key not working

### ISSUE THREAD

**Issue by henros** [sequelpro/sequelpro#3353] opened 2019-01-11 13:31 UTC
- Sequel Pro Version: 
![image](https://user-images.githubusercontent.com/1159305/51036069-510ee680-15ac-11e9-9ca0-e5b0bd059520.png)

- macOS Version:
![image](https://user-images.githubusercontent.com/1159305/51036091-5c621200-15ac-11e9-9643-6b9f369cc638.png)

- MySQL Version:
5.6.35

**Description**
In old versions like 1.1.1 and 1.1.2 you can click the arraw and follow foreign key that bring you to that table and filter out the selected id. In lastest build this does not work. This might be old news and might be same as #3335 but as this happens in Content view as well I report it as new issue.

In version 1.1.1 (and 1.1.2 but I left that one waiting for a more stable version)
1. 
![image](https://user-images.githubusercontent.com/1159305/51036303-ffb32700-15ac-11e9-8166-b03ef977892b.png)
Take me here
![image](https://user-images.githubusercontent.com/1159305/51036340-16597e00-15ad-11e9-9173-05673d82f197.png)

on version 16180f9d3c
![image](https://user-images.githubusercontent.com/1159305/51036432-62a4be00-15ad-11e9-80e4-9af40dd317fd.png)

reloads the entire target table without filter
![image](https://user-images.githubusercontent.com/1159305/51036473-849e4080-15ad-11e9-9cb9-b667f11e61bb.png)

**Comment by dmoagx** [comment] 2019-01-11 20:56
Duplicate of #2792

**Closed by dmoagx** 2019-01-11 20:56 UTC

**Comment by dmoagx** [comment] 2019-01-11 20:58
Duplicate of #2792
