### ISSUE TITLE
Language problems

### ISSUE THREAD

**Issue by OlofT** [sequelpro/sequelpro#2312] opened 2015-10-29 10:53 UTC
It should be possible to turn off internationalizations.

Most terms in computer science and databases are in English. Translating to my language can sometimes be confusing where I first need to guess what the translator have been thinking. Especially when there are no good translations available. E.g. "ejaculators" are very confusing, but when you realize that the English term is "triggers", you understand what the translator is aiming for. Another example is "question" and "query", two different words in English but perhaps not in many other languages.

I would say that the translations overall have a high quality, but this problem just can't be solved, so there should be an option to turn it off.

(This is perhaps more of an opinion than a bug-report).

**Comment by dmoagx** [comment] 2015-10-29 11:04
http://apple.stackexchange.com/questions/245/is-it-possible-to-launch-a-program-in-a-specific-language

Duplicate of #1106

**Closed by dmoagx** 2015-10-29 11:04 UTC
