### ISSUE TITLE
[REQ] Auto save session

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1797] opened 2013-11-09 05:49 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1797
Reporter:m.jason....@gmail.com Date:2013-08-30 15:40:25 Status:New

Set Sequel Pro to automatically save a session periodically and upon program quit.  When Sequel Pro closes (either normally or abnormally), all queries in progress are lost.  I have gotten into the habit of occasionally saving, but it'd be nice to have this happen automatically in the background so that when the program is re-launched it can ask if you want to restore the previous session, or start with a blank one.

**Comment by anunigam** [comment] 2015-05-15 20:19
I agree on this.  This is really important.  I would pay money for this!!

**Comment by abhibeckert** [comment] 2015-05-15 21:41
dupe of #2006

**Closed by abhibeckert** 2015-05-15 21:41 UTC
Labels: Enhancement
