### ISSUE TITLE
mac pro 10.13.1 (17B1003)保存连接信息报错

### ISSUE THREAD

**Issue by 594349525** [sequelpro/sequelpro#3102] opened 2018-07-03 09:53 UTC
An error occured while trying to add the password to your Keychain. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -25293.

**Comment by dmoagx** [comment] 2018-07-06 20:29
Duplicate of #2900

**Closed by dmoagx** 2018-07-06 20:29 UTC
