### ISSUE TITLE
Cannot Edit Stored Procedures or Functions

### ISSUE THREAD

**Issue by ryanbarsatan** [sequelpro/sequelpro#2650] opened 2017-01-07 03:31 UTC
Hi, I'm not sure if I just can't find the option or what, but It seems like you are not able to edit stored procedures or functions. This seems like a pretty pivotal function to have been left out of such a great client.

**Comment by stuconnolly** [comment] 2017-01-07 11:37
Duplicate of #2612

**Closed by stuconnolly** 2017-01-07 11:37 UTC
Labels: Duplicate
