### ISSUE TITLE
404s for screenshots in your documentation

### ISSUE THREAD

**Issue by pixelverbieger** [sequelpro/sequelpro#3012] opened 2018-03-21 09:16 UTC
a lot of (or all?) articles listed in
https://sequelpro.com/docs/ref/core-features
show 404 errors for the screenshots

**Comment by stuconnolly** [comment] 2018-10-10 19:45
Duplicate of #3019 

Realise this was raised just before, but 3019 has a little more info.

**Closed by stuconnolly** 2018-10-10 19:45 UTC
Labels: Bug, Duplicate, Website
