### ISSUE TITLE
Tables Window "Flips" Upside Down (Sceenshots Attached)

### ISSUE THREAD

**Issue by mvabl-steve** [sequelpro/sequelpro#3361] opened 2019-01-22 16:23 UTC
- Sequel Pro Version: Nightly Build 5426
- macOS Version: Mojave
- MySQL Version: 5.7

**Description**
The table listing flips upside down when I switch from connection tab to connection tab

**Steps To Reproduce**
I haven't firmly established what recreates this behavior. But I have noticed:
1. When I have more than one SQL connection, if I execute an operation in one tab, then switch to another tab, I get the "flip"
2. If I refresh the table list, it corrects.
3. I have *not* noticed any other issues connected to this. It's just an annoyance.

**Expected Behaviour**
N/A

**Additional Context**
N/A
![screen shot 2019-01-22 at 9 34 55 am](https://user-images.githubusercontent.com/1252882/51549318-2e948d00-1e38-11e9-96ee-1c8a6b8fb129.png)

**Comment by dmoagx** [comment] 2019-01-22 20:41
Duplicate of #3214

**Closed by dmoagx** 2019-01-22 20:41 UTC
