### ISSUE TITLE
Crash on clicking User

### ISSUE THREAD

**Issue by marcohanke** [sequelpro/sequelpro#3133] opened 2018-08-12 13:32 UTC
Everytime i click on the user Button SequalPro crashes.
If i close the Feedback Window and click again, the User-Window opens, i can add a user, but there are no permissions/rights to add to the user/db. So i actually cant add users ...

```
NSUnknownKeyException

[<NSManagedObject 0x600000492cf0> setValue:forUndefinedKey:]: the entity Privileges is not key value coding-compliant for the key "Delete_history_priv".

(
	0   CoreFoundation                      0x00007fff27efe2db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff4f09fc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff27efe229 -[NSException raise] + 9
	3   Sequel Pro                          0x00000001000ba81d -[SPUserManager _initializeSchemaPrivsForChild:fromData:] + 941
	4   Sequel Pro                          0x00000001000b9dfb -[SPUserManager _initializeTree:] + 1213
	5   Sequel Pro                          0x00000001000b962e -[SPUserManager _initializeUsers] + 208
	6   Sequel Pro                          0x00000001000b94af -[SPUserManager windowDidLoad] + 312
	7   AppKit                              0x00007fff2547ee8c -[NSWindowController _windowDidLoad] + 547
	8   AppKit                              0x00007fff25422d0f -[NSWindowController window] + 110
	9   Sequel Pro                          0x00000001000bab0d -[SPUserManager beginSheetModalForWindow:completionHandler:] + 68
	10  Sequel Pro                          0x0000000100036d45 -[SPDatabaseDocument showUserManager:] + 306
	11  AppKit                              0x00007fff256fe13c -[NSToolbarButton sendAction:to:] + 75
	12  AppKit                              0x00007fff25649097 -[NSToolbarItemViewer mouseDown:] + 5197
	13  AppKit                              0x00007fff25d4ad6d -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5891
	14  AppKit                              0x00007fff25d479c4 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2359
	15  AppKit                              0x00007fff25d46c70 -[NSWindow(NSEventRouting) sendEvent:] + 497
	16  Sequel Pro                          0x000000010012e644 -[SPWindow sendEvent:] + 783
	17  AppKit                              0x00007fff25ba8236 -[NSApplication(NSEvent) sendEvent:] + 2462
	18  AppKit                              0x00007fff254088b5 -[NSApplication run] + 812
	19  AppKit                              0x00007fff253d7a72 NSApplicationMain + 804
	20  Sequel Pro                          0x0000000100002454 start + 52
	21  ???                                 0x0000000000000001 0x0 + 1
)
```

Connected via Socket as root with a password
OSX 10.13.6
Sequal Pro 1.1.2
mysql  Ver 15.1 Distrib 10.3.8-MariaDB, for osx10.13 (x86_64) using readline 5.1

**Comment by dmoagx** [comment] 2018-08-30 21:31
Duplicate of #2982

**Closed by dmoagx** 2018-08-30 21:31 UTC
