### ISSUE TITLE
encountered an unexpected error

### ISSUE THREAD

**Issue by crazydhw** [sequelpro/sequelpro#3150] opened 2018-09-04 03:07 UTC
NSInvalidArgumentException
```
-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x1008650a0

(
	0   CoreFoundation                      0x00007fff8f62b03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8f05e76e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8f62e0ad -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff8f573d44 ___forwarding___ + 1028
	4   CoreFoundation                      0x00007fff8f5738b8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
	7   Foundation                          0x00007fff8ed8eda0 __NSThreadPerformPerform + 293
	8   CoreFoundation                      0x00007fff8f547821 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff8f5399ad __CFRunLoopDoSources0 + 269
	10  CoreFoundation                      0x00007fff8f538fdf __CFRunLoopRun + 927
	11  CoreFoundation                      0x00007fff8f5389f8 CFRunLoopRunSpecific + 296
	12  HIToolbox                           0x00007fff9237256f RunCurrentEventLoopInMode + 235
	13  HIToolbox                           0x00007fff923722ea ReceiveNextEventCommon + 431
	14  HIToolbox                           0x00007fff9237212b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	15  AppKit                              0x00007fff964df8ab _DPSNextEvent + 978
	16  AppKit                              0x00007fff964dee58 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	17  AppKit                              0x00007fff964d4af3 -[NSApplication run] + 594
	18  AppKit                              0x00007fff96451244 NSApplicationMain + 1832
	19  Sequel Pro                          0x0000000100002454 start + 52
)
```

**Comment by lowercase00** [comment] 2018-09-05 23:32
I'm not sure if it is the name root cause, by I have a similar error which is preventing me to use the software. Important to say that this is the second computer that I work on - same error. Both with newly created databases. I can use the software for a while, but can't say why, it just breaks.

`NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000003e2c0

(
	0   CoreFoundation                      0x00007fff359a432b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5d006c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff35a3ce04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff3591a870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff3591a238 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff37a1c1f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff5df38661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff5df3850d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff5df37bf9 thread_start + 13
)
`

**Comment by dmoagx** [comment] 2018-09-06 20:07
Duplicate of #2699

**Closed by dmoagx** 2018-09-06 20:07 UTC
