### ISSUE TITLE
Crash connecting to LocalHost

### ISSUE THREAD

**Issue by dexterslu** [sequelpro/sequelpro#2345] opened 2015-12-03 02:13 UTC
Connecting to localhost causing SQL Pro to immediately crash. Here is the exception it's showing. 
   <pre><code> Dec 2, 2015, 9:07:01 PM: assertion failed: 15C48a: libxpc.dylib + 63930 [61AB4610-9304-354C-9E9B-D57198AE9866]: 0x89
Dec 2, 2015, 9:07:01 PM: An uncaught exception was raised
Dec 2, 2015, 9:07:01 PM: Invalid parameter not satisfying: aString != nil
Dec 2, 2015, 9:07:01 PM: (
	0   CoreFoundation                      0x00007fff95b4dae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff99e75f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff95b4d8ba +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fffa029488c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   AppKit                              0x00007fff9aeb860c -[NSCell _objectValue:forString:errorDescription:] + 180
	5   AppKit                              0x00007fff9aeb8428 -[NSCell setStringValue:] + 41
	6   AppKit                              0x00007fff9afe84d6 -[NSControl setStringValue:] + 135
	7   Sequel Pro                          0x0000000100050e61 -[SPDataImport importFile] + 119
	8   Sequel Pro                          0x0000000100041ec6 -[SPDatabaseDocument import:] + 30
	9   Sequel Pro                          0x0000000100108cd0 -[SPWindowController performSelector:withObject:] + 197
	10  libsystem_trace.dylib               0x00007fff9cd0a07a _os_activity_initiate + 75
	11  AppKit                              0x00007fff9b0a551d -[NSApplication sendAction:to:from:] + 460
	12  AppKit                              0x00007fff9b0a52b7 -[NSMenuItem _corePerformAction] + 336
	13  AppKit                              0x00007fff9b0a5017 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	14  libsystem_trace.dylib               0x00007fff9cd0a07a _os_activity_initiate + 75
	15  AppKit                              0x00007fff9b1651f0 -[NSMenu performActionForItemAtIndex:] + 131
	16  AppKit                              0x00007fff9b165163 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
	17  AppKit                              0x00007fff9b164fbb -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
	18  AppKit                              0x00007fff9b08dea1 NSSLMMenuEventHandler + 708
	19  HIToolbox                           0x00007fff9685e7be _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1231
	20  HIToolbox                           0x00007fff9685dc48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
	21  HIToolbox                           0x00007fff968739e6 SendEventToEventTarget + 40
	22  HIToolbox                           0x00007fff968bd99a _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
	23  HIToolbox                           0x00007fff968e8d5b SendMenuCommandWithContextAndModifiers + 59
	24  HIToolbox                           0x00007fff968e8d0c SendMenuItemSelectedEvent + 188
	25  HIToolbox                           0x00007fff968e8be8 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	26  HIToolbox                           0x00007fff968e9596 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 711
	27  HIToolbox                           0x00007fff968e9230 _HandleMenuSelection2 + 460
	28  AppKit                              0x00007fff9afb875e _NSHandleCarbonMenuEvent + 277
	29  AppKit                              0x00007fff9aef8435 _DPSNextEvent + 1906
	30  AppKit                              0x00007fff9b2c4943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	31  AppKit                              0x00007fff9aeedfc8 -[NSApplication run] + 682
	32  AppKit                              0x00007fff9ae70520 NSApplicationMain + 1176
	33  Sequel Pro                          0x0000000100002084 start + 52
	34  ???                                 0x0000000000000002 0x0 + 2
)
Dec 2, 2015, 9:07:01 PM: Found 0 crash files earlier than latest submission on 2015-12-03 01:53:34 +0000
Dec 2, 2015, 9:07:05 PM: *** Assertion failure in -[NSComboBoxCell _objectValue:forString:errorDescription:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1404.34/AppKit.subproj/NSCell.m:1684
Dec 2, 2015, 9:07:05 PM: An uncaught exception was raised
Dec 2, 2015, 9:07:05 PM: Invalid parameter not satisfying: aString != nil
Dec 2, 2015, 9:07:05 PM: (
	0   CoreFoundation                      0x00007fff95b4dae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff99e75f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff95b4d8ba +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x00007fffa029488c -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   AppKit                              0x00007fff9aeb860c -[NSCell _objectValue:forString:errorDescription:] + 180
	5   AppKit                              0x00007fff9aeb8428 -[NSCell setStringValue:] + 41
	6   AppKit                              0x00007fff9afe84d6 -[NSControl setStringValue:] + 135
	7   Sequel Pro                          0x0000000100050e61 -[SPDataImport importFile] + 119
	8   Sequel Pro                          0x0000000100041ec6 -[SPDatabaseDocument import:] + 30
	9   Sequel Pro                          0x0000000100108cd0 -[SPWindowController performSelector:withObject:] + 197
	10  libsystem_trace.dylib               0x00007fff9cd0a07a _os_activity_initiate + 75
	11  AppKit                              0x00007fff9b0a551d -[NSApplication sendAction:to:from:] + 460
	12  AppKit                              0x00007fff9b0a52b7 -[NSMenuItem _corePerformAction] + 336
	13  AppKit                              0x00007fff9b0a5017 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	14  libsystem_trace.dylib               0x00007fff9cd0a07a _os_activity_initiate + 75
	15  AppKit                              0x00007fff9b1651f0 -[NSMenu performActionForItemAtIndex:] + 131
	16  AppKit                              0x00007fff9b165163 -[NSMenu _internalPerformActionForItemAtIndex:] + 35
	17  AppKit                              0x00007fff9b164fbb -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
	18  AppKit                              0x00007fff9b08dea1 NSSLMMenuEventHandler + 708
	19  HIToolbox                           0x00007fff9685e7be _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1231
	20  HIToolbox                           0x00007fff9685dc48 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 404
	21  HIToolbox                           0x00007fff968739e6 SendEventToEventTarget + 40
	22  HIToolbox                           0x00007fff968bd99a _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
	23  HIToolbox                           0x00007fff968e8d5b SendMenuCommandWithContextAndModifiers + 59
	24  HIToolbox                           0x00007fff968e8d0c SendMenuItemSelectedEvent + 188
	25  HIToolbox                           0x00007fff968e8be8 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	26  HIToolbox                           0x00007fff968e9596 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 711
	27  HIToolbox                           0x00007fff968e9230 _HandleMenuSelection2 + 460
	28  AppKit                              0x00007fff9afb875e _NSHandleCarbonMenuEvent + 277
	29  AppKit                              0x00007fff9aef8435 _DPSNextEvent + 1906
	30  AppKit                              0x00007fff9b2c4943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	31  AppKit                              0x00007fff9aeedfc8 -[NSApplication run] + 682
	32  AppKit                              0x00007fff9ae70520 NSApplicationMain + 1176
	33  Sequel Pro                          0x0000000100002084 start + 52
	34  ???                                 0x0000000000000002 0x0 + 2
)
Dec 2, 2015, 9:07:05 PM: Found 0 crash files earlier than latest submission on 2015-12-03 01:53:34 +0000
Dec 2, 2015, 9:11:23 PM: *** -[NSPlaceholderString initWithString:]: nil argument
Dec 2, 2015, 9:11:23 PM: (
	0   CoreFoundation                      0x00007fff95b4dae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff99e75f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff95b4d98d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fffa020fd4a -[NSPlaceholderString initWithString:] + 96
	4   Sequel Pro                          0x000000010002e6a9 -[SPDatabaseDocument setConnection:] + 384
	5   Foundation                          0x00007fffa025fd4b __NSThreadPerformPerform + 279
	6   CoreFoundation                      0x00007fff95a5d5c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x00007fff95a4f41c __CFRunLoopDoSources0 + 556
	8   CoreFoundation                      0x00007fff95a4e93f __CFRunLoopRun + 927
	9   CoreFoundation                      0x00007fff95a4e338 CFRunLoopRunSpecific + 296
	10  HIToolbox                           0x00007fff96886935 RunCurrentEventLoopInMode + 235
	11  HIToolbox                           0x00007fff9688676f ReceiveNextEventCommon + 432
	12  HIToolbox                           0x00007fff968865af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	13  AppKit                              0x00007fff9aef80ee _DPSNextEvent + 1067
	14  AppKit                              0x00007fff9b2c4943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	15  AppKit                              0x00007fff9aeedfc8 -[NSApplication run] + 682
	16  AppKit                              0x00007fff9ae70520 NSApplicationMain + 1176
	17  Sequel Pro                          0x0000000100001994 start + 52
	18  ???                                 0x0000000000000002 0x0 + 2</pre></code>

**Comment by dmoagx** [comment] 2015-12-03 09:47
Duplicate of #2302

**Closed by dmoagx** 2015-12-03 09:47 UTC
