### ISSUE TITLE
Feature Request: Color / highlight app window in bookmark color

### ISSUE THREAD

**Issue by mgrn0** [sequelpro/sequelpro#2133] opened 2015-06-10 12:10 UTC
I often have multiple windows open and sometimes (rarely, but happens) I catch myself almost dumping a production server database instead of the local testing environment.

I love the way I can color/highlight bookmarks already (see attached screenshot), would it be possible to color the whole app window or title bar in the appropriate color (or color a thick border on e.g. top of the window) if I gave a bookmark a color? 

![screen shot 2015-01-21 at 10 15 12 am](https://cloud.githubusercontent.com/assets/3019226/8082027/588d388a-0f7a-11e5-9e85-d6f5a83f232d.png)

E.g. color a bookmark blue, then color the whole window blue if opened?
This way I could easily see that I am on e.g. the production server or not..

Does this make sense / is my explanation clear?

**Comment by dmoagx** [comment] 2015-06-10 12:17
View > Show Tab bar?

**Comment by mgrn0** [comment] 2015-06-10 13:33
uh, thanks. I was not aware of that since I always open a new window for different connections. Thanks!

**Comment by dmoagx** [comment] 2015-06-10 18:20
Duplicate of #346

**Closed by dmoagx** 2015-06-10 18:20 UTC
Labels: WaitingOnUser
