### ISSUE TITLE
CMD + W is closing the whole app on MacOS Mojave

### ISSUE THREAD

**Issue by mkwsra** [sequelpro/sequelpro#3210] opened 2018-10-07 11:43 UTC
When pressing the combination `cmd` + `w` the whole app is being closed, instead, the logical behavior says _the current tab should be closed_ 

I believe it's something related to the new MacOS.

THANKS for this great app!

**Comment by stuconnolly** [comment] 2018-10-07 12:01
Duplicate of #3116

**Closed by stuconnolly** 2018-10-07 12:01 UTC
Labels: Duplicate
