### ISSUE TITLE
Version 1.0.2 when MySQL host == ssh Host will try to connect to 127.0.0.1 first and return error on failure

### ISSUE THREAD

**Issue by nilsmeyer** [sequelpro/sequelpro#2107] opened 2015-04-29 11:25 UTC
We have a database server with a rather peculiar setup, in my.cnf we set:
bind-address=192.0.2.15 

With sequel pro 1.0.1 setting MySQL Host to 192.0.2.15 and SSH Host to the same the connection works. Sequel Pro 1.0.2 instead tries to connect to 127.0.0.1:3306 instead of the Host specified in the MySQL Host field.

**Comment by dmoagx** [comment] 2015-04-29 15:50
There have been no relevant changes to that part of the tunneling code since at least 0.9.6.
I doubt 1.0.2 is the cause of your problem.

* There is some code that seems strange to me, concerning connections with ssh host == mysql host, though.

**Comment by rowanbeentje** [comment] 2015-04-29 16:06
If the ssh host is the same as the mysql host, I think we also try 127.0.0.1 (I forget which is tried first), because we had a lot of user problems that tunnelling wasn't working which turned out to be because mysql was only listening on 127.0.0.1.  We should always try the specified hostname though.

**Comment by nilsmeyer** [comment] 2015-04-29 16:30
That would be the most likely explanation. I have just tried it with SSH to a different host and the connection works. It seems that not only is 127.0.0.1 tried first when ssh host == mysql host, if an error occurs it will also not try to connect to the next host (haven't looked at the actual code) which matches with my experience. 

I think it's reasonable for a user to expect not to be second guessed, so the order should be to try the MySQL Host as specified and to try 127.0.0.1 in case it doesn't work, possibly showing a warning.

**Comment by dmoagx** [comment] 2015-04-29 17:38
>  it will also not try to connect to the next host (haven't looked at the actual code) which matches with my experience.

It will try to connect to the other host (just verified that).
And since you have given no clear indication what "doesn't allow connecting" means to you (i.e. **the actual error message**) there is nothing we can investigate.

**Comment by nilsmeyer** [comment] 2015-04-30 00:39
The actual error message is ' Lost connection to MySQL server at 'reading initial communication packet' which I presume is returned by the MySQL client library. I would also at this point ask for forgiveness for my lack of decorum and precision in describing my problem. 

To reiterate this only happens when I connect to a ssh host that's equal to the MySQL host with the MySQL process itself not listening on tcp/127.0.0.1:3306 (bind-address for multiple hosts has been a long-standing feature request from November 2005).  

It works doing ssh -L 3306:192.168.0.2.1:3306 manually, as well it works using MySQL workbench.

**Comment by dmoagx** [comment] 2015-04-30 16:16
After thinking about it a bit, I think the issue is a race condition.
Namely there is this code in SPConnectionHandler.m which decides if the fallback host is tried:
```objc
	if (![mySQLConnection isConnected]) {
		if (sshTunnel && !cancellingConnection) {
			//...
			if ([sshTunnel state] == SPMySQLProxyForwardingFailed) {
				if ([sshTunnel localPortFallback]) {
```

And there is this code in SPSSHTunnel.m:
```objc
			if ([message rangeOfString:@"connect failed: Connection refused" ].location != NSNotFound) {
				// ...
				connectionState = SPMySQLProxyForwardingFailed;
```

Basically during my tests the first snippet was usually called a few µs before the one actually setting it (both are on different threads) and therefore fails to try the fallback host.

**Comment by dmoagx** [comment] 2015-05-01 00:16
I'm confident that my change in 80a2088 will fix your problem, and if it does not, you should now at least get a "Show Details" button on the error dialog, which we need to further investigate.

**Comment by Toflar** [comment] 2016-05-17 14:13
I think this is still not fixed, at least I run in a similar issue.

When I do the process manually (connect via SSH, then type `myslq -h 10.xx.xx.xxx .....`) it works fine. When I try to connect using Sequel Pro, it does not. Sequel Pro tells me it could not connect to server 10.xx.xx.xxx and the mysql error message is `Can't connect to MySQL server on '127.0.0.1' (4)` so it seems to try to connect to 127.0.0.1 even though I specified 10.xx.xx.xxx. Any idea what I might be doing wrong here?

**Comment by dmoagx** [comment] 2016-07-31 19:39
Closing after no feedback from user.

@Toflar When using SSH the MySQL connection will always be to "127.0.0.1". That is how SSH port forwarding works. You should create a new issue.

**Closed by dmoagx** 2016-07-31 19:39 UTC
Labels: Bug, WaitingOnUser
