### ISSUE TITLE
Complete Database/table search

### ISSUE THREAD

**Issue by Nemo64** [sequelpro/sequelpro#2960] opened 2018-01-04 10:18 UTC
I'd really like a feature where sequel would just iterate over every table and every field and would search a specific value in them. I know that that will be slow etc but sometimes I don't care, I have many messy databases which don't have proper relations (richtext fields etc) and i sometimes need to search for an id or even words when a customer tells me that some word is wrong without any context.

**Comment by dmoagx** [comment] 2018-01-04 19:02
Duplicate of #1294

**Closed by dmoagx** 2018-01-04 19:02 UTC
