### ISSUE TITLE
[NEW FEATURE] Pinned tables

### ISSUE THREAD

**Issue by pingcheng** [sequelpro/sequelpro#3199] opened 2018-10-03 01:51 UTC
Hi, could we have a new feature to pin some tables for a quick switch?

Sometimes we need to switch among several tables to compare data, it is a little inconvenient by search table name every time.

BTW, thanks for building such a beautiful app for Mac mysql client!!!

**Comment by stuconnolly** [comment] 2018-10-03 12:45
Duplicate of #1391

**Closed by stuconnolly** 2018-10-03 12:45 UTC
Labels: Duplicate, Enhancement
