### ISSUE TITLE
can not connect to mysql 8.0 installed by homebrew~

### ISSUE THREAD

**Issue by YSMull** [sequelpro/sequelpro#3089] opened 2018-06-19 02:27 UTC
even with the test builds

**Comment by venjiang** [comment] 2018-06-19 07:07
I have same problem.

**Comment by kookan107** [comment] 2018-06-19 07:53
Me too@

**Comment by loranger** [comment] 2018-06-19 08:02
Since homebrew upgrade updated mysql to 8.0, there should be a massive _me too_ wave incoming 🤔 
Here is an issue to follow-up: #2699

**Comment by dmoagx** [comment] 2018-06-19 17:43
Duplicate of #2699, #3037

**Closed by dmoagx** 2018-06-19 17:43 UTC
