### ISSUE TITLE
can't load database after switch database

### ISSUE THREAD

**Issue by RRRRonny** [sequelpro/sequelpro#3155] opened 2018-09-10 08:30 UTC
After check the database “sys”,sequel pro can’t load any database.
And i use *hibernate* to create a new table in database A; After the operation done ,switch to another database for database source reload.
here is the exception

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000022a5a0

(
	0   CoreFoundation                      0x00007fff4bafc2db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff72c99c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4bb94db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff4ba72820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff4ba721e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff4db811f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff73bcb661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff73bcb50d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff73bcabf9 thread_start + 13
)
```

**Comment by dmoagx** [comment] 2018-09-10 08:35
Duplicate of #2699

**Closed by dmoagx** 2018-09-10 08:35 UTC
