### ISSUE TITLE
Cannot have empty values for "Escape" in "Fields" for exporting

### ISSUE THREAD

**Issue by PomegranateApps** [sequelpro/sequelpro#2813] opened 2017-06-04 20:44 UTC
I would like to be able to export results as CSV without escaping fields but when I try to have an empty value for "Escape" it doesn't work. It shows the "Exporting CSV" dialog without any progress.

**Comment by dmoagx** [comment] 2017-06-04 20:48
Duplicate of #1498

**Closed by dmoagx** 2017-06-04 20:48 UTC

**Comment by kevohagan** [comment] 2017-06-24 18:13
+1 on this
