### ISSUE TITLE
Tables In Sidebar Turned Upside Down

### ISSUE THREAD

**Issue by lyndonjohn** [sequelpro/sequelpro#3265] opened 2018-10-31 06:31 UTC
Table list in sidebar turned upside down.

1. I opened sequel pro and view it in full screen. (going fullscreen freezes the app for a few seconds)
2. I swipe to the left to view or switch apps
3. Swiped back to sequel pro and the list of tables turned upside down.

Note: It doesn't always happen, it only happens randomly.

I'm using **Sequel Pro Nightly Build**
**Build 5418 (78067124)**

My OS is **macOS Mojave version 10.14.1 (18B75)**

![screen shot 2018-10-31 at 2 22 44 pm](https://user-images.githubusercontent.com/29518229/47770112-1d485280-dd19-11e8-98c2-cbcb76949570.png)

**Comment by jpike88** [comment] 2018-10-31 07:43
I see this issue as well.

**Comment by Kraddle** [comment] 2018-10-31 09:59
Me too ;)

**Comment by Jewhurst** [comment] 2018-10-31 17:59
Same, and it switches the language as well. Then switches back. Was coming here to post the same thing

**Comment by jbrooksuk** [comment] 2018-11-02 12:19
Duplicate of https://github.com/sequelpro/sequelpro/issues/3214

**Closed** 2018-11-02 18:05 UTC

**Comment by rscoates** [comment] 2018-11-13 15:13
+1
