### ISSUE TITLE
SSH connexion bug after internet reconnexion

### ISSUE THREAD

**Issue by thsantac** [sequelpro/sequelpro#3043] opened 2018-05-03 09:20 UTC
Hi, 

I have an annoying bug : 
- I connect to a database via SSH,
- SequelPro ask for root@ip-address,
- I enter the password and everything is OK.

If I change my internet connexion (new Wifi network) while the database is still displayed in Sequel and if I want to display the content of a table, Sequel is asking me the password for root@ip-address again.

The problem is :  the spinning colored wheel appears and I cannot enter the password.

**Comment by dmoagx** [comment] 2018-05-03 18:09
Duplicate of #2503 

We are well aware of this issue but it's a very deep architectural problem in Sequel Pro.

**Closed by dmoagx** 2018-05-03 18:09 UTC
