### ISSUE TITLE
[REQ] Compare Schema from two connection tabs

### ISSUE THREAD

**Issue by neokio** [sequelpro/sequelpro#2635] opened 2016-12-20 13:52 UTC
I tend to develop locally with MAMP, updating regularly to a staging server for client review. I constantly modify/refine the db schema. But since the staging server is often being tested by clients, I have to wait until I'm ready to update the staging server to also update the schema. So I make note of what I've changed on the local db, and upon update (several times a day), make those same changes to the staging server db.

The current process:

1. Read my notes, and apply changes to the staging server.
2. View the table structure for the first table (in a local connection tab)
3. View the table structure for the first table (in a staging server connection tab)
4. Do a kind of back-and-forth dance (via CMD-OPTION-left/right arrow) between the two connection tabs, until I'm relatively sure they're identical (resizing the columns to make it easier)
5. Select the next table down in each tab
6. Lather, rinse, repeat steps 4+5 until done

Rather than taking notes (which are a significant distraction from my "heat of the moment" coding) and doing this awkward back-and-forth schema at-a-glance visual spot checking, I'd love a "Schema Comparison" tool. Something that takes the schema of every table in one connection, and DIFFs it with every table schema from another connection.

This would let me quickly compare local and staging databases, and immediately catch discrepancies.

**Comment by abhibeckert** [comment] 2016-12-22 20:53
Duplicate of #72

We're working on this.

In the mean time, I suggest exporting both databases as SQL with only structure, no content, then use FileMerge to compare the two files.

**Closed by abhibeckert** 2016-12-22 20:53 UTC
