### ISSUE TITLE
mysql 8.0 crashed

### ISSUE THREAD

**Issue by lechie** [sequelpro/sequelpro#3138] opened 2018-08-20 07:38 UTC
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60c00003a4e0

(
	0   CoreFoundation                      0x00007fff2ae262db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff51fd0c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2aebedb4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff2ad9c820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff2ad9c1e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff2ceab1f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff52f02661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff52f0250d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff52f01bf9 thread_start + 13
)

**Comment by andycaramba** [comment] 2018-08-20 13:06
The same issue with mysql8 in docker container.
```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6040000276c0

(
	0   CoreFoundation                      0x00007fff2d7582db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff548f9c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2d7f0db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff2d6ce820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff2d6ce1e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x00000001000f3681 -[SPWindowController performSelector:withObject:] + 172
	7   AppKit                              0x00007fff2b405a43 -[NSApplication(NSResponder) sendAction:to:from:] + 312
	8   AppKit                              0x00007fff2ae9a213 -[NSMenuItem _corePerformAction] + 323
	9   AppKit                              0x00007fff2ae99f9b -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	10  AppKit                              0x00007fff2af1fc7a -[NSMenu performActionForItemAtIndex:] + 133
	11  AppKit                              0x00007fff2af1fbe5 -[NSMenu _internalPerformActionForItemAtIndex:] + 94
	12  AppKit                              0x00007fff2af1fa15 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 106
	13  AppKit                              0x00007fff2ade62a2 NSSLMMenuEventHandler + 882
	14  HIToolbox                           0x00007fff2c995904 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1541
	15  HIToolbox                           0x00007fff2c994c4d _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 374
	16  HIToolbox                           0x00007fff2c9a9f21 SendEventToEventTarget + 39
	17  HIToolbox                           0x00007fff2c9f33f9 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
	18  HIToolbox                           0x00007fff2ca1c2ee SendMenuCommandWithContextAndModifiers + 49
	19  HIToolbox                           0x00007fff2ca1c2aa SendMenuItemSelectedEvent + 188
	20  HIToolbox                           0x00007fff2ca1c184 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	21  HIToolbox                           0x00007fff2cb3487c _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 1662
	22  HIToolbox                           0x00007fff2cb33cf7 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 409
	23  HIToolbox                           0x00007fff2c9fc40c _HandlePopUpMenuSelectionWithDictionary + 268
	24  AppKit                              0x00007fff2af1679a _NSSLMPopUpCarbonMenu3 + 5632
	25  AppKit                              0x00007fff2af150f4 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 439
	26  AppKit                              0x00007fff2af8525c -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 570
	27  AppKit                              0x00007fff2aea8670 -[NSControl mouseDown:] + 965
	28  AppKit                              0x00007fff2b5a4d6d -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5891
	29  AppKit                              0x00007fff2b5a19c4 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2359
	30  AppKit                              0x00007fff2b5a0c70 -[NSWindow(NSEventRouting) sendEvent:] + 497
	31  Sequel Pro                          0x000000010012e644 -[SPWindow sendEvent:] + 783
	32  AppKit                              0x00007fff2b402236 -[NSApplication(NSEvent) sendEvent:] + 2462
	33  AppKit                              0x00007fff2ac628b5 -[NSApplication run] + 812
	34  AppKit                              0x00007fff2ac31a72 NSApplicationMain + 804
	35  Sequel Pro                          0x0000000100002454 start + 52
)
```

**Comment by dmoagx** [comment] 2018-08-20 18:36
Duplicate of #2699

**Closed by dmoagx** 2018-08-20 18:36 UTC

**Comment by firstsko** [comment] 2019-07-28 15:53
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6000003c1400

(
	0   CoreFoundation                      0x00007fff3ee752fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff69546a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3eeef106 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff3ee1718f ___forwarding___ + 1485
	4   CoreFoundation                      0x00007fff3ee16b38 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
	7   Foundation                          0x00007fff410b6742 __NSThreadPerformPerform + 328
	8   CoreFoundation                      0x00007fff3eddb683 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff3eddb629 __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff3edbefeb __CFRunLoopDoSources0 + 195
	11  CoreFoundation                      0x00007fff3edbe5b5 __CFRunLoopRun + 1189
	12  CoreFoundation                      0x00007fff3edbdebe CFRunLoopRunSpecific + 455
	13  HIToolbox                           0x00007fff3e01d1ab RunCurrentEventLoopInMode + 292
	14  HIToolbox                           0x00007fff3e01cee5 ReceiveNextEventCommon + 603
	15  HIToolbox                           0x00007fff3e01cc76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff3c3b579d _DPSNextEvent + 1135
	17  AppKit                              0x00007fff3c3b448b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
	18  AppKit                              0x00007fff3c3ae5a8 -[NSApplication run] + 699
	19  AppKit                              0x00007fff3c39dae8 NSApplicationMain + 777
	20  Sequel Pro                          0x0000000100002454 start + 52
)

same crash in Mysql8.0

**Comment by Jeffrey-Lang** [comment] 2019-08-07 10:34
Same issue here
Macbook Pro 2019  Homebrew mysql 8.0.17
OSX: 10.14.6

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6000002e2660

(
	0   CoreFoundation                      0x00007fff42aea2fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6d1b7a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff42b64106 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff42a8c18f ___forwarding___ + 1485
	4   CoreFoundation                      0x00007fff42a8bb38 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff44c8d5c2 __NSThread__start__ + 1194
	8   libsystem_pthread.dylib             0x00007fff6eb792eb _pthread_body + 126
	9   libsystem_pthread.dylib             0x00007fff6eb7c249 _pthread_start + 66
	10  libsystem_pthread.dylib             0x00007fff6eb7840d thread_start + 13
)

**Comment by tbredin** [comment] 2019-10-15 01:27
Bump .. just noting that the duplicate issue has been open for about 2 years now ... I've found myself there countless times
