### ISSUE TITLE
Compatibility for mojave

### ISSUE THREAD

**Issue by ccdilan** [sequelpro/sequelpro#3241] opened 2018-10-17 07:32 UTC
<img width="1112" alt="screen shot 2018-10-17 at 12 52 20 pm" src="https://user-images.githubusercontent.com/17356380/47069130-c9634700-d20b-11e8-8c27-788c4859892c.png">

The above error is occur when closing a tab in sequel pro and when closing application. This will be happen after updating mac os high sierra in to mojave.

And mojave give a new look  introducing DarkMode in to users.All most all the applications support for this and it is good, if there is a Darkmode in Sequel Pro.

**Comment by steffen25** [comment] 2018-10-17 08:05
Same issue here.

**Comment by DaveLo** [comment] 2018-10-17 15:37
I think this is a duplicate of #3116

**Comment by dmoagx** [comment] 2018-10-17 20:12
https://github.com/sequelpro/sequelpro/issues/3242#issuecomment-430770392

**Closed by dmoagx** 2018-10-17 20:12 UTC
