### ISSUE TITLE
SequelPro crashes when closing tabs on macOS Mojave 10.14

### ISSUE THREAD

**Issue by feisar-uk** [sequelpro/sequelpro#3201] opened 2018-10-03 07:22 UTC
Crash log attached
[Sequel Pro_2018-10-03-081732_Mac-mini.txt](https://github.com/sequelpro/sequelpro/files/2441012/Sequel.Pro_2018-10-03-081732_Mac-mini.txt)

**Comment by phpanos** [comment] 2018-10-03 07:43
I have the same issue.

**Comment by feisar-uk** [comment] 2018-10-03 08:44
Sorry, didn't see existing report here: 
https://github.com/sequelpro/sequelpro/issues/3116

**Comment by stuconnolly** [comment] 2018-10-03 12:40
Duplicate of #3116

**Closed by stuconnolly** 2018-10-03 12:40 UTC

**Comment by yadgen** [comment] 2018-12-09 06:30
Me, too.

**Comment by octante** [comment] 2019-02-04 11:35
+1

**Comment by bannostookaylo** [comment] 2019-09-16 17:03
This keeps happening to me as well... replacing what software I use today... sorry SequelPro

**Comment by bannostookaylo** [comment] 2019-09-16 17:08
Well I deleted my previous comment on here because I saw this was a duplicate issue... BUT that other issue is closed to new comments... I am still having a crashing issue every time I close a tab.

**Comment by bannostookaylo** [comment] 2019-09-16 17:10
Looks like using https://github.com/sequelpro/sequelpro/files/2506508/Sequel.Pro-2.zip solved my issue
