### ISSUE TITLE
Missing error pane when Query is the default view

### ISSUE THREAD

**Issue by gboudreau** [sequelpro/sequelpro#3081] opened 2018-06-12 11:32 UTC
Happens on latest HEAD on master (89f756e60808011e556f2bb2d0952b62b97a3617).

- Settings > General > Default View: Query
- Close SequelPro completely
- Re-open it
- Execute a query with an error (`SELECT potatoes FROM garden`, or something)

Problem: the error pane at the bottom of the query view is not visible.
<img width="1157" alt="first" src="https://user-images.githubusercontent.com/370329/41287907-4fe148bc-6e12-11e8-9756-784eadb8354c.png">

If I do `Show Tab Bar` multiple times, the Error pane appears more and more each time, but the textFields are not correctly placed:
<img width="1131" alt="after show tab bar" src="https://user-images.githubusercontent.com/370329/41287961-8e11aed8-6e12-11e8-9e98-08742adaa03e.png">
<img width="1148" alt="after show tab bar hidden" src="https://user-images.githubusercontent.com/370329/41287962-92329a2c-6e12-11e8-9c01-b7628acfc773.png">

The problem is not occurring if the Default View is NOT Query:
- Settings > General > Default View: Structure
- Close SequelPro completely
- Re-open it
- Go to query view
- Execute a query

Error appears.

<img width="1130" alt="ok" src="https://user-images.githubusercontent.com/370329/41287974-a43ded5c-6e12-11e8-8bfb-cff9f36f0392.png">

**Comment by gboudreau** [comment] 2018-06-12 11:33
Oops, forgot to mention, this occurs on the latest master, not in 1.1.2

**Comment by dmoagx** [comment] 2018-06-12 18:21
Duplicate of #2799 

I can't reproduce this with the steps given.
However "Show/Hide Tab Bar" is an interesting point. There is something wonky going on with that since it causes some views to grow beyond their maximum size...

**Closed by dmoagx** 2018-06-12 18:21 UTC

**Comment by gboudreau** [comment] 2018-06-13 01:13
This is indeed related to the new tabs. I did a git bisect, and found this commit to be when this regression was introduced:
```
92ee758b8c2d75782ed4b83ac56068606ef5b27a is the first bad commit
commit 92ee758b8c2d75782ed4b83ac56068606ef5b27a
Author: Abhi Beckert <abhi@abhibeckert.com>
Date:   Fri Mar 18 16:48:10 2016 +1000

    #346 Work on new tab bar design
```

I'll try to dig further, see what I can understand from what was changed, and how it affected the error pane. If you have some ideas/pointers, they would be most welcome.
