### ISSUE TITLE
Sequel Pro Crash when opening the database

### ISSUE THREAD

**Issue by gongmingqm10** [sequelpro/sequelpro#3154] opened 2018-09-09 06:30 UTC
Hi, I have been suffered the Sequel Pro crash issue for this month. And the crash info is attached:

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60400022c3c0

(
	0   CoreFoundation                      0x00007fff45f9e2db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6d13fc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff46036db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff45f14820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff45f141e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000576e6 -[SPTablesList updateTables:] + 1291
	6   Sequel Pro                          0x0000000100045e0b -[SPDatabaseDocument _selectDatabaseAndItem:] + 437
	7   Foundation                          0x00007fff480231f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff6e071661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff6e07150d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff6e070bf9 thread_start + 13
)

```

My computer version is `Mac 10.13.6` and the local database version is `8.0.11`. It only crashes when I trying to connect my local database. And if connect it with the remote database which has a lower mysql version, then it works pretty fine.

I have submit this issue for several times when it crashed. But no responding received. Please help us to fix it and make it working again.

Thanks!

**Comment by dmoagx** [comment] 2018-09-09 12:33
Duplicate of #2699

**Closed by dmoagx** 2018-09-09 12:33 UTC

**Comment by rootDEV2990** [comment] 2020-10-13 16:49
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000032bc20

(
	0   CoreFoundation                      0x00007fff37b65be7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff7093d5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff37be4c77 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff37aca44b ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff37ac9e28 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff3a1787a2 __NSThread__start__ + 1064
	8   libsystem_pthread.dylib             0x00007fff71ce9109 _pthread_start + 148
	9   libsystem_pthread.dylib             0x00007fff71ce4b8b thread_start + 15
)
 

same here...

**Comment by ruden91** [comment] 2021-03-02 06:08
If you want to solve this problem, use Sequel Ace!

https://apps.apple.com/us/app/sequel-ace/id1518036000?ls=1

**Comment by omjangir** [comment] 2022-03-26 16:35
Long time, still getting same error in mac os sequal pro 1.1.2 dmg
@dmoagx  :(

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000237820

(
	0   CoreFoundation                      0x00007fff28acbbbb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff4fed9c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff28b64814 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff28a414a0 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff28a40e68 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002f60a -[SPDatabaseDocument setDatabases:] + 782
	6   Sequel Pro                          0x000000010002ebbe -[SPDatabaseDocument setConnection:] + 605
	7   Foundation                          0x00007fff2ab8c955 __NSThreadPerformPerform + 334
	8   CoreFoundation                      0x00007fff28a63691 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff28b1dc8c __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff28a460f0 __CFRunLoopDoSources0 + 208
	11  CoreFoundation                      0x00007fff28a4556d __CFRunLoopRun + 1293
	12  CoreFoundation                      0x00007fff28a44dd3 CFRunLoopRunSpecific + 483
	13  HIToolbox                           0x00007fff27d2fd96 RunCurrentEventLoopInMode + 286
	14  HIToolbox                           0x00007fff27d2fb06 ReceiveNextEventCommon + 613
	15  HIToolbox                           0x00007fff27d2f884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff25fdca3b _DPSNextEvent + 2085
	17  AppKit                              0x00007fff26772e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	18  AppKit                              0x00007fff25fd184d -[NSApplication run] + 764
	19  AppKit                              0x00007fff25fa0a3a NSApplicationMain + 804
	20  Sequel Pro                          0x0000000100002284 start + 52
	21  ???                                 0x0000000000000002 0x0 + 2
)


@

**Comment by JamesVanWaza** [comment] 2022-03-31 18:59
@omjangir use [@SequelAce](https://github.com/Sequel-Ace/Sequel-Ace)

**Comment by omjangir** [comment] 2022-03-31 19:20
sds

**Comment by omjangir** [comment] 2022-03-31 19:21
> @omjangir use [@SequelAce](https://github.com/Sequel-Ace/Sequel-Ace)

This is also giving error..

Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o 


OpenSSH_7.8p1, LibreSSL 2.6.2
debug1: Reading configuration data /Applications/Sequel Ace.app/Contents/Resources/ssh_config
debug1: /Applications/Sequel Ace.app/Contents/Resources/ssh_config line 1: Applying options for *
debug1: Connecting to hidden.com [3.111.X.X] port 22.
debug1: fd 5 clearing O_NONBLOCK
debug1: Connection established.
debug1: identity file /Users/omjangir/ED_TECH_GAME/hidden.pem type -1
debug1: identity file /Users/omjangir/ED_TECH_GAME/hidden.pem-cert type -1
debug1: identity file /Users/omjangir/.keys/id_rsa type -1
debug1: identity file /Users/omjangir/.keys/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.8
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
debug1: match: OpenSSH_8.2p1 Ubuntu-4ubuntu0.3 pat OpenSSH* compat 0x04000000
debug1: Authenticating to decipherworld.com:22 as 'ubuntu'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY

**Comment by CodeSuite** [comment] 2022-07-06 13:35
@ruden91 Thanks man, this is great!

**Comment by wassikhan** [comment] 2023-06-07 06:52
@ruden91 Thanks Bro, that is working...
