### ISSUE TITLE
Feature Request: Sort Columns in Table Structure

### ISSUE THREAD

**Issue by frangrolemund** [sequelpro/sequelpro#3180] opened 2018-09-26 14:04 UTC
Really love your work, but I'm often stymied because I can't sort the columns in the table structure.  Our tables have a ton of columns and it is really painful to scroll that list without a search option.  A sort would be hugely appreciated.

**Comment by dmoagx** [comment] 2018-09-26 20:56
Duplicate of #882

**Closed by dmoagx** 2018-09-26 20:56 UTC
