### ISSUE TITLE
Query editor is REALLY slow depending on which line I am in the code! 

### ISSUE THREAD

**Issue by dubeyq3** [sequelpro/sequelpro#2896] opened 2017-10-13 10:41 UTC
I have a query file which has about 100 lines of code. 
If I edit towards the top of the code, It's taking almost 1 second to type 1 character.

However, (and this is driving me nuts) I can type fine towards the bottom of the code. At line 50 it's taking about half a second per character. 

This is a recent problem. Earlier it used to run just fine. 

I'm on MacOS Sierra 10.12.6 on my 2017 MBP, and using SequelPro 1.1.2

**Comment by dmoagx** [comment] 2018-07-31 20:04
This is a duplicate of either:
a) If you have a Mac with touchbar -> #2783
b) Your query history is too big -> #687

**Closed by dmoagx** 2018-07-31 20:04 UTC
