### ISSUE TITLE
Exporting a view broken in 1.1.2

### ISSUE THREAD

**Issue by joshstrike** [sequelpro/sequelpro#3322] opened 2018-11-30 03:13 UTC
This seems to be a bug that cropped up in the exporter back in 2013
https://github.com/sequelpro/sequelpro/issues/707

But in 1.1.2, I just stumbled across the same thing happening. Views are exported with a CREATE TABLE instead of CREATE VIEW.

**Comment by joshstrike** [comment] 2018-11-30 21:43
Ah, I see. That wasn't the problem with the export Sequel Pro was producing. There was something else. When a view column is the sum of FLOAT(11,2) types, Sequel Pro is rendering it as DOUBLE(19), which MySQL rejects.

This is reproducible: 

```
CREATE TABLE `unit` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `price` float(11,2) NOT NULL DEFAULT '0.00',
  `tax` float(11,2) NOT NULL DEFAULT '0.00',
PRIMARY KEY (`id`)
) ENGINE=MyISAM
```

`CREATE VIEW test AS SELECT unit.id, price AS tot FROM unit;`
_Sequel Pro exports price to the placeholder test table as a float_

`CREATE VIEW test AS SELECT unit.id, price+tax AS tot FROM unit;`
_Sequel Pro exports price as a double_

**Comment by dmoagx** [comment] 2018-12-01 00:10
That is most likely a duplicate of #2927

**Comment by dmoagx** [comment] 2019-01-25 23:34
No reply from reporter for > 1 month, closing.

**Closed by dmoagx** 2019-01-25 23:34 UTC
Labels: WaitingOnUser
