### ISSUE TITLE
Sequel Pro crashes each time I close a tab with an open tunnel connection

### ISSUE THREAD

**Issue by abbatis** [sequelpro/sequelpro#3160] opened 2018-09-12 20:37 UTC
When connected to a database through a tunnel using SSH while having multiple tabs open, close the tab with the open tunnel connection. Sequel Pro will crash.

**Comment by dmoagx** [comment] 2018-09-14 21:27
Duplicate of #3116

**Closed by dmoagx** 2018-09-14 21:27 UTC

**Comment by tiredoy** [comment] 2018-10-23 08:30
https://github.com/sequelpro/sequelpro/issues/3116#issuecomment-432148453
