### ISSUE TITLE
Feature Request: new editing mode: Form Editor (like in MySQL Workbench)

### ISSUE THREAD

**Issue by markusweb** [sequelpro/sequelpro#3165] opened 2018-09-14 10:39 UTC
add an option to edit a row like the "Form Editor" from mySqlWorkbench.

at the moment i can easily edit any field in the table/grid view. my tables have many fields, some text fields. it would be very helpful to have a "Form Editor" view like in MySQL Workbench where i see all the field not in a row but each filed in a single line

![bildschirmfoto 2018-09-14 um 12 42 33](https://user-images.githubusercontent.com/536804/45546319-3ce4f380-b81d-11e8-836d-3c629e91cf90.png)

this shows the Form Editor in MySQL Workbench

at the moment there is only the table or grid view editor

![bildschirmfoto 2018-09-14 um 12 40 37](https://user-images.githubusercontent.com/536804/45545720-73217380-b81b-11e8-9764-c6360018a699.png)

Markus

**Comment by dmoagx** [comment] 2018-09-14 20:57
Duplicate of #1236

**Closed by dmoagx** 2018-09-14 20:57 UTC
