### ISSUE TITLE
Filter search bar moves when scrolling in Query Favourites and Query History

### ISSUE THREAD

**Issue by nexbridge** [sequelpro/sequelpro#2213] opened 2015-08-25 09:16 UTC
![screen shot](https://cloud.githubusercontent.com/assets/13848887/9463077/1a79af28-4b12-11e5-9cd9-a6d834127756.png)

**Comment by dmoagx** [comment] 2015-08-27 15:21
Duplicate of #2079
Please search for existing issues before creating a new one.

**Closed by dmoagx** 2015-08-27 15:21 UTC
