### ISSUE TITLE
Start very slow and very memory

### ISSUE THREAD

**Issue by M-sunary** [sequelpro/sequelpro#2843] opened 2017-07-31 03:07 UTC
My mac pro cannot start the Sequel Pro . Start very slow and very memory.
My mac OS version is 10.12.3 , memory 8G

**Comment by abhibeckert** [comment] 2017-07-31 03:12
This is probably caused by #687.

With Sequel Pro closed, please try making a backup of your preferences file:

`cp ~/Library/Preferences/com.sequelpro.SequelPro.plist ~/Desktop/`

then clear your query history:

`defaults delete com.sequelpro.SequelPro queryHistory`

And see if the problem is fixed. If it's not fixed you should restore the preferences file.

Let us know how you go.

**Comment by dmoagx** [comment] 2018-05-19 22:15
Closing after no feedback from reporter.

**Closed by dmoagx** 2018-05-19 22:15 UTC
Labels: Bug, WaitingOnUser
