### ISSUE TITLE
Auto complete does not bring up contextual completions when triggering with shortcut

### ISSUE THREAD

**Issue by shoan** [sequelpro/sequelpro#2406] opened 2016-02-15 02:58 UTC
I am currently running nightly 4654 and since the last few nightlies the auto complete does not provide any table specific completions. All I am seeing is built-in Mysql functions and the names of the databases. But no table or column names. 

When selecting the database on start, the escape key shows the familiar 'fetching structure...' in the context menu. But later any partial completion attempt results in 'No item found'.

I just checked in the stable build 1.1.0.1. The autocomplete works fine there.

**Comment by dmoagx** [comment] 2016-02-15 04:27
Works fine for me with 4655.
Did you recently update mysql?
Also open Console.app and look for messages from Sequel Pro.

**Comment by phantasma2983** [comment] 2016-02-16 09:26
Hey,

I've been having this same issue for a few months now. I'm on the latest nightly 4656 on OSX. I've recorded the screen so you can better understand what the problem is:
https://www.dropbox.com/s/r311eaox8dj7kzj/SequelPro_autocomplete.mp4?dl=0

Thanks,
Daniel

**Comment by dmoagx** [comment] 2016-02-16 09:35
OK, this seems to be related to the MySQL server version.

**Comment by phantasma2983** [comment] 2016-02-16 09:49
Tested it on localhost on MySQL 5.6.23 and am having the same issues.

**Comment by dmoagx** [comment] 2016-02-16 16:32
OK, then it is probably that it works for the database that is set in the connection dialog.

**Comment by n9yty** [comment] 2016-02-16 17:55
Having the same problem, for what it is worth.  Have been for quite a while.

**Comment by dmoagx** [comment] 2016-02-17 13:51
Please try the new nightly build (efe4c9e1e2).

**Comment by phantasma2983** [comment] 2016-02-17 13:53
Tested it and it seems to work. Great job. Thanks!

**Comment by dmoagx** [comment] 2016-02-20 13:11
Issue fixed in 1.1.1
See http://www.sequelpro.com/blog/2016.02/sequel-pro-1-1-1/

**Closed by dmoagx** 2016-02-20 13:11 UTC
Labels: Bug, Fixed-AwaitingRelease

**Comment by n9yty** [comment] 2016-05-12 15:58
Is this broken again? Auto-complete in the latest nightly release (a00f27fda) doesn't work for me (even with the database name supplied in the connection dialog), but the last release version v1.1.2 does work (even without the database name in the connection dialog).  I hope this isn't just a mistake here, but thought I would re-visit this bug report.

**Comment by dmoagx** [comment] 2016-05-16 19:05
Hm, this seems to be a different new issue. See #2507
