### ISSUE TITLE
Pagination: Jump to first/last page

### ISSUE THREAD

**Issue by dmoagx** [sequelpro/sequelpro#2233] opened 2015-09-18 16:30 UTC
I want to add a quick way to get to the first (last) page of a result set.
Technically this is rather trivial, the question is how to add it to the UI:
- Add two new buttons `|<<` and `>>|` in the pagination area
  - Straight forward, but IMHO the pagination area becomes too crowded
- React on holding down shift/alt? while pressing the back/next buttons
  - Still easy to implement, hard to discover
- React on modifier key + change the button image
  - Rather difficult to implement. Only possible modifier key is "alt" as the other two would generate too much visual noise

**Comment by pschulz** [comment] 2015-10-07 19:29
I'd go with the first option. If you and the other users really think that the pagination area is too crowded, I'd choose the third option. Nevertheless, it is harder to discover than the first option - that's why number two is no option for me...

**Comment by emjayess** [comment] 2017-12-08 23:15
Noting that #1264 is this same request (as imported/migrated from google code repo), so one of these two could be resolved as a duplicate.

**Comment by stuconnolly** [comment] 2018-10-03 16:42
Duplicate of #1264

**Closed by stuconnolly** 2018-10-03 16:42 UTC
Labels: Enhancement, OpinionPoll
