### ISSUE TITLE
Icon inside weird square 

### ISSUE THREAD

**Issue by yooouuri** [sequelpro/sequelpro#2672] opened 2017-01-27 21:12 UTC
Noticed the icon is inside a weird square.

<img width="84" alt="schermafbeelding 2017-01-27 om 22 09 24" src="https://cloud.githubusercontent.com/assets/12934957/22387718/4dab23d4-e4dd-11e6-8cc8-c54b9d868a1d.png">

Sequel pro 1.1.2
Build 4541 (602e11a)
Mac OS 10.12.3 (16D32)

**Comment by dmoagx** [comment] 2017-01-27 21:25
Duplicate of #2623

**Closed by dmoagx** 2017-01-27 21:25 UTC
