### ISSUE TITLE
UI issue - tear off tab to new window changes appearance

### ISSUE THREAD

**Issue by tjchambers** [sequelpro/sequelpro#2540] opened 2016-07-31 14:16 UTC
I am running build 4541 SP 1.1.2 on Latest El Capitan

Reproduce:
- Create a new tab using command-T
- Grab the tab in header and drag it onto desktop to make it a separate window
- Left sidebar formatting is now black background and hardly readable text

b4 drag:

![screenshot_30](https://cloud.githubusercontent.com/assets/103654/17277050/9aa6d8cc-56ee-11e6-9408-c02fec5f6382.png)

after drag

![screenshot_32](https://cloud.githubusercontent.com/assets/103654/17277059/ba50e0a0-56ee-11e6-857a-6ac0eaa8c722.png)

**Comment by dmoagx** [comment] 2016-07-31 17:51
Duplicate of #2286

**Closed by dmoagx** 2016-07-31 17:51 UTC
