### ISSUE TITLE
Failed reconnect closes window, including unsaved query

### ISSUE THREAD

**Issue by mcauser** [sequelpro/sequelpro#2533] opened 2016-07-14 04:38 UTC
Contents of Query tab is lost when a disconnect event occurs with failed reconnect.

Can you keep the connection tab open when disconnected instead of closing it?

**Comment by dmoagx** [comment] 2016-07-19 23:33
Duplicate of #1158 

> Can you keep the connection tab open when disconnected instead of closing it?

No, we can't. Basically all of the other code requires a connection to be active or it would crash.
This will have to be redesigned at some point in the future.

**Closed by dmoagx** 2016-07-19 23:33 UTC

**Comment by mcauser** [comment] 2016-07-20 00:43
How about triggering a Save As dialog before closing it?
