### ISSUE TITLE
App crashes when trying to load a view with invalid definer set in the schema

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1742] opened 2013-11-09 05:46 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1742
Reporter:miracle...@gmail.com Date:2013-06-16 02:35:16 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. Open the target view in the left table browser column
2. Message appears: (attached)
3. App shows the bug report form
4. Cannot send the bug report - after pressing Send the form reloads itself (really quickly so it probably sends nothing) and redisplays itself. The only way to exit from this situation is if you restart the app.
![screen shot 2013-06-16 at 12 34 02](https://cloud.githubusercontent.com/assets/5793864/8681804/eeefcb76-2a69-11e5-93d6-154a355ea6c3.png)

**Comment by boudivv** [comment] 2015-07-14 10:08
It looks you (sequelpro) are doing first the data collection and than get the view_definition al the time.
Then if there is an error in the view_definition the app gets lost.
I suggest when in the 'Table info' view of the app, you don't do a data collection, but only do a get view_definition.
Then you at least can investigate the cause of the error in the view within sequelpro. Now one needs to go to an other tool to do that. Rather annoying.

**Comment by dmoagx** [comment] 2017-02-05 02:32
I can't reproduce this issue at all.
Just deleting a user does not make any of the 3 queries we do when selecting a VIEW (with the query tab open) fail.
I can't reproduce the error shown in the screenshot (which would occur if the query ```SELECT * FROM information_schema.VIEWS AS r WHERE r.TABLE_NAME = '%@' AND r.TABLE_SCHEMA = '%@'``` fails, either (and the message suggests there may be some other f.

Maybe the OP meant to say that they deleted the user they were currently connected with?

Since we have barely any information about this issue and no way to contact the OP I think we should close this issue.

**Comment by stuconnolly** [comment] 2017-03-21 20:39
Agreed, unable to reproduce this. Even dropping the user I'm currently connected with doesn't result in any unusual behaviour, let alone a crash.

**Closed by stuconnolly** 2017-03-21 20:39 UTC
Labels: Bug, OpinionPoll
