### ISSUE TITLE
New MacOS replaces colon to slashes in ssh connection

### ISSUE THREAD

**Issue by theArhar** [sequelpro/sequelpro#2189] opened 2015-07-27 10:28 UTC
I can see clearly the part of code
[taskArguments addObject:[NSString stringWithFormat:@"-L %ld:%@:%ld", (long)localPort, remoteHost, (long)remotePort]];
Interesting thing here is ":" in %ld:%@:%ld
But after connection attempt i can see mesage about suddenly closed ssh tunnel or something like that, it is not important.
Important thing is in debug:
Used command: /usr/bin/ssh -v -N -o ... ... user@ip.ad.dr.es -L 54240/127.0.0.1/3306
Problem here 54230 SLASH 127.0.0.1 SLASH 3306

I think it because MacOS thinks that it is file name
Suggestion:
[taskArguments addObject:[NSString stringWithFormat:@"-L \"%ld:%@:%ld\"", (long)localPort, remoteHost, (long)remotePort]];
(adding double quotes)

**Comment by rowanbeentje** [comment] 2015-07-27 10:31
Hi @theArhar  - this has been fixed in the release candidate available on http://www.sequelpro.com/blog . This is a duplicate of https://github.com/sequelpro/sequelpro/issues/2050.

**Closed by rowanbeentje** 2015-07-27 10:31 UTC
