### ISSUE TITLE
BIT is giving strange 00000000 and 10000000 instead of 0 and 1

### ISSUE THREAD

**Issue by jeroendesloovere** [sequelpro/sequelpro#2778] opened 2017-05-03 15:35 UTC
<img width="989" alt="schermafbeelding 2017-05-03 om 17 33 29" src="https://cloud.githubusercontent.com/assets/588616/25668362/c0719a62-3026-11e7-9eae-96972ad8ae77.png">

We see 00000000 instead of 0 and 10000000 instead of 1:
Note: in phpmyadmin the values are 0 and 1
<img width="87" alt="schermafbeelding 2017-05-03 om 17 33 14" src="https://cloud.githubusercontent.com/assets/588616/25668363/c092e85c-3026-11e7-989d-81b1e360cdca.png">

When trying to change the value to 0, the following error shows up:
<img width="422" alt="schermafbeelding 2017-05-03 om 17 33 08" src="https://cloud.githubusercontent.com/assets/588616/25668364/c09b4286-3026-11e7-962c-9dd75aae1462.png">

<img width="182" alt="schermafbeelding 2017-05-03 om 17 36 24" src="https://cloud.githubusercontent.com/assets/588616/25668476/0b55eefc-3027-11e7-81bb-496998596749.png">

**Comment by dmoagx** [comment] 2017-05-03 20:12
Duplicate of #2254 
This has been fixed a long time ago. You should update to 1.1.2!

**Closed by dmoagx** 2017-05-03 20:12 UTC

**Comment by jeroendesloovere** [comment] 2017-05-04 11:24
Ok, thanks.
Updated SequelPro and the problem is fixed.
