### ISSUE TITLE
Table list displayed mirrored

### ISSUE THREAD

**Issue by xlttj** [sequelpro/sequelpro#3238] opened 2018-10-15 14:50 UTC
- Sequel Pro Version: Snapshot Build 481 (f21665e)
- macOS Version: 10.14
- MySQL Version: 5.7.23

**Description**
When I switch between two open tabs, the table list is displayed mirrored.

**Steps To Reproduce**
1. Open two tabs
2. Switch between tabs

**Expected Behaviour**
Table list is displayed correctly

**Additional Context**

Built with latest Xcode like so:

```
git clone https://github.com/sequelpro/sequelpro.git --depth=1
cd sequelpro
sed -i '' -e 's/Debug/Release/g' Makefile
find . -type f -name "*.pbxproj" -exec sed -i '' -e 's/ARCHS_STANDARD_32_64_BIT/ARCHS_STANDARD_64_BIT/g' {} +
make
```

See screenshot:

<img width="294" alt="screenshot" src="https://user-images.githubusercontent.com/20833102/46958531-4a9acc80-d09a-11e8-99f2-58f22b767b8a.png">

**Comment by dmoagx** [comment] 2018-10-15 20:32
Duplicate of #3214

**Closed by dmoagx** 2018-10-15 20:32 UTC
Labels: macOS-10.14
