### ISSUE TITLE
Incorrect encoding on import from "Query"

### ISSUE THREAD

**Issue by fregante** [sequelpro/sequelpro#2322] opened 2015-11-11 13:49 UTC
This [SQL file](http://cl.ly/dn7n) is imported correctly viw the `File > Import...` menu but not when double-clicked (and therefore loaded into the `Query` view)

| Correct import | Wrong import |
| --- | --- |
| <img width="209" alt="screen shot 2015-11-11 at 20 45 53" src="https://cloud.githubusercontent.com/assets/1402241/11092342/8301f28c-8837-11e5-83ab-4e3b50a9e6a5.png"> | <img width="208" alt="screen shot 2015-11-11 at 20 48 16" src="https://cloud.githubusercontent.com/assets/1402241/11092384/d4adad42-8837-11e5-931a-5cddc968bc6a.png"> |

**Comment by dmoagx** [comment] 2015-11-11 19:52
Basically the file is broken.
It's binary contents are
```
E2 80 9C 67 72 6F 77 E2 80 9D
         g  r  o  w          
```
The three extra bytes at the start and end are the typographic quotes, named `LEFT DOUBLE QUOTATION MARK` and `RIGHT DOUBLE QUOTATION MARK`.
From that content it can be determined, that the file is encoded in UTF-8 but there is no header that actually sets this (utf8 ist set when creating the table and reset before adding the content).

That way when importing the File via Import menu, Sequel Pro will use it's internal default encoding of utf8, while it uses the encoding of the selected table in the query editor. If that happens to be anything other than utf8, your import will break.

Also note, that in general you don't want to insert `utf8` data into a `latin1` table (which you are using).
Those quotes only work, because MySQLs latin1 is actually `cp1252` instead of `ISO-8859-1`.

**Comment by bfred-it** [comment] 2015-11-12 04:03
Then I'd change the title to "Exports are invalid" because that file was generated by Sequel itself. I've been having this issue for a while on this site and I was always forced to use the command line until yesterday I realized that the direct import menu worked.

**Comment by dmoagx** [comment] 2015-11-12 15:26
Nope, the first file was not generated by Sequel Pro.
Most likely it was mysqldump.

Also the second file is broken, too, but in a different way.
It correctly contains the utf8 header, but the content is:
```
C2 93 67 72 6F 77 C2 94
      g  r  o  w
```
`c293` and `c294` are invisible control characters in utf8.
`93` and `94` **would** have been the right values, **if** the file were in latin1.

I'm not sure how exactly this output came to be, but you most likely have invalid data in your db (e.g. storing utf8 data with latin1 encoding).

**Comment by bfred-it** [comment] 2015-12-14 06:51
The first file was indeed generated by Sequel but it was a full database dump so I removed the rest of the queries, so okay. 

The second one is definitely straight out of Sequel and while the data might not be completely _correct_, I would hope that a tool built on MySQL would be compatible with as much stuff as MySQL (cli) itself is.

Here's a dump made by mysqldump and the other made by Sequel Pro.

[dumps.zip](https://github.com/sequelpro/sequelpro/files/60875/dumps.zip)

Sequel Pro's dump fails both ways (open in **Query** tab and via **Import...** menu) but mysqldump's is imported correctly via **Import...** menu.

I understand that this might be an edge case but I wish I could use Sequel Pro with any database that I pass by without having to fix their issues (which only show under Sequel, in this case)

**Comment by dmoagx** [comment] 2015-12-16 23:36
I can only imagine one way that `C2 92` would've happened:
```objc
#import <Foundation/Foundation.h>

int main(int argc, char *argv[]) {
	@autoreleasepool {
		const char in[] = {0x92,0};
		
		NSString *str = [NSString stringWithCString:in encoding:NSASCIIStringEncoding]; // or NSISOLatin1StringEncoding
		
		NSLog(@"%@",[str dataUsingEncoding:NSUTF8StringEncoding]);
	}
}
```

```
2015-12-16 23:59:59.330 Untitled 5[49042:507] <c292>
```

The `dataUsingEncoding:NSUTF8StringEncoding` part is basically what happens when writing to the SQL export file. That much is fine.
UTF-8 has support for `RIGHT SINGLE QUOTATION MARK`, so it should be able to write it.

That means the issue happened during the conversion to NSString.
Since `cp1252` also has `RIGHT SINGLE QUOTATION MARK` a correct roundtrip would have happened there if Sequel Pro had used `cp1252`:

```objc
#import <Foundation/Foundation.h>

int main(int argc, char *argv[]) {
	@autoreleasepool {
		const char in[] = {0x92,0};
		
		NSString *str = [NSString stringWithCString:in encoding:NSWindowsCP1252StringEncoding];
		
		NSLog(@"%@",[str dataUsingEncoding:NSUTF8StringEncoding]);
	}
}
```

```
2015-12-17 00:10:51.318 Untitled 5[49640:507] <e28099> // correct
```

On the other hand ASCII and Latin1 do not have that character in question, but are the only charsets for which Cocoa will accept arbitrary byte values.
However since `0x80` to `0xFF` are not valid UTF-8 characters and not a character at all for ASCII (and in part for latin1) they have to be padded to appear in an UTF-8 stream. This is where the `C2` comes from.

Also, assuming that
* The table uses latin1 charset
* Sequel Pro uses utf8 connection charset
* The MySQL installation is sane

MySQL should never return `C2 92`, since the `92` that is stored internally as the value would be converted to utf-8's `E2 80 99` before even sending it to the client.

So when would Sequel Pro use Latin 1 or ASCII instead of cp1252?
There are two ways this can happen:
* Sequel Pro (I think including 1.1) has a bug where it treats MySQLs `latin1` as `ISO-8859-1` while it is in fact `cp1252` (there is quite a difference in the high order bytes).
* Some of the code in Sequel Pro falls back to ASCII if interpreting data as UTF-8 fails.

The thing with export is, it only uses straight utf8, so the first issue should never surface.
And we already ruled out the other possible cause above.

**Comment by dmoagx** [comment] 2015-12-16 23:52
Please do the following from the mysql cli:
```
set character_set_results='binary';

select hex(bio) from hof;
```

**Comment by bfred-it** [comment] 2015-12-17 10:23
Here's the output: [both-queries.zip](https://github.com/sequelpro/sequelpro/files/65226/both-queries.zip)

Sequel is 1.1 stable

**Comment by dmoagx** [comment] 2015-12-17 21:54
OK, one thing I can confirm with the data is that Sequel Pro 1.1 has a display issue because of the messed up latin1 thing in MySQL, which should've been fixed in 5f91e6e18ba9107c4a7a1d1709b3da2e984c123a.

However even then the SQL export from Sequel Pro is fine.

What does this show (execute right after receiving a broken export)?
```sql
show variables like '%char%';
```

Also, try to search for any messaged from Sequel Pro in Console.app

**Comment by bfred-it** [comment] 2015-12-21 13:10
Opened the `sequel.sql` file into the **Query...** tab and added your query at the end. This was the output:

name | value
--- | ---
character_set_client | utf8
character_set_connection | utf8
character_set_database | utf8
character_set_filesystem | binary
character_set_results | utf8
character_set_server | utf8
character_set_system | utf8
character_sets_dir | /usr/local/Cellar/mysql/5.6.22/share/mysql/charsets/

Found this in system.log:

    21/12/15 20:07:39,240 Sequel Pro[88155]: lock contention for shared file list item 0x600000162c40

**Comment by dmoagx** [comment] 2016-01-12 22:02
OK, that console message is unrelated.

> Opened the sequel.sql file into the Query... tab and added your query at the end. 

Please run the `show variables like '%char%';` query after doing an export, not an import.
Also, check that the exported file actually contains broken data, since that query won't be useful otherwise.

And, if you have a testing machine also try a development build from http://nightly.sequelpro.com/ and see if that behaves differently.

**Closed** 2019-07-30 19:19 UTC
