### ISSUE TITLE
How to enable cleartext authentication for sequelpro on macos?

### ISSUE THREAD

**Issue by kariachintan** [sequelpro/sequelpro#2542] opened 2016-08-01 21:48 UTC
I am trying to connect to mysql database from SequelPro on MacOS.

I need to know how can we enable cleartext authentication for SequelPro?

Any ideas?

**Comment by dmoagx** [comment] 2016-08-02 00:05
Duplicate of #2247

**Closed by dmoagx** 2016-08-02 00:05 UTC
