### ISSUE TITLE
Crash when closing a tab

### ISSUE THREAD

**Issue by grobmeier** [sequelpro/sequelpro#3438] opened 2019-04-02 08:10 UTC
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14 (Mojave)
- MySQL Version: mysql  Ver 14.14 Distrib 5.7.15

**Description**

After upgrading to Mojave, I can fully work with SequelPro. However, when I close a tab the application crashes.

**Steps To Reproduce**
1. Open sequelpro
2. open multiple tabs
3. close one tab
4. crash

**Expected Behaviour**

It should not crash. ;-)

**Comment by dmoagx** [comment] 2019-04-02 19:03
Duplicate of #3116

**Closed by dmoagx** 2019-04-02 19:03 UTC
