### ISSUE TITLE
problem on connection or import sql file

### ISSUE THREAD

**Issue by melt-cdk** [sequelpro/sequelpro#2359] opened 2015-12-11 16:33 UTC
I have a problem when i would connect to localhost database or import file : 
NSInvalidArgumentException

*** -[NSPlaceholderString initWithString:]: nil argument

(
	0   CoreFoundation                      0x00007fff921d4ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff9266273c objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff921d498d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff94c1fd4a -[NSPlaceholderString initWithString:] + 96
	4   Sequel Pro                          0x000000010002e6a9 -[SPDatabaseDocument setConnection:] + 384
	5   Foundation                          0x00007fff94c6fd4b __NSThreadPerformPerform + 279
	6   CoreFoundation                      0x00007fff920e45c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x00007fff920d641c __CFRunLoopDoSources0 + 556
	8   CoreFoundation                      0x00007fff920d593f __CFRunLoopRun + 927
	9   CoreFoundation                      0x00007fff920d5338 CFRunLoopRunSpecific + 296
	10  HIToolbox                           0x00007fff93eb6935 RunCurrentEventLoopInMode + 235
	11  HIToolbox                           0x00007fff93eb676f ReceiveNextEventCommon + 432
	12  HIToolbox                           0x00007fff93eb65af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	13  AppKit                              0x00007fff8eb690ee _DPSNextEvent + 1067
	14  AppKit                              0x00007fff8ef35943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	15  AppKit                              0x00007fff8eb5efc8 -[NSApplication run] + 682
	16  AppKit                              0x00007fff8eae1520 NSApplicationMain + 1176
	17  Sequel Pro                          0x0000000100001994 start + 52
)

**Comment by dmoagx** [comment] 2015-12-11 16:49
Duplicate of #2302

**Closed by dmoagx** 2015-12-11 16:49 UTC
