### ISSUE TITLE
OSX 10.11 Issue

### ISSUE THREAD

**Issue by miraclebg** [sequelpro/sequelpro#2136] opened 2015-06-11 16:28 UTC
On El Capitan there is a problem with SSH tunnels:

![screen shot 2015-06-11 at 19 26 13](https://cloud.githubusercontent.com/assets/126405/8112365/ed80e900-106f-11e5-9c9d-edd8f050afe9.png)

If i replace the slashes (59909:127.0.0.1:3306) it all works.

**Comment by miraclebg** [comment] 2015-06-11 16:29
Nevermind... it seems this is fixed in 1.1 RC1!

**Comment by dmoagx** [comment] 2015-06-11 18:40
Duplicate of #2050

**Closed by dmoagx** 2015-06-11 18:40 UTC
