### ISSUE TITLE
8.0.12 crash when database is selected in top right of client

### ISSUE THREAD

**Issue by Caledrith** [sequelpro/sequelpro#3130] opened 2018-08-02 04:04 UTC
When I try to select a database I've made, it crashes. I have attached screen recording of issue. https://streamable.com/9x704

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x604000227ea0

(
	0   CoreFoundation                      0x00007fff2992332b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff50a91c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff299bbe04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff29899870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff29899238 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff2b9a81f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff519c3661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff519c350d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff519c2bf9 thread_start + 13
)
```

**Comment by dmoagx** [comment] 2018-08-02 09:14
Duplicate of #2699

**Closed by dmoagx** 2018-08-02 09:14 UTC
