### ISSUE TITLE
MySQL content only table export contains INSERT statements with syntax errors

### ISSUE THREAD

**Issue by andyjko** [sequelpro/sequelpro#1899] opened 2014-02-18 22:47 UTC
In Sequel Pro 1.0.2, I was recently exporting a large 25 million row table by doing the following:
- File > Export
- Clicked the SQL tab
- Unchecked all tables
- Checked the single table I wanted to export
- Unchecked the "Structure" checkbox (Only "Content" and "Output BLOB fields as hex" were checked, with the default 250 KiB of data for new INSERTs set).
- Output set to Gzip

The export completed successfully, but upon importing, I received several invalid syntax errors that forced me to cancel the import. The cause was that several millions of rows were exported as the following:

```
('','','',,'','','','','','',),
```

None of these rows are empty in the original table. Moreover, the value list is syntactically invalid (specifically the contiguous commas).

My table schema is the following:

```
CREATE TABLE `pageviews` (
  `pageviewid` char(40) NOT NULL,
  `date` date NOT NULL,
  `t` time NOT NULL,
  `sectionid` int(11) unsigned NOT NULL,
  `visitorid` char(40) NOT NULL,
  `ip` varchar(39) CHARACTER SET utf8 DEFAULT '',
  `hostname` varchar(253) NOT NULL DEFAULT '',
  `pathname` varchar(2048) NOT NULL DEFAULT '',
  `querystring` varchar(2048) NOT NULL DEFAULT '',
  `entryids` varchar(2048) NOT NULL DEFAULT '',
  `conversionclick` tinyint(4) NOT NULL DEFAULT '0',
  PRIMARY KEY (`pageviewid`),
  KEY `dateindex` (`date`),
  KEY `visitorid` (`visitorid`),
  KEY `section_index` (`sectionid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf16;
```

**Comment by dmoagx** [comment] 2018-10-14 17:59
Since it looks like no one will be able to reproduce this, I'll close it.

**Closed by dmoagx** 2018-10-14 17:59 UTC
Labels: Bug, WaitingOnUser
