### ISSUE TITLE
Umlaut in Trigger breaks editor

### ISSUE THREAD

**Issue by diractorhm** [sequelpro/sequelpro#3004] opened 2018-03-16 14:35 UTC
When you add a comment in a trigger that contains umlauts like ÄÖÜäöü, the trigger statement will not be displayed properly. In my case the text that will be displayed ends at the first occurrence of an umlaut.

**Comment by dmoagx** [comment] 2018-03-16 17:24
Duplicate of #2462

**Closed by dmoagx** 2018-03-16 17:24 UTC
