### ISSUE TITLE
Structure editor doesn't allow user to set length when database supports fractional time

### ISSUE THREAD

**Issue by bobbysciacchitano** [sequelpro/sequelpro#2599] opened 2016-10-11 10:06 UTC
Both MariaDB and MySQL now support fractional time however in the structure editor I am unable to set the length column to specify the number of places for the fractional value. I can perform an ALTER TABLE manually to specify the length and the column is populated with the value.

Would it be possible to detect whether the server supports this and enable the length column in the structure editor as required?

Thanks.

References
https://mariadb.com/kb/en/mariadb/microseconds-in-mariadb/
http://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html

**Comment by dmoagx** [comment] 2016-10-11 20:33
Duplicate of #1515 
This has been implemented for over a year.

**Closed by dmoagx** 2016-10-11 20:33 UTC
