### ISSUE TITLE
Crash on connecting to MySQL 8.0.3 

### ISSUE THREAD

**Issue by jpomykala** [sequelpro/sequelpro#2983] opened 2018-02-12 19:34 UTC
I got a timeout while sending this bug so I just copy paste exception here. I guess it may be helpful.
I'm using MySQL on docker (https://hub.docker.com/_/mysql/) version 8.0.3. On 5.7.21 everything works ok.

Exception:
```
NSInvalidArgumentException
-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60800004e520

(
	0   CoreFoundation                      0x00007fff2adaffcb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff51a51c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2ae48a24 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff2ad26610 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff2ad25fd8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
	7   Foundation                          0x00007fff2ce431c5 __NSThreadPerformPerform + 334
	8   CoreFoundation                      0x00007fff2ad48721 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff2ae020ac __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff2ad2b260 __CFRunLoopDoSources0 + 208
	11  CoreFoundation                      0x00007fff2ad2a6dd __CFRunLoopRun + 1293
	12  CoreFoundation                      0x00007fff2ad29f43 CFRunLoopRunSpecific + 483
	13  HIToolbox                           0x00007fff2a041e26 RunCurrentEventLoopInMode + 286
	14  HIToolbox                           0x00007fff2a041b96 ReceiveNextEventCommon + 613
	15  HIToolbox                           0x00007fff2a041914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff2830cf5f _DPSNextEvent + 2085
	17  AppKit                              0x00007fff28aa2b4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	18  AppKit                              0x00007fff28301d6d -[NSApplication run] + 764
	19  AppKit                              0x00007fff282d0f1a NSApplicationMain + 804
	20  Sequel Pro                          0x0000000100002454 start + 52
)
```

Console:
```
Feb 12, 2018 at 20:23:49: Found 0 crash files
Feb 12, 2018 at 20:23:57: Sending feedback to http://log.sequelpro.com/submit
Feb 12, 2018 at 20:23:57: Posting 10126 bytes to http://log.sequelpro.com/submit
Feb 12, 2018 at 20:24:57: Connection failed
Feb 12, 2018 at 20:24:57: Upload failed: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x60c0002479e0 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=http://log.sequelpro.com/submit, NSErrorFailingURLKey=http://log.sequelpro.com/submit, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=http://log.sequelpro.com/submit, NSErrorFailingURLKey=http://log.sequelpro.com/submit, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

```

**Comment by dmoagx** [comment] 2018-02-12 22:25
Duplicate of #2699

**Closed by dmoagx** 2018-02-12 22:25 UTC
