### ISSUE TITLE
Label colours for individual connections should colour the main connection window

### ISSUE THREAD

**Issue by hyanwong** [sequelpro/sequelpro#2567] opened 2016-09-17 14:49 UTC
Recently I messed up a production database by mistake because I thought I was entering commands into a Sequel Pro window that was associated with the development database. This could have been avoided if the windows for the 2 databases were more visibly different, e.g. the production one was coloured red. As an enhancement, I suggest that the label selected in the favourites window (which now allows a selection of coloured labels) should also be used somehow to colour the main window opened, so it becomes easy to see which windows correspond to which databases, if multiple windows are open

**Comment by hyanwong** [comment] 2016-09-17 14:50
This is obvious an "enhancement", but I can't change the labels on issues in this repo.

**Comment by dmoagx** [comment] 2016-09-17 23:40
Duplicate of #2565

**Closed by dmoagx** 2016-09-17 23:40 UTC

**Comment by hyanwong** [comment] 2016-09-18 08:41
Thanks for spotting the dup. I downloaded the nightly version listed at the bottom of https://github.com/sequelpro/sequelpro/issues/2565 and it is perfect for my needs.
