### ISSUE TITLE
Sequel Pro Crashes after I upgraded to High Sierra

### ISSUE THREAD

**Issue by srikanthsridhara** [sequelpro/sequelpro#3097] opened 2018-06-27 18:36 UTC
I recently upgraded to high sierra. Since then, when I open sequel pro and select a mysql db, the app crashes. This is the exception I got:
```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60400002ac80

(
	0   CoreFoundation                      0x00007fff510c132b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7822bc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff51159e04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff51037870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff51037238 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff531461f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff7915d661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff7915d50d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff7915cbf9 thread_start + 13
)
```

I used homebrew to install mysql. Is there something I'm missing?
I am able to login and see the list of databases, but when I select a DB, this crash occurs.
I am able to access the same DB through MySqlWorkbench without issues.

I am using MySQL 8.0:
mysql  Ver 8.0.11 for osx10.13 on x86_64 (Homebrew)

**Comment by dmoagx** [comment] 2018-06-27 20:13
Duplicate of #2699

**Closed by dmoagx** 2018-06-27 20:13 UTC
