### ISSUE TITLE
BIT fields show random values

### ISSUE THREAD

**Issue by esimioni** [sequelpro/sequelpro#2260] opened 2015-10-02 19:04 UTC
I've just updated to version 1.1 from the previous GA (1.0.3 I believe) and it doesn't display correctly the BIT fields anymore.
The values shown are apparently random. 1's are displayed as 00000000 or 10000000 (previously they were displayed as 00000001), the same goes for zeros.

**Comment by esimioni** [comment] 2015-10-02 19:10
Sorry for the duplicate, the filters "is:open" and "is:open bit" did not show me the existing issues for this problem.

**Comment by dmoagx** [comment] 2015-10-02 21:20
Duplicate of #2254

Until 1.1.1 is released either downgrade to 1.0.2 (http://www.sequelpro.com/release-archive) or try an experimental nightly build which has this fixed: http://nightly.sequelpro.com/

**Closed by dmoagx** 2015-10-02 21:20 UTC
