### ISSUE TITLE
cannot modify global privileges

### ISSUE THREAD

**Issue by wagnerone** [sequelpro/sequelpro#2381] opened 2016-01-19 19:19 UTC
When I attempt to remove "global privileges" from an RDS/MySQL db / user@ip_address, I get a message indicating something like this and no matter what I try so far I cannot remove said "global privileges".

I get a similar message whenever I add "global privileges" too, but despite the erro message, the privilege changes are applied.

In a pinch when I need to get past this (and being too n00b to do it properly from the mysql CLI client), I tried Querious SQL client demo and it made the change on the same RDS MySQL instance without complaint.

Access denied for user 'MyAdminUser'@'%' (using password: YES)

OS 10.11.12
Sequel Pro 1.1 build 4499 (0bac177)

**Comment by dmoagx** [comment] 2016-01-20 15:47
Duplicate of #2229

**Closed by dmoagx** 2016-01-20 15:47 UTC
