### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by craigcarnell** [sequelpro/sequelpro#2651] opened 2017-01-09 09:57 UTC
I extensively use Sequel Pro on OS X due to it's simplicity. A linux version would be great.

**Comment by abhibeckert** [comment] 2017-01-09 22:59
A linux version would be great, but it requires significant improvement to [GNUstep](http://www.gnustep.org/), which as far as I know is currently progressing at a glacial pace.

**Comment by dmoagx** [comment] 2017-01-10 09:06
Duplicate of #696

**Closed by dmoagx** 2017-01-10 09:06 UTC
Labels: Enhancement
