### ISSUE TITLE
[REQ] iCloud Favourites Syncing

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#773] opened 2013-11-09 04:13 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=773
Reporter:jabakobob@gmail.com Date:2010-07-28 13:22:47 Status:Accepted

Some time we should implement favorite syncing via MobileMe. At the moment I have no clue how to do this, and I don't have a MobileMe subscription.

The relevant docs are here:
<a href="http://developer.apple.com/mac/library/documentation/Cocoa/Conceptual/SyncServices/" rel="nofollow">http://developer.apple.com/mac/library/documentation/Cocoa/Conceptual/SyncServices/</a>

I'm posting this because it came up on the mailing list.

**Comment by tomschlick** [comment] 2015-05-08 19:59
+1 on this

**Comment by abhibeckert** [comment] 2015-06-08 05:42
Duplicate of #1843

**Closed by abhibeckert** 2015-06-08 05:42 UTC
Labels: Component-Logic, Enhancement, Feature-Request, Priority-Low, Usability

**Comment by ThinkGraphical** [comment] 2016-01-13 13:20
+1 icloud or dropbox based syncing!

Even a step further:

It would be so nice to be able to share a group of favorites with the rest of your team.
Think à la 'vaults' in 1password.
