### ISSUE TITLE
Bit fields are showing wrong value

### ISSUE THREAD

**Issue by nikomakela** [sequelpro/sequelpro#2307] opened 2015-10-26 08:05 UTC
Bit fields are showing wrong value. I got a bit field (size 1) like is_enabled or password_expired in sec_user table. For example, I'm sure all the users are enabled (value should be 1), but UI shows that almost every another row is disabled (value is 00000000). The very same fields works well with Sequel Pro version 1.0.2. See the screenshots below.

Table is created with following SQL:
```
CREATE TABLE `sec_user` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `version` bigint(20) NOT NULL,
  `account_expired` bit(1) NOT NULL,
  `account_locked` bit(1) NOT NULL,
  `enabled` bit(1) NOT NULL,
  `password` varchar(255) COLLATE utf8_bin NOT NULL,
  `password_expired` bit(1) NOT NULL,
  `username` varchar(255) COLLATE utf8_bin NOT NULL,
  `class` varchar(255) COLLATE utf8_bin NOT NULL,
  `email` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `firstname` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `last_logged_in_date` datetime DEFAULT NULL,
  `locale` varchar(5) COLLATE utf8_bin DEFAULT NULL,
  `logged_in_from` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `online` bit(1) DEFAULT NULL,
  `password_expiry_date` datetime DEFAULT NULL,
  `phone_number` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `registration_completed` bit(1) DEFAULT NULL,
  `surname` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `sv_number` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `title` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username_uniq_1427272446531` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```
Screenshot of sec_user table with Sequel Pro 1.0.2:
![screen shot 2015-10-26 at 10 00 35](https://cloud.githubusercontent.com/assets/389204/10723909/7b8ee440-7bc8-11e5-8516-9a8cd63ffed3.png)

Screenshot of sec_user table with Sequel Pro 1.1:
![screen shot 2015-10-26 at 10 02 11](https://cloud.githubusercontent.com/assets/389204/10723940/b0db9ec2-7bc8-11e5-95ff-f84eebe0042d.png)

**Comment by dmoagx** [comment] 2015-10-26 10:07
Duplicate of #2254

**Closed by dmoagx** 2015-10-26 10:07 UTC
