### ISSUE TITLE
Keep scroll position

### ISSUE THREAD

**Issue by tobias-r** [sequelpro/sequelpro#2877] opened 2017-09-05 05:44 UTC
Hi Sequel, thanks for this great app!

I have one little request:

When refreshing a table (onPress Cmd-R), it looses the horizontal scroll position. Could you maybe keep the scroll position on refresh? On large tables it is always a lot of scrolling when checking values.

Thanks for your consideration

   Tobias

**Comment by abhibeckert** [comment] 2017-09-05 05:57
Duplicate of #1765

**Closed by abhibeckert** 2017-09-05 05:57 UTC
