### ISSUE TITLE
Choosing mysql 8 database causes an `NSInvalidArgumentException`.

### ISSUE THREAD

**Issue by opensaurusrex** [sequelpro/sequelpro#3086] opened 2018-06-14 08:30 UTC
I recently upgraded to MySQL 8.0.11 with Homebrew and found that Sequel Pro is crashing non-stop.

Latest occurrence was when I was trying to select the database after using `mysql` command to import an SQL file. The following is the error details because I can't seem to send the bloody report for some reason. Any ideas how I can get this working? If not then I will just have to use Jetbrains DataGrip from here on out. :\

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x608000022020

(
	0   CoreFoundation                      0x00007fff3203232b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff596acc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff320cae04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff31fa8870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff31fa8238 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff340aa1f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff5a5de661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff5a5de50d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff5a5ddbf9 thread_start + 13
)
```

**Comment by dmoagx** [comment] 2018-06-14 18:50
Duplicate of #2699

**Closed by dmoagx** 2018-06-14 18:50 UTC
