### ISSUE TITLE
Crash with MySQL 8

### ISSUE THREAD

**Issue by rbosch** [sequelpro/sequelpro#3228] opened 2018-10-11 06:49 UTC
Connecting to a MYSQL 8 (running 8.0.12 via brew) server works, but once you open a database the app crashes.

```
-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000022bfe0

(
	0   CoreFoundation                      0x00007fff30fbe571 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5cf6fefb objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3103bca5 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff30f5d7fe ___forwarding___ + 1468
	4   CoreFoundation                      0x00007fff30f5d1b8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff33278234 __NSThread__start__ + 1218
	8   libsystem_pthread.dylib             0x00007fff5e22833d _pthread_body + 126
	9   libsystem_pthread.dylib             0x00007fff5e22b2a7 _pthread_start + 70
	10  libsystem_pthread.dylib             0x00007fff5e227425 thread_start + 13
)

```

**Comment by dmoagx** [comment] 2018-10-11 09:28
Duplicate of #2699

**Closed by dmoagx** 2018-10-11 09:28 UTC
