### ISSUE TITLE
macos10.13  mysql8.0.11 connection database exception

### ISSUE THREAD

**Issue by molisiye** [sequelpro/sequelpro#3107] opened 2018-07-08 15:12 UTC
```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000003af80

(
	0   CoreFoundation                      0x00007fff2f9b432b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff56b1ec76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2fa4ce04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff2f92a870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff2f92a238 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x000000010002f333 -[SPDatabaseDocument setConnection:] + 748
	7   Foundation                          0x00007fff31a722b5 __NSThreadPerformPerform + 334
	8   CoreFoundation                      0x00007fff2f94ca61 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff2fa0647c __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff2f92f4c0 __CFRunLoopDoSources0 + 208
	11  CoreFoundation                      0x00007fff2f92e93d __CFRunLoopRun + 1293
	12  CoreFoundation                      0x00007fff2f92e1a3 CFRunLoopRunSpecific + 483
	13  HIToolbox                           0x00007fff2ec14d96 RunCurrentEventLoopInMode + 286
	14  HIToolbox                           0x00007fff2ec14b06 ReceiveNextEventCommon + 613
	15  HIToolbox                           0x00007fff2ec14884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff2cec6a73 _DPSNextEvent + 2085
	17  AppKit                              0x00007fff2d65ce34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	18  AppKit                              0x00007fff2cebb885 -[NSApplication run] + 764
	19  AppKit                              0x00007fff2ce8aa72 NSApplicationMain + 804
	20  Sequel Pro                          0x0000000100002454 start + 52
)
```

**Comment by jeansantana** [comment] 2018-07-08 15:55
Same problem here.

**Comment by romainnorberg** [comment] 2018-07-08 16:46
duplicate of https://github.com/sequelpro/sequelpro/issues/2699 @molisiye

**Comment by dmoagx** [comment] 2018-07-08 17:07
Duplicate of #2699

**Closed by dmoagx** 2018-07-08 17:07 UTC

**Comment by githuaz** [comment] 2019-03-18 03:29
Same problem here.
