### ISSUE TITLE
Stop program when I close db tab. 

### ISSUE THREAD

**Issue by mhdhamouday** [sequelpro/sequelpro#3203] opened 2018-10-04 08:14 UTC
When I close db tab program stop working.  
This problem started to appear after update OSX to Mojave

**Comment by romainnorberg** [comment] 2018-10-04 08:20
@mhdhamouday Duplicates of #3116

**Comment by stuconnolly** [comment] 2018-10-04 09:40
Duplicate of #3116

**Closed by stuconnolly** 2018-10-04 09:40 UTC
Labels: Duplicate
