### ISSUE TITLE
Foreign key navigation broken in latest build (16180f9d3c)

### ISSUE THREAD

**Issue by matejsp** [sequelpro/sequelpro#3349] opened 2019-01-07 08:23 UTC
Latest beta (and versions before) is completely broken regarding foreign key navigation.
- not allowing empty value for filter (equals) ...
- most of the time foreign key navigation shows the complete table without applied filter (it should filter by ID)
- if it happens to correctly apply filter, back button is not working

TBH I prefer old behaviour (in 1.1.2). If just it wouldn't crash all the time on Mojave.

Separate issue is that there are display glitches when table names are mirrored upside down.

**Comment by dmoagx** [comment] 2019-01-07 19:19
Duplicate of #2792

**Closed by dmoagx** 2019-01-07 19:19 UTC
