### ISSUE TITLE
Columns defined as bit(1) give several problems

### ISSUE THREAD

**Issue by marcgemis** [sequelpro/sequelpro#2298] opened 2015-10-20 06:09 UTC
Columns defined as bit(1) are not treated correctly in 1.1 build 4499. There are no problems with 0.9.9.1

- The values are not displayed correctly
- Export/Import does not work.

Perhaps a screenshot is telling more. In front a 0.9.9.1, displaying 0 and 1 when needed
In the back a 1.1 that shows almost always 000000

<img width="1638" alt="screen shot 2015-10-20 at 08 02 10" src="https://cloud.githubusercontent.com/assets/3937830/10599322/3b2e742c-7701-11e5-9605-cf18923d7b9c.png">

as for the export, here is a fragment for that table made by 1.1

INSERT INTO `ASALUTATION` (`UIDPK`, `GUID`, `LOCALE`, `TITLE_ORD`, `GENDER`, `TITLE`, `FORMAL_UI_SALUTATION`, `INFORMAL_UI_SALUTATION`, `FORMAL_EMAIL_SALUTATION`, `INFORMAL_EMAIL_SALUTATION`, `IS_DEFAULT`)
VALUES
	(1,'1','en',1,'U','Ms./Mr.','{0} {1}','Hello {0}','Dear Ms./Mr. {1},','Dear {0},',00000000),
	(2,'2','en',2,'F','Ms.','{0} {1}','Hello {0}','Dear Ms. {1},','Dear {0},',00000000),
	(3,'3','en',3,'M','Mr.','{0} {1}','Hello {0}','Dear Mr. {1},','Dear {0},',00000000),
	(260001,'260001','bp',1,'U','Ms./Mr.','{0} {1}','Oi {0}','Dear Ms./Mr. {1},','Dear {0},',00000000),
	(260002,'260002','cs',1,'U','Ms./Mr.','{0} {1}','Hello {0}','Dear Ms./Mr. {1},','Dear {0},',00000000),
	(260003,'260003','da',1,'U','Fr./Hr.','{0} {1}','Hej {0}','Kære Fr./Hr. {1}','Kære {0}',00000000),

and here a fragment from 0.9.9.1

INSERT INTO `ASALUTATION` (`UIDPK`, `GUID`, `LOCALE`, `TITLE_ORD`, `GENDER`, `TITLE`, `FORMAL_UI_SALUTATION`, `INFORMAL_UI_SALUTATION`, `FORMAL_EMAIL_SALUTATION`, `INFORMAL_EMAIL_SALUTATION`, `IS_DEFAULT`)
VALUES
	(1,'1','en',1,'U','Ms./Mr.','{0} {1}','Hello {0}','Dear Ms./Mr. {1},','Dear {0},',b'1'),
	(2,'2','en',2,'F','Ms.','{0} {1}','Hello {0}','Dear Ms. {1},','Dear {0},',b'0'),
	(3,'3','en',3,'M','Mr.','{0} {1}','Hello {0}','Dear Mr. {1},','Dear {0},',b'0'),
	(260001,'260001','bp',1,'U','Ms./Mr.','{0} {1}','Oi {0}','Dear Ms./Mr. {1},','Dear {0},',b'1'),
	(260002,'260002','cs',1,'U','Ms./Mr.','{0} {1}','Hello {0}','Dear Ms./Mr. {1},','Dear {0},',b'1'),
	(260003,'260003','da',1,'U','Fr./Hr.','{0} {1}','Hej {0}','Kære Fr./Hr. {1}','Kære {0}',b'1'),
	(260004,'260004','de',1,'U','Frau/Herr','Frau/Herr {1}','Hallo {0}','Sehr geehrte(r) Frau/Herr {1},','Hallo {0},',b'1'),
	(260005,'260005','es',1,'U','Sr./Sra.','{0} {1}','Hola {0}','Apreciado Sr./Sra. {1},','Hola {0},',b'1'),

**Comment by marcgemis** [comment] 2015-10-20 06:22
And the table info

CREATE TABLE `ASALUTATION` (
  `UIDPK` bigint(20) NOT NULL,
  `GUID` varchar(255) NOT NULL,
  `LOCALE` varchar(20) NOT NULL,
  `TITLE_ORD` int(11) NOT NULL,
  `GENDER` varchar(1) NOT NULL,
  `TITLE` varchar(255) NOT NULL,
  `FORMAL_UI_SALUTATION` varchar(255) NOT NULL,
  `INFORMAL_UI_SALUTATION` varchar(255) NOT NULL,
  `FORMAL_EMAIL_SALUTATION` varchar(255) NOT NULL,
  `INFORMAL_EMAIL_SALUTATION` varchar(255) NOT NULL,
  `IS_DEFAULT` bit(1) DEFAULT b'0',
  PRIMARY KEY (`UIDPK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by marcgemis** [comment] 2015-10-20 06:32
I found a copy of 1.0.2  That also works fine, though I prefer the presentation of 0.9.9.1.

<img width="1191" alt="screen shot 2015-10-20 at 08 32 00" src="https://cloud.githubusercontent.com/assets/3937830/10599729/1556f43c-7705-11e5-921f-2a51dc63d481.png">


and the export fragment

INSERT INTO `ASALUTATION` (`UIDPK`, `GUID`, `LOCALE`, `TITLE_ORD`, `GENDER`, `TITLE`, `FORMAL_UI_SALUTATION`, `INFORMAL_UI_SALUTATION`, `FORMAL_EMAIL_SALUTATION`, `INFORMAL_EMAIL_SALUTATION`, `IS_DEFAULT`)
VALUES
	(1,'1','en',1,'U','Ms./Mr.','{0} {1}','Hello {0}','Dear Ms./Mr. {1},','Dear {0},',00000001),
	(2,'2','en',2,'F','Ms.','{0} {1}','Hello {0}','Dear Ms. {1},','Dear {0},',00000000),
	(3,'3','en',3,'M','Mr.','{0} {1}','Hello {0}','Dear Mr. {1},','Dear {0},',00000000),
	(260001,'260001','bp',1,'U','Ms./Mr.','{0} {1}','Oi {0}','Dear Ms./Mr. {1},','Dear {0},',00000001),
	(260002,'260002','cs',1,'U','Ms./Mr.','{0} {1}','Hello {0}','Dear Ms./Mr. {1},','Dear {0},',00000001),
	(260003,'260003','da',1,'U','Fr./Hr.','{0} {1}','Hej {0}','Kære Fr./Hr. {1}','Kære {0}',00000001),
	(260004,'260004','de',1,'U','Frau/Herr','Frau/Herr {1}','Hallo {0}','Sehr geehrte(r) Frau/Herr {1},','Hallo {0},',00000001),
	(260005,'260005','es',1,'U','Sr./Sra.','{0} {1}','Hola {0}','Apreciado Sr./Sra. {1},','Hola {0},',00000001),

**Comment by dmoagx** [comment] 2015-10-20 11:42
Duplicate of #2254 
Please search for existing issues before creating a new one.

**Closed by dmoagx** 2015-10-20 11:42 UTC
