### ISSUE TITLE
When opening a table it cashes

### ISSUE THREAD

**Issue by liacmedia** [sequelpro/sequelpro#3169] opened 2018-09-17 09:16 UTC
When opening my local database an exception occures.

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x604000022180

(
	0   CoreFoundation                      0x00007fff3f6f52db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff66961c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3f78ddb4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff3f66b820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff3f66b1e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff4177a1f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff67893661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff6789350d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff67892bf9 thread_start + 13
)
```

**Comment by dmoagx** [comment] 2018-09-17 20:30
Duplicate of #2699

**Closed by dmoagx** 2018-09-17 20:30 UTC
