### ISSUE TITLE
The list of table names on the left is blurred

### ISSUE THREAD

**Issue by yuercl** [sequelpro/sequelpro#3279] opened 2018-11-03 16:31 UTC
- Sequel Pro Version:  build by XCode from「Latest commit 81986f5」
- macOS Version: Mac OS X Mojave. 10.14
- MySQL Version: 5.7.20 (Aliyun RDS)

**Description**
The list of table names on the left is blurred. 
When i open two tabs of connection and switch one to another. 

**Additional Context**

<img width="270" alt="2018-11-04 00 30 08" src="https://user-images.githubusercontent.com/2859382/47954753-daaca180-dfc8-11e8-8c7f-76a0af7433cb.png">

**Comment by dmoagx** [comment] 2018-11-03 17:06
Duplicate of #3214

**Closed by dmoagx** 2018-11-03 17:06 UTC
