### ISSUE TITLE
crashes when closing tabs

### ISSUE THREAD

**Issue by QusaiFarraj** [sequelpro/sequelpro#3431] opened 2019-03-26 21:00 UTC
this issue has been going on for a while now and it needs to be addressed.

Every time I close a tab, Sequel Pro crashes and quit like I never used it. When I reopen it, I get this message, please report this to sequel pro and I did a lot. for like 3 months now with no action.

I reported this issue to Apple and no actions have been taken so far.

from the crash log:

> Termination Reason:    Namespace OBJC, Code 0x1

**Comment by wadehammes** [comment] 2019-03-27 13:55
Seconded. Happens everyday. Same error, with ability to report.

**Comment by twjackson** [comment] 2019-03-27 23:46
Same here. Everyday, all day.

**Comment by pingcheng** [comment] 2019-03-28 10:55
get the test build instead, https://sequelpro.com/test-builds
the issue had been fixed there.

use it and wait for the stable release

**Comment by kaystrobach** [comment] 2019-03-28 12:55
@pingcheng what's the plan for the next stable release, since the last one is 2 years old - thank you for your work.

**Comment by twjackson** [comment] 2019-03-28 13:57
Thanks @pingcheng

**Comment by wadehammes** [comment] 2019-03-28 14:06
Thanks @pingcheng. LOVE the dark mode!

**Comment by pingcheng** [comment] 2019-03-28 22:47
> @pingcheng what's the plan for the next stable release, since the last one is 2 years old - thank you for your work.

hi， @kaystrobach, I am also a user as well :smile:
but according to the project board https://github.com/sequelpro/sequelpro/projects/2, there are still three issues are under consideration 😂

**Comment by dmoagx** [comment] 2019-03-31 17:12
Duplicate of #3116

**Closed by dmoagx** 2019-03-31 17:12 UTC

**Comment by QusaiFarraj** [comment] 2019-04-08 16:23
@dmoagx Thanks for taking care of this issue.

**Comment by polycode-nz** [comment] 2019-04-16 21:37
@dmoagx Is your recommendation for us to fix this to use a test build? Last time I grabbed a nightly it deleted all my favourites and I couldn't get them back.
