### ISSUE TITLE
System hang caused by Sequel Pro on High Sierra

### ISSUE THREAD

**Issue by chrisphenry** [sequelpro/sequelpro#2890] opened 2017-09-26 16:40 UTC
Twice today after updating to High Sierra GM, Sequel Pro has seemingly caused my system to hang with no way to recover. Mouse remains responsive, Keyboard does nothing, screen frozen. Has anyone else encountered this?

**Comment by dmoagx** [comment] 2017-09-26 20:10
What leads you to believe Sequel Pro was the cause?

**Comment by chrisphenry** [comment] 2017-09-26 20:18
Simply the fact that the system hung twice when I changed the database using the switcher in the top left. I’ll keep an eye on it but thought I’d mention here in case others had observed the same thing.

**Comment by dmoagx** [comment] 2017-09-26 20:32
If you have another computer around, enable SSH to your Mac (System Prefs > Sharing > Remote Login) and connect via SSH when the issue occurs.
Then run command
```
sudo spindump "Sequel Pro"
```
and upload the file it has written (note: this file contains a dump of all running applications and all devices plugged into your Mac).

**Comment by abhibeckert** [comment] 2017-09-26 22:51
> note: this file contains a dump of all running applications and all devices plugged into your Mac

@chrisphenry if you're not willing to upload the file somewhere public you can email it to contact@sequelpro.com

**Comment by bmx269** [comment] 2017-09-28 17:03
I too can verify that this is happening. The computer came to a halt, and after being able to quit SequelPro the computer returned to normal. From what I have read, it is related to the new APFS, and indexing.

**Comment by abhibeckert** [comment] 2017-09-28 21:24
> From what I have read, it is related to the new APFS, and indexing.

Can you provide a link with more details?

**Comment by chrisphenry** [comment] 2017-09-29 15:03
@abhibeckert I've not yet had the chance to dump anything but also observe that the same thing has happened in other apps too, for instance requesting a page in Safari just caused my system to hang (this time without mouse). In additional I've noticed some graphical issues with windows and transparency that I've seen in prior OSX releases in various apps.

**Comment by yuweitaocn** [comment] 2017-10-10 13:52
on High Sierra ,when i use import csv ,It will be stuck

**Comment by abhibeckert** [comment] 2017-10-10 23:27
@yuweitaocn do you mean sequel pro will hang, or the entire system?

**Comment by yuweitaocn** [comment] 2017-10-12 07:59
@abhibeckert sequel pro will hang 
![image](https://user-images.githubusercontent.com/1688061/31485408-4f07bf9e-aef9-11e7-978b-d9e238d39ff6.png)
 alwasy  reading 
i guess mac os change  file system cause this problem .

**Comment by yuweitaocn** [comment] 2017-10-12 08:02
Old system does not have this one problem

**Comment by rhenusone** [comment] 2017-11-29 13:49
I'm also having this issue. It seems to be since the filesystem of mac os x has been changed.

**Comment by rv-mpotter** [comment] 2018-03-03 03:57
I'm having the same issue, but for me, after the High Sierra upgrade, Sequel Pro goes into a not responding state every time I try to start it.

**Comment by dmoagx** [comment] 2018-03-03 18:43
@rv-mpotter Does your Mac crash or does Sequel Pro hang?

**Comment by jaco** [comment] 2018-03-03 19:14
Same problem here, Sequel Pro hangs when connecting every time. Problem occurs only on nighty. 

Stable works fine but it doesn’t support protocol handler (mysql://…).

**Comment by dmoagx** [comment] 2018-03-04 09:10
@jaco If Sequel Pro hangs, this is not the same problem.
This issue is specifically about Sequel Pro (supposedly) crashing the whole OS.

**Comment by omar-faruk-sust** [comment] 2018-03-19 16:34
I'm having the issue with sequel pro to start. after the High Sierra upgrade, Sequel Pro does not get open when I try to start it. even the icon of sequel pro is not showing a question mark. what's the issue?

**Comment by dmoagx** [comment] 2018-03-19 19:47
@omar-faruk-sust If there is a question mark displayed on the icon it means that OS X cannot find the application because it was moved or deleted.

**Comment by Munmw** [comment] 2018-03-20 04:01
![image](https://user-images.githubusercontent.com/6494545/37635412-5cc2c10a-2c36-11e8-9fcc-e04f8cccdc77.png)
Having the same issue as well. import all kind of csv and got hang at Reading csv in Sequel pro. OS did not hang.

**Comment by chrisphenry** [comment] 2018-03-20 19:13
Follow up: I'm on a new Mac now and no issues with Sequel Pro at all which would potentially suggest these issues are most likely related to upgrading from Sierra -> High Sierra only. I observed no issues when installing High Sierra clean on my previous Mac in December.

**Comment by omar-faruk-sust** [comment] 2018-03-23 04:37
@dmoagx , i am reinstall Sequel Pro, now it's working again. Thanks

**Comment by dmoagx** [comment] 2018-05-19 22:07
Since this issue didn't get anywhere, I will close it now.

**Closed by dmoagx** 2018-05-19 22:07 UTC
Labels: WaitingOnUser, macOS-10.13

**Comment by victoriafrench** [comment] 2018-08-07 04:28
I have a clean High Sierra machine as well, it has never had a different OS. My ssd is using the new OS format and is encrypted. Version 1.1.2 hangs on every startup with the beach ball of death and the fans going crazy. After about 5 minutes the system goes back to normal and the app is usable.

**Comment by majimboo** [comment] 2019-08-03 15:13
Importing a 2.2gb sql file is stuck at **reading....** just got the macbookpro this week.

**Comment by janmichael88** [comment] 2019-09-18 23:01
did this get resolved?

**Comment by shawnCaza** [comment] 2020-04-14 02:53
Can't seem to import csv either.
