### ISSUE TITLE
Crash when opening database

### ISSUE THREAD

**Issue by wangzianan** [sequelpro/sequelpro#3122] opened 2018-07-23 02:39 UTC
I used the latest version of 1.1.2, but it crashed when I opened the database. My mac version is High Sierra 10.13.6. My error message is
![error](https://user-images.githubusercontent.com/13514472/43054523-94f0a3a4-8e64-11e8-9fd7-7ec368de2272.png)

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6040002397e0

(
	0   CoreFoundation                      0x00007fff50adc2db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff77c7dc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff50b74db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff50a52820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff50a521e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x0000000100057a0e -[SPTablesList updateTables:] + 1291
	6   Sequel Pro                          0x0000000100046133 -[SPDatabaseDocument _selectDatabaseAndItem:] + 437
	7   Foundation                          0x00007fff52b611f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff78baf661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff78baf50d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff78baebf9 thread_start + 13
)

```

**Comment by Yingkaixiang** [comment] 2018-07-24 03:32
I have got a same problem.
Sequel Pro version is 1.1.2
MySQL version is 8.0.11
MacOS is High Sierra 10.13.6

**Comment by dmoagx** [comment] 2018-07-24 07:00
Duplicate of #2699

**Closed by dmoagx** 2018-07-24 07:00 UTC
