### ISSUE TITLE
crashes when closing tabs

### ISSUE THREAD

**Issue by QusaiFarraj** [sequelpro/sequelpro#3430] opened 2019-03-26 21:00 UTC
this issue has been going on for a while now and it needs to be addressed.

Every time I close a tab, Sequel Pro crashes and quit like I never used it. When I reopen it, I get this message, please report this to sequel pro and I did a lot. for like 3 months now with no action.

I reported this issue to Apple and no actions have been taken so far

**Comment by stychos** [comment] 2019-03-26 21:02
Duplicate of https://github.com/sequelpro/sequelpro/issues/3116. Use nightly builds.

**Comment by infostreams** [comment] 2019-03-28 09:22
Just release the new version, it's insane that a hard (reproducible) crash takes 6 months to release AFTER the issue is fixed. I switched to the AWESOME [TablePlus](https://tableplus.io/) as a result. Disappointing, guys. You lost a very long-time user.

**Comment by dmoagx** [comment] 2019-03-31 17:06
> takes 6 months to release AFTER the issue is fixed

Wow said 6 months?
The crash was fixed in Nov 2016: #2609 😂

**Comment by dmoagx** [comment] 2019-03-31 17:06
Duplicate of #3116

**Closed by dmoagx** 2019-03-31 17:06 UTC

**Comment by infostreams** [comment] 2019-04-01 07:27
It was fixed on the 4th of November, so about 5 months: one month off. I guess I don't understand why you don't just release a minor 'patch' version release to fix this for everyone else. The [majority of users are on Mojave](https://www.gosquared.com/global/mac/mojave/#launch), and for them the whole app crashes if you do something simple like clicking the 'close' button. Really not a good experience. I don't understand why you wouldn't want to address that.
