### ISSUE TITLE
Re-opening connection panel after disconnect sends connection details to the right

### ISSUE THREAD

**Issue by petecooper** [sequelpro/sequelpro#3445] opened 2019-04-09 14:28 UTC
- Sequel Pro Version: 5438 (664a46cd)
- macOS Version: 10.13.6
- MySQL Version: 5.7.25-28 (Percona)

**Description**
Disconnecting from host using Cmd + W then re-opening connection panel using Cmd + T floats connection details to the right side.

**Steps To Reproduce**
1. Open SequelPro, note correct position of connection details.
2. Connect to server, disconnect from server with Cmd + W.
3. Open connection panel with Cmd + T, note right-floated connection details.

**Expected Behaviour**
Connection details panel should maintain its centred position.

**Additional Context**

![1of3](https://user-images.githubusercontent.com/226578/55808425-f702bc00-5adb-11e9-808c-6a2191d7f588.png)

![2of3](https://user-images.githubusercontent.com/226578/55808174-7d6ace00-5adb-11e9-9b80-f238d07b1301.png)

![3of3](https://user-images.githubusercontent.com/226578/55808200-88bdf980-5adb-11e9-9e62-48a291569828.png)

**Comment by dmoagx** [comment] 2019-04-23 18:24
Duplicate of #2412

**Closed by dmoagx** 2019-04-23 18:24 UTC
