### ISSUE TITLE
client send 'select count(1)' query when click text field result, block too long

### ISSUE THREAD

**Issue by htwenning** [sequelpro/sequelpro#3132] opened 2018-08-10 09:18 UTC
hi,
when  click text field column of result, it will send a query to db , and this cost too much time some time. I think it's checking existence of data?  but i just want to copy that text field out...

**Comment by dmoagx** [comment] 2018-09-07 21:03
Duplicate of #3001

**Closed by dmoagx** 2018-09-07 21:03 UTC
