### ISSUE TITLE
Crash when connecting to remote mysql server(mysql8.0) via ssh

### ISSUE THREAD

**Issue by xiebruce** [sequelpro/sequelpro#3398] opened 2019-03-01 04:21 UTC
- Sequel Pro Version: `1.1.2 Build 4541 (602e11a)`
- macOS Version: `macOS Mojave 10.14.1 (18B75)`
- MySQL Version: `mysql  Ver 8.0.11 for linux-glibc2.12 on x86_64 (MySQL Community Server - GPL)`

**Description**
1. Crash when connecting to remote mysql server via ssh.
2. But Works fine when I connect to local mysql server(not via ssh) even if my local mysql server, version is `mysql  Ver 8.0.13 for osx10.14 on x86_64 (Homebrew)`.
3. I also try to connect to local mysql server on my Mac(mysql 8.0.13), I can connect, but when I choose a database(any database), it shows the same error:
![image](https://user-images.githubusercontent.com/13575500/53615915-31df1d80-3c1b-11e9-982d-f94954d743c4.png)
![image](https://user-images.githubusercontent.com/13575500/53615944-5b984480-3c1b-11e9-89af-b6d33d6f71f4.png)

So, I can say the bug is about login via ssh, I don't have a mysql 5.7 so I can't test whether it will work or not.

**Steps To Reproduce**
1. Fill in the connection parameters
![image](https://user-images.githubusercontent.com/13575500/53614894-70bea480-3c16-11e9-974f-74d9186b2c75.png)

2. Click `connect` button

**Expected Behaviour**
Login to mysql, view databases and tables.

**Additional Context**
no Additional Context

After I click the `connect` button, it popup this:
![image](https://user-images.githubusercontent.com/13575500/53615504-225ed500-3c19-11e9-82b1-33ef63c8773c.png)

Click `Details` above, then shows the following Exception detail:
```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000c6c8d0

(
	0   CoreFoundation                      0x00007fff51ca8e65 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7dd04720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff51d2622d -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff51c4a820 ___forwarding___ + 1486
	4   CoreFoundation                      0x00007fff51c4a1c8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
	7   Foundation                          0x00007fff53fecabb __NSThreadPerformPerform + 327
	8   CoreFoundation                      0x00007fff51c0e155 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff51c0e0fb __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff51bf1b95 __CFRunLoopDoSources0 + 195
	11  CoreFoundation                      0x00007fff51bf113e __CFRunLoopRun + 1219
	12  CoreFoundation                      0x00007fff51bf0a28 CFRunLoopRunSpecific + 463
	13  HIToolbox                           0x00007fff50e89b35 RunCurrentEventLoopInMode + 293
	14  HIToolbox                           0x00007fff50e8986b ReceiveNextEventCommon + 618
	15  HIToolbox                           0x00007fff50e895e8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff4f145eb7 _DPSNextEvent + 997
	17  AppKit                              0x00007fff4f144c56 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1362
	18  AppKit                              0x00007fff4f13ecb9 -[NSApplication run] + 699
	19  AppKit                              0x00007fff4f12e3f7 NSApplicationMain + 780
	20  Sequel Pro                          0x0000000100002454 start + 52
	21  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by xiebruce** [comment] 2019-03-01 04:24
BTW, when will next release come? It's been three years, I love sequel pro.

**Comment by stychos** [comment] 2019-03-01 04:25
When [required](https://github.com/sequelpro/sequelpro/projects/2) parts will be done. https://github.com/sequelpro/sequelpro/issues/3385

**Comment by xiebruce** [comment] 2019-03-01 04:44
@stychos  wow, that's great, thank you.

**Comment by dmoagx** [comment] 2019-03-01 18:59
Duplicate of #2699

**Closed by dmoagx** 2019-03-01 18:59 UTC
