### ISSUE TITLE
Unable to get private key

### ISSUE THREAD

**Issue by scottfoster** [sequelpro/sequelpro#2251] opened 2015-10-01 08:37 UTC
I just upgraded to Sequel Pro 1.1 and now when I try to connect to my Amazon RDS, I get

MySQL said: SSL connection error: Unable to get private key

The key file option is selected and the location is ~/cert.pem

Any ideas?

**Comment by dmoagx** [comment] 2015-10-01 09:50
Instead of "~", have you tried a "real" path?

**Comment by scottfoster** [comment] 2015-10-01 14:30
I cannot manually type in a "real" path. When I select it use the file selector, it automatically puts it in as ~/cert.pem.

**Comment by dmoagx** [comment] 2015-10-01 15:01
If you have private key and client certificate in one file, make sure to split them (ie. you need to specify all three files and they all need to be in PEM format).

**Comment by vlanard** [comment] 2015-10-13 20:33
Same problem here. Amazon RDS provides a bundled pem file to their users (http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ConnectToInstance.html) to connect over ssl. It does not contain a key, just a list of certificates. It no longer works with Sequel Pro 1.1. I tried various ways to chop up the amazon pem, but didn't solve the problem, and again - in this case, they presumably have the private key, but users don't. The Amazon bundled pem file works fine from mysql command line passed as --ssl-ca value. 
@scottfoster I reverted back to Sequel Pro 1.0.2 to get around this.

**Comment by dmoagx** [comment] 2015-10-13 20:36
Well, I don't have an Amazon RDS account, so I can't test it.
Someone would have to provide us with temporary access.

**Comment by vlanard** [comment] 2015-10-13 20:37
Let me take a look and see how feasible that would be.

**Comment by vlanard** [comment] 2015-10-13 21:03
Well, good news. Not a bug! I went ahead and created a test database, test login, etc for you, and reinstalled 1.1 to verify everything before I sent you the info, but then found I was able to connect from 1.1 if I moved the Amazon bundled pem out of the Key File field (I must have left it populated before), and ONLY included it as the CA Cert value.

So @scottfoster, solution is to 
1) REMOVE AWS pem from Key File field
2) ADD AWS pem path to the CA Cert field
 Test connection. 

Works for me. Granted, in v1.0.2 this pem worked from the Key Field, but since the pem doesn't actually contain a key, v1.1 seems like correct behavior.

Sorry for the false churn, @dmoagx! Glad it's working with AWS!

**Comment by dmoagx** [comment] 2015-10-13 21:18
I guess we could add a check for that, though.

**Comment by vlanard** [comment] 2015-10-13 21:22
Let me know if you need a test setup - I'm assuming you would already have one handy if you decided to add that though.

**Comment by dmoagx** [comment] 2015-10-14 23:06
I've added code in 264babe2f0d1b5c7713c1a9df0417e4ec5b84bd2 and fa62a27d1fea6f8671a6c021d792433d64fc8d8f which will check the private key file and client cert file (at the time of choosing them) and complain if those are invalid.

**Comment by dmoagx** [comment] 2015-11-05 23:43
Closing after no feedback from initial reporter.

**Closed by dmoagx** 2015-11-05 23:43 UTC
Labels: WaitingOnUser

**Comment by Telemakhos** [comment] 2016-03-26 00:13
Just faced this problem and I solved it using [this cert](http://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem) in the CA Cert field...

http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_MySQL.html#MySQL.Concepts.SSLSupport
