### ISSUE TITLE
SSH connections fail on El Capitan

### ISSUE THREAD

**Issue by rickokid** [sequelpro/sequelpro#2207] opened 2015-08-18 01:22 UTC
SSH connection no longer work in El Capitan - the error is that the SSH tunnel has unexpectedly closed.  The error detail shows the forwarding specification is incorrect - if I copy the SSH command Sequel is trying to execute and replace the slashes in the forwarding spec with colons it connects the tunnel fine - i.e. 57412:127.0.0.1:3306 (rather than 57412/127.0.0.1/3306).
<img width="422" alt="sequel ssh error" src="https://cloud.githubusercontent.com/assets/13842805/9320265/14d9edb4-45ac-11e5-91a2-791997590793.png">
<img width="614" alt="sequel ssh error detail" src="https://cloud.githubusercontent.com/assets/13842805/9320267/152e0390-45ac-11e5-8365-e3fcde3c5de1.png">

**Comment by dmoagx** [comment] 2015-08-18 07:31
Duplicate of #2050 
This has already been fixed since 1.1rc1: http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/
Please search for existing issues, before creating a new one.

**Closed by dmoagx** 2015-08-18 07:31 UTC

**Comment by rickokid** [comment] 2015-08-18 08:24
I did!  I searched the first page for SSH and no go.  Guess it was further
back.  Any idea when a stable release will come out with the fix?

**Comment by dmoagx** [comment] 2015-08-18 08:35
If nothing major goes wrong probably in 2-4 weeks.
