### ISSUE TITLE
Keychain problems with version 1.1

### ISSUE THREAD

**Issue by jamesharvard** [sequelpro/sequelpro#2268] opened 2015-10-05 09:58 UTC
[MacOS 10.6; perhaps related to #2251?]

I have a connection favourite saved that uses an SSH tunnel. Since upgrading to v1.1 I get a prompt when connecting that says:

> The SSH password could not be loaded from the keychain; please enter the SSH password for SequelPro-xxxxxxxxxx: *password-prompt-here*

It works fine if I enter the password when prompted. I've also tried modifying the connection (by ticking & unticking the 'connect using SSL' box, which triggers the 'save changes' & 'test connection' buttons to shows) but I get this error: 

> Error adding password to Keychain
> An error occured while trying to add the password to your Keychain. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -25299.

**Comment by dmoagx** [comment] 2015-10-05 10:11
-25299 means "Duplicate item". Try opening Keychain access.app and search for the item (by username or host name). If there are two items with exactly the same name, try deleting one.

**Comment by jamesharvard** [comment] 2015-10-05 12:05
OK, that explains why I can't re-save the connection's SSH password, but presumably it does not explain why Sequel Pro is giving an error when trying to read it in the first place?

**Comment by rowanbeentje** [comment] 2015-10-05 12:16
There's also a range of keychain bugs where if an item is changed, it may not be accessible for the rest of the keychain session (until a restart of OS X or whatever underlying system controls access...).  I've usually seen it manifest as a blank password result rather than an error though.

**Comment by jamesharvard** [comment] 2015-10-05 13:25
I've restarted, and removed both the SSH and MySQL passwords from the keychain. Once I removed the MySQL password (ie not just the SSH password) I could re-save the connection. However I still get an error message saying that the SSH password could not be loaded from the keychain.

Could it be that the Sequel Pro v1.1 is failing to use the right/separate identifier for the SSH password, as opposed to the MySQL password? I notice that both passwords in the keychain have the same long integer in their name.

![screen shot 2015-10-05 at 14 21 08](https://cloud.githubusercontent.com/assets/14975019/10281435/64ca7498-6b6c-11e5-9010-a4905cf1a6a4.png)

**Comment by jamesharvard** [comment] 2015-10-05 13:31
Just wanted to reiterate that this is Mac OS 10.6…

**Comment by rowanbeentje** [comment] 2015-10-05 13:56
The long integer is used as an identifier for the connection, so that connections with the same name don't have conflicts (although it is a bit long on 64bit!).  The "SSHTunnel" in the name _looks_ like it's using the right identifier to me...

**Comment by jamesharvard** [comment] 2015-10-05 15:51
OK, well for whatever reason v1.1 seems unable to get the SSH tunnel password from Keychain on my Mac OS 10.6.

If the connection drops (e.g. when my broadband dropped a few minutes ago) then Sequel Pro is unable to reconnect and opens a password prompt as per the screenshot attached.

I also don't seem to be able to command-tab to the application, as if it's frozen. However it doesn't show as 'not responding' if I right-click the icon in the dock.

Will have to revert to the old version of the app, I think :-(

![screen shot 2015-10-05 at 16 39 49](https://cloud.githubusercontent.com/assets/14975019/10285270/fbe7732c-6b7f-11e5-87bc-11b3d96cacdd.png)

**Comment by jamesharvard** [comment] 2015-10-05 16:17
Also, I can confirm that this was not just a problem with one particular connection. I have another connection to a different server that also uses an ssh tunnel, and this exhibited the same problem.

**Comment by dmoagx** [comment] 2015-10-05 16:27
Since 1.0.2 there has been only one commit related to keychain code, related to the OS X SDK version.
https://github.com/sequelpro/sequelpro/commit/834724b5b23c774b1750b2ba53e6be9d02128edb

This could be related, but I checked 10.6 a few weeks ago and it worked for me.

**Comment by dmoagx** [comment] 2015-10-05 22:55
Just tried it on 10.6 and can reproduce.
What is a bit strange though, is that it only affects SSH. Getting the MySQL password from Keychain works fine.

**Comment by jamesharvard** [comment] 2016-02-10 12:12
I (and presumably others using 10.6, maybe other OS versions too) am unable to update to the latest security release http://www.sequelpro.com/release-notes#release_1.1.0.1 because of this show-stopping bug. Any chance this could be prioritised for release, please?

**Comment by jamesharvard** [comment] 2016-02-10 12:22
Further to this, I assume the best solution is to disable automatic update checks for the time being?

**Comment by mnfgul** [comment] 2016-02-17 10:53
Hi, I have the same problem on mac os  el capitan. It was working before but now whenever i try to connect a db it ask me to allow key chain access and it freezes. Is there any solution for this? Thanks for help.

**Comment by jamesharvard** [comment] 2016-02-17 14:00
Hello, @mnfgul, my experience was that I had to downgrade to the previous version (the old version of the app is placed in 'Trash' during the upgrade, so you can just drag it back to the Applications folder).

**Comment by dmoagx** [comment] 2016-02-20 13:14
Issue fixed in 1.1.1
See http://www.sequelpro.com/blog/2016.02/sequel-pro-1-1-1/

**Closed by dmoagx** 2016-02-20 13:14 UTC
Labels: Bug, Fixed-AwaitingRelease, OSXVersion-10.6

**Comment by magichim** [comment] 2018-01-04 12:20
@dmoagx 1.1.1 also same bug case to me. 

-error message

An error occured while trying to add the password to your Keychain. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -25293.

**Comment by dmoagx** [comment] 2018-01-04 19:01
@magichim You are likely experiencing a bug in macOS 10.13. See #2948

**Comment by magichim** [comment] 2018-01-05 03:46
@dmoagx Oh really thanks! Just reboot is finish :)
