### ISSUE TITLE
Crash when closing a tab on macOS Mojave

### ISSUE THREAD

**Issue by pescod106** [sequelpro/sequelpro#3344] opened 2018-12-29 03:47 UTC
- Sequel Pro Version:
- macOS Version::10.14.2
- MySQL Version:5.7

**Description**

**Steps To Reproduce**
1.use command  + w close sequel's tab, the sequel pro will exist
2.none

**Expected Behaviour**
none
**Additional Context**
none

**Comment by pescod106** [comment] 2018-12-29 03:52
it is also happen in mac os 10.14.2

**Comment by cliveyuan** [comment] 2018-12-29 08:49
me too

**Comment by danielkdesigner** [comment] 2018-12-31 14:36
same here. macOS Mojave 10.14.2. Really hinders my workflow as I always try to close my production db tab before editing any data in my local db just for the sake of not confusing myself and accidentally editing production.

**Comment by scolandrea** [comment] 2018-12-31 16:21
Duplicated issue #3116 please close it.

**Comment by dmoagx** [comment] 2018-12-31 18:36
Duplicate of #3116

**Closed by dmoagx** 2018-12-31 18:36 UTC
