### ISSUE TITLE
Crash when closing a connection tab when multiple tabs are open

### ISSUE THREAD

**Issue by ChristopherCommuniq** [sequelpro/sequelpro#3237] opened 2018-10-15 12:40 UTC
- Sequel Pro Version:
- macOS Version: 10.14 (18A391)
- MySQL Version: 

**Description**
SequelPro crashes when a connection-tab gets closed by clicking on the 'X' or using the keyboard shortcut [CMD] + [W].

**Steps To Reproduce**
1. Open SequelPro;
2. Connect to a host (can also be localhost);
3. Open a new connection tab ([CMD] + [T]);
4. Close the tab by clickin on the 'X' or using the keyboard shortcut [CMD] + [W];
5. **Result:** the applications closes and generates the error screen (error reporting also is bugged).

**Expected Behaviour**
The connection tab should close and the connection should be terminated.

Error report:
<img width="999" alt="screenshot 2018-10-15 at 14 40 39" src="https://user-images.githubusercontent.com/19683366/46951452-4fef1b80-d088-11e8-902e-53bc96b81d46.png">

**Comment by slifin** [comment] 2018-10-15 14:11
I've been getting this issue too, very annoying, is it worth changing to nightlies? I see a lot of labels for: https://github.com/sequelpro/sequelpro/issues?q=is%3Aissue+is%3Aopen+label%3AFixed-AwaitingRelease "Fixed-AwaitingRelease" when is the release? I'd rather not run my database software with nightlies if I could avoid it

**Comment by BarryCarlyon** [comment] 2018-10-15 16:32
I don't get a crash or crash dialog. But I do get the whole app closing.

If I `apple + w` a single tab the whole app shutsdown

**Comment by dmoagx** [comment] 2018-10-15 19:45
Duplicate of #3116

**Closed by dmoagx** 2018-10-15 19:45 UTC
