### ISSUE TITLE
Display problems when dragging a new connection tab into its own window

### ISSUE THREAD

**Issue by ploaiza** [sequelpro/sequelpro#2863] opened 2017-08-16 16:56 UTC
Open up a database. Open up another database in a new tab.  Grab the the 2nd tab and drag it out into its own window.  The text in the second tab gets fuzzy, the text in the original window for the selected table is fuzzy.  The background for the tables in the 2nd tab is black.
![screen shot 2017-08-16 at 12 55 14 pm](https://user-images.githubusercontent.com/119003/29375218-361c101e-8282-11e7-9a15-49d8e764476d.png)

**Comment by abhibeckert** [comment] 2017-08-17 20:59
Confirmed.

As a workaround, you can enable "Reduce Transparency" in System Preferences -> Accessibility -> Display.

**Comment by dmoagx** [comment] 2017-08-17 21:15
Duplicate of #2286

**Closed by dmoagx** 2017-08-17 21:15 UTC
Labels: Bug
