### ISSUE TITLE
Filter box moves!

### ISSUE THREAD

**Issue by nexbridge** [sequelpro/sequelpro#2825] opened 2017-06-23 13:42 UTC
When I'm on the query editor window and click the Query Favourites or Query History dropdown, if there's too many entries in the dropdown to fit on the screen so that you have to scroll down the list, when you scroll the little filter and magnifying glass box moves with the scroll!  I've attached a screenshot to illustrate.

I'm using Sequel Pro 1.1.2, build 4541, on macOS 10.12.4.

![screen shot 2017-06-23 at 14 31 23](https://user-images.githubusercontent.com/13848887/27484661-ed51cb88-5821-11e7-9a46-efc19a1493ec.png)

**Comment by dmoagx** [comment] 2017-06-29 20:20
Duplicate of #2079

**Closed by dmoagx** 2017-06-29 20:20 UTC
