### ISSUE TITLE
Stuck on Loading Database 

### ISSUE THREAD

**Issue by ruthvikkonda** [sequelpro/sequelpro#3388] opened 2019-02-19 01:25 UTC
I've already tried looking at previous posts with same errors and nothing has worked
Here is the exact same error that I'm having:
https://github.com/sequelpro/sequelpro/issues/794#issue-22378617

I tried everything mentioned in the previous post to fix the problem but nothing has worked.

- Sequel Pro Version: 1.1.2
- macOS Version: Mojave 10.14.1
- MySQL Version: 8.0.15

**Description**
Stuck on loading database with only the first table showing up in the top left.

**Steps To Reproduce**
1. Connect to local host (127.0.0.1)
2. Load any previous database created

**Expected Behaviour**
Load the database and all the tables with it.

**Additional Context**

<img width="950" alt="screen shot 2019-02-18 at 5 23 49 pm" src="https://user-images.githubusercontent.com/40615074/52983936-229ddb80-33a2-11e9-8c22-89b079a875c3.png">

**Comment by stychos** [comment] 2019-02-19 01:28
Use nightly builds, 1.1.2 is unstable on Mojave (or you can try [my build](https://github.com/stychos/sequelpro/releases)).

**Comment by ruthvikkonda** [comment] 2019-02-19 01:31
Where do I go to download the nightly build?

**Comment by stychos** [comment] 2019-02-19 01:31
https://sequelpro.com/test-builds

**Comment by ruthvikkonda** [comment] 2019-02-19 01:38
My database loaded perfectly! Thank you so much! One more question. I'm new to Sequel Pro; I just started using it today. Do I have to save anything after editing my tables/database? So far all I've done is add my "localhost" connection to favorites, and every time I launch Sequel Pro, I connect to that localhost and then load in my database. Should I be saving or doing anything?

**Comment by ruthvikkonda** [comment] 2019-02-19 01:43
Also is there a way to switch the theme of the sequel pro nightly back to white? The dark theme's icons and the interface aren't that polished if I'm being honest. They're hard to make out and it's slightly harder to use the application with this dark theme on
<img width="157" alt="screen shot 2019-02-18 at 5 43 03 pm" src="https://user-images.githubusercontent.com/40615074/52984509-abb61200-33a4-11e9-8592-04e72b006bcd.png">
<img width="378" alt="screen shot 2019-02-18 at 5 43 06 pm" src="https://user-images.githubusercontent.com/40615074/52984511-abb61200-33a4-11e9-87dc-a4f6f1d06a4c.png">

**Comment by stychos** [comment] 2019-02-19 01:52
That's fixed in my build, you can use it or made your own with these PR's: https://github.com/sequelpro/sequelpro/pull/3386, https://github.com/sequelpro/sequelpro/pull/3375, https://github.com/sequelpro/sequelpro/pull/3387

**Comment by stychos** [comment] 2019-02-19 01:57
> One more question. I'm new to Sequel Pro; I just started using it today. Do I have to save anything after editing my tables/database? So far all I've done is add my "localhost" connection to favorites, and every time I launch Sequel Pro, I connect to that localhost and then load in my database. Should I be saving or doing anything?

It's a database front-end, database performs all actions immediately (until you're using transactions).

**Comment by ruthvikkonda** [comment] 2019-02-19 03:58
Oh okay thank you for all your help!

**Comment by dmoagx** [comment] 2019-02-19 11:48
Duplicate of #2699

**Closed by dmoagx** 2019-02-19 11:48 UTC

**Comment by lariskau** [comment] 2019-06-05 13:03
Nightly build works for me too thank you so much!

**Comment by jjoek** [comment] 2019-07-02 13:59
Nightly build works for me as well. Thanks

**Comment by easonlin404** [comment] 2019-07-17 03:33
Same problems. Nightly build worked for well. Thanks.

**Comment by TedAce** [comment] 2019-07-25 06:20
Nightly build fixed a problem. Thanks

**Comment by chrismaltais** [comment] 2019-09-14 21:41
Nightly build fixed the issue for me as well, cheers! 🎉

**Comment by CollinHerber** [comment] 2019-11-01 17:44
Night build fixed my problems as well.

**Comment by taotao9125** [comment] 2019-11-04 04:49
Nightly build works for me , thank you so much.

**Comment by jakobheuer** [comment] 2019-11-13 11:02
Praise nightly build 🎉

**Comment by dhavalkakkad** [comment] 2020-03-18 09:36
NIghtly build works for me too. Thanks :-)

**Comment by Stetzon** [comment] 2020-03-19 13:00
+1 for nightly build - on High Sierra

**Comment by laurentsmohr** [comment] 2020-03-24 10:01
+1 for nightly build on High Sierra, mysql 8.0.19 (old authentication)
This should be patched in the main version, to save some pain for others :)

**Comment by korikiyu** [comment] 2020-05-24 18:10
wow it worked for me too. Thank you a million

**Comment by howtomakeaturn** [comment] 2020-09-15 08:17
NIghtly build works for me too. Thanks :-)

**Comment by jobayedsumon** [comment] 2020-09-21 15:41
Thanks for the test build suggestion guys.

**Comment by rey-born** [comment] 2021-05-27 04:45
Nightly build worked for me. Thanks!

**Comment by sunilgodithi** [comment] 2021-06-07 01:13
Worked for me as well, Thank you

**Comment by nishantpatel227** [comment] 2021-07-08 16:17
That worked for me. Thank you

**Comment by hmaesta** [comment] 2021-09-09 14:49
For anyone arriving in 2021 _or later..._ Download [Sequel Ace](https://github.com/Sequel-Ace/Sequel-Ace).

**Comment by lailyn** [comment] 2023-01-23 15:12
woaah, you saved my live. [It](https://sequelpro.com/test-builds) works for me!!

**Comment by nilesbyzt** [comment] 2023-06-23 18:21
that worked!! thanks
