### ISSUE TITLE
Mac Mojave closing Tab Crashes App

### ISSUE THREAD

**Issue by mike-s-** [sequelpro/sequelpro#3416] opened 2019-03-14 22:46 UTC
I am still having issues with the issue that was reported in 3116. I also know that another colleague that I work with who has the same mac as I do has the same exact issue.
Also to note I am running this on a MacBook Pro (15-inch, 2018) with a 2.2 GHz Intel Core i7 processor and 32 GB of ram.

- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.2
- MySQL Version: 5.7.12

**Steps To Reproduce**
1. Open a window
2. Open another window
3. Close either of those windows
4. App crashes

Crash logs https://gist.github.com/mike-s-/b47435aecb149e03720bfd7a053d1f66

Thanks,

**Comment by dmoagx** [comment] 2019-03-15 10:34
Duplicate of #3116

**Closed by dmoagx** 2019-03-15 10:34 UTC
