### ISSUE TITLE
cprefsd causing Sequel Pro to crash/become unresponsive.

### ISSUE THREAD

**Issue by mstnorris** [sequelpro/sequelpro#3135] opened 2018-08-14 12:17 UTC
Since yesterday evening (no known changes from myself nor any software updates have been installed) Sequel Pro has been Not Responding/displaying the spinning beach ball upon opening a connection. I usually have between 1-10 tabs open but this is now happening with just one connection open. The cprefsd process is using upwards of 80% CPU. cprefsd stores all the user defaults/settings for an app.

macOS High Sierra 10.13.6 (17G65)
Sequel Pro 1.1.2 Build 4541 (602e11a)

Apologies I don't know what else may help you, but if there is anything specific that I can tell you that will help let me know.

*Update 1*

If I kill the cprefsd process Sequel Pro responds again and I can continue until the process is spun up again (shortly after).

*Update 2*

I've deleted Sequel Pro (and all the config/plist files using AppZapper) and ran it again as-if-new. This seems to be performing OK at the moment so I guess there was something wrong when setting up a new favourite or similar.

**Comment by dmoagx** [comment] 2018-08-14 20:06
Duplicate of #687

**Closed by dmoagx** 2018-08-14 20:06 UTC
