### ISSUE TITLE
SQL Export of JSON fields is broken

### ISSUE THREAD

**Issue by iCodr8** [sequelpro/sequelpro#3352] opened 2019-01-11 08:33 UTC
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.2
- MySQL Version: 5.7.24

**Description**
When the data of a table with a JSON field is exported, then it can not be imported back to sequel pro.

This error is printed, when the exported sql file will be imported:

```
mysql Cannot create a JSON value from a string with CHARACTER SET 'binary'.
```

The solution to fix this problem is to add a convert to the data of the field:

```
(X'[^,\)]*')
CONVERT($1 using utf8mb4)
```

See:
https://stackoverflow.com/a/42029919/8518463

**Comment by dmoagx** [comment] 2019-01-11 08:38
Duplicate of #2647

**Closed by dmoagx** 2019-01-11 08:38 UTC

**Comment by roncarino** [comment] 2020-03-03 01:24
> Duplicate of #2647

I think this is the last thread mentioning this issue.
> I think this has already been fixed in #2199 and will be included in the next release.
> 
> You can try a nightly build from https://sequelpro.com/nightly/

Hi @dmoagx, first of all, thanks for your work. 
Just for reference, this problem is still happening even on nightly version you linked on #2647.
I am on last nightly version Build 5446 (97c1b857). All the threads seem to be Closed.

Cheers, Loris

**Comment by dmoagx** [comment] 2020-03-03 22:25
Please provide detailed steps to reproduce.

**Comment by roncarino** [comment] 2020-03-04 10:01
- Sequel Pro Nightly Build: 5446 (97c1b85)
- MacOs Version: Mojave 10.14.6
- MySQL Version: 14.14 Distrib 5.7.28, for Linux (x86_64)

All the rest is same of first message from @iCodr8. Here the copy:

Description
When the data of a table with a JSON field is exported, then it can not be imported back to sequel pro.

This error is printed, when the exported sql file will be imported:

`> mysql Cannot create a JSON value from a string with CHARACTER SET 'binary'.`

The solution to fix this problem is to add a convert to the data of the field:

```
(X'[^,\)]*')
CONVERT($1 using utf8mb4)
```
See:
[https://stackoverflow.com/a/42029919/8518463](https://stackoverflow.com/a/42029919/8518463)
