### ISSUE TITLE
crashes when I try to open a database

### ISSUE THREAD

**Issue by nutmix** [sequelpro/sequelpro#3059] opened 2018-05-23 12:26 UTC
how to reproduce:

1. download the latest sequel pro from website and install.
1. connect to mysql installed on localhost using 127.0.0.1 and root user/pass
1. select a database from the dropdown.
1. crashes.  Fails to report error (gets a timeout).

It is worth noting that I can connect with Toad Edge and mysql workbench no problem to the database.  Only sequelpro fails.
Mac OS 10.13.4
mysql 8.x

Also, after install, when I try to run the app again, spotlight cant find it.

**Comment by dmoagx** [comment] 2018-05-23 17:22
Duplicate of #2699

**Closed by dmoagx** 2018-05-23 17:22 UTC

**Comment by paepcke** [comment] 2018-12-08 19:15
The discussion on #2699 was (productively) locked. I did follow jpmurray's instructions on installing the nightly, and that did solve my problem. Mojave 10.14. MySQL 8.0.11. 

I had originally installed MySQL Pro 1.1.2 directly. I removed the .app from the Applications folder, and used jpmurray's brew based instruction to install the nightly. This was successful.

**Comment by samholst** [comment] 2019-03-13 04:20
Nightly seemed to have fixed mine as well. I was experiencing the same issue of MacOS Mojave.

**Comment by Gowtham-chidambaranathan** [comment] 2020-08-25 17:11
ss
