### ISSUE TITLE
BIT fields are displaying opposite values

### ISSUE THREAD

**Issue by pbienick** [sequelpro/sequelpro#2332] opened 2015-11-20 15:21 UTC
In Sequel Pro 1.1, all bit fields are displaying the opposite value of what is actually stored in the database. I've confirmed this both with a friend running SQL Workbench and the mysql command line. Additionally, if I attempt to change the value of a bit field in the grid, I get a message that says "The row was not written to the MySQL database. You probably haven't changed anything....". 

For example, there's one field in our main user table called "account_enabled". It's displaying '00000000' for all records - if that were true, nobody would be able to login. If I try to change the value of that field to a '1', I get the aforementioned message. 

I am using MySQL 5.6.25.

**Comment by dmoagx** [comment] 2015-11-20 15:43
Duplicate of #2254 
Please search for existing issues before creating a new one!

**Closed by dmoagx** 2015-11-20 15:43 UTC

**Comment by pbienick** [comment] 2015-11-20 15:55
Thank you, and I apologize, but I definitely searched for this issue before reporting. Looks like I missed the default filter that only queries for open issues.
