### ISSUE TITLE
Queries locking entire window when run via GUI

### ISSUE THREAD

**Issue by nexbridge** [sequelpro/sequelpro#2882] opened 2017-09-12 11:05 UTC
When I perform a query that takes a long time, e.g. an ALTER TABLE query on a large table, if I run it from the query editor then a pop-up appears (with an option to stop the query), and while it's running I can then click on other connection tabs and continue working on other stuff - which is great.  But if I do it via the GUI, e.g. change a column attribute in the structure tab, then the pop-up doesn't appear, and instead it locks the entire Sequel Pro window (i.e. all tabs) until the query is complete - so for example if it takes an hour to complete then that means I'm unable to work on any other tabs during that time!

I'm using Sequel Pro 1.1.2 on macOS 10.12.6.

**Comment by dmoagx** [comment] 2017-09-12 11:34
Duplicate of #710

**Closed by dmoagx** 2017-09-12 11:34 UTC
Labels: Duplicate
