### ISSUE TITLE
Bind ctrl-h key to Backspace

### ISSUE THREAD

**Issue by takahashi-croco** [sequelpro/sequelpro#2605] opened 2016-10-27 00:50 UTC
Please bind ctrl-h key to Backspace.
In other mac app, always backspace with ctrl-h key.

**Comment by dmoagx** [comment] 2016-11-20 22:25
Duplicate of: #1974 
See: 1974#issuecomment-54702112 (disregard the part about nightly builds. This is already included in 1.1.2)

**Closed by dmoagx** 2016-11-20 22:25 UTC
