### ISSUE TITLE
Resizing window using third party window snapping tools leads to blank space

### ISSUE THREAD

**Issue by advicepyro** [sequelpro/sequelpro#3267] opened 2018-10-31 21:09 UTC
- Sequel Pro Version: Build 5418 (78067124)
- macOS Version: 10.14.1
- MySQL Version: 5.7.23

**Description**
When using a third party tool such as BetterTouchTool to instantly resize the window (i.e. Windows 7+ style window snapping), the nightly Sequel Pro builds do not pickup on the window size change, and as a result there is a large gap.

This does not happen when using the standard green zoom button.

**Steps To Reproduce**
1. Use a tool like BetterTouchTool, or any equivalent tool that mimics Windows window snapping.
2. Resize the window to fill the screen.

**Additional Context**
See screenshot:

![screen shot 2018-10-31 at 5 05 13 pm](https://user-images.githubusercontent.com/6377466/47819040-b6826380-dd2f-11e8-8d8a-f30cfe620d9d.png)

**Comment by dmoagx** [comment] 2018-10-31 23:52
Duplicate of #3091

**Closed by dmoagx** 2018-10-31 23:52 UTC
