### ISSUE TITLE
Multiple editor tabs

### ISSUE THREAD

**Issue by PierceMcGeough** [sequelpro/sequelpro#2486] opened 2016-04-26 12:01 UTC
This was a great feature in SQLyog.

Within the one connection you should be able to have multiple tabs for queries and content views.

From the view your Structure, Content, etc... tabs should be available for each working tab.

On Editor Tab 1 you could be viewing the Users table and have a few queries wrote in the query tab
On Editor Tab 2 you could be viewing the Clients table with queries related to that in the query tab

And as you switch between editor tabs your place and content on the main tabs are maintained

**Comment by abhibeckert** [comment] 2016-04-26 21:28
Currently your only option is to have multiple tabs (or windows) for the same server.

Duplicate of #1069.

**Closed by abhibeckert** 2016-04-26 21:28 UTC

**Comment by PierceMcGeough** [comment] 2016-04-27 08:06
Sorry didn't see the other issue.
