### ISSUE TITLE
Crash when linking via binary foreign key

### ISSUE THREAD

**Issue by Feng-Shui** [sequelpro/sequelpro#3170] opened 2018-09-18 04:36 UTC
Hi,

Getting a consistent crash last night re binary foreign keys.

Running MySQL `5.7.23-0ubuntu0.18.04.1`.

Using [spatie/laravel-binary-uuid](https://github.com/spatie/laravel-binary-uuid) to use binary UUIDs as primary keys.  When clicking the link icon to take you to the referenced table, I'm getting the following crash.  However, the navigation works in the sense that the target table is opened.

Happy to provide any extra info including sample SQL if that's useful.

Really appreciate the product, just made a donation to say thanks!

```
NSInternalInconsistencyException

Invalid parameter not satisfying: aTitle != nil

(
	0   CoreFoundation                      0x00007fff382a72db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5f448c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff382ad072 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff3a3d6340 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   AppKit                              0x00007fff357bb840 -[NSMenu indexOfItemWithTitle:] + 503
	5   AppKit                              0x00007fff357bb61d -[NSMenu itemWithTitle:] + 22
	6   Sequel Pro                          0x000000010001fe55 -[SPTableContent setTableDetails:] + 6699
	7   Foundation                          0x00007fff3a3652b5 __NSThreadPerformPerform + 334
	8   CoreFoundation                      0x00007fff3823fa11 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff382f942c __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff38222470 __CFRunLoopDoSources0 + 208
	11  CoreFoundation                      0x00007fff382218ed __CFRunLoopRun + 1293
	12  CoreFoundation                      0x00007fff38221153 CFRunLoopRunSpecific + 483
	13  HIToolbox                           0x00007fff3750bd96 RunCurrentEventLoopInMode + 286
	14  HIToolbox                           0x00007fff3750bb06 ReceiveNextEventCommon + 613
	15  HIToolbox                           0x00007fff3750b884 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff357bca73 _DPSNextEvent + 2085
	17  AppKit                              0x00007fff35f52e34 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	18  AppKit                              0x00007fff357b1885 -[NSApplication run] + 764
	19  AppKit                              0x00007fff35780a72 NSApplicationMain + 804
	20  Sequel Pro                          0x0000000100002454 start + 52
	21  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by dmoagx** [comment] 2018-09-26 21:03
Duplicate of #2098

**Closed by dmoagx** 2018-09-26 21:03 UTC
