### ISSUE TITLE
automatic excute table structure alter command

### ISSUE THREAD

**Issue by InspireXie** [sequelpro/sequelpro#3020] opened 2018-03-30 16:18 UTC
the software always try to do this command automatically：
 ALTER TABLE `xxx` COMMENT = '';
however, i don't have permission to modify table stucture .
so, it would give me a warn.
"An error occurred when trying to change the table's comment to ''.  
MySQL said: ALTER command denied to ...."
how can I disable  automatic excute table structure alter command?

**Comment by dmoagx** [comment] 2018-03-31 15:00
Sequel Pro doesn't automatically execute any ALTER queries.
The only way the command you mentioned would be executed, is if you go to Table Info, select the text in the comment box, remove all of it and then leave the comment box.

What exact version are you using?

**Comment by InspireXie** [comment] 2018-04-04 06:24
the create syntax shows comments rightly,but  the comment box shows ‘’, so, as you said, because the the comment box shows ‘’ , Sequel Pro may thought I remove all comments and then leave the comment box. but actually i did nothing, just because it shows '' instead of the really comment at first .

**Comment by InspireXie** [comment] 2018-04-04 06:26
so , can i disable this future (disable any alter sql in settings ),or any other way to fix this problem ?

**Comment by InspireXie** [comment] 2018-05-11 08:48
sorry for my reply is so late,
the version is Snapshot Build 5224 (3477d223)

**Comment by dmoagx** [comment] 2018-07-06 21:00
The [GitHub page](https://github.com/alibaba/oceanbase) seems to be pretty much dead and all other content is in Chinese only (and I don't speak Chinese).

So unless you can provide a server I can connect to in order to reproduce this, I can't do anything here.

**Comment by InspireXie** [comment] 2018-08-29 07:17
sorry, I can't  provide the server to u since the database is belong to our company.
but thanks anyway.
best wishes ~

**Comment by dmoagx** [comment] 2018-10-14 16:45
Closing, because we are not able to triage the cause.

**Closed by dmoagx** 2018-10-14 16:45 UTC
Labels: WaitingOnUser
