### ISSUE TITLE
Adding a database user crashes the application

### ISSUE THREAD

**Issue by mfronmark** [sequelpro/sequelpro#2128] opened 2015-06-04 15:03 UTC
I have had this issue since installing version 1.0.2.

No matter the host or mysql version, the application crashes after I add a database user. Doens't matter if I add rights or not.

**Comment by dmoagx** [comment] 2015-06-04 15:04
Duplicate of #1961.
Please search for existing issues before creating a new one.

**Closed by dmoagx** 2015-06-04 15:04 UTC

**Comment by mfronmark** [comment] 2015-06-04 15:06
Wow, that was fast. I did search but didn't find anything when I did.
