### ISSUE TITLE
Fresh Installation, can't do anything.

### ISSUE THREAD

**Issue by domluther** [sequelpro/sequelpro#3120] opened 2018-07-22 16:56 UTC
I am running a clean installation of the latest version of High Sierra. I installed mysql using brew, set the server running then downloaded and ran Sequel Pro. I socket connect (localhost, username, password) and then select a database. When I do this it automatically brings up the below error. I try to submit it and after a while it says 'Error submitting your feedback to the server. The request timed out'. If I close the submit error screen then it shows the grey box saying Loading Database 'NewBetting'... but that never finishes. 

MySQL 8.0.1.1 and SequelPro 1.1.2

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000002ab60

(
	0   CoreFoundation                      0x00007fff442472db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6b3e8c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff442dfdb4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff441bd820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff441bd1e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff462cc1f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff6c31a661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff6c31a50d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff6c319bf9 thread_start + 13
)

**Comment by dmoagx** [comment] 2018-07-22 17:02
Duplicate of #2699

**Closed by dmoagx** 2018-07-22 17:02 UTC
