### ISSUE TITLE
LOGO background

### ISSUE THREAD

**Issue by Val-istar-Guo** [sequelpro/sequelpro#2665] opened 2017-01-19 11:50 UTC
![ce4d1b4f-9798-4489-8e5e-0022a709f614](https://cloud.githubusercontent.com/assets/12405937/22105722/57392f62-de80-11e6-838f-a23116718445.png)

安装之后，logo有一个莫名的白色背景让人感觉很奇怪。

**Comment by fmalizia21** [comment] 2017-01-19 14:44
Same issue
![Uploading Schermata 2017-01-19 alle 15.43.53.png…]()

**Comment by stuconnolly** [comment] 2017-01-19 22:13
Duplicate of #2623 

Fix will be in the next release.

**Closed by stuconnolly** 2017-01-19 22:13 UTC
