### ISSUE TITLE
Long operations (import data/alter table etc.) should not block other tabs

### ISSUE THREAD

**Issue by dylanwenzlau** [sequelpro/sequelpro#2352] opened 2015-12-06 21:06 UTC
I very frequently find myself unable to use the Structure tab in Sequel Pro to change columns, because it will lock the program for the entire duration of the ALTER. Because of that I frequently end up using raw SQL to modify columns, which is good practice for me, but kind of defeats the purpose of having the Structure tab at all.

Same problem with importing data. I just had to wait several minutes for a 1 GB file to import, and I was unable to use Sequel Pro during that time. It presents a huge problem for those like myself who use SQL constantly. I can always jump to the command line or write custom application code, but again that kind of defeats the purpose of having an awesome SQL tool like Sequel Pro.

**Comment by dmoagx** [comment] 2015-12-06 21:09
Duplicate of #710 

Duplicate of #1004

**Closed by dmoagx** 2015-12-06 21:09 UTC

**Comment by dylanwenzlau** [comment] 2015-12-06 21:14
Wow, those have been open for a while, I guess that explains why I didn't see them with my quick scan of the recent issues.

**Comment by dmoagx** [comment] 2015-12-06 21:52
Note that the lack of tab switching during import is because Apple provides **absolutely zero** support for tabbed windows in OS X, in the first place.
