### ISSUE TITLE
Not connecting on latest Mac Software 10.11

### ISSUE THREAD

**Issue by ChrisChiera** [sequelpro/sequelpro#2196] opened 2015-08-05 16:07 UTC
Error says, "Bad local forwarding specification ' 50724/127.0.0.1/3306'"

Issue also applies to Navicat now so appears to be a change in the most recent version of OS X.

**Comment by dmoagx** [comment] 2015-08-05 16:10
*sigh*
The last one was not even 6 hours ago...

Duplicate of #2050 
This has already been fixed in 1.1rc1: http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/
Please search for existing issues, before creating a new one.

**Closed by dmoagx** 2015-08-05 16:10 UTC

**Comment by ChrisChiera** [comment] 2015-08-05 16:16
Don't sigh, it's going to be ok =). Did a search for "10.11" before creating the issue, but showed 0 results. https://github.com/sequelpro/sequelpro/issues?utf8=✓&q=is%3Aissue+is%3Aopen+10.11

You may want to add "10.11" and "El Capitan" to the issue title, especially if you are easily frustrated by duplicates. The issue you mention also doesn't mention  the actual error that appears when connecting on 10.11 which is another thing people will be searching for. So imagine you will continue to get duplicates of this issue as people searching open issues, will not know to search for, "SSH Port Forwarding uses non-standard syntax" when referring this issue.

Glad it's resolved in a release candidate and

**Comment by dmoagx** [comment] 2015-08-05 16:18
You did not remove the "is:open" that GitHub automatically added in the search field:
https://github.com/sequelpro/sequelpro/issues?utf8=%E2%9C%93&q=is%3Aissue+ssh+10.11

**Comment by ChrisChiera** [comment] 2015-08-05 16:21
That's correct, I purposely was searching for "open issues" regarding the inability to connect on 10.11. If there were no open issues then I would open an issue since one still exists. No worries though, my suggestion about adding 10.11 to the existing thread is only incase getting additional duplicates will bother you, since until it's resolved in the production version people will continue to mention it presumably. Thanks for your help today.
