### ISSUE TITLE
左侧表菜单字体大小问题

### ISSUE THREAD

**Issue by jibingbing123** [sequelpro/sequelpro#3036] opened 2018-04-23 10:19 UTC
mac外接显示器后，sequel pro左侧表显示很小，字体不能调整

**Comment by dmoagx** [comment] 2018-05-01 15:55
English only, please.

**Comment by jibingbing123** [comment] 2018-05-02 01:38
After the MAC external display, the left table of sequel pro is small and the font cannot be adjusted.

**Comment by dmoagx** [comment] 2018-07-06 20:44
That is not a useful issue description.

https://github.com/sequelpro/sequelpro/wiki/How-do-I-write-a-proper-issue-report%3F

**Comment by stuconnolly** [comment] 2018-10-08 22:35
Duplicate of #2872

**Closed by stuconnolly** 2018-10-08 22:35 UTC
Labels: WaitingOnUser
