### ISSUE TITLE
SSH connection failing using El Capitan public beta

### ISSUE THREAD

**Issue by ipearx** [sequelpro/sequelpro#2176] opened 2015-07-15 07:23 UTC
When connecting I receive the error: "The SSH Tunnel has unexpectedly closed" when using the El Capitan 10.11 Beta (15A215h). Exact same configuration was fine with Yosemite.

The following is under 'error detail'. When attempting the used command in Terminal, it appears to work fine. Note I've obfuscated the server and username.

Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 -p 12111 username@server.com -L 49794/127.0.0.1/3306

Bad local forwarding specification ' 49794/127.0.0.1/3306'

**Comment by Jellyfrog** [comment] 2015-07-15 07:59
Ive got el capitan in my other macbook and it works fine there, try nightly?
The correct syntax for forwarding is `-L 49794:127.0.0.1:3306`

**Comment by dmoagx** [comment] 2015-07-15 08:23
Duplicate of #2050 
This has already been fixed in 1.1rc1: http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/
Please search for existing issues, before creating a new one.

**Closed by dmoagx** 2015-07-15 08:23 UTC

**Comment by codestic** [comment] 2015-10-14 10:58
@dmoagx You, are the real hero here. This drove me nuts! :)

**Comment by infynity** [comment] 2017-03-09 06:02
### just update sequel
