### ISSUE TITLE
Launch Sequel Pro and open favorite from terminal

### ISSUE THREAD

**Issue by kevinkaske** [sequelpro/sequelpro#2723] opened 2017-03-10 22:34 UTC
It would be great to have the option to launch Sequel Pro and open a favorite right from the terminal. Something like sequelpro --open NameOfFav

If this option exists I have not been able to find documentation on it.

**Comment by stuconnolly** [comment] 2017-04-01 21:32
Duplicate of #206

**Closed by stuconnolly** 2017-04-01 21:32 UTC
Labels: Duplicate
