### ISSUE TITLE
opening some tables in information_schema on mysql 8.0.12 will crash or keeps reloading data.

### ISSUE THREAD

**Issue by steve3d** [sequelpro/sequelpro#3174] opened 2018-09-24 07:51 UTC
I'm using mysql 8.0.12 from homebrew, and with latest source cloned from this repo, when I try to open some table in `information_schema`, like `CHARACTER_SETS`, `COLUMNS`, then sequel pro either keeps reloading data forever or crash after few seconds.

but with latest mariadb 10.3.x, it's ok to open any table in `information_schema`.

**Comment by steve3d** [comment] 2018-09-26 00:52
<img width="1091" alt="2018-09-26 8 51 36" src="https://user-images.githubusercontent.com/670687/46050936-65e47d00-c169-11e8-97dc-8ea299f96cf0.png">

I think this is different, look at the screen shot, it keeps this way forever or crash after a few seconds.

**Comment by dmoagx** [comment] 2018-09-26 09:46
No that is exactly what #3121 is about.

Duplicate of #3121

**Closed by dmoagx** 2018-09-26 09:46 UTC
Labels: WaitingOnUser
