### ISSUE TITLE
command+w will crash

### ISSUE THREAD

**Issue by JasonMsbaby** [sequelpro/sequelpro#3444] opened 2019-04-09 13:26 UTC
when open multiple tab and press cmd+w want to close this tab
the app crash

**Comment by mklahorst** [comment] 2019-04-10 21:03
Same here, but really any time I have multiple tabs open, and close one tab, all of Sequel Pro crashes - happens 99.99% of the time. using latest version.

**Comment by dmoagx** [comment] 2019-04-10 21:38
Duplicate of #3116

**Closed by dmoagx** 2019-04-10 21:38 UTC
