### ISSUE TITLE
Feature Request - JSON view in the field editor

### ISSUE THREAD

**Issue by jladerer** [sequelpro/sequelpro#2487] opened 2016-04-27 17:24 UTC
It would be convenient to have a JSON formatting when editing TEXT fields. If you save it with the formatting then the string is no longer valid JSON when it is queried.

Perhaps adding another button down by Text Image Hex or a dropdown option or something.

I'm sure XML formatting would be nice too. :)

![screen shot 2016-04-27 at 1 05 56 pm](https://cloud.githubusercontent.com/assets/13121125/14861438/3a6686a0-0c7b-11e6-9a08-c90ffce7611f.png)

**Comment by dmoagx** [comment] 2016-04-27 18:24
Duplicate of #2310

**Closed by dmoagx** 2016-04-27 18:24 UTC
