### ISSUE TITLE
Modify Stored Funcs and Procs

### ISSUE THREAD

**Issue by optikalefx** [sequelpro/sequelpro#1890] opened 2014-01-30 23:05 UTC
It would be really awesome (and quick) to allow us to edit the stored func or proc from the quick open. Just drop the function or proc and re-create it. It's a pain to always write that syntax every time I wanna make 1 change.

**Comment by stuconnolly** [comment] 2018-10-09 22:16
Duplicate of #82

**Closed by stuconnolly** 2018-10-09 22:16 UTC
Labels: Duplicate
