### ISSUE TITLE
Sequel Pro encountered an unexpected error when select database in MySQL 8.0.12

### ISSUE THREAD

**Issue by jichengli** [sequelpro/sequelpro#3236] opened 2018-10-15 07:15 UTC
![image](https://user-images.githubusercontent.com/43261602/46935143-e02f5f80-d08c-11e8-800e-65b96138d55d.png)
> Preferences
```
{
    BlobTextEditorSpellCheckingEnabled = 0;
    CSVFieldImportMappingAlignment = 0;
    CSVImportFieldEnclosedBy = "\"";
    CSVImportFieldEscapeCharacter = "\\ or \"";
    CSVImportFieldTerminator = ",";
    CSVImportFirstLineIsHeader = 0;
    CSVImportLineTerminator = "\\r\\n";
    CustomQueryEditorBackgroundColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 666683a1 a0203e83 a9a8283e 83d9d858 3e0186>;
    CustomQueryEditorBacktickColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 66660183 f3f2f23e 83c7c646 3f0186>;
    CustomQueryEditorCaretColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 666683f9 f8783f83 f9f8783f 83f3f272 3f0186>;
    CustomQueryEditorCommentColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 6666839f 9e9e3e83 b9b8b83e 83969515 3f0186>;
    CustomQueryEditorHighlightQueryColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 666683d1 d0503e83 d9d8583e 838f8e8e 3e0186>;
    CustomQueryEditorNumericColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 666683be bd3d3f83 9493133f 83faf979 3f0186>;
    CustomQueryEditorQuoteColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 666683f2 f1713f83 fbfa7a3f 838d8c0c 3f0186>;
    CustomQueryEditorSQLKeywordColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 6666838c 8b0b3f83 eae9693f 83fefd7d 3f0186>;
    CustomQueryEditorSelectionColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 66668389 88883e83 8f8e8e3e 83b5b4b4 3e0186>;
    CustomQueryEditorTextColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 666683f9 f8783f83 f9f8783f 83f3f272 3f0186>;
    CustomQueryEditorThemeName = "User-defined";
    CustomQueryEditorVariableColor = <040b7374 7265616d 74797065 6481e803 84014084 8484074e 53436f6c 6f720084 84084e53 4f626a65 63740085 84016301 84046666 666683fd fcfc3e83 fdfcfc3e 83fdfcfc 3e0186>;
    "FRFeedbackReporter.lastCrashCheckDate" = "2018-10-15 07:00:59 +0000";
    GlobalResultTableFont = <040b7374 7265616d 74797065 6481e803 84014084 8484064e 53466f6e 741e8484 084e534f 626a6563 74008584 01692484 055b3336 635d0600 00001a00 0000fffe 4c007500 63006900 64006100 47007200 61006e00 64006500 00008401 660e8401 63009801 98009800 86>;
    LastImportIntoNewTableEncoding = Default;
    LastImportIntoNewTableType = Default;
    LastUsedVersion = 4541;
    LastViewMode = 1;
    NSNavPanelExpandedSizeForOpenMode = "{704, 437}";
    NSNavPanelExpandedSizeForSaveMode = "{712, 585}";
    "NSSplitView Subview Frames DBViewSplitter" =     (
        "0.000000, 0.000000, 261.000000, 692.000000, NO, NO",
        "262.000000, 0.000000, 1178.000000, 692.000000, NO, NO"
    );
    "NSSplitView Subview Frames SPBundleEditorSplitView" =     (
        "0.000000, 0.000000, 142.000000, 552.000000, NO, NO",
        "143.000000, 0.000000, 757.000000, 552.000000, NO, NO"
    );
    "NSSplitView Subview Frames SPContentFilterSplitView" =     (
        "0.000000, 0.000000, 213.000000, 361.000000, NO, NO",
        "214.000000, 0.000000, 286.000000, 361.000000, NO, NO"
    );
    "NSSplitView Subview Frames SPNavigatorSchemaStatus" =     (
        "0.000000, 0.000000, 395.000000, 233.000000, NO, NO",
        "0.000000, 234.000000, 395.000000, 100.000000, NO, NO"
    );
    "NSSplitView Subview Frames SPQueryFavoriteSplitView" =     (
        "0.000000, 0.000000, 177.000000, 363.000000, NO, NO",
        "178.000000, 0.000000, 385.000000, 363.000000, NO, NO"
    );
    "NSSplitView Subview Frames TableInfoSplitter" =     (
        "0.000000, 0.000000, 1148.000000, 111.000000, NO, NO",
        "0.000000, 120.000000, 1148.000000, 302.000000, NO, NO"
    );
    "NSTableView Columns SPTableStructureSource" =     (
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 046e616d 6586>,
        119,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 04747970 6586>,
        132,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 066c656e 67746886>,
        103,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 08756e73 69676e65 6486>,
        54,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 087a6572 6f66696c 6c86>,
        41,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 0662696e 61727986>,
        37,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 046e756c 6c86>,
        57,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 034b6579 86>,
        26,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 07646566 61756c74 86>,
        104,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 05457874 726186>,
        126,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 08656e63 6f64696e 6786>,
        116,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 09636f6c 6c617469 6f6e86>,
        121,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 07636f6d 6d656e74 86>,
        101
    );
    "NSTableView Hidden Columns SPTableStructureSource" =     (
    );
    "NSTableView Sort Ordering SPTableStructureSource" =     (
    );
    "NSToolbar Configuration TableWindowToolbar" =     {
        "TB Display Mode" = 1;
        "TB Icon Size Mode" = 1;
        "TB Is Shown" = 1;
        "TB Size Mode" = 1;
    };
    "NSToolbar Configuration com.apple.NSColorPanel" =     {
        "TB Is Shown" = 1;
    };
    "NSWindow Frame DBView" = "0 151 1440 715 0 0 1440 877 ";
    "NSWindow Frame NSFindPanel" = "222 320 528 174 0 0 1440 877 ";
    "NSWindow Frame NSFontPanel" = "726 314 445 237 0 0 1440 877 ";
    "NSWindow Frame QueryConsole" = "0 60 1440 817 0 0 1440 877 ";
    "NSWindow Frame SPCSVFieldMappingSheet" = "2065 443 634 370 1440 -126 1920 1057 ";
    "NSWindow Frame SPContentFilterManagerWindow" = "442 310 500 393 0 0 1440 877 ";
    "NSWindow Frame SPCreateSyntaxSheet" = "572 411 411 363 0 0 1440 877 ";
    "NSWindow Frame SPExportWindow" = "462 247 517 520 0 0 1440 877 ";
    "NSWindow Frame SPFieldEditorBlobSheet" = "-1818 175 1294 759 -1920 -167 1920 1177 ";
    "NSWindow Frame SPFieldEditorTextSheet" = "387 349 667 450 0 0 1440 877 ";
    "NSWindow Frame SPQueryFavoriteManagerWindow" = "449 379 563 393 0 0 1440 877 ";
    "NSWindow Frame SPTableFilterPanel" = "170 282 752 339 0 0 1440 877 ";
    QueryFavoriteReplacesContent = 1;
    ResetAutoIncrementAfterDeletionOfAllRows = 1;
    SPExportLastDirectory = "/Users/tomato/Downloads";
    SPFirstRun = 0;
    SPLastFavoriteID = 6639456810744316542;
    "SPSplitView Lengths " =     (
        0,
        504
    );
    "SPSplitView Lengths DBViewSplitter" =     (
        261,
        1178
    );
    "SPSplitView Lengths SPBundleEditorSplitView" =     (
        142,
        757
    );
    "SPSplitView Lengths SPContentFilterSplitView" =     (
        213,
        286
    );
    "SPSplitView Lengths SPNavigatorSchemaStatus" =     (
        233,
        100
    );
    "SPSplitView Lengths SPQueryFavoriteSplitView" =     (
        177,
        385
    );
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2018-10-15 05:12:54 +0000";
    SULastProfileSubmissionDate = "2018-10-10 06:37:01 +0000";
    SUSendProfileInfo = 1;
    importFormatPopupValue = SQL;
}
```
> Console
```
2018年10月15日 10:58:31: Found 0 crash files
2018年10月15日 13:11:51: Found 0 crash files
2018年10月15日 13:12:25: Found 0 crash files
2018年10月15日 13:13:01: Found 0 crash files
2018年10月15日 13:20:24: Found 0 crash files
2018年10月15日 14:17:11: Found 0 crash files
2018年10月15日 14:17:44: Found 0 crash files
2018年10月15日 14:18:04: Sending feedback to http://log.sequelpro.com/submit
2018年10月15日 14:18:04: Posting 11337 bytes to http://log.sequelpro.com/submit
2018年10月15日 14:18:40: Found 0 crash files
2018年10月15日 14:18:48: Sending feedback to http://log.sequelpro.com/submit
2018年10月15日 14:18:48: Posting 11553 bytes to http://log.sequelpro.com/submit
2018年10月15日 14:19:48: Connection failed
2018年10月15日 14:19:48: Upload failed: Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x60000045b330 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=http://log.sequelpro.com/submit, NSErrorFailingURLKey=http://log.sequelpro.com/submit, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=The request timed out.}}, NSErrorFailingURLStringKey=http://log.sequelpro.com/submit, NSErrorFailingURLKey=http://log.sequelpro.com/submit, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}

```
> Exception
```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60c000223640

(
	0   CoreFoundation                      0x00007fff3ab3f2db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff61ce6c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3abd7db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff3aab5820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff3aab51e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff3cbc41f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff62c18661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff62c1850d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff62c17bf9 thread_start + 13
)

```

**Comment by jichengli** [comment] 2018-10-15 07:19
![image](https://user-images.githubusercontent.com/43261602/46935352-811e1a80-d08d-11e8-988b-572b99798eee.png)

**Comment by dmoagx** [comment] 2018-10-15 07:56
Duplicate of #2699

**Closed by dmoagx** 2018-10-15 07:56 UTC

**Comment by pardeepbattu02** [comment] 2019-03-06 13:52
This is the same error which I am getting again & again. Please help me to resolve this.

**Comment by PwntasticKev** [comment] 2019-10-16 21:08
Has this issue been resolved? I'm getting the same thing.

**Comment by at0dd** [comment] 2019-10-16 21:15
@PwntasticKev if you look at the related issue #2699 it's fixed and will be in the next release.

**Comment by PwntasticKev** [comment] 2019-10-16 21:16
> @PwntasticKev if you look at the related issue #2699 it's fixed and will be in the next release.

When will that be? lol after some digging i found this. works like a charm. https://sequelpro.com/test-builds

**Comment by Shoukat-bjr** [comment] 2019-10-27 17:36
Thanks @PwntasticKev, now it's working right way :)

**Comment by NathanielNat** [comment] 2020-03-20 15:50
How did it help ?

**Comment by NathanielNat** [comment] 2020-03-20 16:01
> Thanks @PwntasticKev, now it's working right way :)

Which version worked for you ?

**Comment by Gideonmacha** [comment] 2020-05-14 16:23
Fixed 100% working. Previously Sequel pro had problems with the latest version of mac os Mojave 10.14 and mysql 8.0, to ensure sequel pro works fine during the whole process of development you need to download Sequel pro Test build version here: https://sequelpro.com/test-builds

**Comment by alihan-dev** [comment] 2022-01-26 15:20
> > @PwntasticKev if you look at the related issue #2699 it's fixed and will be in the next release.
> 
> When will that be? after some digging i found this. works like a charm. https://sequelpro.com/test-builds

Thank you, I ran it without any problems.
