### ISSUE TITLE
Creating a new user crashes the application

### ISSUE THREAD

**Issue by arkin-** [sequelpro/sequelpro#2168] opened 2015-07-07 10:03 UTC
I have this problem in both iMac 2014, and MBP late-2011.

You connect to a MySQL server (5.5.43 ubuntu 14.04), create a new database ("test" utf-8). You then go into users, add a new one, enter a password, select all privileges for the "test" database and save.

The application then crashes, opening it back up shows the user created with permissions.

**Comment by rowanbeentje** [comment] 2015-07-07 10:08
This is a duplicate of https://github.com/sequelpro/sequelpro/issues/1961 :)

This has been fixed in 1.1RC1, available at http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/ .  (Please search for existing issues before creating new ones, including already-closed issues!)

**Closed by rowanbeentje** 2015-07-07 10:08 UTC
Labels: Duplicate

**Comment by arkin-** [comment] 2015-07-07 10:11
Ah apologies! I did do a search, my terms must have been incorrect.

P.S. Cool, an update!
