### ISSUE TITLE
create sql pro for windows and linux please

### ISSUE THREAD

**Issue by arditi-t2s** [sequelpro/sequelpro#3447] opened 2019-04-12 20:23 UTC
Please create a version for windows and linux, there is nothing that comes even close to this software, you HAVE SPOILED US NOW CAN'T GO BACK TO TRASH SOFTWARE

**Comment by stychos** [comment] 2019-04-13 10:30
it's barely alive in macOS, so I don't believe that's possible

**Comment by dmoagx** [comment] 2019-04-13 19:13
Duplicate of #2578

**Closed by dmoagx** 2019-04-13 19:13 UTC

**Comment by AdityaAnand1** [comment] 2020-03-23 14:02
> it's barely alive in macOS, so I don't believe that's possible

Supporting a bigger OS such as Windows would likely fix that 😃
