### ISSUE TITLE
BINARY field default value issues

### ISSUE THREAD

**Issue by Haravikk** [sequelpro/sequelpro#2593] opened 2016-10-09 10:13 UTC
It seems that Sequel Pro's default for binary fields isn't properly supported, or the queries it builds do not support it.

Basically, when the default is left blank for a not-null BINARY field, Sequel Pro/SQL stuffs it full of null characters like so:

```
`uuid` binary(16) NOT NULL DEFAULT '\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0'
```

However, if I attempt to move the above field in the structure view, I get an error about an invalid default value. To re-order binary rows I find I have to allow NULL (and use it as a default), then disable null values after moving it.

Almost all editing of the field will result in the same error unless the default is removed (causing it to repopulate automatically).

I assume it probably has something to do with the queries used by Sequel Pro to alter the field(s), perhaps it should handle the value in HEX form to avoid this issue?

**Comment by dmoagx** [comment] 2016-10-09 14:13
> Basically, when the default is left blank for a not-null BINARY field, Sequel Pro/SQL stuffs it full

No, it doesn't.
That is entirely MySQLs doing.
It seems you are confusing `VARBINARY` (up to X bytes) and `BINARY` (exactly X bytes).

As for the other problem:
Duplicate of #1957

**Closed by dmoagx** 2016-10-09 14:13 UTC
