### ISSUE TITLE
In macos-mojave version，close tab will crash.

### ISSUE THREAD

**Issue by wwaayyaa** [sequelpro/sequelpro#3176] opened 2018-09-25 08:57 UTC
In MacOS-mojave version，close tab will crash.
sequel pro version：1.1.2  build 4541

**Comment by dmoagx** [comment] 2018-09-25 18:36
Duplicate of #3075 

Also: https://github.com/sequelpro/sequelpro/issues/3175#issuecomment-424452480

**Closed by dmoagx** 2018-09-25 18:36 UTC
