### ISSUE TITLE
Full of bugs since Mac OS 10.14

### ISSUE THREAD

**Issue by thsantac** [sequelpro/sequelpro#3414] opened 2019-03-14 19:26 UTC
Hi,

This app I used to love so much despite some annoying bugs has become more and more unusable since Mojave.

1- With several tabs opened : if you close one tab, app quits.
2-Very annoying : sometimes, when you insert some data in tables, data are not inserted. You have to quit the app and relaunch it to see noting has been inserted.

Is there any plan to get this app compatible with Mojave ?

Thanks

**Comment by dmoagx** [comment] 2019-03-15 10:34
Duplicate of #3116

**Closed by dmoagx** 2019-03-15 10:34 UTC
