### ISSUE TITLE
Query execution time misreported over ssh connections

### ISSUE THREAD

**Issue by gdsmith** [sequelpro/sequelpro#2889] opened 2017-09-22 09:22 UTC
The query execution time for queries run over SSH seems to include some overhead (perhaps for the transfer times) and not just the time for the execution of the query.

In Sequel Pro:
<img width="340" alt="screenshot 2017-09-22 13 16 58" src="https://user-images.githubusercontent.com/908695/30737624-5d2f1af6-9f98-11e7-9919-c0c68430bc2e.png">

vs on the server:
<img width="223" alt="screenshot 2017-09-22 13 20 00" src="https://user-images.githubusercontent.com/908695/30737770-c905adbc-9f98-11e7-90a3-fb8a784c8330.png">

Is there any way of setting it so it displays only the execution time?

**Comment by dmoagx** [comment] 2017-09-22 17:09
See https://github.com/sequelpro/sequelpro/issues/264#issuecomment-207645163
Duplicate of #264

**Closed by dmoagx** 2017-09-22 17:09 UTC
