### ISSUE TITLE
Upside down text in table listing

### ISSUE THREAD

**Issue by jpike88** [sequelpro/sequelpro#3368] opened 2019-01-29 03:29 UTC
- Sequel Pro Version: Latest nightly
- macOS Version: HiMojave
- MySQL Version: 5.7

**Description**
See screenshot
![screen shot 2019-01-29 at 10 28 11 am](https://user-images.githubusercontent.com/9585787/51882222-bd615680-23b0-11e9-8920-5fdb8d110ca7.png)

**Steps To Reproduce**
1. Connect to a database
2. Happens occasionally

**Comment by dmoagx** [comment] 2019-01-29 22:51
Duplicate of #3214

**Closed by dmoagx** 2019-01-29 22:51 UTC
