### ISSUE TITLE
Filter toolbar less useful in build 78067124 than in previous releases

### ISSUE THREAD

**Issue by freezey** [sequelpro/sequelpro#3262] opened 2018-10-29 18:12 UTC
The experience I am accustomed to with the filter bar in Sequel Pro is that it is always present and that the filter can be quickly cleared by clicking a small X icon.

In the most recent nightly build (78067124 - which I just installed this morning) the filter bar is only present after hitting cmd+F or pulling it up from the menu and I do not see a way to dismiss the filter bar or clear the filter.  I tried just erasing the text from the filter input, but it threw an error "No valid SQL expression could be generated. Make sure that you have filled in all required fields".

For me - the previous behavior was much more useful.  I browse databases every day and I use the quick filter option dozens of times per day.  I prefer having the filter bar open all the time, and having a quick way to dismiss the current filter is a must.

(
UPDATED feedback after a couple weeks of use in a follow-up post below
https://github.com/sequelpro/sequelpro/issues/3262#issuecomment-440829909
)

**Comment by jpike88** [comment] 2018-10-30 07:13
Filter toolbar should be present by default, I had no idea how to get it back until I saw this

**Comment by pernielsentikaer** [comment] 2018-10-30 07:38
Yes, same problem. Also waiting for something like an inputfield where its possible to write your own search creterias ;)

**Comment by dmoagx** [comment] 2018-10-30 19:49
> I do not see a way to dismiss the filter bar or clear the filter.

![bildschirmfoto 2018-10-30 um 20 47 10 740](https://user-images.githubusercontent.com/5793864/47745918-1f60d180-dc85-11e8-8a2a-cd66d11b226c.png)

**Comment by pernielsentikaer** [comment] 2018-10-31 06:59
If its possible to "open" it with cmd+f - should'nt it be possible to close it again that way?

**Comment by chrisvickers** [comment] 2018-10-31 13:50
I would agree with @pernielsentikaer on this. Either put it back by default or use a shortcut.

**Comment by dmoagx** [comment] 2018-10-31 20:14
> Could it also be possible to not show the 'Filter' button? It takes up a whole new line, and has nothing else to offer. I always press 'Enter' anyways.

No, because the plan is to add other buttons there.

**Comment by chumbawumba** [comment] 2018-11-01 18:08
Also the functionality of the "filter" function, even though visibly similar, doesn't work the same way the old "search" functionality worked. Leaving the field blank, for example, now produces an error. Also, when you switch between filterable fields, the content in the input field is cleared.

**Comment by dmoagx** [comment] 2018-11-01 18:15
>  Leaving the field blank, for example, now produces an error.
This will be changed in the future.

**Comment by sebastianheise** [comment] 2018-11-05 01:38
I agree that this adds "one extra click (keystroke)" - several hundred times throughout my day! :( 
Please add at least an option to turn this on by default.

**Comment by ZeldaZach** [comment] 2018-11-05 03:36
I was about to file a ticket "search bar went missing" before I saw this. Definitely a regression, imo. 

An option could be to have a configurable setting, such as "always have search bar visible," to give users the choice. Feels a bit hasty removing it.

Besides that, loving the beta builds. Keep up the great work!

**Comment by Jewhurst** [comment] 2018-11-05 18:58
Not sure if this should be its own issue, but this is also quite annoying
![screen recording 2018-11-05 at 1 55 15 pm](https://user-images.githubusercontent.com/5921832/48020027-e69c7e80-e102-11e8-8d35-5ee565d386f9.gif)

**Comment by zmears** [comment] 2018-11-08 14:33
I also get the "No valid SQL expression could be generated. Make sure that you have filled in all required fields" error when clicking on the arrow to move between tables. It does not filter for the id I have clicked on when going to the related table either.

**Comment by iamdanielp** [comment] 2018-11-09 10:54
I also first thought this was some kind of bug before I found this issue. I personally also prefer the previous behaviour with the filter bar always visible. If there's a good reason for changing the behaviour as was indicated by @dmoagx then I also think a setting would make both types of users happy. I also find the "filter button bar" unnecessary but as indicated I guess there's a good reason for this.

Personally I also preferred the older look and feel of the tabs. No they expand the whole window width plus the add tab button is always to the far right. The older behaviour looked better and having the add tab button just next to the last tab was more convenient. But I guess this is a different issue.

Otherwise, great work and I love the application.

**Comment by dmoagx** [comment] 2018-11-22 02:51
To get a better overview of the different feedback I've created a new label and split out the points mentioned: https://github.com/sequelpro/sequelpro/labels/MultifilterUI

> The experience I am accustomed to with the filter bar in Sequel Pro is that it is always present (...)  In the most recent nightly build the filter bar is only present after hitting cmd+F or pulling it up from the menu

> The toolbar not being present by default is a little bit less convenient,

#3304 

>  I do not see a way to dismiss the filter bar or clear the filter.

> I do miss the "X" button to clear the current filter in a single click.

#3302 

> I tried just erasing the text from the filter input, but it threw an error "No valid SQL expression could be generated. Make sure that you have filled in all required fields".

> Leaving the field blank, for example, now produces an error.

#3083 

> If its possible to "open" it with cmd+f - should'nt it be possible to close it again that way?

> I think that hitting cmd+f when the filter is already present should clear the filter and close the filter toolbar

#3305 

> Also, when you switch between filterable fields, the content in the input field is cleared.

> Not sure if this should be its own issue, but this is also quite annoying that it removes the filter typed in everytime you change a dropdown.

#3306

I'll close this issue as a duplicate. Please subscribe to the one's mentioned above.

**Closed by dmoagx** 2018-11-22 02:51 UTC
Labels: MultifilterUI

**Comment by sauron918** [comment] 2018-11-28 13:18
> when clicking on the arrow to move between tables. It does not filter for the id I have clicked on when going to the related table either.

It really hinders

**Comment by dmoagx** [comment] 2018-11-28 17:15
@sauron918 That is a completely separate issue that has existed long before the filter redesign: #2792

**Comment by Gowa2017** [comment] 2018-12-18 08:38
I think we shoule make is displayed default? Now if want to use filter bar, we must do a more action.

It seems not need much more time, only when we open a new tab.

But, I think, I need a method to make it displayed default.
