### ISSUE TITLE
Connection problems to MySQL 5.7

### ISSUE THREAD

**Issue by GoBijan** [sequelpro/sequelpro#2340] opened 2015-11-26 12:38 UTC
I upgraded MySQL from 5.6 to 5.7 via Homebrew on OS X to server version: 5.7.9 Homebrew
Now I get this annoying error message when trying to connect to the DB:

NSInvalidArgumentException

*** -[NSPlaceholderString initWithString:]: nil argument

(
	0   CoreFoundation                      0x00007fff91275e32 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff8cf93dd4 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff912dc65d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff8850c512 -[NSPlaceholderString initWithString:] + 96
	4   Sequel Pro                          0x000000010002e6a9 -[SPDatabaseDocument setConnection:] + 384
	5   Foundation                          0x00007fff884f541e __NSThreadPerformPerform + 279
	6   CoreFoundation                      0x00007fff9120b8b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x00007fff911eb0ac __CFRunLoopDoSources0 + 556
	8   CoreFoundation                      0x00007fff911ea5cf __CFRunLoopRun + 927
	9   CoreFoundation                      0x00007fff911e9fc8 CFRunLoopRunSpecific + 296
	10  HIToolbox                           0x00007fff8ae2fd55 RunCurrentEventLoopInMode + 235
	11  HIToolbox                           0x00007fff8ae2fb8f ReceiveNextEventCommon + 432
	12  HIToolbox                           0x00007fff8ae2f9cf _BlockUntilNextEventMatchingListInModeWithFilter + 71
	13  AppKit                              0x00007fff91963d96 _DPSNextEvent + 1067
	14  AppKit                              0x00007fff919631c5 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	15  AppKit                              0x00007fff91957d28 -[NSApplication run] + 682
	16  AppKit                              0x00007fff91920fbe NSApplicationMain + 1176
	17  Sequel Pro                          0x0000000100001994 start + 52
)

**Comment by rowanbeentje** [comment] 2015-11-26 12:41
Whenever you update the MySQL version, the internal databases used by MySQL may need updating.  MySQL ships with a command-line tool which performs these necessary updates - run `mysql_upgrade` and you should find this is fixed.

**Comment by rowanbeentje** [comment] 2015-11-26 12:42
(Closing as a duplicate of https://github.com/sequelpro/sequelpro/issues/2302 , already addressed in an upcoming version)

**Closed by rowanbeentje** 2015-11-26 12:42 UTC
Labels: Duplicate
