### ISSUE TITLE
Remote access to MySQL with HTTP tunneling

### ISSUE THREAD

**Issue by babca** [sequelpro/sequelpro#2627] opened 2016-12-03 11:06 UTC
Unfortunately every local webhoster have remote access to their MySQL server disabled, and they refuse to allow even a single IP adress, so I can't use Sequel Pro for most of my db administration. It's a pain to be forced to use phpmyadmin. It's 2016!

Is there any universal HTTP tunnel available that I can use with Sequel Pro?
Something like [SQLyogTunnel.php](https://gist.github.com/anonymous/2297fdc6e11c9d9e62cc02af1c00771e), a single PHP file which exposes MySQL API via HTTP tunnel. Or maybe there is a client-server app which makes remote db server appear as local one, so I can make a local connection to it with Sequel Pro.
Do you know any solutions for this? I would be happy for any suggestions. Thank you!

**Comment by dmoagx** [comment] 2016-12-03 12:49
Duplicate of #185

**Closed by dmoagx** 2016-12-03 12:49 UTC
