### ISSUE TITLE
Running a query causes all tabs to test connections to servers

### ISSUE THREAD

**Issue by Brynyard** [sequelpro/sequelpro#2725] opened 2017-03-11 19:28 UTC
... which again causes the entire program to freeze for 30 seconds if one of the tabs are open to a server that is no longer available. And just to add insult to injury there's no way to stop this happening, and the only alternative if the server is temporarily unavailable is to close the tab (the entire program is locked until you either can reconnect or close that tab).

This quit simply shouldn't be a "feature". Servers may become unavailable for a short period of time (eg in internal networks, VPN, etc), and this shouldn't mean all the current work (queries and state) is lost, and the program locks up.

**Comment by Brynyard** [comment] 2017-04-03 21:36
Additionally Sequel Pro seems to crash quite consistently if more than 1 tab is open to an unavailable server.

**Comment by abhibeckert** [comment] 2017-04-03 22:20
Duplicate of #2731

**Closed by abhibeckert** 2017-04-03 22:20 UTC
Labels: Bug, Duplicate
