### ISSUE TITLE
Sequel Pro 1.0.2 (OSX 10.10.2 + 10.10.3) crashes after adding new user

### ISSUE THREAD

**Issue by mhmli** [sequelpro/sequelpro#2095] opened 2015-04-10 08:25 UTC
Every time! (The add works though.)

**Comment by dmoagx** [comment] 2015-04-10 11:09
Duplicate of #1961.
Please search for existing issues before creating a new one!

**Closed by dmoagx** 2015-04-10 11:09 UTC

**Comment by mhmli** [comment] 2015-04-10 12:12
Apologies. Opened a new ticket as a) http://nightly.sequelpro.com/ doesn't work any more and b) #1961 hasn't been touched for the last few months.
