### ISSUE TITLE
CURRENT_TIMESTAMP with fractional seconds gets wrapped in quotes

### ISSUE THREAD

**Issue by BigstickCarpet** [sequelpro/sequelpro#2617] opened 2016-11-17 17:32 UTC
This is similar to Issue https://github.com/sequelpro/sequelpro/issues/2240, but seems to only happen when CURRENT_TIMESTAMP is used with fractional seconds (e.g. `CURRENT_TIMESTAMP(6)`)

The following table definition works fine with Sequel Pro (v1.1.2).  I can add/update rows via the "content" view, and the `my_date_field` automatically gets set to the current date/time with each change.  👍 
```sql
CREATE TABLE `my_table` (
  `my_text_field` varchar(50),
  `my_date_field` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
```

However, the following table definition does **not** work.  When I try to add/update a row, an error occurs because Sequel Pro appears to be treating `CURRENT_TIMESTAMP(6)` as a string literal. 👎 
```sql
CREATE TABLE `my_table` (
  `my_text_field` varchar(50),
  `my_date_field` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
```

![error](https://cloud.githubusercontent.com/assets/3453903/20400213/6dd09eca-acb9-11e6-9b2e-296705a26369.png)

**Comment by dmoagx** [comment] 2016-11-17 18:53
Duplicate of #2315

**Closed by dmoagx** 2016-11-17 18:53 UTC
