### ISSUE TITLE
Cosmetic issue; Dragging tab off to new window loss of window transparency (goes black)

### ISSUE THREAD

**Issue by frumbert** [sequelpro/sequelpro#2632] opened 2016-12-15 01:00 UTC
OSX 10.11.6 (15G1212)
SequelPro 1.1.2 (4541)

Steps to create:
1. Open a database
2. Right-click a table, open in new tab
3. Drag tab off into new window

<img width="904" alt="screen shot 2016-12-15 at 11 59 00 am" src="https://cloud.githubusercontent.com/assets/592257/21207729/ef528c00-c2bd-11e6-9a87-8d9c7d776821.png">

**Comment by dmoagx** [comment] 2016-12-15 16:13
Duplicate of #2286

**Closed by dmoagx** 2016-12-15 16:13 UTC
