### ISSUE TITLE
macOS Mojave总是会自动关闭

### ISSUE THREAD

**Issue by 243512842** [sequelpro/sequelpro#3299] opened 2018-11-16 02:34 UTC
同时打开多个数据库的情况下，如果关闭其中一个，其他数据库全都被强制退出

**Comment by BenjaminHoegh** [comment] 2018-11-16 07:33
@243512842 In English please

**Comment by justinmoh** [comment] 2018-11-17 12:09
> 同时打开多个数据库的情况下，如果关闭其中一个，其他数据库全都被强制退出

Literally:
>  "(the sequel pro on-) macOS Mojave would always shutdown automatically"
>  "In the situation of simulteneously opening multiple databases, if close one of them, other databases will all be force quit."

@243512842 

翻译了，不谢。英语对这里的许多人来说都不是母语，是第二甚至第三语言。用英语，多尝试，没人会笑你。

The issue has been discussed multiple times across this issue board. You probably missed out the point that Sequel Pro is no longer officially maintained. If you are using `version 1.1.2`, then you're using an unsupported version. 

Like more than 2 years back, I've seen maintainers saying the owner had gone MIA and some how they're not able to publish the build steps... etc. Put it simple way, if you want to use an _maintained version_, you have to try the nightly builds, solve many issues mentioned on this issue tracker. I think the current active maintainer is still Max, you can follow his comments.

Translated for you :

> 这个问题已经在此讨论多次。你可能不知道， Sequel Pro 已经没有正式的维护升级了。如果你使用的版本是 `version 1.1.2`，那就是已经不再维护的“正式”版本。
>
> 几年前我曾看见其他维护者说产品的主人“不见了”，然后他们不知何故没有办法执行正式的版本维> 护。。。简单来说，如果你要使用一个维护中的版本，你需要使用 Nightly Builds，那里头已经解决了这里提到的许多问题。相信现在的维护着依然是 Max （dmoagx) ，你可以看看他的留言。

**Comment by dmoagx** [comment] 2018-11-18 18:01
So, I guess this is another duplicate of #3116

**Closed by dmoagx** 2018-11-18 18:01 UTC
