### ISSUE TITLE
Dragging a tab off into a new window corrupts the left full tab

### ISSUE THREAD

**Issue by raptor235** [sequelpro/sequelpro#2929] opened 2017-11-23 19:15 UTC
http://www.flowpress.com/screenshots/screenshot_2017-11-23_at_2.14.27PM.png

**Comment by afelicioni** [comment] 2018-01-11 15:53
Able to reproduce this on macOS 10.13.2 (17C88)

The issue happens also on original window if docking back the tab.

A _glitch_ also occurs on original window, looking like a phantom selection is active
<img width="556" alt="schermata 2018-01-11 alle 16 00 04" src="https://user-images.githubusercontent.com/1416945/34832430-390f6000-f6ea-11e7-9166-bf45bf6ae6ef.png">

Anyway, if in new window you open a new clear tab, the whole window is redrawn correctly

**Comment by dmoagx** [comment] 2018-01-11 19:17
Duplicate of #2286

**Closed by dmoagx** 2018-01-11 19:17 UTC
