### ISSUE TITLE
Would love a "Record View" showing a row full page

### ISSUE THREAD

**Issue by heartfelttech** [sequelpro/sequelpro#3148] opened 2018-09-03 02:30 UTC
It'd be very hady to be able to select a row and view it as a record, with a column of row names and a column of row values. 

For example, if a row in a database has a lot of columns, this would be a better view to browse what's in it rather than lots of horizontal scrolling.

**Comment by dmoagx** [comment] 2018-09-07 20:59
Duplicate of #1236

**Closed by dmoagx** 2018-09-07 20:59 UTC
