### ISSUE TITLE
Compatibility with El Capitan (10.11 (15A204h)) when using SSH tunnel

### ISSUE THREAD

**Issue by pavel-pola** [sequelpro/sequelpro#2166] opened 2015-07-05 22:25 UTC
Hello,
I use Sequel Pro along with the latest beta from Apple and there was a change in OpenSSH implementation. When I try to connect using SSH tunnel, I get an error like this:

Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 usr@server.host -L 49780/127.0.0.1/3306 -L 49781/server.host/3306

Bad local forwarding specification ' 49780/127.0.0.1/3306'

According to Apple engineers, you have to use ":" as a separator for elements of SSH tunnelling specification. 

Could you please test it? 

Thanks,

Pavel

**Comment by dmoagx** [comment] 2015-07-05 22:47
Duplicate of #2050 
This has already been fixed in 1.1rc1: http://www.sequelpro.com/blog/2015.06/sequel-pro-1-1-rc1/
Please search for existing issues, before creating a new one.

**Closed by dmoagx** 2015-07-05 22:47 UTC
