### ISSUE TITLE
Application icon looks ugly on MacBook Pro 15'' 2016

### ISSUE THREAD

**Issue by DexterHD** [sequelpro/sequelpro#2743] opened 2017-03-27 08:39 UTC
I see app icon borders. Looks like icon background is not transparent.
I know, it's not important, but maybe you can fix it?

![icon-background](https://cloud.githubusercontent.com/assets/1532188/24347718/f113b8f6-12e1-11e7-886f-d911653f1125.png)

**Comment by dmoagx** [comment] 2017-03-27 17:11
Duplicate of #2623

**Closed by dmoagx** 2017-03-27 17:11 UTC
