### ISSUE TITLE
make test builds downloadable again

### ISSUE THREAD

**Issue by jwwisniewski** [sequelpro/sequelpro#3219] opened 2018-10-09 10:33 UTC
Hey guys,

Could you make the latest test builds https://sequelpro.com/test-builds downloadable again? 

Thanks,
Jakub

**Comment by anthonysomerset** [comment] 2018-10-09 13:54
Duplicate of #2953 

its probably worth also referring you to #3034 as well in this case

**Comment by stuconnolly** [comment] 2018-10-09 14:19
Duplicate of #2953 

This is currently being worked on.

**Closed by stuconnolly** 2018-10-09 14:19 UTC
