### ISSUE TITLE
Crash on Import 'NSInternalInconsistencyException'

### ISSUE THREAD

**Issue by sunkingdice** [sequelpro/sequelpro#3289] opened 2018-11-09 13:51 UTC
- Sequel Pro Version: 1.1.2 / 4541
- macOS Version: 10.13.6
- MySQL Version: AWS instance 

**Description**
I am importing some CSV files - I did so on multiple MacBooks and witnessed SequelPro crashing at random points of the file imports with this message - it seems to have no connection to the computer used (I used 6 different Macs) or the file - the crash happened at different files and different MiB processed:

```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Switching the selectedTableDocument via a background thread is not supported!'

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff2bbdc2db __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff52d79c76 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff2bbe2072 +[NSException raise:format:arguments:] + 98
3   Foundation                          0x00007fff2dd0b340 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
4   Sequel Pro                          0x00000001000f3cfb -[SPWindowController _switchOutSelectedTableDocument:] + 142
5   Sequel Pro                          0x00000001000f3dc1 -[SPWindowController dealloc] + 33
6   libobjc.A.dylib                     0x00007fff52d73db4 _ZN11objc_object17sidetable_releaseEb + 266
7   AppKit                              0x00007fff29100270 -[NSWindowController release] + 154
8   libobjc.A.dylib                     0x00007fff52d6f087 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 817
9   CoreFoundation                      0x00007fff2bb15a06 _CFAutoreleasePoolPop + 22
10  Foundation                          0x00007fff2dc478ad -[NSAutoreleasePool drain] + 144
11  Sequel Pro                          0x000000010004c4f1 -[SPDataImport importCSVFile:] + 8588
12  Sequel Pro                          0x000000010004f207 -[SPDataImport _importBackgroundProcess:] + 224
13  Foundation                          0x00007fff2dc611f8 __NSThread__start__ + 1197
14  libsystem_pthread.dylib             0x00007fff53cab661 _pthread_body + 340
15  libsystem_pthread.dylib             0x00007fff53cab50d _pthread_body + 0
16  libsystem_pthread.dylib             0x00007fff53caabf9 thread_start + 13
```

**Comment by datayeah** [comment] 2018-11-12 12:10
I've had the same crash. I tried build df10e20443 and it doesn't crash anymore.
thanks for fixing that :)

**Comment by dmoagx** [comment] 2018-12-14 01:38
Closing after no feedback from reporter

**Closed by dmoagx** 2018-12-14 01:38 UTC
Labels: WaitingOnUser

**Comment by llorban** [comment] 2019-07-22 19:20
Same issue occurring. csv exported from Apple Numbers

**Comment by llorban** [comment] 2019-07-22 19:22
The issue is resolved by opening the Apple Numbers exported csv (utf-8) and re-exporting it from Excel. Some weird line ending issue perhaps?
