### ISSUE TITLE
export table

### ISSUE THREAD

**Issue by Patrikkbbc** [sequelpro/sequelpro#2305] opened 2015-10-23 14:06 UTC
![screen shot 2015-10-22 at 12 48 18 pm](https://cloud.githubusercontent.com/assets/8640860/10662168/43643c24-78bb-11e5-952f-ea50219662a9.png)

When I export any table in the name of the exported file it does not have the name of the table but only the name of the database

**Comment by dmoagx** [comment] 2015-10-23 15:03
Issue reproducible with 1.1

**Comment by dmoagx** [comment] 2015-10-24 12:40
Duplicate of #1858

**Closed by dmoagx** 2015-10-24 12:40 UTC
Labels: Bug
