### ISSUE TITLE
BIT(1) field values appear as bytes, can't inline edit

### ISSUE THREAD

**Issue by tamasssimon** [sequelpro/sequelpro#2259] opened 2015-10-02 15:56 UTC
I.e., 1 appears as 10000000, 0 appears as 00000000.  This happened after upgrade to Build 4499.  

This is when viewing table content or query results.

In addition, I can no longer inline edit these values.  Throws an warning:

The row was not written to the MySQL database. You probably haven't changed anything.
Reload the table to be sure that the row exists and use a primary key for your table.
(This error can be turned off in the preferences.)

To be specific, this happens why I type 0 or 1.  It doesn't allow me to type more values (i.e., 00000000 or 10000000), because there is an input limit.  The tooltip shows: 
Maximum text length is set to 1.  Inserted text was truncated.

**Comment by dmoagx** [comment] 2015-10-02 16:31
Duplicate of #2254

**Closed by dmoagx** 2015-10-02 16:31 UTC
