### ISSUE TITLE
no way to clear filter and app gives an error

### ISSUE THREAD

**Issue by vcgnetwork** [sequelpro/sequelpro#3417] opened 2019-03-15 14:12 UTC
- Sequel Pro Version: latest build 5438 (664a46cd)
- macOS Version: 10.14.4 Beta (18E194d)
- MySQL Version: 5.7

**Description**

**Steps To Reproduce**
1. open SequelPro
2. click on a table 
3. CMD-F to show the filter because by default its not visible
4. search for something -> all good there
5. PROBLEM -> when you clear the filter input box and try to refresh it gives this error: 
Invalid Filter - No valid SQL expression could be generated. Make sure that you have filled in all required fields.
6. How do you clear the filter?

**Expected Behaviour**
There sould also be a minus icon even if only 1 filter is left to get rid of it or a button that says clear filters.

**Additional Context**

<img width="854" alt="sequelpro-error" src="https://user-images.githubusercontent.com/3748598/54437373-d7f65180-470a-11e9-96c8-2493ea9ba8bb.png">

**Comment by vcgnetwork** [comment] 2019-03-15 14:13
By the way, Thank you for this application I have been using it since it came out.

**Comment by vcgnetwork** [comment] 2019-03-15 14:14
LAST THING -- THANK YOU FOR "DARK MODE" ITS AWESOME!!

**Comment by daveismyname** [comment] 2019-03-21 15:48
you can toggle it by clicking on the third icon in this image.

![](https://i.imgur.com/ceQQZ2F.png)

**Comment by dmoagx** [comment] 2019-04-02 19:11
Duplicate of #3083

**Closed by dmoagx** 2019-04-02 19:11 UTC
