### ISSUE TITLE
Expected timeline on Issue 3116

### ISSUE THREAD

**Issue by winklevoss333** [sequelpro/sequelpro#3301] opened 2018-11-16 14:34 UTC
What is the expected timeline around the fix for the attached link actually being deployed? The issue is locked and there is no information on when it is to be released to resolve the continual crashing issues. 

If this has been resolved, please advise on the workaround. Even with the most updated version, mojave users still experience crashing when closing tabs.

https://github.com/sequelpro/sequelpro/issues/3116

**Comment by dmoagx** [comment] 2018-11-18 17:58
Duplicate of #3034

**Closed by dmoagx** 2018-11-18 17:58 UTC
