### ISSUE TITLE
User is too long error when having a user with 32 characters

### ISSUE THREAD

**Issue by bkintanar** [sequelpro/sequelpro#2914] opened 2017-11-06 21:05 UTC
I get this error when accessing the user accounts dialog if I have a mysql user with 32 characters.

<img width="532" alt="screen shot 2017-11-07 at 4 55 39 am" src="https://user-images.githubusercontent.com/685928/32463829-e03bfe60-c378-11e7-90f2-45bacbbfd6e9.png">

**Comment by dmoagx** [comment] 2017-11-06 22:44
Duplicate of #1886

**Closed by dmoagx** 2017-11-06 22:44 UTC
