### ISSUE TITLE
Improvement: Open table in new Tab should not also open the table in the current tab

### ISSUE THREAD

**Issue by bronius** [sequelpro/sequelpro#2512] opened 2016-06-02 03:06 UTC
I just noticed the really useful two-finger click / right-click / context click on a table > Open Table in New Tab context menu item. Works like a dream!  When context-clicking on another table to open it in a new tab, however, the current table should not lose focus, and the clicked table should not replace the contents of the current tab.

THANK YOU for keeping up this terrific tool!

**Comment by abhibeckert** [comment] 2016-06-02 21:31
I agree, right clicking on an item should not change the selection. It should work like Finder:

![screen shot 2016-06-03 at 07 30 32](https://cloud.githubusercontent.com/assets/266088/15761734/2b3973b4-295d-11e6-88eb-867b349cfce5.png)

**Comment by dmoagx** [comment] 2016-06-03 09:48
This has been discussed before and there should be an issue around. Short version: This is a limitation in how SP works. The context menu can only work on the table that is currently active.

**Comment by dmoagx** [comment] 2016-06-03 09:55
Duplicate of #1250

**Closed by dmoagx** 2016-06-03 09:55 UTC
Labels: Enhancement
