### ISSUE TITLE
SSH tunneling is broken in El Capitan

### ISSUE THREAD

**Issue by orcinus** [sequelpro/sequelpro#2135] opened 2015-06-10 20:44 UTC
I fully realize El Capitan is still in beta, but this is an issue that will not go away unless fixed on Sequel Pro side.

As it turns out, El Capitan uses a newer version of SSH, that doesn't allow "/" as the separator in local forwarding specification anymore (e.g. -L 59606/192.168.187.127/3306), rendering SSH tunneling unusable in Sequel Pro 1.0.2 Build 4096.

Should probably be updated to use ":" as soon as possible.

**Comment by dmoagx** [comment] 2015-06-10 20:46
Duplicate of #2050 
This is already fixed in 1.1rc1

**Comment by orcinus** [comment] 2015-06-10 20:46
Ah. Sorry.
Couldn't find it for some reason.

**Closed by dmoagx** 2015-06-10 20:46 UTC

**Comment by adamwintle** [comment] 2015-09-18 05:36
Where can I download 1.1?

**Comment by jklp** [comment] 2015-09-20 23:31
You can check out their blog but the direct link is http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/

**Comment by kiranbiliyawala** [comment] 2015-10-11 18:26
awesome, thanks for sharing. :)

**Comment by Chemaclass** [comment] 2016-07-07 09:27
Thanks!
