### ISSUE TITLE
Add Filter feature (multi filter on `Content` search)

### ISSUE THREAD

**Issue by toshim45** [sequelpro/sequelpro#3162] opened 2018-09-13 00:58 UTC
<img width="733" alt="screen shot 2018-09-13 at 7 52 03 am" src="https://user-images.githubusercontent.com/8453594/45460893-40e41900-b72a-11e8-859e-f727784c0e08.png">

single filter

```
Search: <column-name> < operation > <value-to-search > <Add Filter> <Filter>
```

if we click add filter then:

```
Search: <column-name> < operation > <value-to-search > <Add Filter>
Search: <column-name> < operation > <value-to-search > <Add Filter>
Search: <column-name> < operation > <value-to-search > <Add Filter> <Filter>
```

**Comment by dmoagx** [comment] 2018-09-14 21:26
Duplicate of #63

**Closed by dmoagx** 2018-09-14 21:26 UTC
