### ISSUE TITLE
1.2 must be released — ASAP. This is ridiculous!

### ISSUE THREAD

**Issue by paulmillr** [sequelpro/sequelpro#3298] opened 2018-11-14 15:21 UTC
Everything here is done except for some tiny feature: https://github.com/sequelpro/sequelpro/projects/2

#3116 is pretty important issue. 

@dmoagx @stuconnolly what's the deal here? Why can't you just push off a new release?

There is no excuse — instead of adding more and more new code, just focus on the freaking stable build. I maintain popular OSS software and know it's not a problem.

It has been more than two years now.

**Comment by dmoagx** [comment] 2018-11-14 16:43
Duplicate of #3034

**Closed by dmoagx** 2018-11-14 16:43 UTC
