### ISSUE TITLE
MySQL 5.7.20 user is too long.

### ISSUE THREAD

**Issue by Kyslik** [sequelpro/sequelpro#2949] opened 2017-12-08 11:42 UTC
When I try to access "users" sequelpro throws me a error **user is too long.** I am on MySQL 5.7.20 which has limit for user names `32` ([source](https://dev.mysql.com/doc/refman/5.7/en/user-names.html))

This SQL query:

```sql
SELECT length(User) as l FROM mysql.user ORDER BY l DESC LIMIT 1
```

returns:

`29`

Am I missing something?

---

<img width="1048" alt="screen shot 2017-12-08 at 12 37 29 pm" src="https://user-images.githubusercontent.com/2067589/33764577-37e45e32-dc15-11e7-923e-b755bc61b9d2.PNG">

**Comment by dmoagx** [comment] 2017-12-08 12:27
Duplicate of #1886

**Closed by dmoagx** 2017-12-08 12:27 UTC
