### ISSUE TITLE
Sequel Pro Crashes when you close a tab on mojave

### ISSUE THREAD

**Issue by rohithrpai** [sequelpro/sequelpro#3443] opened 2019-04-08 16:09 UTC
SequelPro has a bug that causes it to crash upon closing a tab. 

![image](https://user-images.githubusercontent.com/25734068/55739165-833ab380-59f6-11e9-831b-3e79af4fa8e3.png)

Please find attached the text document that goes in detail about the system config and faults.

[SequelPro_crash_report.txt](https://github.com/sequelpro/sequelpro/files/3055244/SequelPro_crash_report.txt)

**Comment by dmoagx** [comment] 2019-04-08 18:55
Duplicate of #3116

**Closed by dmoagx** 2019-04-08 18:55 UTC

**Comment by fenichelar** [comment] 2019-04-17 14:25
@dmoagx #3116 is locked and I'm still seeing this bug. Can you unlock the existing ticket or reopen this?

**Comment by fenichelar** [comment] 2019-04-17 14:27
Sequel Pro 1.1.2
Build 4541 (602e11a)
macOS 10.14.2

Report attached.
[report.txt](https://github.com/sequelpro/sequelpro/files/3090088/report.txt)
