### ISSUE TITLE
utf8mb4 support needed. Thanks.

### ISSUE THREAD

**Issue by zfavourite99** [sequelpro/sequelpro#3067] opened 2018-06-01 02:34 UTC
![png](https://user-images.githubusercontent.com/2630290/40817920-3df5145a-6587-11e8-9340-68ca10098fa1.png)

this picture is select database charset when create database.

list has no utf8mb4. And so many utf8 or utf8mb3

mysql version 8.0
sequel pro version 1.1.2
mac os 10.13.4

**Comment by ngocphamm** [comment] 2018-06-02 15:39
I didn't get this behavior with Maria 10.1, so I tried with a docker image of MySQL 8, but I got this issue https://github.com/sequelpro/sequelpro/issues/3037

Not sure why you even managed to login to your MySQL server 🤔

**Comment by ngocphamm** [comment] 2018-06-02 16:13
So I was able to connect to the docker MySQL 8 by doing some tricks I found [here](https://stackoverflow.com/a/50130875/514015).

I guess you can try using a nightly build of Sequel Pro. https://sequelpro.com/test-builds. Latest successful build (8 months ago) worked for me.

**Comment by stuconnolly** [comment] 2018-10-14 21:53
Duplicate of #1745

MySQL 8.0 support is being tracked via #2699

**Closed by stuconnolly** 2018-10-14 21:53 UTC
