### ISSUE TITLE
Dragging tab into a new window causes black sidebar

### ISSUE THREAD

**Issue by garbit** [sequelpro/sequelpro#2319] opened 2015-11-10 09:40 UTC
**Expected behaviour**
Whilst connected to multiple databases with multiple tabs I should be able to drag a tab into it's own window and the sidebar (tables view) should maintain it's styling.

**Actual behaviour**
After dragging a tab into it's own window the sidebar goes black and the list highlighting is offset from the selected table.

**Steps to reproduce**
Open up multiple connections to different databases in any number of tabs and drag a tab into it's own window. Reproducible 100% of the time. 

**Hardware & Software**
Sequel Pro 1.1 build 4499 (0bac177)
MacBook Pro 15", OS X 10.11.1 connected to an iMac 2011 (2560x1440 resolution) over Target Display Mode (TDM) using a Thunderbolt cable. Mbp being used as the host and iMac connected as second display running different resolution.

![screenshot 2015-11-10 09 37 58 copy](https://cloud.githubusercontent.com/assets/555396/11059019/f580e39e-878e-11e5-8a05-8efac05838e9.png)

**Comment by dmoagx** [comment] 2015-11-10 17:24
I don't have a Mac with 10.11 and inside the VM there is no graphic acceleration so it won't happen there.
Either someone else will have to look into it or it has to wait.

**Comment by dmoagx** [comment] 2015-12-06 21:54
Duplicate of #2286 

(Thanks @samuelbradshaw for noticing)

**Closed by dmoagx** 2015-12-06 21:54 UTC
