### ISSUE TITLE
Unable to connect to simple MySQL docker container

### ISSUE THREAD

**Issue by bsarrazin** [sequelpro/sequelpro#3211] opened 2018-10-07 15:27 UTC
Assuming you have docker installed, create a brand new container:
```zsh
$ docker run --name HelloWorld --publish 3306:3306 --env MYSQL_USER=HelloWorld --env MYSQL_PASSWORD=P4ssw0rd! --env MYSQL_DATABASE=HelloWorld --env MYSQL_ROOT_PASSWORD=P4ssw0rd! mysql:latest
```

Connect via MySQLWorkbench:
![image](https://user-images.githubusercontent.com/1077441/46583374-d621b700-ca23-11e8-9030-1615dd4794c2.png)

Connection failure using Sequel Pro:
![image](https://user-images.githubusercontent.com/1077441/46583380-f0f42b80-ca23-11e8-84d6-0d979d5ec317.png)

**Comment by dmoagx** [comment] 2018-10-07 22:53
Duplicate of #2797

**Closed by dmoagx** 2018-10-07 22:53 UTC
