### ISSUE TITLE
Input fields bug

### ISSUE THREAD

**Issue by vad1m** [sequelpro/sequelpro#2278] opened 2015-10-08 11:21 UTC
Fields like "ssh host name" allowing to insert multiline values. By mistake I copied Ip address with some text in the cell around IP. After inserting to "ssh host name" field IP looks good, but I cannot connect to that IP. Then I figured out that some text located near IP (I used arrow keys to navigate "behind" the IP to upper level). Please fix it (remove tabs and CR symbols on paste action).
SP  v 1.1

**Comment by dmoagx** [comment] 2015-10-08 11:41
Duplicate of #2269 

Please search for existing issues before creating a new one!

**Closed by dmoagx** 2015-10-08 11:41 UTC
