### ISSUE TITLE
Cant connect to database in MySequel 8.x

### ISSUE THREAD

**Issue by priteshkadiwala** [sequelpro/sequelpro#3050] opened 2018-05-10 15:26 UTC
# These are the error messages

```NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x604000227b60

(
	0   CoreFoundation                      0x00007fff479076bb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6f01f942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4799e9e4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff4787f183 __forwarding__ + 1443
	4   CoreFoundation                      0x00007fff4787eb58 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff4999b1f8 _NSThreadstart_ + 1197
	8   libsystem_pthread.dylib             0x00007fff6ff4e661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff6ff4e50d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff6ff4dbf9 thread_start + 13
)

```
# This is another error message
```
{
    BlobTextEditorSpellCheckingEnabled = 0;
    DefaultFavorite = 0;
    "FRFeedbackReporter.lastCrashCheckDate" = "2018-05-10 15:01:00 +0000";
    LastUsedVersion = 4541;
    LastViewMode = 5;
    NSNavPanelExpandedSizeForSaveMode = "{712, 448}";
    "NSSplitView Subview Frames DBViewSplitter" =     (
        "0.000000, 0.000000, 174.000000, 577.000000, NO, NO",
        "175.000000, 0.000000, 865.000000, 577.000000, NO, NO"
    );
    "NSSplitView Subview Frames NSColorPanelSplitView" =     (
        "0.000000, 0.000000, 224.000000, 263.000000, NO, NO",
        "0.000000, 264.000000, 224.000000, 43.000000, NO, NO"
    );
    "NSSplitView Subview Frames SPNavigatorSchemaStatus" =     (
        "0.000000, 0.000000, 395.000000, 233.000000, NO, NO",
        "0.000000, 234.000000, 395.000000, 100.000000, NO, NO"
    );
    "NSSplitView Subview Frames TableInfoSplitter" =     (
        "0.000000, 0.000000, 835.000000, 85.000000, NO, NO",
        "0.000000, 94.000000, 835.000000, 234.000000, NO, NO"
    );
    "NSTableView Columns SPTableStructureSource" =     (
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 046e616d 6586>,
        80,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 04747970 6586>,
        92,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 066c656e 67746886>,
        64,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 08756e73 69676e65 6486>,
        54,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 087a6572 6f66696c 6c86>,
        41,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 0662696e 61727986>,
        37,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 046e756c 6c86>,
        57,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 034b6579 86>,
        26,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 07646566 61756c74 86>,
        65,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 05457874 726186>,
        87,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 08656e63 6f64696e 6786>,
        77,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 09636f6c 6c617469 6f6e86>,
        82,
        <040b7374 7265616d 74797065 6481e803 84014084 8484084e 53537472 696e6701 8484084e 534f626a 65637400 8584012b 07636f6d 6d656e74 86>,
        62
    );
    "NSTableView Hidden Columns SPTableStructureSource" =     (
    );
    "NSTableView Sort Ordering SPTableStructureSource" =     (
    );
    "NSToolbar Configuration TableWindowToolbar" =     {
        "TB Display Mode" = 1;
        "TB Icon Size Mode" = 1;
        "TB Is Shown" = 1;
        "TB Size Mode" = 1;
    };
    "NSToolbar Configuration com.apple.NSColorPanel" =     {
        "TB Is Shown" = 1;
    };
    "NSWindow Frame DBView" = "10 390 1040 600 0 0 1920 1177 ";
    "NSWindow Frame QueryConsole" = "1288 114 575 225 0 0 1920 1177 ";
    "NSWindow Frame SPCreateSyntaxSheet" = "1186 759 411 363 0 0 1920 1177 ";
    "NSWindow Frame SPFieldEditorTextSheet" = "1067 672 667 450 0 0 1920 1177 ";
    SPFirstRun = 0;
    SPLastFavoriteID = "-7815100490414285711";
    "SPSplitView Lengths " =     (
        0,
        504
    );
    "SPSplitView Lengths DBViewSplitter" =     (
        174,
        865
    );
    "SPSplitView Lengths SPNavigatorSchemaStatus" =     (
        233,
        100
    );
    SUEnableAutomaticChecks = 1;
    SUHasLaunchedBefore = 1;
    SULastCheckTime = "2018-05-10 13:41:52 +0000";
    SULastProfileSubmissionDate = "2018-05-07 15:06:34 +0000";
    SUSendProfileInfo = 1;
    SelectLastFavoriteUsed = 1;
    TableInformationPanelCollapsed = 0;
}
```

**Comment by dmoagx** [comment] 2018-05-10 16:58
Duplicate of #2699

**Closed by dmoagx** 2018-05-10 16:58 UTC
