### ISSUE TITLE
App CRASH with NSRangeException – JSON functions in CONSTRAINT

### ISSUE THREAD

**Issue by TrogWarZ** [sequelpro/sequelpro#3063] opened 2018-05-28 23:58 UTC
SQL server: `mysql  Ver 15.1 Distrib 10.3.7-MariaDB, for osx10.12 (x86_64) using readline 5.1`

SequelPro: `1.1.2 Build 4541 (602e11a)`

Note: i see that json or check functionality is not implemented yet in `1.1.2` – it's okay if they're just ignored. But right now app crashes totally and i cannot do anything with SequelPro even if i don't use this features directly from GUI.

---

Exception:
```
NSRangeException

*** -[__NSArrayM objectAtIndex:]: index 4 beyond bounds [0 .. 3]

(
	0   CoreFoundation                      0x00007fff8f7032cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffa451e48d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff8f61cadc -[__NSArrayM objectAtIndex:] + 204
	3   Sequel Pro                          0x0000000100078fdf -[SPTableData informationForTable:] + 2853
	4   Sequel Pro                          0x000000010007812f -[SPTableData updateInformationForCurrentTable] + 212
	5   Sequel Pro                          0x0000000100077905 -[SPTableData tableEncoding] + 93
	6   Sequel Pro                          0x0000000100119365 -[SPDatabaseDocument(SPDatabaseViewControllerPrivateAPI) _loadTableTask] + 397
	7   Foundation                          0x00007fff9109c8ad __NSThread__start__ + 1243
	8   libsystem_pthread.dylib             0x00007fffa501d93b _pthread_body + 180
	9   libsystem_pthread.dylib             0x00007fffa501d887 _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fffa501d08d thread_start + 13
)
```

How to reproduce?

```sql
CREATE DATABASE `app_crash_test`;
CREATE TABLE `app_crash_test`.`any_table` (
    `any_field` LONGTEXT NOT NULL,
    CONSTRAINT `CONSTRAINT_1` CHECK (`any_field` IS NOT NULL OR json_valid(`any_field`))
);
```

After this – click on the table (to see info or data) and see crash (i cannot send report too).

Functions like `JSON_*` in columns descriptions are good, no crash, problems only with constraints.

**Comment by dmoagx** [comment] 2018-05-30 21:43
Duplicate of #2814

**Closed by dmoagx** 2018-05-30 21:43 UTC
