### ISSUE TITLE
Crash when using a KM cable to switch keyboard focus from mac to my PC

### ISSUE THREAD

**Issue by corymalcolmtaylor** [sequelpro/sequelpro#3276] opened 2018-11-02 10:41 UTC
- Sequel Pro Version:1.1.2 build 4541
- macOS Version:10.14
- MySQL Version:5.7.21

**Description**
I have a new IZEC-A34 KM cable and when I use it via the hotkey (Alt-s) to switch my keyboard and mouse focus from my mac to my PC Sequel Pro crashes a few seconds later.  I should mention that on my mac I also have an external keyboard, mouse and monitor.  My mac is a macbook air (early 2015). 

**Steps To Reproduce**
1.  Set up MacBook Air with external monitor (via the miniDisplay Port) and an external keyboard and mouse via a USB hub.  Connect KM cable to the USB hub and set it up and connect it to PC. Once the KM cable is working open Sequel Pro and put the sequel pro window on the macs external monitor.  Use Alt-S to switch to the PC.  Wait a few seconds or maybe a minute and the crash will happen.
2.

**Expected Behaviour**
Sequel Pro should continue to function and not crash.

**Additional Context**

sequel pro exception:
```
NSInternalInconsistencyException

deferredCurrentActivation already set when we got another deferred activate event

(
	0   CoreFoundation                      0x00007fff3459f43d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff604b0720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff345ba08e +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff3695655d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   AppKit                              0x00007fff31d2de60 -[NSApplication _handleActivateDeferredEvent:] + 196
	5   AppKit                              0x00007fff31a47818 -[NSApplication(NSEvent) sendEvent:] + 2588
	6   AppKit                              0x00007fff31a34795 -[NSApplication run] + 755
	7   AppKit                              0x00007fff31a23e97 NSApplicationMain + 780
	8   Sequel Pro                          0x0000000100002454 start + 52
)
```
=======================
second time, same crash, same exception
```
NSInternalInconsistencyException

deferredCurrentActivation already set when we got another deferred activate event

(
	0   CoreFoundation                      0x00007fff3459f43d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff604b0720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff345ba08e +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff3695655d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   AppKit                              0x00007fff31d2de60 -[NSApplication _handleActivateDeferredEvent:] + 196
	5   AppKit                              0x00007fff31a47818 -[NSApplication(NSEvent) sendEvent:] + 2588
	6   AppKit                              0x00007fff31a34795 -[NSApplication run] + 755
	7   AppKit                              0x00007fff31a23e97 NSApplicationMain + 780
	8   Sequel Pro                          0x0000000100002454 start + 52
)
```

**Comment by corymalcolmtaylor** [comment] 2018-11-03 10:38
Crash also happens when I disconnect my external monitor and left my keyboard and mouse attached via the USB usb to which the IZEC-A34 KM cable was also attached as usual ad as necessary for my setup. Obviously this is more of a Mac OS issue or an issue in the KM cable software than a Sequel Pro issue.

**Comment by dmoagx** [comment] 2018-11-08 20:59
I will close this.
As you already mentioned this is probably an OS X issue.
The stack trace contains nothing that points to Sequel Pro as the cause, especially since we don't fiddle with things like `deferredCurrentActivation` - that is Apple framework stuff.

I've also had cases were a random app would crash (sometimes) the moment I plugged in a smart card reader, so that stuff happens.

**Closed by dmoagx** 2018-11-08 20:59 UTC
