### ISSUE TITLE
Crash when creating user/changing user password

### ISSUE THREAD

**Issue by NicolasPaccaud** [sequelpro/sequelpro#2059] opened 2015-01-21 00:25 UTC
Sequel repeatly crash when creating new user or changing password of existing one.
It happens on different servers (different hosts/versions of mysql, mariadb); all accessed by ssh connexion.

Here are parts of crash message :
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000010e61a00

VM Regions Near 0x10e61a00:
--> 
    __TEXT                 0000000100000000-00000001001fc000 [ 2032K] r-x/rwx SM=COW  /Applications/Sequel Pro.app/Contents/MacOS/Sequel Pro

Application Specific Information:
objc_msgSend() selector name: isKindOfClass:

Let me know if I can provide some informations.

**Comment by dmoagx** [comment] 2015-01-22 01:42
Duplicate of #1961

**Closed by dmoagx** 2015-01-22 01:42 UTC
