### ISSUE TITLE
PLEASE RELEASE YOUR BUG FIXES

### ISSUE THREAD

**Issue by willihelm** [sequelpro/sequelpro#3355] opened 2019-01-14 10:25 UTC
Please release your bug fixes. It is extremely annoying that the program crashes every time you close a tab. I know that it is fixed already but is not released. The last release was April 2016!

Or at least let us know if the project is dead?!

**Comment by rowanbeentje** [comment] 2019-01-14 11:04
Duplicate of https://github.com/sequelpro/sequelpro/issues/3034 , let's continue discussion in there instead of spawning more threads :)

**Closed by rowanbeentje** 2019-01-14 11:04 UTC
