### ISSUE TITLE
only one table has black background,others are ok, is it weird?

### ISSUE THREAD

**Issue by irying** [sequelpro/sequelpro#2805] opened 2017-05-27 02:45 UTC
![image](https://cloud.githubusercontent.com/assets/16642199/26517354/7f23d646-42c9-11e7-97ba-8a8b1f2f6f78.png)

**Comment by tschoffelen** [comment] 2017-05-29 19:55
Can you upload a SQL export of that table (structure, and if possible the content), so that we can reproduce this?

**Comment by irying** [comment] 2017-05-30 02:39
@tschoffelen i have forgot what i have done, and only this table always  black though restart... i think it isn't a bug, it supposed to be an operation error...so i put it here that maybe someone has encountered it and solved it

ps: the same table , the same structure in other server is ok...

**Comment by nicolassing** [comment] 2017-07-21 08:54
Indeed, I have the same problem :/

**Comment by nicolassing** [comment] 2017-07-21 08:57
I have no problem with version 1.1.1 BTW

**Comment by tschoffelen** [comment] 2017-07-21 13:37
To confirm, this error happened in higher or lower versions than 1.1.1? 

If it's happening in a more recent version, can you send a SQL export to we might try to reproduce the problem?

**Comment by nicolassing** [comment] 2017-07-21 13:42
higher version !

I'll try to send you an export as soon as i have time to switch back to the last version :)

**Comment by erfanimani** [comment] 2017-07-31 08:54
I'm having the same problem on 1.1.2.

![image](https://user-images.githubusercontent.com/930470/28770182-d6964f1a-7610-11e7-9108-3db0f399ec85.png)

I can consistently reproduce with that specific table/data.

**Comment by abhibeckert** [comment] 2017-07-31 21:44
> If needed, I can send an export to someone (can I PM on Github?)

Please do that, table structure and content as a .sql file would be good.

Email to contact@sequelpro.com if the data is sensitive.

**Comment by erfanimani** [comment] 2017-08-03 02:08
Thanks. It actually seems to have gone away after a restart and can't reproduce it any more... I'll see when it happens again.

**Comment by stuconnolly** [comment] 2018-10-03 13:48
Closing after no further feedback.

**Closed** 2018-10-03 13:48 UTC
Labels: Bug, WaitingOnUser
