### ISSUE TITLE
Table name placeholder not respected for sql export file name

### ISSUE THREAD

**Issue by codesnipde** [sequelpro/sequelpro#2149] opened 2015-06-18 12:04 UTC
When exporting to sql, the placeholders for database, host and date and time are respected but table is not:

![bildschirmfoto 2015-06-18 um 14 01 30](https://cloud.githubusercontent.com/assets/3320701/8230657/ab26561e-15c2-11e5-8c33-1627be7b272a.png)

The preview that is generated is still correct, but the file name that is written is:
eplatform_ju__192.168.178.10_18.06.15_14-01.sql

You see two underscores after database with the table name 'backend_layout' being left out.

**Comment by dmoagx** [comment] 2015-06-18 17:28
Duplicate of #1858

**Closed by dmoagx** 2015-06-18 17:28 UTC
