### ISSUE TITLE
potential bug with El Capitan

### ISSUE THREAD

**Issue by khimscho** [sequelpro/sequelpro#2143] opened 2015-06-16 15:42 UTC
Hi,

installed the developer preview of OS X 10.11 El Capitan and I think there's an issue with Sequel Pro connecting to databases. I'm going over an SSH tunnel, so perhaps issue lies here.
Happy to help if more info is needed.

Ken

**Comment by willtcarey** [comment] 2015-06-16 15:52
Duplicate of #2050. It's been fixed in the 1.1rc1 release. https://github.com/sequelpro/sequelpro/releases/tag/release-1.1-rc1

**Comment by khimscho** [comment] 2015-06-16 15:53
Apologies and thank you. Brilliant.

**Closed** 2015-06-20 20:03 UTC
