### ISSUE TITLE
Using localhost with an SSH tunnel 

### ISSUE THREAD

**Issue by steverobbins** [sequelpro/sequelpro#2346] opened 2015-12-04 05:55 UTC
I realize that this has been [asked many times before](https://code.google.com/p/sequel-pro/issues/detail?id=1146) but that was 4 years ago and I wanted to see if this could be revisited.

To recap, the MySQL grants only allow connection via `localhost`, i.e.

```
GRANT USAGE ON *.* TO 'user'@'localhost' IDENTIFIED BY PASSWORD <secret>
```

When trying to configure an SSH tunnel using `localhost` as the MySQL host, you are given this message

![image](http://i.imgur.com/zMGvelB.png)

Because this is a shared host and I can't change the grant options, using `127.0.0.1` will not work.

Based on the response in that mentioned issue, using `localhost` isn't possible "without additional tools."  Are we still facing the same limitation today?  Is there a solution out there now that we can use?

**Comment by steverobbins** [comment] 2015-12-04 06:01
It looks like this may be a different issue with the `bind-address` configuration http://stackoverflow.com/a/19012220/763468

**Comment by dmoagx** [comment] 2015-12-04 08:24
This is now technically possible if both, server and client use OpenSSH 6.7 or newer.
Sequel Pro doesn't support it right now, though, and I assume there won't be that many servers with a OpenSSH version that recent.

Duplicate of #2054

**Closed by dmoagx** 2015-12-04 08:24 UTC

**Comment by dmoagx** [comment] 2015-12-04 08:29
You can however manually create the SSH tunnel with socket forwarding and just connect to the forwarded socket in Sequel Pro for the time being.
