### ISSUE TITLE
Crash to print table

### ISSUE THREAD

**Issue by robbert4** [sequelpro/sequelpro#3103] opened 2018-07-04 01:37 UTC
When print table and I click to print, Close Sequel Pro, this fix after the last update MAC OS.
Thanks
Mac OS V. 10.13.5
Sequel Pro. V. 1.1.2 compile 4541 602e11a

**Comment by dmoagx** [comment] 2018-07-06 20:30
Issue description unclear, but most likely a duplicate of #3025 anyway.

**Closed by dmoagx** 2018-07-06 20:30 UTC
