### ISSUE TITLE
Application crashing after click on close button

### ISSUE THREAD

**Issue by prafful-panwar** [sequelpro/sequelpro#3792] opened 2021-05-13 16:41 UTC
rocess:               Sequel Pro [10290]
Path:                  /private/var/folders/*/Sequel Pro.app/Contents/MacOS/Sequel Pro
Identifier:            com.sequelpro.SequelPro
Version:               1.1.2 (4541)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Pro [10290]
User ID:               501

Date/Time:             2021-05-13 22:05:32.463 +0530
OS Version:            macOS 11.3.1 (20E241)
Report Version:        12
Bridge OS Version:     5.3 (18P4556)
Anonymous UUID:        CE2EE197-EFF8-C444-812A-857CDB375F16

Sleep/Wake UUID:       300FC4C3-5F35-4CCC-B619-FCA951050843

Time Awake Since Boot: 39000 seconds
Time Since Wake:       7900 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [10290]

VM Regions Near 0:
--> 
    __TEXT                      100000000-1001d8000    [ 1888K] r-x/rwx SM=COW  /var/folders/*/Sequel Pro.app/Contents/MacOS/Sequel Pro

**Comment by bderblatter-qualtrics** [comment] 2021-05-13 17:54
I just reproduced. what's even worse is the debug dialog that comes up afterward crashes too

**Comment by Shogobg** [comment] 2021-05-15 17:13
@prafful-panwar @bderblatter-qualtrics this project was abandoned, check out https://github.com/Sequel-Ace/Sequel-Ace

**Comment by RodgerYa** [comment] 2021-05-24 02:32
I have same probrem just now, here is reports.
`Process:               Sequel Pro [56676]
Path:                  /private/var/folders/*/Sequel Pro.app/Contents/MacOS/Sequel Pro
Identifier:            com.sequelpro.SequelPro
Version:               1.1.2 (4541)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Pro [56676]
User ID:               501

Date/Time:             2021-05-24 10:30:58.683 +0800
OS Version:            macOS 11.3.1 (20E241)
Report Version:        12
Bridge OS Version:     5.3 (18P4556)
Anonymous UUID:        6B1BCBDD-38A9-3D1B-418E-DBFDD9F1556A

Sleep/Wake UUID:       C16ADCFB-CB47-4DB7-BC32-2802F6B37BCA

Time Awake Since Boot: 160000 seconds
Time Since Wake:       2600 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [56676]


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=888.5M resident=0K(0%) swapped_out_or_unallocated=888.5M(100%)
Writable regions: Total=3.0G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=3.0G(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               256K        2 
Activity Tracing                   256K        1 
CG backing stores                 4320K        6 
CG image                           488K       29 
CoreAnimation                     31.2M      272 
CoreGraphics                        12K        2 
CoreImage                          428K       25 
CoreUI image data                 5144K       43 
Foundation                          40K        2 
Image IO                           304K       32 
JS JIT generated code              1.0G        3 
JS VM Isolated Heap                 40K        3 
Kernel Alloc Once                    8K        1 
MALLOC                           373.5M       86 
MALLOC guard page                   72K       15 
MALLOC_MEDIUM (reserved)           1.2G       10         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M       18 
Stack                             16.6M       18 
VM_ALLOCATE                        124K       28 
WebKit Malloc                     8296K       11 
__DATA                            20.0M      436 
__DATA_CONST                      24.8M      257 
__DATA_DIRTY                      1269K      170 
__FONT_DATA                          4K        1 
__LINKEDIT                       504.0M       16 
__OBJC_RO                         70.1M        1 
__OBJC_RW                         2480K        3 
__TEXT                           384.6M      435 
__UNICODE                          588K        1 
mapped file                      248.3M       32 
shared memory                      760K       16 
===========                     =======  ======= 
TOTAL                              4.3G     1976 
TOTAL, minus reserved VM space     2.7G     1976 

`

**Comment by bderblatter-qualtrics** [comment] 2021-05-26 18:40
I actually found Sequel Ace right after reporting this. working great so far

**Comment by robertlipe** [comment] 2021-06-06 02:03
Please close this report. This is reported every few days for the last several years.

This project is clearly abandoned. Sequel Ace started from the same code and operates similarly, but isn't maintained by people that don't care that the app crashes hundreds of times a day for users around the world. Please close this issue and move to Sequel Ace and contribute to its development.

Your penance is telling the NEXT five people that report this problem to move to Sequel Ace. :-) That helps the user, it helps reduce clutter here, and it helps Sequel Ace gain traction.

**Closed as completed** 2021-06-07 08:11 UTC
