### ISSUE TITLE
Duplicate database doesn't copy views, procedures & functions

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1491] opened 2013-11-09 05:24 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1491
Reporter:swro...@gmail.com Date:2012-11-07 19:37:06 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. Choose a database w/ views, procedures and/or functions
2. Choose duplicate or rename database
3. Duplicate database will error out after copying tables, but not views, procedures or functions. Rename database won't error out, but only tables will be moved to the new database name, and the old name will still exist.

<b>What is the expected output? What do you see instead?</b>
Completely renamed/duplicated database!

What version of Sequel Pro are you using? Nightly 3908
What version of OS X are you using? 10.8.2
What version of MySQL are you connecting to on the server? 5.5.27

<b>Please provide any additional information below.</b>

**Comment by dioobr** [comment] 2016-01-29 10:32
When renamed, the original database isn't deleted, empty but not deleted.

Sequel Pro 1.1.0.1 (Build 4500)
Mac OS Lion 10.7.5
MySQL 5.5.40

**Comment by dmoagx** [comment] 2016-01-29 16:51
@dioobr → #2334

**Comment by stuconnolly** [comment] 2017-04-01 21:55
Duplicate of #1235

**Closed by stuconnolly** 2017-04-01 21:55 UTC
Labels: Bug
