### ISSUE TITLE
install success but can't use,help me please

### ISSUE THREAD

**Issue by yangzh8343** [sequelpro/sequelpro#3166] opened 2018-09-14 11:52 UTC
this alert info show every step:click connect or refresh databases
![image](https://user-images.githubusercontent.com/30249683/45548452-f7451c80-b856-11e8-95a9-8d522de08cc1.png)
i find it's connect sucess yet,because i create a database success use sequel pro,but can't appear in the left menu

**Comment by dmoagx** [comment] 2018-09-14 21:11
Duplicate of #2699

**Closed by dmoagx** 2018-09-14 21:11 UTC
