### ISSUE TITLE
Cannot manage EVENTS  (See/Add/Edit)

### ISSUE THREAD

**Issue by fsantulli** [sequelpro/sequelpro#3042] opened 2018-05-01 15:36 UTC
We have many scheduled events defined with CREATE EVENT. We are going to show them just using the SHOW EVENTS command from the query window.

Could you push some code to let them be shown as tables, views, procedures or functions?

Best regards.

Federico

**Comment by dmoagx** [comment] 2018-05-01 15:54
Duplicate of #1241

**Closed by dmoagx** 2018-05-01 15:54 UTC
