### ISSUE TITLE
[REQ] Increase number of remembered queries in Query History

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#630] opened 2013-11-09 03:56 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=630
Reporter:timmycha...@gmail.com Date:2010-04-09 12:43:16 Status:Accepted

Currently, the preference to remember queries in the Query History is limited to the most-recent 99 
queries. Is it possible/practical to increase this number to something much larger? 1,000 would be 
a good start, but if it could be much higher (or unlimited), that would be wonderful.

Slightly less-critical—but somewhat related—is the awkward warning message displayed when I try 
and enter a number beyond the 99 limit (see attached). Perhaps an indication of the actual limit 
would be helpful, or instead of a button to &quot;Discard Changes,&quot; have it automatically change the 
value to the maximum rather than making me try and figure out the max by trial and error 
(although I do love a good puzzle).

I'm currently using nightly build 2085.

**Comment by fulldecent** [comment] 2017-03-28 00:46
Implemented here

![screen shot 2017-03-27 at 8 45 41 pm](https://cloud.githubusercontent.com/assets/382183/24383966/7bde4cca-132e-11e7-8e2c-32ab5701a761.png)


Recommending close issue.

**Comment by abhibeckert** [comment] 2017-03-28 01:11
Duplicate of #2415

**Closed by abhibeckert** 2017-03-28 01:11 UTC
Labels: Duplicate, Enhancement
