### ISSUE TITLE
MySQL 8.0.11 bug. can`t connect the choose database

### ISSUE THREAD

**Issue by pruas** [sequelpro/sequelpro#3129] opened 2018-08-02 03:22 UTC
it always throw this exception:

`NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x60000023f220

(
	0   CoreFoundation                      0x00007fff353372db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5c4d8c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff353cfdb4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff352ad820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff352ad1e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000055a8 -[SPCustomQuery performQueriesTask:] + 3575
	7   Foundation                          0x00007fff373bc1f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff5d40a661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff5d40a50d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff5d409bf9 thread_start + 13
)`

**Comment by dmoagx** [comment] 2018-08-02 09:15
Duplicate of #2699

**Closed by dmoagx** 2018-08-02 09:15 UTC
