### ISSUE TITLE
Triggers and procedures

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#870] opened 2013-11-09 04:24 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=870
Reporter:it.digiv...@gmail.com Date:2010-10-21 08:09:44 Status:Accepted

It would be nice to see the TRIGGERS and PROCEDURES created in the table create syntax window

**Comment by fulldecent** [comment] 2017-03-28 01:09
Duplicate of #639.

**Comment by abhibeckert** [comment] 2017-03-28 01:30
Duplicate of #82

**Closed by abhibeckert** 2017-03-28 01:30 UTC
Labels: Duplicate, Enhancement
