### ISSUE TITLE
add rows  when  a column is  timestamp(x) DEFAULT CURRENT_TIMESTAMP(x) ,the column get zero value.

### ISSUE THREAD

**Issue by YouEclipse** [sequelpro/sequelpro#3029] opened 2018-04-10 05:27 UTC
running on OSX 10.12.6  SequelPro 1.1.2  #Build4541(602e11a)
MySQL version 

> innodb_version	5.7.16
protocol_version	10
slave_type_conversions	
tls_version	TLSv1,TLSv1.1
version	5.7.16
version_comment	MySQL Community Server (GPL)
version_compile_machine	x86_64
version_compile_os	Linux

for example,when i create a table 
`
CREATE TABLE t1 (
   id int(11) NOT NULL AUTO_INCREMENT,
   ts TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ,
   PRIMARY KEY(id)
);  `

when i add a row using sequelpro manually, the ts value should current timestamp,but get zero value
![image](https://user-images.githubusercontent.com/8252317/38537648-5d8c97cc-3cc2-11e8-9278-fce27416d847.png)

instead ,i add a column using SQL
`INSERT INTO t1 (id) VALUES(2);`
i got the right value

![image](https://user-images.githubusercontent.com/8252317/38537685-92547146-3cc2-11e8-99c2-3b66ab8601e2.png)

**Comment by dmoagx** [comment] 2018-04-10 18:37
Fractional seconds are not supported in 1.1.2
You'll have to wait for 1.2 or use a nightly build.

Duplicate of #2315

**Closed by dmoagx** 2018-04-10 18:37 UTC
