### ISSUE TITLE
Read-only mode / Dummy mode

### ISSUE THREAD

**Issue by dmaciej** [sequelpro/sequelpro#2739] opened 2017-03-22 09:14 UTC
It would be nice to have a feature to connect in read-only mode or at least to have an option to set the `--i-am-a-dummy` (`--safe-updates`) connection flag (https://dev.mysql.com/doc/refman/5.7/en/mysql-tips.html#safe-updates)

**Comment by stuconnolly** [comment] 2017-03-22 12:58
Duplicate of #2227

**Closed by stuconnolly** 2017-03-22 12:58 UTC
