### ISSUE TITLE
Following a foreign key doesn't filter the target table

### ISSUE THREAD

**Issue by sebastianheise** [sequelpro/sequelpro#3280] opened 2018-11-05 01:48 UTC
- Sequel Pro Version: Build 5422 (81986f5d)  - but I noticed this already a few weeks ago on older builds
- macOS Version: 10.14.1
- MySQL Version: 5.6.40

**Description**
When clicking the little arrow in a circle next to a foreign key, the new tables is displayed, but not filtered. All rows are shown instead of just the target row.

**Steps To Reproduce**
1. Create two tables that are linked by a FK.
2. Create multiple rows and enter a FK.
3. Click the link next to a FK

**Expected Behaviour**
Only show the FK target row.

**Comment by dmoagx** [comment] 2018-11-05 08:09
Duplicate of #2792

**Closed by dmoagx** 2018-11-05 08:09 UTC
