### ISSUE TITLE
Weird dock icon

### ISSUE THREAD

**Issue by victorronnow** [sequelpro/sequelpro#2848] opened 2017-08-06 18:02 UTC
<img width="274" alt="skaermbillede 2017-08-06 kl 20 01 23" src="https://user-images.githubusercontent.com/17050767/29005743-29999b6a-7ae2-11e7-9e74-727ff077863a.png">

**Comment by dmoagx** [comment] 2017-08-06 18:15
Duplicate of #2623

**Closed by dmoagx** 2017-08-06 18:15 UTC
