### ISSUE TITLE
Sequel Pro 1.1: Exception when mysql_upgrade has not been run after upgrading MySQL to 5.7 (homebrew)

### ISSUE THREAD

**Issue by phoenixgao** [sequelpro/sequelpro#2302] opened 2015-10-22 03:07 UTC
Test connection works fine, but once connect this error happens.

(Sequel Pro installed on Mac 10.10, mysql installed on remote ubuntu 14.04 server)

<pre>
NSInvalidArgumentException

*** -[NSPlaceholderString initWithString:]: nil argument

(
	0   CoreFoundation                      0x00007fff8e42503c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff99e4076e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8e424eed +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff908182dc -[NSPlaceholderString initWithString:] + 102
	4   Sequel Pro                          0x000000010002e6a9 -[SPDatabaseDocument setConnection:] + 384
	5   Foundation                          0x00007fff9086bd00 __NSThreadPerformPerform + 293
	6   CoreFoundation                      0x00007fff8e341a01 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x00007fff8e333b8d __CFRunLoopDoSources0 + 269
	8   CoreFoundation                      0x00007fff8e3331bf __CFRunLoopRun + 927
	9   CoreFoundation                      0x00007fff8e332bd8 CFRunLoopRunSpecific + 296
	10  HIToolbox                           0x00007fff91e8356f RunCurrentEventLoopInMode + 235
	11  HIToolbox                           0x00007fff91e832ea ReceiveNextEventCommon + 431
	12  HIToolbox                           0x00007fff91e8312b _BlockUntilNextEventMatchingListInModeWithFilter + 71
	13  AppKit                              0x00007fff927469bb _DPSNextEvent + 978
	14  AppKit                              0x00007fff92745f68 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
	15  AppKit                              0x00007fff9273bbf3 -[NSApplication run] + 594
	16  AppKit                              0x00007fff926b8354 NSApplicationMain + 1832
	17  Sequel Pro                          0x0000000100001994 start + 52
	18  ???                                 0x0000000000000002 0x0 + 2
)
</pre>

**Comment by dmoagx** [comment] 2015-10-22 09:37
Where did you install MySQL from?

**Comment by phoenixgao** [comment] 2015-10-23 02:42
Am I the only one getting this error?

I installed (upgraded) mysql by following this document:
http://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/

<pre>
mysql --version
mysql  Ver 14.14 Distrib 5.7.8-rc, for Linux (x86_64) using  EditLine wrapper
</pre>

connect to mysql from console works fine. 
When I try to connect from sequel pro, an error window pops up and sequel pro keeps the status "connecting..."
and It's empty in select datebases dropdown. But I can create a new database at that time and then all databases appears in the select dropdown.
If I click one of them I can see table list. If I click one of the tables, then sequel pro hangs.

**Comment by dmoagx** [comment] 2015-10-23 15:10
> http://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/

Using that works fine for me with 1.1
```
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-66-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Fri Oct 23 16:28:06 2015
max@ubuntu:~$ mysql --version
mysql  Ver 14.14 Distrib 5.7.8-rc, for Linux (x86_64) using  EditLine wrapper
```
Connecting works, I can see databases and select tables, etc.

Is this a fresh install or did you upgrade from a previous version?

**Comment by Dretch** [comment] 2015-10-27 15:20
I am getting the same issue. I am running OS X 10.10.5 (Yosemite) with MySQL 5.7.9.

**Comment by dmoagx** [comment] 2015-10-27 16:06
Um...that's nice and all, but if you don't provide any info for me to work with I can't help you either.

**Comment by dmoagx** [comment] 2015-10-27 16:11
Btw, related crash report is: http://log.sequelpro.com/view/2434

**Comment by phoenixgao** [comment] 2015-10-28 04:16
@dmoagx I upgraded from a previous version, which is default version installed via `apt-get install mysql-server mysql-client`. (I guess it was 5.5.x?) The phpmyadmin works, even my application works btw.

I will also try to install a fresh new one to see if it solves my problem, but I think there might be other people who did upgrade would see this error too.

**Comment by dmoagx** [comment] 2015-10-28 09:35
Did you run the `mysql_upgrade` program?

**Comment by phoenixgao** [comment] 2015-10-29 01:36
Yes, I did. there was some timestamp columns default value was '0000-00-00 00:00:00' and I have to change them to default current_timestamp to complete the upgrade.

**Comment by Dretch** [comment] 2015-10-29 11:23
@dmoagx 

Originally I had not run `mysql_upgrade`. I have just run it and I have the same problem with Sequel Pro.

**Comment by dmoagx** [comment] 2015-10-29 14:47
@Dretch Thanks, that's something I can look into.

**Comment by dmoagx** [comment] 2015-10-29 21:19
OK, I could reproduce the issue by just replacing a mysql 5.5 server with 5.7 without properly upgrading.

I actually thought he had already fixed that issue (for another reason) but it looks like c7b5e880003153e599a452151ee1f3a3e40aff4c did not make it into the 1.1 branch.

**Comment by dmoagx** [comment] 2015-10-30 01:00
Fixed in d82dc7bbd87c29895910ae7ff7382d98687eba00 for the 1.1.x branch

**Comment by Dretch** [comment] 2015-10-30 14:21
Thanks !

**Comment by vihuvac** [comment] 2015-11-18 19:49
I got the same error, Sequel Pro just stopped working even when it was working fine:

**MySQL** (installed via homebrew): ```mysql  Ver 14.14 Distrib 5.7.9, for osx10.11 (x86_64) using  EditLine wrapper```

**OS**: Mac OS X 10.11.1 El Capitan

**Comment by Tamiyadd** [comment] 2015-11-19 11:48
Same error too, i'm using mysql installed via homebrew and OSX El Capitan

**Comment by giannisp** [comment] 2015-11-19 20:20
OS X El Capitan + homebrew + MySQL 5.7.9:
The fix was to run:
`mysql_upgrade -u root -p`
`mysql.server restart`

**Comment by vihuvac** [comment] 2015-11-20 04:20
@giannisp awesome, it worked! Thank you very much :+1:

**Comment by phoenixgao** [comment] 2015-11-20 06:34
The error is because a old version server was not properly upgraded to 5.7.

To fix it need to run
`mysql_upgrade`
manually fix some fields if needed
and then restart mysql server

**Comment by Tamiyadd** [comment] 2015-11-20 08:54
worked like a charm, awesome!

thanks

**Comment by knilob** [comment] 2015-11-20 18:38
Thanks, @giannisp. Running the mysql_upgrade command totally did the trick.

**Comment by Alhadis** [comment] 2015-11-25 15:03
@giannisp: You ripper! :D That fix worked a treat, thanks cobber! :+1:

I also have MySQL managed by Homebrew, so perhaps a recent update had something to do with it...?

**Comment by aginanjar** [comment] 2015-11-26 04:56
Yes, it's worked. Thanks @giannisp  . :rocket:

**Comment by Ardakilic** [comment] 2015-11-30 17:49
I had the same issue, none of the methods above worked, completely reinstalling the MySQL from homebrew fixed the issue for my case:

```shell
brew uninstall mysql
rm -Rf /usr/local/var/mysql
brew install mysql
mysql.server start
```

**Comment by kjunggithub** [comment] 2015-12-09 00:00
I am on El Capitan and mysql installed via homebrew. @giannisp's solution did it for me! Thanks.

**Comment by LucasKA** [comment] 2015-12-09 00:24
+1 to @giannisp 

Same issue

**Comment by bramchi** [comment] 2015-12-09 14:05
@giannisp great tip, worked for me too

**Comment by karolyi** [comment] 2015-12-13 14:47
+1, mysql_upgrade + restart fixed it, thx for the clarification

**Comment by vaske** [comment] 2016-01-04 08:04
@giannisp thanks man!

**Comment by azrr** [comment] 2016-01-07 13:47
many thanks! just saved my day.

**Comment by Elyx0** [comment] 2016-01-11 16:09
Saved my day too ! Pasted my exception `*** -[NSPlaceholderString initWithString:]: nil argument sequelpro` and ended up here. Thanks again.

**Comment by jsalamin** [comment] 2016-01-11 20:44
@giannisp Thank you, these commands fixed the issue!

```
mysql_upgrade -u root -p
mysql.server restart
```

**Comment by ciarant** [comment] 2016-01-13 17:19
@giannisp Thank you!

**Comment by taledo** [comment] 2016-01-17 22:44
Glad I found this! The `mysql_upgrade` did the trick :+1:

**Comment by hiddebraun** [comment] 2016-01-28 18:50
Same here, i have a homebrew installed mysql (5.7.10) and after a `mysql_upgrade` and `mysql.server restart` everything is working again ;-)

**Comment by Jatiba** [comment] 2016-02-02 08:28
@giannisp Thank you, mysql_upgrade did the trick! 
MacOS X 10.11.3 - Sequel Pro crashes after homebrew update of MySQL.

**Comment by anthony-robin** [comment] 2016-02-07 09:36
Thanks you @giannisp  !

**Comment by resting** [comment] 2016-02-08 06:18
Thanks. `mysql_upgrade -uroot` did the trick for me.
Had to restart mysql after upgrade and boom!

**Comment by jsoprano** [comment] 2016-02-13 16:15
Guys, I'm still getting the same error when I try to connect with a user that is not root, if I connect with the root user everything works perfectly but the moment I try to connect with a user that has only access to one database even tho connecting with that user from the console works perfectly using sequel Pro I get the same error reported here. Tried the `mysql_upgrade -uroot -p` and restarted but still having the same issue.

**Comment by jsoprano** [comment] 2016-02-13 16:54
Just downloaded the RC1a version from here: https://github.com/sequelpro/sequelpro/releases/tag/1.1.1-rc1 and now it works perfectly.

**Comment by dmoagx** [comment] 2016-02-13 17:05
@jsoprano Nevertheless, please open Console.app and look for messages from Sequel Pro, there is still a high chance something is not right.

**Comment by jsoprano** [comment] 2016-02-13 18:18
@dmoagx just tested closing Sequel Pro, tailing the /var/log/system.log file and opening the app and connecting again and didn't find any logs written, should I be looking in a different log or that its ok?

**Comment by dmoagx** [comment] 2016-02-13 18:27
system.log is fine usually.
If nothing is logged then your issue probably had a different cause - which would also match with `mysql_upgrade` not fixing the problem for you.
Do you still have a full crash report?

**Comment by jsoprano** [comment] 2016-02-13 18:33
@dmoagx yes, I did report it today the last time that it happened but I also have the crash report file or contents if you want me to mail it or paste it here, just let me know what you prefer.

**Comment by jbryanscott** [comment] 2016-02-16 22:57
I received the same error after upgrading from 5.5 --> 5.6 --> 5.7.11 on Ubuntu 14.04. This worked for me:

`root@server $ mysql_upgrade -uroot -p`
`root@server $ sudo service mysql restart`

**Comment by dmoagx** [comment] 2016-02-20 13:12
Issue fixed in 1.1.1
See http://www.sequelpro.com/blog/2016.02/sequel-pro-1-1-1/

**Closed by dmoagx** 2016-02-20 13:12 UTC
Labels: Bug, Fixed-AwaitingRelease

**Comment by realwol** [comment] 2016-09-28 07:12
Thanks a lot.

**Comment by phruek1412** [comment] 2017-08-14 06:07
Thanks so much, you made my day

**Comment by wenlong-ihoment** [comment] 2017-12-05 08:50
@giannisp That works, thank you so much!
