### ISSUE TITLE
Pop-up sheet causes seg fault

### ISSUE THREAD

**Issue by nexbridge** [sequelpro/sequelpro#2824] opened 2017-06-23 10:26 UTC
When I double-click on a TEXT field in the table view to edit it, it opens up a pop-up sheet, which then promptly crashes Sequel Pro. Unfortunately it doesn't seem to be strictly replicable, in that immediately after I start Sequel Pro it doesn't happen, but only after it's "been running for a while" (and I don't know how long that "while" is), whereupon it always seems to happen.  I don't think it's restricted to TEXT fields either, but rather any field that opens up a pop-up sheet to edit.  I've looked through your previously reported issues, and there does seem to be mention of similar issues, but I wasn't sure whether this was the same issue or not.  I've attached a crash log for you - let me know if there's anything else you need.

Thanks!

[crash_log.txt](https://github.com/sequelpro/sequelpro/files/1097484/crash_log.txt)

**Comment by dmoagx** [comment] 2017-06-23 10:55
One odd thing about the crash report is that there are muuuuuuuch too many `-[NSConnection run]` threads, but that thing is OS X-internal and I don't even know what creates them.

Anyway, the crash you are seeing is a variant of #2492 
I don't know why/when it happens, but I suspect it is closely related to search.
Next time this crash occurs please try to remember whether/how you used search (cmd+F) before that.

**Comment by nexbridge** [comment] 2017-06-23 10:58
Thanks for the response.  Regarding how I use search, do you mean on Sequel Pro specifically, or on my Mac in general?

**Comment by dmoagx** [comment] 2017-06-23 11:01
In Sequel Pro

**Comment by nexbridge** [comment] 2017-06-23 12:33
Do you mean what filter I last used, or whether I specifically typed cmd+F to do it?  Only I never type cmd+F, I access the filter via trackpad click, if that answers your question?

**Comment by dmoagx** [comment] 2017-06-23 12:41
I don't mean the SQL table filter in Sequel Pro, I'm referring to the OS X search in text fields feature (cmd+F or Edit > Search > Search…), that can be used in the Query Editor or the pop up edit sheet.

**Comment by nexbridge** [comment] 2017-06-23 12:54
Ah - right I can replicate it on demand now.  In the window where you type in SQL queries to run (is that what you mean by the query editor?), if I then type cmd+F, then click Next, then open up a pop-up edit sheet, then click Cancel, it seg faults.

**Comment by dmoagx** [comment] 2017-06-25 19:48
OK, I can reproduce that.

However, even after looking at it for hours I don't understand what OS X does there.
There is `_NSTextFinderImpl` which seems to be the abstract base class of `_NSGlobalTextFinder`, `_NSFindPanelTextFinder` and `_NSBarTextFinder`.

Then there is `NSTextFinder` which seems to be an unrelated class, but is passed to _NSTextFinderImpl in `-[_NSTextFinderImpl setFinder:]` which stores it **unretained**.

Now, there is only one shared `_NSFindPanelTextFinder` instance, but the editor sheet has its own `NSTextFinder` which only lives as long as the sheet. When it is dealloc'd the `_NSFindPanelTextFinder` still has the reference and will then cause a zombie call.

There is one call made by us involved in this:
```objc
[editTextView setUsesFindBar:YES];
```
(in `-[SPFieldEditorController init]`) (which is there for cross OS-version compatibility). That call causes the problematic `NSTextFinder` to be created.

**Comment by nexbridge** [comment] 2017-06-27 09:52
Ok thanks for investigating - is there any way to fix or work around it?

**Comment by dmoagx** [comment] 2017-06-30 20:48
So I did all kinds of tracing through the Cocoa code and in the end it boils down to this: If the object that gets the focus after closing the sheet is not an NSTextView it will crash.

This is true for SP as well as for a minimal test app I wrote.

I'm at a point where I believe this is simply a bug in OS X.

The only sane way to avoid this seems to be to use the same style (panel/bar) for all NSTextViews in the app.

**Comment by nexbridge** [comment] 2017-07-03 08:36
Thanks for all your efforts - when you say "The only sane way to avoid this seems to be to use the same style (panel/bar) for all NSTextViews in the app” are you talking to your developers about adding a workaround, rather than me?  Only I've no idea what that means!

**Comment by dmoagx** [comment] 2017-07-04 20:07
> are you talking to your developers about adding a workaround

Yes.
There is nothing you can do at the moment other than making sure the find panel is not open before you use the field editor sheet.

**Closed** 2022-08-08 22:31 UTC
Labels: Bug
