### ISSUE TITLE
Crashes loads on Mojave

### ISSUE THREAD

**Issue by mchristie** [sequelpro/sequelpro#3205] opened 2018-10-05 10:48 UTC
Since updating to Mojave I've seen Sequel Pro crash loads, in particular when I close any tab.

**Comment by knaps151** [comment] 2018-10-05 10:58
The same issue with me, as soon as you close a tab connection the application crashes. :(

**Comment by stuconnolly** [comment] 2018-10-05 11:27
Duplicate of #3116 

Please search open issues before raising new ones.

**Closed by stuconnolly** 2018-10-05 11:27 UTC
Labels: Duplicate
