### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by leaxoy** [sequelpro/sequelpro#3191] opened 2018-09-30 18:11 UTC
I noticed that the last official build is one year ago, there many feature during this year(mysql 8 support, dark mode..) we can't use, so it's great to publish a new release.

**Comment by brunnopleffken** [comment] 2018-09-30 18:40
I agree... It's been two and a half years since the last update, I'm not using Sequel Pro anymore because it just doesn't support MySQL 8... BTW, after upgrading to macOS Mojave, the UI seems a little out of place...

**Comment by daniesy** [comment] 2018-09-30 19:00
@brunnopleffken what are you using now?

**Comment by brunnopleffken** [comment] 2018-09-30 19:12
> @brunnopleffken what are you using now?

I'm using TablePlus, for both MySQL 8 and PostgreSQL.

**Comment by daniesy** [comment] 2018-09-30 19:15
Thanks, i'll give it a shot

**Comment by dmoagx** [comment] 2018-09-30 21:16
Duplicate of #3034

**Closed by dmoagx** 2018-09-30 21:16 UTC
