### ISSUE TITLE
SQL editor is extremly slow when writing query with 50+ rows

### ISSUE THREAD

**Issue by Matej-Petrla** [sequelpro/sequelpro#3127] opened 2018-07-31 07:57 UTC
When writing long SQL query, editor si slowing down with every new row.
If is query too long, when you start typping you wait for seconds before it is written in editor.

**Comment by dmoagx** [comment] 2018-07-31 20:05
This is a duplicate of either:
a) If you have a Mac with touchbar -> #2783
b) Your query history is too big -> #687

**Closed by dmoagx** 2018-07-31 20:05 UTC
