### ISSUE TITLE
Control-H is overriden by SequelPro in SQL editing pad

### ISSUE THREAD

**Issue by razzmatazz** [sequelpro/sequelpro#2275] opened 2015-10-07 14:39 UTC
Nice app!

The standard behaviour for this Control-H shortcut on OS X is an does <delete-char-backwards>/<backspace>. This key binding is also used in bash, etc.

On SequelPro SQL query editor pressing it opens a "MySQL Help" panel. Would it be possible to remap that to some other keybinding and keep Control-H working as in any other OS X input field?

Thanks

**Comment by dmoagx** [comment] 2015-10-07 22:15
Duplicate of: #1974 
See (minus the nightly part):
https://github.com/sequelpro/sequelpro/issues/1974#issuecomment-54702112

**Closed by dmoagx** 2015-10-07 22:15 UTC
