### ISSUE TITLE
Sequel Pro Crashes in Mojave on closing a tab

### ISSUE THREAD

**Issue by subhgogoi** [sequelpro/sequelpro#3360] opened 2019-01-21 04:52 UTC
Sequel Pro crashes on closing a tab. Please help!

**Comment by eiselems** [comment] 2019-01-21 09:17
Duplicate of #3116 also see #2609

**Comment by cristianodpp** [comment] 2019-01-21 11:52
Same here. it always happening if have one or more tabs opened

**Comment by pretty** [comment] 2019-01-21 22:35
Yep, same for me

**Comment by pingcheng** [comment] 2019-01-21 22:56
checked project kanban, the last update is Nov last year, is this repo still maintained?

**Comment by johl-moto** [comment] 2019-01-21 23:04
Also the crash reporting dialog, crashes.

**Comment by pretty** [comment] 2019-01-21 23:38
Crashes for me too when trying to report, the irony

**Comment by ricardo-lewis** [comment] 2019-01-22 03:33
I thought that Cmd + W had become Cmd + Q, but it actually crashes instead?

**Comment by kennycason** [comment] 2019-01-22 09:59
Similar, possibly related issue:
- Mac, Mojave
- Version 1.1.2
- Crashes on close tab
- Crashes on closing of app
- Fails to send crash report
- Now I the app will startup but the moment I select a database it hangs on "connecting" (connection test passes). I'm also able to interact with the database via other SQL tools and CLI. I was also able to connect with Sequel Pro just an hour before.

**Comment by dmoagx** [comment] 2019-01-22 20:41
Duplicate of #3116

**Closed by dmoagx** 2019-01-22 20:41 UTC

**Comment by fguillen** [comment] 2019-04-11 12:50
@dmoagx you mark this issue as duplicated and pointing to another thread but the other thread is closed. I am wondering what is the status of this issue. Thanks a lot.

**Comment by lautaroml** [comment] 2019-04-17 20:17
Same here.

**Comment by vwmoose** [comment] 2019-04-21 14:36
Issue still occuring on Mojave 10.14.4.

**Comment by EriannaAbyss** [comment] 2019-04-24 12:55
Is there any news when the fix for #3166 is actually going to be released? That issue was marked as awaiting release on October 30th of 2018. That's 6 months ago.

**Comment by maarten00** [comment] 2019-05-10 09:58
Please tag a release with this bugfix.

**Comment by artisaninweb** [comment] 2019-05-21 09:46
This bug is very annoying, i'm considering switching to another program!
Please fix it!

**Comment by ricardo-lewis** [comment] 2019-05-21 12:16
@artisaninweb strangely the issue was fixed in the nightly builds ages ago so head on over and grab one

**Comment by pingcheng** [comment] 2019-05-21 12:41
> This bug is very annoying, i'm considering switching to another program!
> Please fix it.

same here, very frustrating

**Comment by ggiotta-DV** [comment] 2019-05-23 07:59
same here , Mojave + 1.1.2

**Comment by Kolvin** [comment] 2019-05-29 10:50
Been dealing with this for ages + valid points made regarding #3166

**Comment by philipwhitt** [comment] 2019-06-06 19:53
same here; Mojave 10.14.3, SequelPro 1.1.2

**Comment by arraydesign** [comment] 2019-06-07 02:21
same here; Mojave 10.14.5, SequelPro 1.1.2

**Comment by gilad-solter** [comment] 2019-06-10 08:48
Same here, any news on this one?

**Comment by pingcheng** [comment] 2019-06-11 06:04
The next version of macOS is coming and the offical fix is not yet

**Comment by gilad-solter** [comment] 2019-06-11 07:22
Download the nighly build from here: https://sequelpro.com/test-builds
Issue fixed there + you get the dark theme support!

**Comment by cuzzea** [comment] 2019-06-11 07:58
Same here: 
v 1.1.2 build 4541 (602e11a)
Mac Mojave 10.14.5

**Comment by cuzzea** [comment] 2019-06-11 08:00
> Download the nighly build from here: https://sequelpro.com/test-builds
> Issue fixed there + you get the dark theme support!

Worked for me. Just downloaded the latest build (3 months ago).

**Comment by arghajit** [comment] 2019-06-27 06:07
@cuzzea Worked like a charm. Though it is in development did not face any issue so far.

Build 97C1B85783

**Comment by SwingGuy1024** [comment] 2019-08-08 22:54
I still see it on Mojave 10.14.6, using SQ Pro 1.1.2 build 4541.
I don't want to use a nightly build. I want to use a released version that has been fixed.

**Comment by slasho** [comment] 2019-08-21 16:51
> Download the nighly build from here: https://sequelpro.com/test-builds
> Issue fixed there + you get the dark theme support!

WOW thanks!!!!! dark mode looks real nice

**Comment by romulis** [comment] 2019-09-25 03:10
Same issue. Been driving me crazy forever. 

Mojave 10.14.6, using SQ Pro 1.1.2 build 4541.

Crashes whenever trying to close a window or tab.

![sequel-pro-issue](https://user-images.githubusercontent.com/15822771/65566227-0ef1bf00-df07-11e9-9787-3672a9488bea.gif)

**Comment by hhsadiq** [comment] 2019-10-14 12:11
still happening to me, and I am on the latest version.

**Comment by rubenjleon** [comment] 2019-10-14 12:26
Strange.  I've been using Sequel Pro for many years and I can't get it to crash as so many  have talked about.  I'm in Catalina now and no matter how many tabs I open and close, it doesn't crash.
 
<img width="211" alt="image" src="https://user-images.githubusercontent.com/7998624/66751043-ed6b5f80-ee42-11e9-9ab3-23b4f392c43f.png">

**Comment by SAHANDPK** [comment] 2019-10-15 16:44
Solution is here:
Move your target tab, that you want to close,  to the last place and then close it!
For example if you have 5 tabs ( 1-2-3-4-5) and you want close tab number 3, first move tab number 3 to last like this: (1-2-4-5-3) and then click close button on tab 3!

**Comment by SAHANDPK** [comment] 2019-10-15 16:45
> still happening to me, and I am on the latest version.

Solution is here:
Move your target tab, that you want to close, to the last place and then close it!
For example if you have 5 tabs ( 1-2-3-4-5) and you want close tab number 3, first move tab number 3 to last like this: (1-2-4-5-3) and then click close button on tab 3!

**Comment by SAHANDPK** [comment] 2019-10-15 16:46
> Same issue. Been driving me crazy forever.
> 
> Mojave 10.14.6, using SQ Pro 1.1.2 build 4541.
> 
> Crashes whenever trying to close a window or tab.
> 
> ![sequel-pro-issue](https://user-images.githubusercontent.com/15822771/65566227-0ef1bf00-df07-11e9-9787-3672a9488bea.gif)

Solution is here:
Move your target tab, that you want to close, to the last place and then close it!
For example if you have 5 tabs ( 1-2-3-4-5) and you want close tab number 3, first move tab number 3 to last like this: (1-2-4-5-3) and then click close button on tab 3!

**Comment by maarten00** [comment] 2019-10-15 16:57
> @dmoagx you mark this issue as duplicated and pointing to another thread but the other thread is locked. I am wondering what is the status of this issue. Thanks a lot.

To quote the reason of closing:
>I have locked this issue.
This has been fixed long before this issue was even opened and 99% of the discussion going on here is violating the very basics of issue tracker etiquette!
@dmoagx 

The bitter irony here is the definition of the word 'fixed'. In my opinion, 'fixed' means the bug has been fixed, merged to master and a new release was drafted and compiled. This project has not seen a stable release for over 3,5 years and the stable release is therefore obsolete. The only solution is using a nightly build. Using nightly software for connections to production databases is hardly a good idea. 

It's a shame, but it's probably time to move on. I have switched to Tableplus. It's not free, but has seen a hell of a lot more updates over the past few months than Sequel Pro ever has.

**Comment by daveupress** [comment] 2019-12-10 20:21
https://sequelpro.com/test-builds Nightly Build works for me without crashes!

**Comment by ARH-Digital** [comment] 2019-12-17 05:00
Still an ongoing issue. - Might have to try the nightly build.

- Sequel Pro Version: 1.1.2 - Build 4541
- macOS Version: Catalina - 10.15.1
- MySQL Version: 5.7.25

**Description**
Closing a tab causes the program to crash - See video from https://github.com/sequelpro/sequelpro/issues/3360#issuecomment-542304422 it is identical.

**Steps To Reproduce**
Close a connection tab.

**Expected Behaviour**
Program should not crash or close completely when a single connection tab is closed.

**Comment by cristeacosmin** [comment] 2020-01-09 14:07
> > still happening to me, and I am on the latest version.
> 
> Solution is here:
> Move your target tab, that you want to close, to the last place and then close it!
> For example if you have 5 tabs ( 1-2-3-4-5) and you want close tab number 3, first move tab number 3 to last like this: (1-2-4-5-3) and then click close button on tab 3!

You are insane if you think someone is going to move tabs before closing them.

**Comment by SAHANDPK** [comment] 2020-01-09 14:50
> > > still happening to me, and I am on the latest version.
> > 
> > 
> > Solution is here:
> > Move your target tab, that you want to close, to the last place and then close it!
> > For example if you have 5 tabs ( 1-2-3-4-5) and you want close tab number 3, first move tab number 3 to last like this: (1-2-4-5-3) and then click close button on tab 3!
> 
> You are insane if you think someone is going to move tabs before closing them.

Oh, great to meet you doctor!

**Comment by klausbreyer** [comment] 2020-01-21 07:29
nightly build helps!

**Comment by mrtrwhite** [comment] 2020-01-27 11:09
> Strange. I've been using Sequel Pro for many years and I can't get it to crash as so many have talked about. I'm in Catalina now and no matter how many tabs I open and close, it doesn't crash.
> 
> <img alt="image" width="211" src="https://user-images.githubusercontent.com/7998624/66751043-ed6b5f80-ee42-11e9-9ab3-23b4f392c43f.png">

Good for you. It happens to me 99% of the time, on Catalina, on a brand new MBP, highest spec.

**Comment by abdulmanan7** [comment] 2020-02-10 21:13
The same problem switched! hope it fixes soon

**Comment by mortscode** [comment] 2020-02-25 07:31
same problem. please push the fix. just showed a colleague my work flow and Sequel Pro crashed multiple times. Embarrassing, frustrating, and distracting. Love the application otherwise.

**Comment by bateller** [comment] 2020-03-12 19:11
Nightly build works, but is by no means a production acceptable solution

**Comment by mujay** [comment] 2020-04-10 03:53
https://sequelpro.com/test-builds It's works for me without crashes!!

**Comment by Hesesses** [comment] 2020-04-16 11:27
Any estimates when this will be fixed for non-nightly build?

**Comment by sheadawson** [comment] 2020-04-24 03:31
Come one guys, this needs to be released...

**Comment by pingcheng** [comment] 2020-04-24 03:33
apparently this repo is no longer maintained
sorry guys, i am moving to an another one. Bug still look forward to having this back

**Comment by alsan1997** [comment] 2020-04-26 14:29
please fix this soon!!!! crashing on closing tabs

**Comment by AneekRahman** [comment] 2020-05-03 00:40
For the love of, how long does it take to fix an issue like this?

**Comment by zwacki1337** [comment] 2020-05-10 10:09
fix this!

**Comment by SBenoit5** [comment] 2020-05-29 10:20
https://sequelpro.com/test-builds

**Comment by mcauser** [comment] 2020-07-21 03:00
Confirmed issue on:
macOS Mojave 10.14.6 (18G6020)
Sequel Pro 1.1.2 Build 4541 (602e11a)

Closing any tab crashes. Moving any tab to last place then closing crashes.

Fixed in test build 97c1b85783
https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip

**Comment by ghost** [comment] 2020-09-04 07:24
when nightly build is no option...

https://dbeaver.io/download/

**Comment by Abinash1108** [comment] 2020-09-11 06:35
Is this issue fixed?

**Comment by SwingGuy1024** [comment] 2020-09-11 11:06
I've left the company where I was using this, but I'm not entirely sure. However,  when I downloaded a pre-release later version, it was fixed. Now that there's a newer final version, it's probably fixed, but I haven't verified this.

**Comment by jakubboucek** [comment] 2020-09-19 07:03
Sequel Pro is definitely death.
Long live [Sequel Ace](https://sequel-ace.com/), new living fork of them!

**Comment by anshajgoel** [comment] 2020-09-19 14:19
Whats the problem in using Nightly build? 
@jakubboucek Have you used Sequel Ace thoroughly? How is it? There are like 5 reviews of it on the App Store!

**Comment by jakubboucek** [comment] 2020-09-19 16:34
@anshajgoel:

> Whats the problem in using Nightly build?  

The problem is the [last night build](https://sequelpro.com/test-builds) is 1 year, 3 months old.

> @jakubboucek Have you used Sequel Ace thoroughly? How is it? There are like 5 reviews of it on the App Store!  

I using Sequel Ace about last two month, it not crash yet. Unlike Sequel Pro – then is unusable in Mojave and does not support MariaDB 10.4.1+ because new [new grant model](https://jira.mariadb.org/browse/MDEV-17658). Aaggh! Try it, you will see.

**Comment by mirko77** [comment] 2021-03-03 16:58
2 years and it is still not fixed. And we thought our dev team was slow at fixing bugs but you guys win hands down

**Comment by anshajgoel** [comment] 2021-03-07 18:50
@mirko77 - as @jakubboucek suggested above, use Sequel Ace. It's far better. 🙌  I can't thank him enough for suggesting that, life's been easy since.

**Comment by mlboy** [comment] 2021-10-25 03:59
mark

**Comment by benlieb** [comment] 2021-11-04 04:40
Sequel Ace it is then. I can't believe how long I tolerated the crashes in Sequel Pro. I just learned never to close tabs or windows or CRAAASH. Lol. So annoying. I think I actually tried Sequel Ace a while back, but I couldn't get it to connect. Whatever the reason, this time it is fine, though I couldn't make it work with a socket connection.

**Comment by SBenoit5** [comment] 2021-11-04 05:07
Just download the latest beta version. The issue is fixed.

**Comment by PiotrKostanski** [comment] 2021-11-10 12:04
Honestly guys, don't bother. Just install Sequel Ace.

**Comment by medaminejridi** [comment] 2022-02-09 14:31
Still crashes in mac monterey 12.1
https://sequelpro.com/builds/Sequel-Pro-Build-97c1b85783.zip    Last build works like charm .
