### ISSUE TITLE
connect to 127.0.0.1 successfully but when choose Database it failed...

### ISSUE THREAD

**Issue by mozhe24** [sequelpro/sequelpro#3115] opened 2018-07-18 02:13 UTC
I have met a problem when I use V1.1.2 sequel pro to connect to my localhost mysql, it works.
But when I choose Database , the software show it fails and I can use 'Query' to write SQL to execute and get data from my local Database...Both the standard and Socket connection type have been tried, but they both have this problem.
<img width="817" alt="wx20180718-101200 2x" src="https://user-images.githubusercontent.com/10355080/42855445-27178338-8a73-11e8-9cee-eac4dd1f1c59.png">
<img width="946" alt="wx20180718-101232 2x" src="https://user-images.githubusercontent.com/10355080/42855447-2788d178-8a73-11e8-9e84-fec0a9abb6d2.png">

**Comment by romainnorberg** [comment] 2018-07-18 08:37
hello @mozhe24 I thing it's a Duplicate of #2699 . You can try the last build (https://sequelpro.com/test-builds) but it's really buggy.

**Comment by dmoagx** [comment] 2018-07-18 16:59
Duplicate of #2699

**Closed by dmoagx** 2018-07-18 16:59 UTC

**Comment by mozhe24** [comment] 2018-07-19 01:08
Thanks , I have used then last build and don't find this same bug...connecting to localhost is ok
