### ISSUE TITLE
Reopen previous sessions with their contents on startup

### ISSUE THREAD

**Issue by dland** [sequelpro/sequelpro#2222] opened 2015-09-11 08:20 UTC
It's really easy to ⌘-Q and exit the app instead of ⌘-W to close the current tab.

It would be extremely helpful to record the current sessions/connections and the contents of the query pane (i.e. the equivalent .spf files) and restore them upon startup. That way you don't lose any work (and avoids having to grovel through the query history, which mashes all the queries from different connections together and is therefore pretty useless when you work with a dozen different clusters).

Similarly, if the db connection is down (e.g. you're temporarily outside your VPN and no way to get back in) it would be nice to be able to dismiss the dialog box and leave the query pane in a disconnected state. Because again, if you can't connect, and you cancel the reconnect, the pane is closed and you have no chance to save the session.

**Comment by dmoagx** [comment] 2015-09-11 21:54
Duplicate of #304

**Closed by dmoagx** 2015-09-11 21:54 UTC
