### ISSUE TITLE
Crash when selecting a database on MySQL 8.0.11

### ISSUE THREAD

**Issue by guimadaleno** [sequelpro/sequelpro#3112] opened 2018-07-16 14:27 UTC
Hello. 

Since I upgraded my local MySQL server to 8.0.11, I’m having this issue. 
When I connect and select a database, it simply crashes.
I've also noticed the same problem happening when I import SQL files.
I uploaded a video that show what happens in practice. 

https://youtu.be/JgTCb6n2XRQ

I really appreciate your help.

**Comment by redjersey** [comment] 2018-07-16 14:39
I'm having the exact same problem. Here is the error log:

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000037520

(
	0   CoreFoundation                      0x00007fff442602db __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff6b401c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff442f8db4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff441d6820 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff441d61e8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff462e51f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff6c333661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff6c33350d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff6c332bf9 thread_start + 13
)

**Comment by guimadaleno** [comment] 2018-07-16 16:35
I downgraded my MySQL server to 5.7.22 and it works fine now. I don't know much about MySQL but it seems this bug is caused by their latest update. At least I can work now lol. Thanks anyway.

**Comment by dmoagx** [comment] 2018-07-17 06:57
Duplicate of #2699

**Closed by dmoagx** 2018-07-17 06:57 UTC
