### ISSUE TITLE
Bug: BIT type is not displayed correctly

### ISSUE THREAD

**Issue by Marco-MCN** [sequelpro/sequelpro#2257] opened 2015-10-02 09:19 UTC
Hi,
we just update from v 1.0.2 to 1.1 (on MacBook 2011 + Yosemite) and have following problem:

Value     ->     Viewed with v1.0.2    ->  Viewed with v1.1 
 b'0'                     00000000                    10000000
 b'1'                     00000001                    10000000

In fact is impossible distinguish from b'0' to b'1'.
See attachment.
![screen shot 2015-10-02 at 11 19 11](https://cloud.githubusercontent.com/assets/14938284/10243317/1d4b1aee-68f8-11e5-9c6f-6f40a4d22abe.png)
![screen shot 2015-10-02 at 11 18 27](https://cloud.githubusercontent.com/assets/14938284/10243318/1d4d9a4e-68f8-11e5-8952-b8884170d61f.png)

**Comment by Marco-MCN** [comment] 2015-10-02 09:24
We discover that value listed change if select have 1 or more attributes:
1) If select only the bit attribute view all 00000000 independently if 1 or 0
2) If select two or more attributes view 10000000 independently if 1 or 0

![screen shot 2015-10-02 at 11 19 11](https://cloud.githubusercontent.com/assets/14938284/10243325/2aacba6c-68f8-11e5-8cc8-4781bb112918.png)
![screen shot 2015-10-02 at 11 18 52](https://cloud.githubusercontent.com/assets/14938284/10243326/2ab2e662-68f8-11e5-90fb-c55f07105c7b.png)
![screen shot 2015-10-02 at 11 18 27](https://cloud.githubusercontent.com/assets/14938284/10243328/2ab3e15c-68f8-11e5-89f3-4ca5a21db300.png)
![screen shot 2015-10-02 at 11 18 08](https://cloud.githubusercontent.com/assets/14938284/10243327/2ab34a08-68f8-11e5-92d1-48a15241d162.png)

**Comment by dmoagx** [comment] 2015-10-02 11:21
Duplicate of #2254

**Closed by dmoagx** 2015-10-02 11:21 UTC
