### ISSUE TITLE
Application hangs on opening existing database

### ISSUE THREAD

**Issue by Sosycs** [sequelpro/sequelpro#3114] opened 2018-07-17 15:43 UTC
I work on mac os High Sierra. MySQL version 8.0.11, Apache 2.4.33
I was able to create a database and a table on it. However, I could not open again this database after I restarted the application. 
I tried the following steps several times:
1- Quit the application.
2- stop mySQL server.
3- start mySQL server.
4- open Sequel Pro and try to open the database.

What can I do?

<img width="946" alt="screen shot 2018-07-17 at 6 38 22 pm" src="https://user-images.githubusercontent.com/6597399/42828298-06b4c1aa-89f1-11e8-8c75-f03b9c293fd2.png">

**Comment by jcalado** [comment] 2018-07-17 19:15
I think the culprit here is MySQL 8.
Either rollback or use MySQL WorkBench.

**Comment by JamesVanWaza** [comment] 2018-07-17 20:10
@jcalado @Sosycs 
Duplicate of #2699

**Comment by dmoagx** [comment] 2018-07-17 21:15
Duplicate of #2699

**Closed by dmoagx** 2018-07-17 21:15 UTC
