### ISSUE TITLE
Problem in Mac OS Mojave

### ISSUE THREAD

**Issue by raag** [sequelpro/sequelpro#3223] opened 2018-10-10 14:56 UTC
When close the application or a tab on the last update of Mac OS it crashes.

**Comment by humole** [comment] 2018-10-10 16:02
Same problem, what I found on the console log:
default	10:58:32.879535 -0500	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Sequel Pro, _appTrackingState = 2
default	10:58:32.879572 -0500	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: Sequel Pro, quit, updating active tracking timer
default	10:58:32.879600 -0500	loginwindow	-[PersistentAppsSupport(Internal) updateActiveTrackingTimer] | Creating timer

And I have a crash log too, though I don't know how to upload it.

**Comment by humole** [comment] 2018-10-10 16:08
Sorry, I found that this is a duplicate of https://github.com/sequelpro/sequelpro/issues/3116
The fix seems to been worked out, just waiting for a release. Maybe pin that issue to prevent dupes on a common issue like this?

**Comment by stuconnolly** [comment] 2018-10-10 16:16
Duplicate of #3116

**Closed by stuconnolly** 2018-10-10 16:16 UTC
Labels: Duplicate
