### ISSUE TITLE
SP crashes when closing tabs

### ISSUE THREAD

**Issue by Firehed** [sequelpro/sequelpro#2751] opened 2017-03-28 23:21 UTC
This is happening 100% of the time on my local machine with the latest build. Check for updates says 93239c0688 and the about menu says nightly build 5165 (bab93f8). Not sure if this means the update did not apply correctly or if (presumably) 4d450e1 didn't actually fix the issue.

Happy to provide any additional information as necessary. OS X 10.12.3 on the latest 15" rMBP (2016 touch bar model). I didn't see anything that looked immediately useful in the system console.

**Comment by dmoagx** [comment] 2017-03-28 23:26
Duplicate of #2750 

But, if you don't need SSH launch Sequel Pro from Terminal with:
```
NSZombieEnabled=YES /Applications/Sequel\ Pro.app/Contents/MacOS/Sequel\ Pro
```
And post the output when it crashes.

**Comment by Firehed** [comment] 2017-03-28 23:28
```
$ NSZombieEnabled=YES /Applications/Sequel\ Pro.app/Contents/MacOS/Sequel\ Pro

2017-03-28 16:27:17.038 Sequel Pro[89297:29979481] Not yet implemented.
2017-03-28 16:27:17.039 Sequel Pro[89297:29979481] Not yet implemented.
2017-03-28 16:27:17.526 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:17.634 Sequel Pro[89297:29979481] Not yet implemented.
2017-03-28 16:27:17.635 Sequel Pro[89297:29979481] Not yet implemented.
2017-03-28 16:27:17.635 Sequel Pro[89297:29979481] Not yet implemented.
2017-03-28 16:27:17.635 Sequel Pro[89297:29979481] Not yet implemented.
2017-03-28 16:27:17.637 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:17.641 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint


2017-03-28 16:27:23.294 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.297 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.345 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.387 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.429 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.433 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.479 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.698 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.798 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:23.806 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.423 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.541 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.546 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.549 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.558 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.594 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.605 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.642 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.647 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.652 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.656 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.697 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.708 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.745 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.758 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.761 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.765 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.803 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.809 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.847 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.860 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.899 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.909 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.948 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.961 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:24.999 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:25.009 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:25.080 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:25.090 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:25.093 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:25.097 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:26.095 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:26.100 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde62a30220>) had to adjust the size of <NSPopUpButton: 0x7fde623245f0> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:26.656 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:26.768 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:26.772 Sequel Pro[89297:29979481] NSToolbarItem (<NSToolbarItem: 0x7fde5f7f0960>) had to adjust the size of <NSPopUpButton: 0x7fde5a427740> from {298, 26} to the expected size of {300, 27}. Make sure that this toolbar item view has a valid frame/min/max size. This is an app bug, please do not file a bug against AppKit or NSToolbar! Break on _NSToolbarAdjustedBorderedControlSizeBreakpoint
2017-03-28 16:27:26.871 Sequel Pro[89297:29979481] *** -[SPTableTriggers retain]: message sent to deallocated instance 0x7fde624ca000
Trace/BPT trap: 5```

**Comment by dmoagx** [comment] 2017-03-28 23:41
Huh, that's interesting.
Does it already crash if you just open and close a window or do you need to have an open connection?

**Comment by Firehed** [comment] 2017-03-28 23:43
Apparently a connection is not required. I was able to repro the issue by just opening SP, hitting cmd+t, then cmd+w.

**Comment by dmoagx** [comment] 2017-03-29 00:04
OK, wait...
There is something fishy with the nightly builds.
5165 and `bab93f8` does not match.

**Comment by dmoagx** [comment] 2017-03-29 00:13
bab93f8ce7 was 5149 and 5165 is supposed to be 93239c0688.

I just checked with the disassembler and 5165 does not contain the code it should...

**Comment by Firehed** [comment] 2017-03-29 00:21
Ok, that's super weird. Not just some odd behavior with the about screen?

When I `sha1sum` the binary in /Applications/SP/Contents/MacOS I get `f44745d7bdcd677c6506408763a433ba60d05969` if that's any help.

**Comment by abhibeckert** [comment] 2017-03-29 01:03
@Firehed every nightly build in the last 5 days hasn't worked properly.

I'm at my day job now (11am), and will investigate as soon as I get home. You might like to subscribe to notifications on #2752 and test once I've uploaded a more recent build.

In the mean time, consider downloading build `74ba04e2a8 ` from https://sequelpro.com/test-builds - I'm confidant that build does not have the crashing bug you're running into.

**Comment by Firehed** [comment] 2017-03-29 01:06
Will do. Thanks to both of you for looking into this.

**Comment by abhibeckert** [comment] 2017-03-29 22:04
@Firehed can you try the latest test build? You can just do "Check for Updates" to install it.

**Comment by Firehed** [comment] 2017-03-29 22:06
Yes, that resolved the issue. The build in the update screen now matches the about screen, and the latest build (well, probably an earlier one) resolves the crash.

**Comment by abhibeckert** [comment] 2017-03-29 22:13
We believe there may be multiple causes for the crash, so re-open this issue if it comes back again please.

**Closed by abhibeckert** 2017-03-29 22:13 UTC
Labels: Duplicate, WaitingOnUser
