### ISSUE TITLE
Crash when trying to open a DB

### ISSUE THREAD

**Issue by rafaelmdurante** [sequelpro/sequelpro#3172] opened 2018-09-20 13:15 UTC
```
SYSTEM
MacOS: 10.13.6
MacBookPro10,1
Memory 16384
CPU Type: Intel i7
-------------------
EXCEPTION

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6000000377e0

(
	0   CoreFoundation                      0x00007fff31c9666b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff58eec942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff31d2d994 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff31c0e133 ___forwarding___ + 1443
	4   CoreFoundation                      0x00007fff31c0db08 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff33d371f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff59e1b661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff59e1b50d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff59e1abf9 thread_start + 13
)
------------------
CONSOLE
20 de set de 2018 14:50:18: objc[1714]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8ee63c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1110c4cd8). One of the two will be used. Which one is undefined.
20 de set de 2018 14:50:18: assertion failed: 17G65: libxpc.dylib + 75013 [0BC7AD67-671D-31D4-8B88-C317B8379598]: 0x89
20 de set de 2018 14:50:21: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
20 de set de 2018 15:02:42: Found 0 crash files
20 de set de 2018 15:02:49: Sending feedback to http://log.sequelpro.com/submit
20 de set de 2018 15:02:49: Posting 8239 bytes to http://log.sequelpro.com/submit
20 de set de 2018 15:03:56: Found 0 crash files
20 de set de 2018 15:04:59: Found 0 crash files
20 de set de 2018 15:05:09: Sending feedback to http://log.sequelpro.com/submit
20 de set de 2018 15:05:09: Posting 7553 bytes to http://log.sequelpro.com/submit
20 de set de 2018 15:06:10: Connection failed
20 de set de 2018 15:06:10: Upload failed: Error Domain=NSURLErrorDomain Code=-1001 "Esgotou-se o tempo limite da solicita√ß√£o." UserInfo={NSUnderlyingError=0x600000441350 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "Esgotou-se o tempo limite da solicita√ß√£o." UserInfo={NSErrorFailingURLStringKey=http://log.sequelpro.com/submit, NSErrorFailingURLKey=http://log.sequelpro.com/submit, _kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4, NSLocalizedDescription=Esgotou-se o tempo limite da solicita√ß√£o.}}, NSErrorFailingURLStringKey=http://log.sequelpro.com/submit, NSErrorFailingURLKey=http://log.sequelpro.com/submit, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=Esgotou-se o tempo limite da soli
cita√ß√£o.}
20 de set de 2018 15:09:39: Found 0 crash files
```

**Comment by dmoagx** [comment] 2018-09-26 20:59
Duplicate of #2699

**Closed by dmoagx** 2018-09-26 20:59 UTC
