### ISSUE TITLE
'openssl/aes.h' not found in SPDataAdditions.m

### ISSUE THREAD

**Issue by Commenter123** [sequelpro/sequelpro#2242] opened 2015-09-30 12:23 UTC
I cloned the repo, opened it in Xcode, pressed Run.
Error: 'openssl/aes.h' not found in SPDataAdditions.m

How to resolve this issue?

**Comment by dmoagx** [comment] 2015-09-30 13:06
OpenSSL is no longer being used.
If you want to build an older branch you have to supply the OpenSSL headers yourself.
Duplicate of #2223

**Closed by dmoagx** 2015-09-30 13:06 UTC

**Comment by rowanbeentje** [comment] 2015-09-30 13:08
(As t'other thread says, for the 1.1 branch or other, using the 10.8 SDK is best.  master shouldn't have references to aes.h at all)
