### ISSUE TITLE
Sequelpro crashes after closing a tab

### ISSUE THREAD

**Issue by tejuino-rafael** [sequelpro/sequelpro#3240] opened 2018-10-16 14:33 UTC
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14
- MySQL Version: 10.1.19-MariaDB

**Description**
Sequelpro crashes after closing one of multiple opened tabs.

**Steps To Reproduce**
1. Open more than one tab
2. Close one tab

**Expected Behaviour**
Closing a tab should not crash the whole app.

**Additional Context**
It started since OSX Mohave upgrade.

**Comment by betzerra** [comment] 2018-10-16 14:49
Rafa, I think this is a duplicate from https://github.com/sequelpro/sequelpro/issues/3116

**Comment by stuconnolly** [comment] 2018-10-16 20:15
Spot on, this is a duplicate of #3116.

There's even this in the bug template...

<pre>
&lt!-- Please search existing issues to avoid creating duplicates. &gt;
&lt!-- For application crashes on macOS 10.14 (Mojave) please see issue #3116. --&gt;
</pre>

**Closed by stuconnolly** 2018-10-16 20:15 UTC
