### ISSUE TITLE
Crash on closing window

### ISSUE THREAD

**Issue by nisof** [sequelpro/sequelpro#2649] opened 2017-01-06 17:06 UTC
Hi

SequelPro crashes repeatedly on closing a window.
I am using Nightly Build 4720.
1. open SequelPro
2. open a Recent Saved - opens new window
3. Close initial window behind

And SequelPro dies.. Totally repeatable.
Small video attached.

Nisan
[sequelpro.mov.zip](https://github.com/sequelpro/sequelpro/files/690362/sequelpro.mov.zip)

**Comment by dmoagx** [comment] 2017-01-06 18:00
this is most likely a duplicate of #2609

**Closed by dmoagx** 2017-01-06 18:00 UTC
