### ISSUE TITLE
MySQL server in broken state will crash Sequel Pro

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1758] opened 2013-11-09 05:47 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1758
Reporter:adam.ier...@gmail.com Date:2013-07-14 11:24:32 Status:Accepted

<b>What steps will reproduce the problem?</b>
1. Connect to MariaDB 10.0.3 (possibly other versions)
2. Crash
<b>3.</b>

<b>What version of Sequel Pro are you using?</b>

Tried with 1.0.2 and nightly build on Jul 14, 2013.

<b>What version of OS X are you using?</b>

10.8.4

<b>What version of MySQL are you connecting to on the server?</b>

MariaDB 10.0.3

<b>Please provide any additional information below.</b>

Tried with and without SSH, same result. This used to work, then suddenly stopped working. I have no idea why. I did not change anything client-side, but it's possible that MariaDB was updated one revision.

Exception dump:
```
NSInvalidArgumentException

*** -[NSPlaceholderString initWithString:]: nil argument

(
	0   CoreFoundation                      0x00007fff81702b06 __exceptionPreprocess + 198
	1   libobjc.A.dylib                     0x00007fff81a8a3f0 objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff817028dc +[NSException raise:format:] + 204
	3   Foundation                          0x00007fff8bc22dac -[NSPlaceholderString initWithString:] + 93
	4   Sequel Pro                          0x0000000100032c46 -[SPDatabaseDocument setConnection:] + 450
	5   Foundation                          0x00007fff8bc485ca __NSThreadPerformPerform + 225
	6   CoreFoundation                      0x00007fff81681b31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x00007fff81681455 __CFRunLoopDoSources0 + 245
	8   CoreFoundation                      0x00007fff816a47f5 __CFRunLoopRun + 789
	9   CoreFoundation                      0x00007fff816a40e2 CFRunLoopRunSpecific + 290
	10  HIToolbox                           0x00007fff848c0eb4 RunCurrentEventLoopInMode + 209
	11  HIToolbox                           0x00007fff848c0c52 ReceiveNextEventCommon + 356
	12  HIToolbox                           0x00007fff848c0ae3 BlockUntilNextEventMatchingListInMode + 62
	13  AppKit                              0x00007fff81d6c533 _DPSNextEvent + 685
	14  AppKit                              0x00007fff81d6bdf2 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 128
	15  AppKit                              0x00007fff81d631a3 -[NSApplication run] + 517
	16  AppKit                              0x00007fff81d07bd6 NSApplicationMain + 869
	17  Sequel Pro                          0x00000001000022b4 start + 52
)
```

**Comment by dmoagx** [comment] 2015-11-06 01:54
Duplicate of #2302 
Forward merging, since the other one already has a fix.

**Closed by dmoagx** 2015-11-06 01:54 UTC
Labels: Bug, Component-Logic, Priority-Low
