### ISSUE TITLE
Incorrect BIT fields values are shown

### ISSUE THREAD

**Issue by vbashko** [sequelpro/sequelpro#2288] opened 2015-10-14 14:34 UTC
Sequel Pro 1.1, build 4499. MySQL 10.0.20-MariaDB.

CREATE TABLE TEST (
  `ID` int(11),
  `BIT_FIELD` bit(1),
  `BOOL_FIELD` boolean,
  PRIMARY KEY (`ID`)
);

INSERT INTO TEST (ID, BIT_FIELD, BOOL_FIELD) VALUES (1, TRUE, TRUE);
INSERT INTO TEST (ID, BIT_FIELD, BOOL_FIELD) VALUES (2, TRUE, FALSE);
INSERT INTO TEST (ID, BIT_FIELD, BOOL_FIELD) VALUES (3, FALSE, TRUE);
INSERT INTO TEST (ID, BIT_FIELD, BOOL_FIELD) VALUES (4, FALSE, FALSE);
INSERT INTO TEST (ID, BIT_FIELD, BOOL_FIELD) VALUES (5, FALSE, FALSE);
INSERT INTO TEST (ID, BIT_FIELD, BOOL_FIELD) VALUES (6, FALSE, FALSE);

<img width="202" alt="untitled" src="https://cloud.githubusercontent.com/assets/11600023/10486621/7e67a672-7298-11e5-97a2-bb9be532737c.png">

Look at BIT_FIELD presentation. Even the same values are shown differently.

**Comment by dmoagx** [comment] 2015-10-14 15:26
Duplicate of #2254

Until 1.1.1 is released either downgrade to 1.0.2 (http://www.sequelpro.com/release-archive) or try an experimental nightly build which has this fixed: http://nightly.sequelpro.com/

**Closed by dmoagx** 2015-10-14 15:26 UTC
