### ISSUE TITLE
crashing under macOS 10.14 on tab close

### ISSUE THREAD

**Issue by beskhu** [sequelpro/sequelpro#3235] opened 2018-10-15 01:36 UTC
Hello, sequel pro is crashing under macOS 10.14 on tab close
please fix it when possible. I made a donation recently, and I will make another after new release fixing it.
best regards

**Comment by dmoagx** [comment] 2018-10-15 01:52
Duplicate of #3116

**Closed by dmoagx** 2018-10-15 01:52 UTC
