### ISSUE TITLE
Filter content always displayed

### ISSUE THREAD

**Issue by noniagriconomie** [sequelpro/sequelpro#3427] opened 2019-03-25 11:38 UTC
Hello,

First thank you for the soft

As the latest released version crashes, I use the night build (5438)
Just a question, is there a way to keep the "filter feature" on top of table view always open?

On the latest realease it is ok
On the night build it is not, when i close and reopen the app, i have to go again on the Menu > Table > Filter Content

Is this possible or did i miss any feature toggle in the preferences?

Many thank for your time

Cheers!

**Comment by bencummins** [comment] 2019-03-25 11:46
You can use CMD+F as a quick way to open it - I find my way automatically doing this each time I switch to a new table view now.

Would be nice to have the option to have it there by default though

**Comment by noniagriconomie** [comment] 2019-03-25 13:15
yes indeed, `cmd+f`, but I ask for a permanent setting :)
any way, thank you

**Comment by ghs** [comment] 2019-03-27 10:07
Yes, with the current "stable" 1.1.2 the filters are always on once opened but with Nightly build (5438) are gone with every table change...

**Comment by dmoagx** [comment] 2019-03-31 17:28
Duplicate of #3304

**Closed by dmoagx** 2019-03-31 17:28 UTC
