### ISSUE TITLE
Modern Design Idea

### ISSUE THREAD

**Issue by BenjaminHoegh** [sequelpro/sequelpro#2891] opened 2017-09-29 18:36 UTC
I have made this idea to a new more modern design of SequelPro, of course the icons in the top need to be change, but right now they are just a example.

<img width="897" alt="skaermbillede 2017-09-29 kl 20 40 17" src="https://user-images.githubusercontent.com/22152591/31030661-7161915c-a556-11e7-8d0a-1d77022303ec.png">

**Comment by Chinese1904** [comment] 2017-09-30 00:21
FYI and for reference https://github.com/sequelpro/sequelpro/issues/2730

**Comment by jerearaujo03** [comment] 2017-10-11 16:03
+1

**Comment by inoas** [comment] 2017-10-14 06:42
No thanks,
Taking out structure - since ios7 - is a failure on erogonomics and discoverability. It may charge your brain less looking at stills of this type but it will charge your brains more using it day to day.
The shades of grey also create an accessibility problem. The missing window title bar is a problem too, the missing activity indicator fir tabs is another problem. At least you kept the status bar.

**Comment by abhibeckert** [comment] 2017-10-15 23:27
We don't have enough engineering resources to develop custom user interface controls that are functionally as good as the system default controls.

This means things like removing borders between controls and making the sidebar extend into the toolbar simply isn't possible for us.

However we are planning to overhaul the UI soon as mentioned in #2730 and there are a bunch of things we could take from your design.

Can you provide the original document with layers/etc? And are you happy to release the design under the terms of the MIT license? https://github.com/sequelpro/sequelpro/blob/master/LICENSE

**Comment by inoas** [comment] 2017-10-16 10:43
The Icons could indeed change. Here is actually room for improvement towards black&white, high-res/retina icons.
The Status Bars could lose their glossy effects because that looks outdated compared to macOS current feel and does not bring any benefits really.
That aside I'd rather see a critique on why something is bad

**Comment by lloydw** [comment] 2017-10-22 00:43
Please give us the ability to have multiple databases visible in the sidebar. Having to change database from the top dropdown list is very frustrating.

**Comment by inoas** [comment] 2017-10-22 11:53
The Database could be part of a tree view on the sidebar to the left side, inside the tables.
Maybe like Postman's groups.

However could you care to elaborate why it is frustrating to change it from the top dropdown?

**Comment by lloydw** [comment] 2017-10-22 19:43
Yes, a tree view would be great! Most other database tools display databases like this (maybe an ALL option that the top would give you the best of both worlds)

I work on multiple databases all day and losing context in one database to lookup a table, column name, or do a query in another database is very frustrating.

**Comment by inoas** [comment] 2017-10-22 21:10
Well personally I think one window per database is the best way to do things and single-window applications are bad design especially on Pro apps (for newbie apps like iTunes it is ok).

So why not just spawn a 2nd window and use your mac OS window manager to switch... Expose, Mission Control, Tabbing?

**Comment by abhibeckert** [comment] 2017-10-23 03:32
@lloydw Please create a separate issue where we can discuss switching to a tree view of databases/tables.

PS: you can press `Cmd-Shift-D` to quickly switch to another datbaase.

**Comment by TomMuc1** [comment] 2017-10-28 07:38
the user interface at the moment is intuitive, the icons are much better to differentiate than the actual apple 'after steve jobs' idiocy, all tools are in the right place and moreover it looks nice, modern and professional. that said - we are product/interface designers.

**Comment by inoas** [comment] 2017-10-28 10:26
The current "trend" of no-design @ apple since Fadell has been kicked out (because of Maps fiasco) and an industrial designer (Jonny Ive) took over as head of general design may have proofed to be successful for now, but it sucks from so many angles of ergonomics and discover-ability that my 60y old mom can use windows7+thunderbird+firefox but failed to use ios10+ipad. That says it all. 

So please be careful with the changes you do. We do not need to be hip. There is no viable alternative on the market and I just wish mariadb, mysql, percona etc support will continue to grow. 

**The only usability issue I got is that stupid animation when you edit textareas. It should be instant and it should stream the contents (it did not do back then, maybe it does now already).**
Here productivity is hindered by animation and possibly by the textarea/blob not loading in a streaming/fast way.

So another gripe with the new way of design is using a lot of animations and transparency (so much in fact that the CSS-Working Group and Accessibility guys Apple sends to the CSS-WG had to push for css features that allow for reduced animation and reduced transparency because basically this is a hell for visually impaired, older or epileptic people.

**Comment by Kaspik** [comment] 2019-02-20 16:15
Duplicate of https://github.com/sequelpro/sequelpro/issues/2730, outdated.

**Closed by Kaspik** 2019-02-20 16:15 UTC
Labels: Enhancement
