### ISSUE TITLE
Unexpected error every time I try and connect

### ISSUE THREAD

**Issue by BrianKauffman** [sequelpro/sequelpro#3105] opened 2018-07-05 16:09 UTC
I am running version 1.1.2 on my Macbook OS 10.13.5 and am unable to connect to any DB. I keep getting an "Unexpected Error" pop-up. The error is:

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000230b40

**Comment by dmoagx** [comment] 2018-07-05 17:39
Duplicate of #2699

**Closed by dmoagx** 2018-07-05 17:39 UTC
