### ISSUE TITLE
SSH Tunnel is broken on Mac OS 10.11

### ISSUE THREAD

**Issue by Jahor** [sequelpro/sequelpro#2234] opened 2015-09-22 01:17 UTC
When connecting using built-in SSH tunnelling on Mac OS 10.11 GM get error:
> Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 ep-natd -L 54892/<db-instance>/3306

> Bad local forwarding specification ' 54892/<db-instance>/3306'

I assume it wants `54892:<db-instance>:3306`

**Comment by dmoagx** [comment] 2015-09-22 01:27
Duplicate of #2050 
This has already been fixed since 1.1rc1: http://www.sequelpro.com/blog/2015.08/sequel-pro-1-1-rc2/
Please search for existing issues, before creating a new one.

**Closed by dmoagx** 2015-09-22 01:27 UTC
Labels: Duplicate

**Comment by Jahor** [comment] 2015-09-22 01:31
Sorry, only searched in open ones
Thanks for a quick update
