### ISSUE TITLE
Active tab doesn't show the name of the connection

### ISSUE THREAD

**Issue by Zolcsi67** [sequelpro/sequelpro#2064] opened 2015-02-06 11:52 UTC
I have two connections set up in Sequel Pro, one that is called "localhost" and it is for my local dev server, and one for the production server.
I use both of them at the same time, so I'd like to know, which one is which, this is critical. But the active tab doesn't show the connection name in the title. I am attaching a screenshot to show this.

**Comment by Zolcsi67** [comment] 2015-02-06 11:53
![screenshoterror](https://cloud.githubusercontent.com/assets/3718245/6078926/1443ab5a-adff-11e4-91bb-98409267c008.png)

**Comment by dmoagx** [comment] 2015-02-08 08:29
Duplicate of #1202

(Btw: you might want to take a look at #346 )

**Closed by dmoagx** 2015-02-08 08:29 UTC
