### ISSUE TITLE
Crash when closing tab Mojave 10.14.3

### ISSUE THREAD

**Issue by braddersg1t** [sequelpro/sequelpro#3439] opened 2019-04-02 08:11 UTC
I know there is a ticket #3116 but it is not being acknowledged as an existing issue. The problem is not solved.

- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.3
- MySQL Version: mariaDB 10.3.13

**Description**
Sequel Pro crashes when I close a tab when 2 tabs open.

**Steps To Reproduce**
1. Open 2 tabs
2. Close last tab

**Expected Behaviour**
Close last tab without crashing

**Additional Context**
New Mac with new install of Sequel Pro

**Comment by aaron-hall-7** [comment] 2019-04-02 18:52
It's fixed in one of the nightly builds. I just updated to the latest nightly build and no longer have the issue. It looks like it'll be coming out in version 1.2

**Comment by dmoagx** [comment] 2019-04-02 18:59
Duplicate of #3116

**Closed by dmoagx** 2019-04-02 18:59 UTC
