### ISSUE TITLE
SQL Import with JSON values throwing error

### ISSUE THREAD

**Issue by narrative1st** [sequelpro/sequelpro#2984] opened 2018-02-16 21:22 UTC
Attempting to grab a SQL dump with JSON values, I'm still getting the error described here:

https://github.com/sequelpro/sequelpro/issues/2647

Unchecking BLOB works, but not sure if not necessary. Using latest version (1.1.2)

**Comment by dmoagx** [comment] 2018-02-17 12:31
Well, what I wrote one year ago is sadly still true: https://github.com/sequelpro/sequelpro/issues/2647#issuecomment-278757124

Duplicate of #2647

**Closed by dmoagx** 2018-02-17 12:31 UTC
