### ISSUE TITLE
Crash when closing a tab on macOS Mojave

### ISSUE THREAD

**Issue by drahgon55** [sequelpro/sequelpro#3454] opened 2019-04-23 22:36 UTC
version 1.1.2, build 4541 (602e11a)

This post claims it was fixed. However this is still happening to me. The other thread is locked so i made a new one
https://github.com/sequelpro/sequelpro/issues/3401

**Comment by AlanJimenez-palace** [comment] 2019-04-24 02:29
I have the same issue, I can't open any database, the last problem just appeared today and I cannot report the problema because I get an error after a while when I press the submit button.

**Comment by afoxlittle** [comment] 2019-04-24 05:29
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff79bfa56c objc_retain + 28
1   com.apple.AppKit              	0x00007fff4c70103c -[NSTableView _uncachedNumberOfRows] + 105
2   com.apple.AppKit              	0x00007fff4c700f3f -[_NSTableRowHeightStorage numberOfRows] + 62
3   com.apple.AppKit              	0x00007fff4c7086ff -[NSTableView _totalHeightOfTableView] + 282
4   com.apple.AppKit              	0x00007fff4c707bff -[NSTableView _minimumFrameSize] + 77
5   com.apple.AppKit              	0x00007fff4c7071c7 -[NSTableView tile] + 438
6   com.apple.AppKit              	0x00007fff4c733739 -[NSTableView bounds] + 122
7   com.apple.AppKit              	0x00007fff4c9ef5c8 tableViewFocusRingType + 119
8   com.apple.AppKit              	0x00007fff4c8917b4 -[NSTableView(NSTableViewNonARC) designatedFocusRingView] + 99
9   com.apple.AppKit              	0x00007fff4c7945b3 -[NSView noteFocusRingMaskChanged] + 31
10  com.apple.AppKit              	0x00007fff4c689d51 -[NSView setNeedsDisplayInRect:] + 701
11  com.apple.WebKitLegacy        	0x00007fff5d5aabb6 -[NSView(WebSetNeedsDisplayInRect) _web_setNeedsDisplayInRect:] + 486
12  com.apple.AppKit              	0x00007fff4c689981 -[NSView setNeedsDisplay:] + 79
13  com.apple.AppKit              	0x00007fff4c68b2ec -[NSView(NSInternal) _invalidateEffectiveVibrantBlendingStyle] + 119
14  com.apple.AppKit              	0x00007fff4c7139b4 -[NSTableView _removeBackgroundView] + 156
15  com.apple.AppKit              	0x00007fff4c7138ff -[NSTableView viewWillMoveToSuperview:] + 64
16  com.apple.AppKit              	0x00007fff4c6b9f64 -[NSView _setSuperview:] + 213
17  com.apple.AppKit              	0x00007fff4c810588 -[NSTableView _setSuperview:] + 324
18  com.apple.AppKit              	0x00007fff4c6bd72f -[NSView removeFromSuperview] + 146
19  com.apple.AppKit              	0x00007fff4c7a4083 -[NSView removeFromSuperviewWithoutNeedingDisplay] + 36
20  com.apple.AppKit              	0x00007fff4c74239b -[NSView _finalize] + 1056
21  com.apple.AppKit              	0x00007fff4c741df4 -[NSView dealloc] + 209
22  com.apple.AppKit              	0x00007fff4c818883 -[NSClipView dealloc] + 164
23  libobjc.A.dylib               	0x00007fff79c020c8 objc_object::sidetable_release(bool) + 268
24  libobjc.A.dylib               	0x00007fff79bfd47c (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 710
25  com.apple.CoreFoundation      	0x00007fff4ef9060a _CFAutoreleasePoolPop + 22
26  com.apple.Foundation          	0x00007fff5122ce02 -[NSAutoreleasePool drain] + 144
27  com.apple.AppKit              	0x00007fff4c63cf1f -[NSApplication run] + 810
28  com.apple.AppKit              	0x00007fff4c62c3f0 NSApplicationMain + 777
29  com.sequelpro.SequelPro       	0x0000000100002454 start + 52

**Comment by kta** [comment] 2019-04-24 06:47
this issue is already fixed and released test-builds version

look at this
https://sequelpro.com/test-builds

**Comment by andy-laravel** [comment] 2019-04-24 09:47
> this issue is already fixed and released test-builds version
> 
> look at this link and download the latest version
> https://sequelpro.com/test-builds

'test builds' :/

Now you can't turn the filter off - try to clear that text in the filter? Error. Great. Fixes tab crash issue, but new issues arise.

Can't they just release a fix for the original version? Such a small request, would stop the daily issues being reported. Its been what, 2 years?

**Comment by stychos** [comment] 2019-04-24 09:50
> Now you can't turn the filter off - try to clear that text in the filter? Error. 
You can merge this manually, solves this trouble: https://github.com/sequelpro/sequelpro/pull/3422

**Comment by andy-laravel** [comment] 2019-04-24 09:51
> > Now you can't turn the filter off - try to clear that text in the filter? Error.
> 
> You can merge this manually, solves this trouble: #3422

How do you merge an application?

**Comment by stychos** [comment] 2019-04-24 09:52
Download repository, merge this branch into the master and compile. It's all about git, github and opensource.

**Comment by dmoagx** [comment] 2019-04-24 11:04
Duplicate of #3116

**Closed by dmoagx** 2019-04-24 11:04 UTC
