### ISSUE TITLE
Keep app open when closing the last connection

### ISSUE THREAD

**Issue by powelski** [sequelpro/sequelpro#3333] opened 2018-12-18 08:54 UTC
Currently, Sequel Pro closes itself when we close the last opened connection. When I need to work with several connections, it's troublesome. I always need to remember to have at least one open before I close all the others. Otherwise I need to open the app again.

Most Mac apps keep the app open when we close the last tab/file.

**Comment by powelski** [comment] 2018-12-18 10:46
Are you sure? It’s not about the crash.

**Comment by dmoagx** [comment] 2018-12-20 19:42
Sequel Pro does not exit when the last connection is closed.
And this issue report contains zero information that could be used to identify an issue…

**Comment by powelski** [comment] 2018-12-20 20:37
What kind of information should I share? I'm using the newest version of Sequel Pro (1.1.2) and newest macOS.

If you open any connection and then close it via `cmd+W` or File -> Close tab, the app will be closed. To open another connection, you need to manually reopen the app.

> Sequel Pro does not exit when the last connection is closed.

Not at all what I'm experiencing.

**Comment by dmoagx** [comment] 2018-12-20 20:41
That means this is another duplicate of #3116

**Closed by dmoagx** 2018-12-20 20:41 UTC
Labels: WaitingOnUser

**Comment by powelski** [comment] 2018-12-20 21:12
It's possible. When I tried opening two tabs and closed just one it indeed crashed. Then, when I reopened the app and closed just one tab, the app closed it correctly and stood opened. Closing the app when closing the only app seems to be a crash too then.
