### ISSUE TITLE
crash when opening database

### ISSUE THREAD

**Issue by ziyao2522** [sequelpro/sequelpro#3397] opened 2019-02-28 07:12 UTC
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000024ee0

(
	0   CoreFoundation                      0x00007fff38a0123b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5fc95c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff38a99d94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff38977700 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff389770c8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff3aa87148 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff60bc7661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff60bc750d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff60bc6bf9 thread_start + 13
)

**Comment by dmoagx** [comment] 2019-02-28 22:56
duplicate of #2699

**Closed by dmoagx** 2019-02-28 22:56 UTC
