### ISSUE TITLE
password can't be saved, always lost.

### ISSUE THREAD

**Issue by sictxk** [sequelpro/sequelpro#3080] opened 2018-06-12 11:30 UTC
**Error updating Keychain item**
An error occured while trying to update the Keychain item. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -25293.

**Comment by dmoagx** [comment] 2018-06-12 18:11
Duplicate of #2900, #3070

**Closed by dmoagx** 2018-06-12 18:11 UTC
