### ISSUE TITLE
Clicking the foreign key button does not work

### ISSUE THREAD

**Issue by jpike88** [sequelpro/sequelpro#3328] opened 2018-12-13 07:08 UTC
- Sequel Pro Version:5425 df10e204
- macOS Version:high sierra
- MySQL Version:5.x

**Description**
Clicking the foreign key button to jump to that row in another table used to work, now it doesn't. It takes to the table containing the row, but does not filter for it.

**Steps To Reproduce**
1. Click foreign key button in a cell

**Expected Behaviour**
Should filter the appropriate row in the target table

**Additional Context**

**Comment by dmoagx** [comment] 2018-12-13 10:07
Duplicate of #2792

**Closed by dmoagx** 2018-12-13 10:07 UTC
