### ISSUE TITLE
Crash when connecting to MySQL server

### ISSUE THREAD

**Issue by laurenkt** [sequelpro/sequelpro#2921] opened 2017-11-14 16:43 UTC
Sequel Pro version: 1.1.2 (602e11a)
MySQL version: 8.0.2 (running inside a Docker container: the `mysql:8.0` container)

Essentially when I put in the connection details and connect the app immediately crashes with the following stack trace.

Let me know if there's something I can do to help narrow this down

```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x610000c4fdb0

(
	0   CoreFoundation                      0x00007fffcf3a62cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffe41be48d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffcf427f04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fffcf318755 ___forwarding___ + 1061
	4   CoreFoundation                      0x00007fffcf3182a8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x00000001000f3681 -[SPWindowController performSelector:withObject:] + 172
	7   libsystem_trace.dylib               0x00007fffe4cd63a7 _os_activity_initiate_impl + 53
	8   AppKit                              0x00007fffcd593721 -[NSApplication(NSResponder) sendAction:to:from:] + 456
	9   AppKit                              0x00007fffcd066666 -[NSMenuItem _corePerformAction] + 324
	10  AppKit                              0x00007fffcd0663d2 -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	11  libsystem_trace.dylib               0x00007fffe4cd63a7 _os_activity_initiate_impl + 53
	12  AppKit                              0x00007fffcd0ef955 -[NSMenu performActionForItemAtIndex:] + 121
	13  AppKit                              0x00007fffcd0ef8cc -[NSMenu _internalPerformActionForItemAtIndex:] + 94
	14  AppKit                              0x00007fffcd0ef6f9 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 107
	15  AppKit                              0x00007fffccfa6580 NSSLMMenuEventHandler + 986
	16  HIToolbox                           0x00007fffce854d85 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1708
	17  HIToolbox                           0x00007fffce853ff6 _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 428
	18  HIToolbox                           0x00007fffce869d14 SendEventToEventTarget + 40
	19  HIToolbox                           0x00007fffce8b63e6 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
	20  HIToolbox                           0x00007fffce8e19fb SendMenuCommandWithContextAndModifiers + 59
	21  HIToolbox                           0x00007fffce8e19aa SendMenuItemSelectedEvent + 188
	22  HIToolbox                           0x00007fffce8e187d _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	23  HIToolbox                           0x00007fffce8c0b6b _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 2007
	24  HIToolbox                           0x00007fffce8bfbd3 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 612
	25  HIToolbox                           0x00007fffce8bf7ab _HandlePopUpMenuSelectionWithDictionary + 287
	26  AppKit                              0x00007fffcd0e65a7 _NSSLMPopUpCarbonMenu3 + 6218
	27  AppKit                              0x00007fffcd0e4ca3 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 456
	28  AppKit                              0x00007fffcd1603a5 -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 564
	29  AppKit                              0x00007fffcd074ddb -[NSControl mouseDown:] + 832
	30  AppKit                              0x00007fffcd70f24f -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 6341
	31  AppKit                              0x00007fffcd70ba6c -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 1942
	32  AppKit                              0x00007fffcd70af0a -[NSWindow(NSEventRouting) sendEvent:] + 541
	33  Sequel Pro                          0x000000010012e644 -[SPWindow sendEvent:] + 783
	34  AppKit                              0x00007fffcd58f681 -[NSApplication(NSEvent) sendEvent:] + 1145
	35  AppKit                              0x00007fffcce0a427 -[NSApplication run] + 1002
	36  AppKit                              0x00007fffccdd4e0e NSApplicationMain + 1237
	37  Sequel Pro                          0x0000000100002454 start + 52
	38  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by dmoagx** [comment] 2017-11-14 20:24
Duplicate of #2699

**Closed by dmoagx** 2017-11-14 20:24 UTC
