### ISSUE TITLE
Bit fields display incorrectly in version 1.1

### ISSUE THREAD

**Issue by cyoder** [sequelpro/sequelpro#2304] opened 2015-10-22 21:41 UTC
I have a table that looks like this: 

CREATE TABLE `event_actions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `event_id` int(11) DEFAULT NULL,
  `processing` bit(1) NOT NULL,
  `complete` bit(1) NOT NULL,
  `complete_date` datetime DEFAULT NULL,
  `process_after` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_asc_event_id` (`event_id`),
  CONSTRAINT `FK_asc_event_id_const` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

When I run this query, I get back different results in the display vs. the criteria in the query:

SELECT * from event_actions where processing = 0 and complete = 1;

Results:

id = 1
event_id = 1
processing = 10000000  <==  WRONG VALUE SEE ABOVE QUERY
complete = 00000000  <==  WRONG VALUE SEE ABOVE QUERY
complete_date = 2015-10-22 16:16:11
process_after = 2015-10-22 16:00:00

I updated to the latest greatest (1.1 build 4477) and started seeing this problem today.  My custom software (Java/JPA) sees the values correctly, so this creates a huge problem when validating that the custom software is inserting/updating data correctly in the db.

Thanks!

**Comment by dmoagx** [comment] 2015-10-22 23:42
1. The final 1.1 version is 4499. You probably found an outdated download.
2. Duplicate of #2254

**Closed by dmoagx** 2015-10-22 23:42 UTC

**Comment by cyoder** [comment] 2015-10-23 00:04
Updated through application and checked for updates prior to submitting this bug.

**Comment by cyoder** [comment] 2015-10-23 00:08
And you are correct, I denoted the wrong build - 4499 was the latest version I installed that showed this issue.  I re-downloaded and verified the build and the issue still exists.  I've reverted back to version 1.0.2 until this is fixed.
