### ISSUE TITLE
crashing sequel in mysql 8

### ISSUE THREAD

**Issue by rafalogan** [sequelpro/sequelpro#3045] opened 2018-05-03 14:29 UTC
everytime that I start the application it hangs and  I have to close sequel.
then it will not start any more.

**Comment by dmoagx** [comment] 2018-05-03 18:07
What exactly is your issue?

The tile says it crashes when you connect to MySQL 8, but the text says it crashes as soon as you open it...

**Comment by JasinYip** [comment] 2018-05-04 08:55
same here. Connect testing is fine, but after running a query or switch a database(actually it's query too), it will get crashed and shows a error dialog witch is useless(can't send error log and cannot exit the dialog)

**Comment by dmoagx** [comment] 2018-05-07 16:11
I'm pretty sure this is a duplicate of #2699

**Comment by boyfox** [comment] 2018-05-18 16:42
Please, increasing publishing next release time with supporting mysql 8 , we waiting next release sequel pro!

**Comment by gvanbeck** [comment] 2018-05-25 12:14
+1

**Comment by dmoagx** [comment] 2018-05-30 21:48
Since no one did provide additional infos I'm closing this as a duplicate of #2699

**Closed by dmoagx** 2018-05-30 21:48 UTC
Labels: WaitingOnUser
