### ISSUE TITLE
Foreign key link fails to resolve when target table is in a different db

### ISSUE THREAD

**Issue by Firehed** [sequelpro/sequelpro#3048] opened 2018-05-09 17:30 UTC
When clicking the "go to this row" FK arrow icon, the link does not work unless it points to a row in a table in the currently-visible DB/schema.

To reproduce:
- `CREATE DATABASE db1`
- `USE db1`
- ``CREATE TABLE tbl1 (id int(11) auto_increment, primary key(`id`))``
- `insert into tbl1 (id) values (1);`
- `CREATE DATABASE db2`
- `USE db2`
- ``CREATE TABLE tbl2 ( id int(11) auto_increment, tbl1_id int(11), primary key(`id`), constraint `fk` foreign key (`tbl1_id`) references `db1`.`tbl1` (`id`) );``
- `insert into tbl2 (tbl1_id) values (1);`
- click the FK arrow on the tbl1_id column

This behavior is present in SP 1.1.2 (602e11a) on macOS 10.13.3.

**Comment by dmoagx** [comment] 2018-05-09 17:41
Duplicate of #2504

**Comment by Firehed** [comment] 2018-05-09 17:41
Ah, tried searching for an existing issue but didn't find that one. Thanks!

**Closed by dmoagx** 2018-05-09 17:41 UTC
