### ISSUE TITLE
App crashes all the time on Mojave

### ISSUE THREAD

**Issue by gregblass** [sequelpro/sequelpro#3208] opened 2018-10-05 23:20 UTC
Ever since I upgraded to Mojave, the app has become fairly unstable. Lots of random crashes. Anyone else experiencing this? I can give more details if necessary, but wanted to throw a feeler out there. Was surprised no one else had reported anything yet.

**Comment by gregblass** [comment] 2018-10-05 23:20
It seems to be that it crashes once on load, and then reloads, and is fine.

**Comment by stuconnolly** [comment] 2018-10-05 23:34
Duplicate of #3116

**Closed by stuconnolly** 2018-10-05 23:34 UTC
Labels: Duplicate

**Comment by gregblass** [comment] 2018-10-06 00:16
I was not opening two tabs at all. This is not a duplicate.

**Comment by gregblass** [comment] 2018-10-06 00:17
Unless the issue is un-related to opening two tabs. But I only had one tab open.
