### ISSUE TITLE
Sequel Pro Runs REALLY slow on my 2016 MBP

### ISSUE THREAD

**Issue by edgework** [sequelpro/sequelpro#2679] opened 2017-02-03 21:11 UTC
It seems everything takes a second or two to reply. Clicking on something, opening a tab, everything and often I check Activity monitor and it says Sequel Pro is using upwards of 3GB of memory.  This is with VERY small databases open.  It works fine on my old 2014 MBP.

**Comment by dmoagx** [comment] 2017-02-03 23:39
How large is this file: `~/Library/Preferences/com.sequelpro.SequelPro.plist`?

**Comment by edgework** [comment] 2017-02-03 23:50
161MB

**Comment by dmoagx** [comment] 2017-02-04 00:02
That's your problem. Go to Query Editor > History > Clear Global History

**Comment by abhibeckert** [comment] 2017-02-04 01:07
Duplicate of #687

We are may fix this before the next release. See https://github.com/sequelpro/sequelpro/issues/687#issuecomment-226597759

**Closed** 2017-02-04 01:07 UTC
Labels: WaitingOnUser

**Comment by edgework** [comment] 2017-02-04 01:15
@dmoagx  you make it sound like I did something wrong...  Is it not your problem that you let this happen?

BTW that did fix the problem.

**Comment by abhibeckert** [comment] 2017-02-04 01:18
@edgework you didn't do anything wrong.

We are using Apple's standard preferences file format to store query history and it falls apart with large queries. That 161MB file really should be only 20KB or so.

As part of #687 we will change queries are stored.
