### ISSUE TITLE
Add 'Favorite' Tables

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#1705] opened 2013-11-09 05:43 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=1705
Reporter:orth.m...@gmail.com Date:2013-05-03 10:59:15 Status:New

Problem: 
Working with large databases with many tables is difficult when only using a handful of tables.  If a user is only interested in a small subset,  he has to scroll through lots of tables, or manage several tabs.

Solution:
Add ability to mark tables as &quot;Favorites&quot; and include the Favorites list in the sidebar.  This would greatly speed workflow when logging in to be able to easily select one of the Favorite tables rather than filtering/looking for each table for every session.

**Comment by Rajadas** [comment] 2015-07-01 10:43
Otherwise, allow temporary filtering for multiple tables.
Something like: "%_report; %_financial, %_notes"

**Comment by dmoagx** [comment] 2015-07-01 10:57
If you have more than a handful of tables in a DB Sequel Pro will automatically show a filter bar in the table list with full regex support.

**Comment by pablomedok** [comment] 2018-02-13 10:45
I'm vote for this with both hands

**Comment by stuconnolly** [comment] 2018-10-08 22:27
Duplicate of #1391

**Closed by stuconnolly** 2018-10-08 22:27 UTC
Labels: Enhancement
