### ISSUE TITLE
Loading DB but not tables

### ISSUE THREAD

**Issue by sasafister** [sequelpro/sequelpro#3123] opened 2018-07-24 15:03 UTC
Everything was working fine, but suddenly it stoped working. I have localhost setup and it's really basic stuff. When I load that config it connect's, but when I select one DB I want to see, it stop working.

![Image of Yaktocat](https://i.imgur.com/dxgm0nO.png)

**Comment by dmoagx** [comment] 2018-07-24 18:20
Duplicate of #2699

**Closed by dmoagx** 2018-07-24 18:20 UTC

**Comment by sasafister** [comment] 2018-07-25 06:40
This doesn't solve this issue. I have macbook air and everything works fine, but on my new macbook pro it doesn't work :/
