### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by TheAladeen** [sequelpro/sequelpro#2704] opened 2017-02-28 08:04 UTC
Hi,

Whenever I run Sequel Pro my RAM usage spikes for the process to over 3.6GB and then causes my system to lag until I force quit the application.

I have tested with builds ffe8c13268 and b87faacf80 to no resolution.

Please let me know if you have not experienced this issue and what data is required from me.

I am running macOS Sierra 10.12.3

**Comment by abhibeckert** [comment] 2017-02-28 08:49
What is the filesize of `~/Library/Preferences/com.sequelpro.SequelPro.plist`?

**Comment by TheAladeen** [comment] 2017-02-28 08:54
Wow... 971.5MB

Can I simply delete this and rerun the application?
![screen shot 2017-02-28 at 10 53 38 am](https://cloud.githubusercontent.com/assets/15083745/23398189/3608b838-fda4-11e6-9ce6-6d63a4adc73f.png)

**Comment by abhibeckert** [comment] 2017-02-28 08:56
Your query history is too big.

Run this in Terminal to clear it:

    defaults delete com.sequelpro.SequelPro queryHistory

Closing as a duplicate of #687

**Closed by abhibeckert** 2017-02-28 08:56 UTC
