### ISSUE TITLE
can not refresh database.

### ISSUE THREAD

**Issue by zfavourite99** [sequelpro/sequelpro#3065] opened 2018-05-30 09:37 UTC
connect to mysql 8.0，refresh database，show this error，and database list has no data.
```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x600000a47bf0

(
	0   CoreFoundation                      0x00007fff3543c32b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5cab6c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff354d4e04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff353b2870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff353b2238 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x00000001000f3681 -[SPWindowController performSelector:withObject:] + 172
	7   AppKit                              0x00007fff330e9a43 -[NSApplication(NSResponder) sendAction:to:from:] + 312
	8   AppKit                              0x00007fff32b7e213 -[NSMenuItem _corePerformAction] + 323
	9   AppKit                              0x00007fff32b7df9b -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	10  AppKit                              0x00007fff32c03c7a -[NSMenu performActionForItemAtIndex:] + 133
	11  AppKit                              0x00007fff32c03be5 -[NSMenu _internalPerformActionForItemAtIndex:] + 94
	12  AppKit                              0x00007fff32c03a15 -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 106
	13  AppKit                              0x00007fff32aca2a2 NSSLMMenuEventHandler + 882
	14  HIToolbox                           0x00007fff34677904 _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1541
	15  HIToolbox                           0x00007fff34676c4d _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 374
	16  HIToolbox                           0x00007fff3468bf21 SendEventToEventTarget + 39
	17  HIToolbox                           0x00007fff346d53f9 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 411
	18  HIToolbox                           0x00007fff346fe2ee SendMenuCommandWithContextAndModifiers + 49
	19  HIToolbox                           0x00007fff346fe2aa SendMenuItemSelectedEvent + 188
	20  HIToolbox                           0x00007fff346fe184 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	21  HIToolbox                           0x00007fff3481687c _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 1662
	22  HIToolbox                           0x00007fff34815cf7 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 409
	23  HIToolbox                           0x00007fff346de40c _HandlePopUpMenuSelectionWithDictionary + 268
	24  AppKit                              0x00007fff32bfa79a _NSSLMPopUpCarbonMenu3 + 5632
	25  AppKit                              0x00007fff32bf90f4 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 439
	26  AppKit                              0x00007fff32c6925c -[NSPopUpButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 570
	27  AppKit                              0x00007fff32b8c670 -[NSControl mouseDown:] + 965
	28  AppKit                              0x00007fff33288d6d -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5891
	29  AppKit                              0x00007fff332859c4 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2359
	30  AppKit                              0x00007fff33284c70 -[NSWindow(NSEventRouting) sendEvent:] + 497
	31  Sequel Pro                          0x000000010012e644 -[SPWindow sendEvent:] + 783
	32  AppKit                              0x00007fff330e6236 -[NSApplication(NSEvent) sendEvent:] + 2462
	33  AppKit                              0x00007fff329468b5 -[NSApplication run] + 812
	34  AppKit                              0x00007fff32915a72 NSApplicationMain + 804
	35  Sequel Pro                          0x0000000100002454 start + 52
)
```

**Comment by dmoagx** [comment] 2018-05-30 21:38
Duplicate of #2699

**Closed by dmoagx** 2018-05-30 21:38 UTC
