### ISSUE TITLE
record data truncated in Content view edit

### ISSUE THREAD

**Issue by wagnerone** [sequelpro/sequelpro#2697] opened 2017-02-20 22:12 UTC
I made an edit to a record in Content view today and when I hit enter, the value was truncated with an ellipsis at the end. This broke our application and we ended up chasing it down to this.

I flipped to Query view and searched for that same record and saw the "..." there too. I restored the value in the record that was displayed in the Query results and that retained the entire value.

I then switched bcak to Content view and tried to edit it there and got the same truncated results.

I was not using Edit -> "Edit all field in pop-up sheet", but I since switched to that and editin via that pop-up doesn't truncate the value on the Content view.

macOS 10.12.3
Sequql Pro 1.1.2 build 4541

Thanks,
Mike

**Comment by abhibeckert** [comment] 2017-02-21 00:04
@wagnerone what was the table structure? (especially the data type of the column being edited)

**Comment by abhibeckert** [comment] 2017-02-21 00:33
I did some testing and found a VARBINARY(500) column will be truncated to 255 bytes (and an epilepsis added) when editing in the content view.

As described above, this behaviour does not happen editing the results of a custom query pane.

@wagnerone please confirm if this is the same bug you saw?

Also, #2284 may be related to this bug.

**Comment by dmoagx** [comment] 2017-02-21 03:19
Actually this sounds more like a regression on #1702

**Comment by abhibeckert** [comment] 2017-02-21 03:45
Also the external edit sheet is unusable with varbinary columns.

It shows hex in the "Text" tab, and you can't type unless you delete the entire thing (at which point whatever you type appears to be interpreted as UTF-8).

**Comment by wagnerone** [comment] 2017-02-21 18:41
The column I was editing and referencing my report was varchar(4096).

Table detail: InnoDB, UTF-8, utf8_bin

Mike

**Comment by dmoagx** [comment] 2017-02-21 20:23
@wagnerone How did you start editing and how did you end it? (e.g. did you double click on the varchar field itself or on a column left of it and then entered it via tab / commit by using return or by selecting another row?)
I can't reproduce this with 1.1.2 right now.

**Comment by abhibeckert** [comment] 2017-02-21 21:48
> Table detail: InnoDB, UTF-8, utf8_bin

I can't reproduce it either. Can you provide the create table syntax?

![image](https://cloud.githubusercontent.com/assets/266088/23186540/3d1742dc-f8d3-11e6-9424-15e94711ba01.png)

**Comment by abhibeckert** [comment] 2017-03-03 04:14
Removing critical priority since we can't reproduce this.

**Comment by dmoagx** [comment] 2018-10-14 17:06
No feedback from reporter in > 1 month, closing.

**Closed by dmoagx** 2018-10-14 17:06 UTC
Labels: Bug, WaitingOnUser
