### ISSUE TITLE
connection fails when username contains '@'

### ISSUE THREAD

**Issue by yifan** [sequelpro/sequelpro#2965] opened 2018-01-16 12:05 UTC
I am trying to connect to Azure MySQL server, the default username Azure creates will append '@server' to whatever username I put. When I try to connect to server with this username, I get 'Access Denied' from MySQL (username@xx.xx.xx.xx). If I try to use MySQL client with username@server, it works. 
`mysql -h myserver.mysql.database.azure.com -u user@server -p` works. but not with Sequel Pro.

**Comment by dmoagx** [comment] 2018-01-16 20:16
Can't reproduce.
Connecting with `username@something` works fine with regular MySQL and Sequel Pro and since I don't have an Azure account, I can't test it there.

**Comment by dmoagx** [comment] 2018-07-06 21:02
No feedback from reporter in 30 days -> closing.

**Closed by dmoagx** 2018-07-06 21:02 UTC
Labels: WaitingOnUser
