### ISSUE TITLE
Feature Request: have option to keep timestamp fields on update

### ISSUE THREAD

**Issue by markusweb** [sequelpro/sequelpro#3164] opened 2018-09-14 10:26 UTC
i want to have an option to keep timestamp field when editing any other field in the row.
i have field like this

`eingang timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`

so, everytime i insert a new row or update an existing row, the field "eingang" would be updated. NOW it is important for me that the field "eingang" will not be touched on an update. My webapp will take care of any eingang or "changed" fields with timestamt on update...

to manage or edit the database i am using an webgui, there i can check the field "eingang" to keep its value.

![editing](https://user-images.githubusercontent.com/536804/45544923-fd1c0d00-b818-11e8-85f0-8c35ffac503c.png)

i can edit or update any other field in the row, as long as i have checked the field it will not be updated (it will add an `eingang=eingang` to the query, so the field will keep its value).

**Comment by dmoagx** [comment] 2018-09-14 20:55
Duplicate of #2885

**Closed by dmoagx** 2018-09-14 20:55 UTC
