### ISSUE TITLE
Instructions to obtain latest stable version

### ISSUE THREAD

**Issue by pjebs** [sequelpro/sequelpro#3372] opened 2019-01-31 23:47 UTC
The website downloads version 1.1.2 which is 3 years old.

Is it possible to put a note on README that suggests how to obtain the latest stable version?

**Comment by pjebs** [comment] 2019-02-01 10:12
Why is this the case?

**Comment by gregblass** [comment] 2019-02-01 16:48
I have no affiliation with this company, but if people are looking for a stable alternative, this program was well worth the license fee: https://tableplus.io/

It also has support for PostgreSQL in the same program, which was amazing for me. Exports and imports MySQL JSON fields no problem too! And has a dark mode.

**Comment by dmoagx** [comment] 2019-02-01 19:12
Duplicate of #3034

**Closed by dmoagx** 2019-02-01 19:12 UTC
