### ISSUE TITLE
Add filter for favorites

### ISSUE THREAD

**Issue by rubenrubiob** [sequelpro/sequelpro#3137] opened 2018-08-20 07:03 UTC
Hi!

I have been using and recommending Sequel Pro for quite some time, it is an awesome tool!

There is a small thing that I find it is missing, that I think it will be good to have. In the favorites panel, when you open the application, there is no filtering box. That is okay if you do not have many favorites, because it is easy to find the one you are looking for. But when you have quite a few (in my case, more than 50 and counting), it is hard to find them. I show you an example:

![favorites](https://user-images.githubusercontent.com/9865569/44324937-82e5ac00-a457-11e8-80ca-51e8e9326cbc.png)

As you see, I try to group them by server, and to use color codes in order to make them easier to find, but sometimes I do not know or I do not remember the server.

I was thinking that it may be possible to do a filter box like in the tables tab within a database:

![image](https://user-images.githubusercontent.com/9865569/44325031-cb9d6500-a457-11e8-9306-a0ad51bd3592.png)

Would that be possible? I think it would be a great adding.

Thank you for your effort!

Regards!

**Comment by stuconnolly** [comment] 2018-10-03 15:14
Duplicate of #2626

**Closed by stuconnolly** 2018-10-03 15:14 UTC
