### ISSUE TITLE
点击退出的时候就崩溃

### ISSUE THREAD

**Issue by yinanwang1** [sequelpro/sequelpro#3222] opened 2018-10-10 07:07 UTC
在程序坞右键点击选择退出，然后就崩溃提示一个发送崩溃报告。

**Comment by stuconnolly** [comment] 2018-10-10 17:06
English only please.

If my translation is correct(?) then this likely the same as #3116 

Can you please confirm by attaching the crash log?

**Comment by 1018ji** [comment] 2018-10-12 03:05
你这是升级系统了？自己编译一个版本用就可以了

**Comment by 1018ji** [comment] 2018-10-12 03:07
> English only please.
> 
> If my translation is correct(?) then this likely the same as #3116
> 
> Can you please confirm by attaching the crash log?

When will the new version 1.2 be released?

**Comment by stuconnolly** [comment] 2018-10-14 17:54
There's currently no date set for the release of 1.2

**Comment by stuconnolly** [comment] 2018-10-14 17:55
Duplicate of #3116

**Closed by stuconnolly** 2018-10-14 17:55 UTC
Labels: Duplicate, WaitingOnUser

**Comment by nanase-takesi** [comment] 2019-01-14 09:40
NSInvalidArgumentException

-[OS_dispatch_mach_msg numberOfRowsInTableView:]: unrecognized selector sent to instance 0x102008a00

(
	0   CoreFoundation                      0x00007fff3fbf1fa5 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6bce8efb objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3fc6fc8d -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff3fb935de ___forwarding___ + 1468
	4   CoreFoundation                      0x00007fff3fb92f98 _CF_forwarding_prep_0 + 120
	5   AppKit                              0x00007fff3d141136 -[NSTableView _uncachedNumberOfRows] + 303
	6   AppKit                              0x00007fff3d140f73 -[_NSTableRowHeightStorage numberOfRows] + 62
	7   AppKit                              0x00007fff3d148b06 -[NSTableView _totalHeightOfTableView] + 282
	8   AppKit                              0x00007fff3d147ff7 -[NSTableView _minimumFrameSize] + 77
	9   AppKit                              0x00007fff3d1475be -[NSTableView tile] + 438
	10  AppKit                              0x00007fff3d174421 -[NSTableView bounds] + 122
	11  AppKit                              0x00007fff3d435e90 tableViewFocusRingType + 119
	12  AppKit                              0x00007fff3d2d5648 -[NSTableView(NSTableViewNonARC) designatedFocusRingView] + 99
	13  AppKit                              0x00007fff3d1d556d -[NSView noteFocusRingMaskChanged] + 31
	14  AppKit                              0x00007fff3d0c955f -[NSView setNeedsDisplayInRect:] + 701
	15  WebKitLegacy                        0x00007fff4e5a2776 -[NSView(WebSetNeedsDisplayInRect) _web_setNeedsDisplayInRect:] + 486
	16  AppKit                              0x00007fff3d0c918f -[NSView setNeedsDisplay:] + 79
	17  AppKit                              0x00007fff3d0cab02 -[NSView(NSInternal) _invalidateEffectiveVibrantBlendingStyle] + 126
	18  AppKit                              0x00007fff3d154241 -[NSTableView _removeBackgroundView] + 156
	19  AppKit                              0x00007fff3d15418d -[NSTableView viewWillMoveToSuperview:] + 64
	20  AppKit                              0x00007fff3d0f9857 -[NSView _setSuperview:] + 213
	21  AppKit                              0x00007fff3d2531a4 -[NSTableView _setSuperview:] + 324
	22  AppKit                              0x00007fff3d0fd045 -[NSView removeFromSuperview] + 149
	23  AppKit                              0x00007fff3d1e5048 -[NSView removeFromSuperviewWithoutNeedingDisplay] + 36
	24  AppKit                              0x00007fff3d183141 -[NSView _finalize] + 1060
	25  AppKit                              0x00007fff3d182b96 -[NSView dealloc] + 209
	26  AppKit                              0x00007fff3d25b502 -[NSClipView dealloc] + 164
	27  libobjc.A.dylib                     0x00007fff6bce279c _ZN11objc_object17sidetable_releaseEb + 266
	28  libobjc.A.dylib                     0x00007fff6bcdd7c2 _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 726
	29  CoreFoundation                      0x00007fff3fb0cd42 _CFAutoreleasePoolPop + 22
	30  CoreFoundation                      0x00007fff3fb59c81 CFRunLoopTimerInvalidate + 566
	31  CoreFoundation                      0x00007fff3fb59631 __CFRunLoopDoTimer + 944
	32  CoreFoundation                      0x00007fff3fb5911d __CFRunLoopDoTimers + 333
	33  CoreFoundation                      0x00007fff3fb3a6c4 __CFRunLoopRun + 2187
	34  CoreFoundation                      0x00007fff3fb39be6 CFRunLoopRunSpecific + 467
	35  HIToolbox                           0x00007fff3edc5b35 RunCurrentEventLoopInMode + 293
	36  HIToolbox                           0x00007fff3edc586b ReceiveNextEventCommon + 618
	37  HIToolbox                           0x00007fff3edc55e8 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	38  AppKit                              0x00007fff3d081eb7 _DPSNextEvent + 997
	39  AppKit                              0x00007fff3d080c56 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1362
	40  AppKit                              0x00007fff3d07acb9 -[NSApplication run] + 699
	41  AppKit                              0x00007fff3d06a3f7 NSApplicationMain + 780
	42  Sequel Pro                          0x0000000100002454 start + 52
	43  ???                                 0x0000000000000001 0x0 + 1
)

**Comment by ahsar** [comment] 2019-03-29 01:57
> 你这是升级系统了？自己编译一个版本用就可以了

但是编译之后去掉了 content页面直接查找filter功能
