### ISSUE TITLE
Quits unexpectedly when closing tab/window on Mojave

### ISSUE THREAD

**Issue by cornellsteven** [sequelpro/sequelpro#3182] opened 2018-09-26 18:51 UTC
If I close a tab or window (doesn't matter how – have tested clicking the "X", right-clicking and selectiong "Close Tab", and using CMD+W), Sequel Pro quits unexpectedly. 

A co-worker mentioned something similar happening when updating settings, but I don't know the full details about that.

**Comment by anotherdevs** [comment] 2018-09-26 20:10
Duplicate of #3177 #3176 #3175 #3124 #3116 #3075 

Which is just sad that you didn't bother using the search function. Allow me to help you: https://github.com/sequelpro/sequelpro/issues?utf8=%E2%9C%93&q=Mojave

However see this: https://github.com/sequelpro/sequelpro/issues/3034 @abhibeckert and @mattlangtree have abandoned Sequel Pro and @dmoagx will carry it on in a fork.

**Comment by cornellsteven** [comment] 2018-09-26 20:15
@anotherdevs I'm so very sorry. I don't report a lot of issues and I did search (though, admittedly manually) through the _open_ issues. And based on the dates, I thought I was good. I didn't think about the beta of Mojave.

As an aside, if you'd like more people to report issues, perhaps be a little less callous when responding. Not everyone uses github issues on a regular basis.

**Comment by dmoagx** [comment] 2018-09-26 20:30
@cornellsteven 
To be fair, @anotherdevs was only expressing what I have been thinking the last 6 or so months, as I've explained yesterday: https://github.com/sequelpro/sequelpro/issues/3175#issuecomment-424452480

Also, even searching for something as simple as "crash" (among the open issues) would list your issue as the 6th result (that is still visible even without scrolling on my small MBP screen): https://github.com/sequelpro/sequelpro/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+crash

Searching for "Mojave" (which you used yourself in the title of your issue) even puts it in 2nd place (excluding this duplicate): https://github.com/sequelpro/sequelpro/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mojave

**Comment by dmoagx** [comment] 2018-09-26 20:31
Anyway, duplicate of #3116

**Closed by dmoagx** 2018-09-26 20:31 UTC

**Comment by cornellsteven** [comment] 2018-09-26 20:36
@dmoagx You might have added your comment before you saw my edit, or maybe not, but either way, I wanted to say that I had just read your comments on a couple of the other issues and realized very quickly that I'm the idiot here. I retracted my snippy comment to @anotherdevs. I do apologize for adding to your frustrations and promise to follow better issue etiquette from now on. Cheers!

**Comment by dmoagx** [comment] 2018-09-26 20:53
Thanks!
