### ISSUE TITLE
Last column in export database dialog table selector covered by scrollbar

### ISSUE THREAD

**Issue by KaHa6uc** [sequelpro/sequelpro#2680] opened 2017-02-04 15:26 UTC
It's not actually an issue, it's rather a nuisance.

When you have "Show scrollbars: when scrolling" set in System Preferences/General and try to export a database and scroll to a table at the bottom, the last column in the export list menu is covered by the scrollbar when you hover it. You have to scroll, wait for the scrollbar to disappear and then point to the column in order to uncheck it.

A padding after the last column to avoid the scrollbar would eliminate this annoyance.

![screen shot 2017-02-04 at 17 20 11](https://cloud.githubusercontent.com/assets/2924578/22619511/7fd3c4c0-eafe-11e6-8db4-abeeabbc4748.png)

**Comment by dmoagx** [comment] 2017-02-05 01:33
Duplicate of #1757

**Closed by dmoagx** 2017-02-05 01:33 UTC
