### ISSUE TITLE
Highlighting no longer functions

### ISSUE THREAD

**Issue by joshuaziering** [sequelpro/sequelpro#2755] opened 2017-03-31 22:21 UTC
Just installed the latest build and the "Green" highlight feature no longer works. I have this db set as light green in my list but when I connect to it in "New Connection Window" mode I don't get the cool green bar at the top. 
![screen shot 2017-03-31 at 3 19 21 pm](https://cloud.githubusercontent.com/assets/1530131/24571369/9ce7977e-1625-11e7-9fc8-f1a9796aae0e.png)
![screen shot 2017-03-31 at 3 20 56 pm](https://cloud.githubusercontent.com/assets/1530131/24571382/ac602dd8-1625-11e7-9e89-84711f3ebbf9.png)

**Comment by dmoagx** [comment] 2017-03-31 22:26
Duplicate of #2753

**Closed by dmoagx** 2017-03-31 22:26 UTC
