### ISSUE TITLE
SequelPro - crash all the time in Mojave when app closed

### ISSUE THREAD

**Issue by softmixt** [sequelpro/sequelpro#3356] opened 2019-01-14 19:00 UTC
I see that there are more issues related to the one happens to me so maybe I repeat this "Bug Report" anyway I'll like to have it fixed soon as possible. 
So to reproduce the issue is simple when I close the app automatically "crash modal" popsup.
<img width="1703" alt="captura de pantalla 2019-01-14 a las 19 57 42" src="https://user-images.githubusercontent.com/1758477/51134019-b70e9e80-1836-11e9-8e22-def60632f25a.png">

I have : Mojave: 10.14.2 (18C54)

**Comment by marcomehnert** [comment] 2019-01-15 10:37
As much as I love to use SequelPro, this issue will lead me to look for an alternative. Its annoying and does not look like it will be fixed soon.

**Comment by kommaJules** [comment] 2019-01-15 12:42
We have the same problem

**Comment by marcomehnert** [comment] 2019-01-15 12:46
I have downloaded the current nighly build from https://sequelpro.com/test-builds and look forward to V 1.2 this Version does not crash.

**Comment by kommaJules** [comment] 2019-01-15 13:02
@marcomehnert thanks! that works! Specifically commit the build resulting from commit 16180f9d3c with date 2018-12-20 11:15:19 UTC

**Comment by dmoagx** [comment] 2019-01-15 19:54
Duplicate of #3116

**Closed by dmoagx** 2019-01-15 19:54 UTC

**Comment by softmixt** [comment] 2019-01-17 09:05
> https://sequelpro.com/test-builds

Awesome thanks this build is not crashing any more thanks for the help and sorry for the duplicate bug report
