### ISSUE TITLE
Sequal Pro not working with mysql 8.x

### ISSUE THREAD

**Issue by ovaqlab** [sequelpro/sequelpro#3345] opened 2019-01-02 10:04 UTC
- Sequel Pro Version: 1.1.2
- macOS Version: 10.14.2 
- MySQL Version: 8.0.12

**Description**
Sequel Pro not working with MySQL 8.x.  Sequel pro takes too much time to build the table list and after a few seconds, it will be crash.

**Comment by dmoagx** [comment] 2019-01-02 12:07
duplicate of #2699

**Closed by dmoagx** 2019-01-02 12:07 UTC
