### ISSUE TITLE
Crash when connecting using SSH using key with unsaved password

### ISSUE THREAD

**Issue by irot** [sequelpro/sequelpro#3171] opened 2018-09-20 03:50 UTC
Sequel Pro: 1.1.2
macOS: 10.13.6
DB: MySQL 5.7.23
Connection: SSH with password-protected key

Connecting to a database using SSH with a password-protected SSH key. The SSH key password is not saved on the keychain so must be provided each time. The initial connection works fine; press Connect, the SSH password dialog appears, I type my password in, and I'm connected. No problems.

When I finish work for the day, I just close my laptop. The next day when I check Sequel Pro, I'm prompted for the SSH password again (I assume the previous session has expired). I'm unable to type my password in as Sequel Pro just hangs with a spinning beachball and I have to force quit.

**Comment by dmoagx** [comment] 2018-09-26 21:02
Duplicate of #2503

**Closed by dmoagx** 2018-09-26 21:02 UTC
