### ISSUE TITLE
Table listing shown upside down when changing tabs

### ISSUE THREAD

**Issue by chrisminett** [sequelpro/sequelpro#3259] opened 2018-10-29 12:14 UTC
- Sequel Pro Version: Build 5418 (78067124)
- macOS Version: 10.14
- MySQL Version: 5.7.22

**Description**
When changing between multiple connection tabs (I had three to different remote hosts), the list of tables is shown upside down: the first entry is at the bottom of the window, and each individual letter is upside down (they are still in the correct order, left-to-right, so they haven't been rotated)

**Steps To Reproduce**
1. Switch from one tab to another

**Expected Behaviour**
Text should not be shown upside down

**Additional Context**
My locale is en-GB. My database connection uses utf8mb4.

![image](https://user-images.githubusercontent.com/1084019/47649081-0288a900-db74-11e8-8120-251fc2dcef77.png)

**Comment by dmoagx** [comment] 2018-10-29 14:19
Duplicate of #3214

**Closed by dmoagx** 2018-10-29 14:19 UTC
