### ISSUE TITLE
'Bad local forwarding specification' under 10.11 and SSH tunneling

### ISSUE THREAD

**Issue by alanhartless** [sequelpro/sequelpro#2164] opened 2015-07-04 18:56 UTC
Love Sequel Pro (although would love a way to filter databases as servers with a large list of databases make it a bit tricky with a dropdown).  :-) Any way off topic.  Taking 10.11 El Capitan for a spin and now Sequel pro won't connect to any of my databases with SSH tunneling.  It returns with the error like 'Bad local forwarding specification '61298/127.0.0.1/3306'  Does the same under Sequel pro 1.1 RC.  ssh -V outputs 'OpenSSH_6.7p1, LibreSSL 2.1.3'

Is there something I need to do Mac side to get it to work or is this a compatiblity issue? 

Thanks!
Alan

**Comment by alanhartless** [comment] 2015-07-04 18:59
Here's a masked version of the error details dialog:
```
Used command:  /usr/bin/ssh -v -N -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -i /Users/myuser/.ssh/id_rsa.pub -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 -p 22 user@server.com -L 61514/127.0.0.1/3306

Bad local forwarding specification ' 61514/127.0.0.1/3306'
```

**Comment by dmoagx** [comment] 2015-07-04 19:23
Duplicate of #2050. This has been fixed in the 1.1rc1 release.
Also you can filter databases in 1.1 via Database > Go to Database…

**Closed by dmoagx** 2015-07-04 19:23 UTC

**Comment by alanhartless** [comment] 2015-07-04 19:31
Oops; sorry, I should have searched.

However, I had installed Sequel Pro from https://github.com/sequelpro/sequelpro/releases/download/release-1.1-rc1/sequel-pro-1.1-RC1.dmg and I'm still getting the error.  Should I be using something else?

**Comment by alanhartless** [comment] 2015-07-04 19:33
I apologize; something clicked and now it's working :-/ Not sure if I had an open instance of the old version or what.  Thanks!

**Comment by rcdilorenzo** [comment] 2015-08-21 01:42
:+1: I had this same problem and the 1.1-rc1 solved it.

**Comment by michaeldhopkins** [comment] 2015-09-24 14:58
:+1: for the 1.1RC2. Thanks for the continued work on this!

**Comment by arezen** [comment] 2015-10-21 22:26
there is a bug with that versions, connections work, but there is an issue with BIT fields. 
Bits does not show values accurately. 

Waiting for 1.2

**Comment by realjinsong** [comment] 2015-12-01 06:59
太赞了，1.1 RC1可以连

**Comment by grayghostvisuals** [comment] 2016-03-22 23:00
:+1: :love_letter:

**Comment by vaibhav4git** [comment] 2016-06-07 05:17
Same issue faced, post helped ! Able to connect now.

**Comment by wenweih** [comment] 2016-10-11 08:12
update to latest version(1.1.2) work for me, thx.

**Comment by abcsun** [comment] 2017-02-28 04:06
It's work for me after updated to v1.1.2. 👍
