### ISSUE TITLE
Rename Database leaves an empty db with original db name

### ISSUE THREAD

**Issue by neokio** [sequelpro/sequelpro#2407] opened 2016-02-15 13:02 UTC
With Sequel Pro (nightly build 4655), connected as root via socket to MAMP PRO (3.5) ...

1) Select database (let's call it "db1") from Sequel Pro's db pulldown
2) Click "Database > Rename Database ..." from the finder menu (I forget what that's actually called)
3) Enter "db2", and click "Rename"
4) I am now on "db2", which has been successfully renamed, but ...
5) Selecting Sequel Pro's db pulldown again, I still see "db1" in there. It's empty, and has no tables. "Refresh Databases" changes nothing.

Easy enough to delete the empty one, but I believe this behavior is unintentional.

**Comment by dmoagx** [comment] 2016-02-15 15:31
Duplicate of #2334
Please search for existing issues before opening a new one.

**Closed by dmoagx** 2016-02-15 15:31 UTC
