### ISSUE TITLE
Sequal Pro Crashing on tab close

### ISSUE THREAD

**Issue by ianvdmerwe** [sequelpro/sequelpro#3377] opened 2019-02-05 13:52 UTC
- Sequel Pro Version: 1.1.2 Build 4541 (602e11a)
- macOS Version: 10.14.3
- MySQL Version: 5.7

**Description**

**Steps To Reproduce**
1. I have two tab(connections open) one to a localhost and one to stage AWS
2. When I close of one the tabs the whole program crashes.

**Expected Behaviour**
I expected the one tab to close and the program to kill the

**Additional Context**

![screenshot 2019-02-05 at 15 51 04](https://user-images.githubusercontent.com/8167821/52277664-ee67fb00-295d-11e9-9d98-57bd7f87680b.png)

![screenshot 2019-02-05 at 15 51 24](https://user-images.githubusercontent.com/8167821/52277715-02abf800-295e-11e9-918e-0619a279ccdf.png)

**Comment by lriggle-strib** [comment] 2019-02-05 15:12
Same, I get this problem too. I'm on Mojave and my build info is below:

<img width="614" alt="screen shot 2019-02-05 at 9 11 48 am" src="https://user-images.githubusercontent.com/7051012/52282490-24898880-2926-11e9-9f17-33c7f5e6f15d.png">

**Comment by waynetheisinger** [comment] 2019-02-05 16:03
Me too

**Comment by ccharlton** [comment] 2019-02-05 18:45
Killing me too. :(

**Comment by dmoagx** [comment] 2019-02-05 19:58
Duplicate of #3116

**Closed by dmoagx** 2019-02-05 19:58 UTC

**Comment by lriggle-strib** [comment] 2019-02-06 20:21
@dmoagx I'm running on the latest version I can download from the SequelPro. Is there a timeframe on when a working version of the application will be available for download?

**Comment by stychos** [comment] 2019-02-07 07:42
@lriggle-strib it seems the project is abandoned, @dmoagx sometimes active here but it's not his responsibility to schedule releases, review & merge pull requests, etc.. Sad, but project seems nearly dead. You can download a master version with two my fixes for tabs [here,](https://github.com/stychos/sequelpro/releases/tag/release-1.2-alpha) but that's not a solution.

**Comment by lriggle-strib** [comment] 2019-02-07 14:00
Well goddamnit. Thanks @stychos

**Comment by rowanbeentje** [comment] 2019-02-07 14:58
As per the thread linked above, nightly builds in which dmoagx has fixed this issue are available at  https://sequelpro.com/nightly/ .  @stychos if you'd like to discuss releases, please keep the discussion to https://github.com/sequelpro/sequelpro/issues/3034 - spreading the conversation out across lots of issues is unhelpful to the already-busy dmoagx!

**Comment by stychos** [comment] 2019-02-07 16:01
@rowanbeentje I have the impression that nobody here interested in discussions. Even the thread you linked is more than half year old and haven't any answers for the questions asked there. @dmoagx clearly stated that releases is not related to him in any way. I tried to help and pushed one pull request and one comment in related thread that are resolves two current blocking troubles but nobody reacted. What I must think?
People downloads broken application and some of them goes here and create (and will create) issues. These broken things may be fixed in the nightly builds or in the other pull requests, but those people are not able to make a build themselves, not all of them can find nightly builds link on the website.
If I am wrong and the project isn't abandoned then start to review opened pull requests, merge working things and make a release, it will be more stable than current "stable" anyway. Or at least answer the question in the thread you're linked. Thanks.

**Comment by rowanbeentje** [comment] 2019-02-07 16:10
@stychos I appreciate your pain, but I think spreading out the same discussion across unrelated threads doesn't help the situation - it just means that those with any time to give end up having to manage tickets rather than do any code work. :(

I'm not able to answer the big question you're asking - I've helped out quite a lot with Sequel Pro in the past, but haven't used it day-to-day for years and so no longer have any motivation to continue work on it, other than the odd issue comment and build fix!

**Comment by stychos** [comment] 2019-02-07 16:21
So.. you aren't maintaining the project, @abhibeckert is even more silent than you. @dmoagx can't do builds. Last commit was a month ago. There's 31 PR awaiting for review. Broken version on the main website. And you think that people will not create similar tickets spreading similar questions? :-) They will.

**Comment by rowanbeentje** [comment] 2019-02-07 17:04
Absolutely they will!  I just tried to help by pointing to the main threads for these discussions.  I appreciate you're now angry, and want to vent, I'm just trying to point out that doing so in other threads may not help.

**Comment by stychos** [comment] 2019-02-07 17:06
Sorry if you thought I'm angry on you :-) I'm not. I really appreciate all your past and current efforts. And anyway, the Sequel Pro is really best application for accessing MySQL/MariaDB databases on Mac platform. Will be more silent in the threads like this in future. Thanks.

**Comment by ccharlton** [comment] 2019-02-15 18:26
The last nightly DMG build helps, for now.
