### ISSUE TITLE
Sequel PRO connection error

### ISSUE THREAD

**Issue by Louieke** [sequelpro/sequelpro#2908] opened 2017-10-29 12:07 UTC
Hello,

I'm having trouble logging in to my Sequel PRO application, using Standard connection.

The error i keep receiving is:
"Connection failed!
Unable to connect to host 127.0.0.1, or the request timed out.
Be sure that the address is correct and that you have the necessary privileges, or try increasing the connection timeout (currently 10 seconds).
MySQL said: Can't connect to MySQL server on '127.0.0.1' (61)"

Can i find the Name / Host / Username / Password / Database / Port using MacBook Terminal?
If yes, how? :)

Hope you can help.

Many thanks in advance!

Kind regards,

Lauran

**Comment by dmoagx** [comment] 2017-10-29 12:16
"61" is "Connection refused", which most likely means there is no MySQL server listening on the IP/Port you entered.

Have you installed a MySQL server on your Mac and from where?

**Comment by mehrna** [comment] 2018-01-01 14:00
It seems tha you are using a MacBook.
My same problem were solved with this solution:

If you have installed brew version of mysql, the
n you have to run the service as your user not the root!
I mean first of all stop the service like this:
`sudo brew services stop mysql`
then start it without sudo like this:
`brew services start mysql`

**Comment by IamGiel** [comment] 2018-07-02 16:35
still getting an error.  Any ideas?

**Comment by brianmadmaxsy** [comment] 2018-07-03 05:28
Setup default password to root user
mysqladmin -u root password ‘welcome’

Test if can connect to root using newly set password
mysql -uroot -pwelcome

OR

Type in terminal> mysql -u root -p
Enter password: *********

mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'newrootpassword';

Expected output: Query OK, 0 rows affected (0.10 sec)

mysql> exit

**Comment by dmoagx** [comment] 2018-07-06 21:11
Closing since the issue reporter never responded and this issue is getting derailed…

**Closed by dmoagx** 2018-07-06 21:11 UTC
Labels: WaitingOnUser

**Comment by kingjab2010** [comment] 2018-07-11 19:38
Has anyone found a solution? Still having this problem.

**Comment by ScoutsOut** [comment] 2018-07-29 17:08
Clean install of High Sierra and I'm running into the same issue:
http://drops.cavscout.us/h19QEL

**Comment by jbatch01** [comment] 2018-08-02 21:14
Similar to @ScoutsOut, I am running into the same issue. Able to login using 'mysql -u root -p', but I still receive an error 'Socket Connection Failed'

**Comment by jbatch01** [comment] 2018-08-07 00:18
@nrollr The short solution (https://www.farces.com/wrestling-with-the-mysql-8-0-11-bear/) from the linked Stackoverflow post fixed the issue. Thanks

**Comment by nrollr** [comment] 2018-08-12 06:16
@dilendrapant That's because you don't have any other versions (other than 8.0.12) installed. You can only switch to an older version once it is installed.

**Comment by salahy** [comment] 2018-09-02 04:46
You need to enable this
<img width="484" alt="screen shot 2018-09-02 at 7 45 57" src="https://user-images.githubusercontent.com/33222524/44952265-4fa61280-ae84-11e8-9656-c33215666d25.png">

**Comment by m-willis** [comment] 2018-10-02 20:34
> where did you locate this setting pls

It's in the MAMP app settings under Servers & Services > MySQL (left sidebar for me)

**Comment by almokhtarbr** [comment] 2018-10-10 22:04
brew switch mysql@5.7
 brew services start mysql@5.7

**Comment by JellyBool** [comment] 2019-04-01 13:38
Any one who still has this issue, try this:

run this  command on your iTerm or Terminal:

```bash
sudo mysql.server start
```

If you see some errors like this:
```
/usr/local/Cellar/mariadb/10.2.11/bin/my_print_defaults: Can't read dir of '/usr/local/etc/my.cnf.d' (Errcode: 2 "No such file or directory")
Fatal error in defaults handling. Program aborted
```

Just make the dir:
```bash
mkdir /usr/local/etc/my.cnf.d
```
and then run it again:
```bash
sudo mysql.server start
``` 

Works for me.

**Comment by sheriffderek** [comment] 2019-04-24 17:42
I'm just using MAMP and Sequel PRO for the first time in a few years - and I couldn't log in. Started MAMP / tried to log in by socket with default root - but no deal. Checked brew and anything else I could. Nothing seemed to help the situation. I couldn't find that 'allow network access' setting... but I pushed this icon - and then it connected. I can't reproduce the error now. Weird... but - in case that helps anyone else:

![Screen_Shot_2019-04-24_at_10_39_24_AM](https://user-images.githubusercontent.com/2066617/56681162-964bb580-667d-11e9-932b-a12e5d8deb2b.png)

**Comment by Narayanak** [comment] 2019-04-28 09:16
Just choose second option for root password security, while you're installing mysql server software .

**Comment by nhantthai** [comment] 2019-06-12 17:00
> Just choose second option for root password security, while you're installing mysql server software .

That works

**Comment by luizpaulo165** [comment] 2019-12-04 14:31
> Setup default password to root user
> mysqladmin -u root password ‘welcome’
> 
> Test if can connect to root using newly set password
> mysql -uroot -pwelcome
> 
> OR (If you can access username root with your password)
> 
> Type in terminal> mysql -u root -p
> Enter password: *********
> 
> mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'newrootpassword';
> 
> Expected output: Query OK, 0 rows affected (0.10 sec)
> 
> mysql> exit

That works!

**Comment by EsdrasGrau** [comment] 2020-02-12 11:04
> Setup default password to root user
> mysqladmin -u root password ‘welcome’
> 
> Test if can connect to root using newly set password
> mysql -uroot -pwelcome
> 
> OR (If you can access username root with your password)
> 
> Type in terminal> mysql -u root -p
> Enter password: *********
> 
> mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'newrootpassword';
> 
> Expected output: Query OK, 0 rows affected (0.10 sec)
> 
> mysql> exit

This worked for me, user a way too long password

**Comment by roalibiten** [comment] 2021-03-29 22:55
> Setup default password to root user
> mysqladmin -u root password ‘welcome’
> 
> Test if can connect to root using newly set password
> mysql -uroot -pwelcome
> 
> OR (If you can access username root with your password)
> 
> Type in terminal> mysql -u root -p
> Enter password: *********
> 
> mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'newrootpassword';
> 
> Expected output: Query OK, 0 rows affected (0.10 sec)
> 
> mysql> exit

that works

**Comment by nilesbyzt** [comment] 2023-06-23 17:57
> Setup default password to root user mysqladmin -u root password ‘welcome’
> 
> Test if can connect to root using newly set password mysql -uroot -pwelcome
> 
> OR (If you can access username root with your password)
> 
> Type in terminal> mysql -u root -p Enter password: *********
> 
> mysql> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'newrootpassword';
> 
> Expected output: Query OK, 0 rows affected (0.10 sec)
> 
> mysql> exit

That works great!! Thanks!!
