### ISSUE TITLE
Unable to connect to local mysql server

### ISSUE THREAD

**Issue by tmertz** [sequelpro/sequelpro#2361] opened 2015-12-13 20:26 UTC
I'm running Sequel Pro 1.1 on a 2014 rMBP running El Capitan 10.10.2. I've installed MySQL via homebrew, and current version is 5.7.10. 
Sequel Pro can easily connect to a remote MySQL server running on a VPS Ubuntu 14.04 LTS. 

The error output looks like this: 

NSInvalidArgumentException

*** -[NSPlaceholderString initWithString:]: nil argument

(
	0   CoreFoundation                      0x00007fff91964ae2 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff88adbf7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff9196498d +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff8b4a9d4a -[NSPlaceholderString initWithString:] + 96
	4   Sequel Pro                          0x000000010002e6a9 -[SPDatabaseDocument setConnection:] + 384
	5   Foundation                          0x00007fff8b4f9d4b __NSThreadPerformPerform + 279
	6   CoreFoundation                      0x00007fff918745c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	7   CoreFoundation                      0x00007fff9186641c __CFRunLoopDoSources0 + 556
	8   CoreFoundation                      0x00007fff9186593f __CFRunLoopRun + 927
	9   CoreFoundation                      0x00007fff91865338 CFRunLoopRunSpecific + 296
	10  HIToolbox                           0x00007fff86509935 RunCurrentEventLoopInMode + 235
	11  HIToolbox                           0x00007fff8650976f ReceiveNextEventCommon + 432
	12  HIToolbox                           0x00007fff865095af _BlockUntilNextEventMatchingListInModeWithFilter + 71
	13  AppKit                              0x00007fff87c320ee _DPSNextEvent + 1067
	14  AppKit                              0x00007fff87ffe943 -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 454
	15  AppKit                              0x00007fff87c27fc8 -[NSApplication run] + 682
	16  AppKit                              0x00007fff87baa520 NSApplicationMain + 1176
	17  Sequel Pro                          0x0000000100001994 start + 52
)

**Comment by dmoagx** [comment] 2015-12-13 23:14
> homebrew

Duplicate of #2302

**Closed by dmoagx** 2015-12-13 23:14 UTC
