### ISSUE TITLE
JSON Field Type for MySQL

### ISSUE THREAD

**Issue by TechWood** [sequelpro/sequelpro#2661] opened 2017-01-18 22:03 UTC
There is no present way to select / update a field with a data type of JSON. Creating a table with SQL query with data type JSON works but can't be updated after without an error.

The JSON data type was added in MySQL 5.7

**Comment by dmoagx** [comment] 2017-01-19 00:51
Duplicate of #2199

**Closed by dmoagx** 2017-01-19 00:51 UTC
Labels: Duplicate
