### ISSUE TITLE
Multi-line filter

### ISSUE THREAD

**Issue by itcentralstation** [sequelpro/sequelpro#3041] opened 2018-05-01 13:01 UTC
It seems pretty basic to allow filtering on multiple fields rather than just 1 field. This is simply and AND between phrases.

**Comment by dmoagx** [comment] 2018-05-01 15:52
Duplicate of #63

Also multiple filters have been possible for ages via Table > Advanced Filter

**Closed by dmoagx** 2018-05-01 15:52 UTC
