### ISSUE TITLE
Export/Import Binary data invalid

### ISSUE THREAD

**Issue by beppert** [sequelpro/sequelpro#2337] opened 2015-11-24 18:24 UTC
When exporting tables containing column type BIT(1) using "SQL" style content export from mysql-5.5.46 on ubuntu linux and re-importing to mysql-5.5.46 on Mac OS X (el capitan) the BIT columns are incorrect (when viewed using BIN(column_name)). File produced by mysqldump and piped to the mysql command line client work correctly.

**Comment by dmoagx** [comment] 2015-11-24 19:09
Duplicate of #2254 / #2262 
Please search for existing issues before opening a new issue!

**Closed by dmoagx** 2015-11-24 19:09 UTC

**Comment by beppert** [comment] 2015-11-24 19:41
ah, sorry, did actually search but realize now the search keywords were not well chosen.
