### ISSUE TITLE
IMG

### ISSUE THREAD

**Issue by LaloEspino** [sequelpro/sequelpro#2637] opened 2016-12-24 04:04 UTC
The image on the app has a border that don't look very nice on Mac, it's not important, but you can fix the problem, for users of Apple this little things count a lot
<img width="96" alt="captura de pantalla 2016-12-23 a la s 22 05 20" src="https://cloud.githubusercontent.com/assets/23319878/21465134/ef013496-c95b-11e6-8aa1-6bd015a8007f.png">

**Comment by dmoagx** [comment] 2016-12-24 06:43
Duplicate of #2623

**Closed by dmoagx** 2016-12-24 06:43 UTC
Labels: Duplicate
