### ISSUE TITLE
SequelPro 1.1.2 keeps crashing when exit

### ISSUE THREAD

**Issue by chuahyen** [sequelpro/sequelpro#3487] opened 2019-06-15 05:06 UTC
When closing the app, it will have a crash report shown.
I am running MacOS Mojava and it crashes in that version of MacOS. It does not crash on the High Sierra version

**Comment by stuconnolly** [comment] 2019-06-15 12:37
Duplicate of #3116

**Closed by stuconnolly** 2019-06-15 12:37 UTC
Labels: Bug, Duplicate
