### ISSUE TITLE
Cannot connect to Mysql 5.6+ accounts with expired passwords

### ISSUE THREAD

**Issue by otheus** [sequelpro/sequelpro#2514] opened 2016-06-03 08:56 UTC
Please update the framework source code to handle expired passwords. See your code at https://github.com/sequelpro/sequelpro/blob/master/Frameworks/SPMySQLFramework/Source/SPMySQLConnection.m#L570 and update it w.r.t https://dev.mysql.com/doc/refman/5.6/en/password-expiration-sandbox-mode.html

**Comment by otheus** [comment] 2016-06-03 09:12
Of course, after this, you will have to detect an expired password and deal with it within the GUI at a sensible level.

**Comment by dmoagx** [comment] 2016-06-03 09:43
Duplicate of #2197 
Please search for existing issues before opening a new one!

**Closed by dmoagx** 2016-06-03 09:43 UTC
