### ISSUE TITLE
mac版 高版本mysql 打开闪退

### ISSUE THREAD

**Issue by itwangshun** [sequelpro/sequelpro#3095] opened 2018-06-25 02:54 UTC
高版本mysql 打开闪退

**Comment by wwq666** [comment] 2018-06-26 13:08
MySQL 8.0.11
sequelpro crashed when enter in database
```
NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x604000033360

(
	0   CoreFoundation                      0x00007fff3454832b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff5b6b6c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff345e0e04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff344be870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff344be238 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x00000001000587cd -[SPTablesList updateTables:] + 1338
	6   Sequel Pro                          0x00000001000469c5 -[SPDatabaseDocument _selectDatabaseAndItem:] + 454
	7   Foundation                          0x00007fff365cd1f8 __NSThread__start__ + 1197
	8   libsystem_pthread.dylib             0x00007fff5c5e8661 _pthread_body + 340
	9   libsystem_pthread.dylib             0x00007fff5c5e850d _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fff5c5e7bf9 thread_start + 13
)
```

**Comment by dmoagx** [comment] 2018-06-26 21:52
@wwq666 That is #2699

**Comment by stuconnolly** [comment] 2018-10-03 12:51
Assuming the original comment relates to the same thing as @wwq666's closing as a duplicate of #2699

**Closed by stuconnolly** 2018-10-03 12:51 UTC
Labels: WaitingOnUser
