### ISSUE TITLE
Website missing images

### ISSUE THREAD

**Issue by aeyachts99** [sequelpro/sequelpro#3073] opened 2018-06-06 07:33 UTC
https://sequelpro.com/docs/get-started/get-connected/remote
![screen shot 2018-06-06 at 08 30 50](https://user-images.githubusercontent.com/12847913/41023438-519bc496-6964-11e8-9de3-36f5b48ebe3c.png)

**Comment by stuconnolly** [comment] 2018-10-10 19:43
Duplicate of #3019

**Closed by stuconnolly** 2018-10-10 19:43 UTC
Labels: Bug, Duplicate, Website
