### ISSUE TITLE
Sequel Pro closed unexpectedly when I close one connection

### ISSUE THREAD

**Issue by fcdeveloper** [sequelpro/sequelpro#3337] opened 2018-12-19 21:54 UTC
When I have at least one or more connection open and close one of them Sequel Pro exit unexpectedly, this is very annoying and need a solution ASAP.

iMac (Retina 5K, 27-inch, Late 2015)
macOS Mojave
Version 10.14.1

**Comment by dmoagx** [comment] 2018-12-20 00:30
Yeah, and I need people to learn basic issue tracker etiquette ASAP

Duplicate of #3116

**Closed by dmoagx** 2018-12-20 00:30 UTC
