### ISSUE TITLE
Latest version update on MacOSX fails at "unpacking archive"

### ISSUE THREAD

**Issue by envieme** [sequelpro/sequelpro#2834] opened 2017-07-13 06:30 UTC
Am on Sequel Pro 1.1 Build 4468 (15800a8) on MacOSX Sierra here. When launched the software says a new version is available to download. When I accept to install the update, I see it downloading the new version fully then showing an error "unable to unpack the archive".

**Comment by dmoagx** [comment] 2017-07-13 09:44
Duplicate of #2757 
You'll have to install the update manually.

**Closed by dmoagx** 2017-07-13 09:44 UTC
