### ISSUE TITLE
Show connection tab Color when only one tab is showing?

### ISSUE THREAD

**Issue by webmaestro** [sequelpro/sequelpro#2568] opened 2016-09-20 15:48 UTC
I love the labeled/colored tabs:

https://github.com/sequelpro/sequelpro/issues/2104#issuecomment-123768435

![image](https://cloud.githubusercontent.com/assets/195184/18677400/802c7690-7f0d-11e6-9a3d-e4167196beb8.png)

But can something be done to provide the Label/Color when tabs are not displayed (_e.g._, when only one 'tab' is displayed)?

WORKAROUND:
You can see the current tab's assigned color if you open a 2nd tab--even if you don't use it.

I suspect a setting to either `'[x] Always show tabs'` in Global preferences or a setting in the New Connection dialog box to  `'[x] Always show tab'`for _this_ connection?

Screenshot Mock-up showing a RED circle in title bar for PROD connection:

![sequel-pro-single-tab-label](https://cloud.githubusercontent.com/assets/195184/18677530/e62a6038-7f0d-11e6-909f-29e3ace922a1.jpg)

Perhaps you could change the TitleBar's background color, although that probably doesn't meet Human Interface Guidelines...

Thank you for your efforts!

**Comment by willpower232** [comment] 2016-09-20 15:51
<img width="131" alt="screen shot 2016-09-20 at 16 50 38" src="https://cloud.githubusercontent.com/assets/1619102/18677958/7922d372-7f52-11e6-861c-dd3a3dcfd25b.png">

**Comment by dmoagx** [comment] 2016-09-20 18:29
Duplicate of #2565

**Closed by dmoagx** 2016-09-20 18:29 UTC

**Comment by webmaestro** [comment] 2016-09-20 19:07
Whoop! <emily-litella>Never mind!</emily-litella>

Thank you!
