### ISSUE TITLE
 "on update CURRENT_TIMESTAMP" is not shown in "Structure->Extra"

### ISSUE THREAD

**Issue by xlight** [sequelpro/sequelpro#2458] opened 2016-03-30 07:05 UTC
version: v1.1.1 build4529
mysql ver: percona mysql 5.6.27
table structure:
```
CREATE TABLE `bb_ah` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `match_id` int(10) unsigned NOT NULL,
  `maker_id` int(10) unsigned NOT NULL,
  `type` enum('pre','live') NOT NULL DEFAULT 'pre',
  `is_main` tinyint(3) NOT NULL,
  `handicap` float NOT NULL,
  `state` enum('on','paused','deleted') NOT NULL DEFAULT 'on',
  `home` float DEFAULT NULL,
  `away` float DEFAULT NULL,
  `addtime` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `lasttime` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `fk_bookmaker_idx` (`maker_id`),
  KEY `matchid-makerid-type-handicap` (`match_id`,`maker_id`,`type`,`handicap`)
) ENGINE=InnoDB AUTO_INCREMENT=519577 DEFAULT CHARSET=utf8mb4;
```

displayed in Sequel Pro:
![image](https://cloud.githubusercontent.com/assets/77911/14134301/c15700da-f688-11e5-8e0c-c3e5b1a0f7e5.png)

the column lasttime

**Comment by dmoagx** [comment] 2016-03-30 19:58
Duplicate of #2315

**Closed by dmoagx** 2016-03-30 19:58 UTC
