### ISSUE TITLE
Specify SSH port number

### ISSUE THREAD

**Issue by jdogg17** [sequelpro/sequelpro#2063] opened 2015-02-05 19:39 UTC
It would be great if it was possible to specify the port to be used when connecting to a db via ssh. Many custom networks use ports other than 22.

**Comment by willpower232** [comment] 2015-02-05 19:42
![screen shot 2015-02-05 at 19 41 23](https://cloud.githubusercontent.com/assets/1619102/6067786/fe953b92-ad6e-11e4-9e7e-4451828a7f0a.png)

Is there something stopping you from seeing the lowest field there?

**Comment by jdogg17** [comment] 2015-02-05 19:51
Hrm…for some reason it wasn’t showing but when I clicked Socket then back to SSH it appeared. 

Thanks for getting back so quickly!

Jordan Aasen
Developer
thenumber.ca
@numbercreative
250.590.7663

**Comment by dmoagx** [comment] 2015-02-05 21:51
Duplicate of #1859

**Closed by dmoagx** 2015-02-05 21:51 UTC
