### ISSUE TITLE
Rework Table Content View

### ISSUE THREAD

**Issue by sequelpro** [sequelpro/sequelpro#935] opened 2013-11-09 04:31 UTC
Issue imported from Google Code: https://code.google.com/p/sequel-pro/issues/detail?id=935
Reporter:schlabbe...@gmail.com Date:2011-01-05 07:37:06 Status:Accepted

This bug will serve as a collection of all bugs that are related to a more advanced table content view.

**Comment by fulldecent** [comment] 2017-03-28 01:15
Recommend close. Not actionable.

**Comment by abhibeckert** [comment] 2017-03-28 01:38
Duplicate of #2313

**Closed by abhibeckert** 2017-03-28 01:38 UTC
Labels: Duplicate, Enhancement
