### ISSUE TITLE
Vagrant tunnel overwrites db?

### ISSUE THREAD

**Issue by linkingarts** [sequelpro/sequelpro#2368] opened 2016-01-03 02:07 UTC
Tonight I had the most bizarre issue.

In my Web app running on Vagrant box (MariaDb), connected via a tunnel using SequelPro. I'd register a user via GUI, and they would disappear and reappear in the db over and over again, even with me doing nothing, every few minutes. This happened both with data as well as with schema changes.

Once I quite SequelPro, all good.

I tested in a private browsing window (Chrome) just to make sure it wasn't my session. Same issue.

Mac OS Yosemite, MariaDb.

**Comment by dmoagx** [comment] 2016-01-03 15:31
Which exact version of Sequel Pro?
Is this reproducible?
Have you looked at the query log?

**Comment by linkingarts** [comment] 2016-01-03 17:10
Sequel Pro 1.1 build 4499 (0bac177)

there's nothing unusual in the console. What seems to be happening is that
if I've got the Vagrant box running and I connect via Sequel Pro, the state
of the db itself seems to get out of sync. So one minute I'll read the db,
and recent changes will show. Then I'll refresh view in a minute or two,
and it will reflect what was in the Vagrant db before I connected. This
applies to both data and schema changes.

On Sun, Jan 3, 2016 at 9:31 AM, Max Lohrmann <notifications@github.com>
wrote:

> Which exact version of Sequel Pro?
> Is this reproducible?
> Have you looked at the query log?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelpro/sequelpro/issues/2368#issuecomment-168505731>
> .
>



-- 

Peter Jacobson
Linking Arts
www.linkingarts.com
www.wedocracy.com
www.petejacobson.com
twitter.com/petejacobson
twitter.com/linkingarts
+1 504 264 6006 / VoIP
+1 504 503 2491 / mobile
peterjacobson / Skype

people + technology + art

**Comment by rowanbeentje** [comment] 2016-01-04 02:45
Sequel Pro won't be running queries without them also showing in the query log (View menu > Show Console).

The problem sounds very strange - it's definitely possible to load a schema/content view in Sequel Pro, wait, edit a row, and then have "invalid" changes applied because it's been changed elsewhere in the meantime - but we also try to minimise this by scoping changes rather than rewriting the whole thing where possible (so only one column will be edited, etc).

Nothing should be re-applying changes on a refresh...

**Comment by linkingarts** [comment] 2016-01-04 03:18
it's freaking weird. Having a lot of trouble chasing down the actual cause,
but nobody else on the team is having this issue - and no one else is using
Sequel Pro so maybe it is? Can't guarantee it though, it could be something
w/vagrant or even MariaDb.

Will try to box out some time to have a closer look at what queries are
running, or re-running. Thanks folks

On Sun, Jan 3, 2016 at 8:45 PM, Rowan Beentje <notifications@github.com>
wrote:

> Sequel Pro won't be running queries without them also showing in the query
> log (View menu > Show Console).
>
> The problem sounds very strange - it's definitely possible to load a
> schema/content view in Sequel Pro, wait, edit a row, and then have
> "invalid" changes applied because it's been changed elsewhere in the
> meantime - but we also try to minimise this by scoping changes rather than
> rewriting the whole thing where possible (so only one column will be
> edited, etc).
>
> Nothing should be re-applying changes on a refresh...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sequelpro/sequelpro/issues/2368#issuecomment-168568560>
> .
>



-- 

Peter Jacobson
Linking Arts
www.linkingarts.com
www.wedocracy.com
www.petejacobson.com
twitter.com/petejacobson
twitter.com/linkingarts
+1 504 264 6006 / VoIP
+1 504 503 2491 / mobile
peterjacobson / Skype

people + technology + art

**Comment by dmoagx** [comment] 2016-07-31 19:59
Closing after no feedback from user.

**Closed by dmoagx** 2016-07-31 19:59 UTC
Labels: WaitingOnUser
