### ISSUE TITLE
Connection details window is not aligned

### ISSUE THREAD

**Issue by VMBindraban** [sequelpro/sequelpro#2940] opened 2017-12-01 08:35 UTC
I don't know how it happened but suddenly this window is no longer aligned in the center.
It tends to 'stick' on the right on startup.

It started to happen on `Sierra` and it continued to happen on `High Sierra`.

Resizing the application doesn't work nor does restarting it.

Sequel Pro 1.1.2.
MacOS High Sierra 10.13.1.

My colleague doesn't have this issue (same versions).

![image](https://user-images.githubusercontent.com/2269400/33474282-3d69b4ce-d67a-11e7-8b78-0d76295a727b.png)

**Comment by dmoagx** [comment] 2017-12-01 22:46
Duplicate of #2412

**Closed by dmoagx** 2017-12-01 22:46 UTC
