### ISSUE TITLE
Error adding password to Keychain

### ISSUE THREAD

**Issue by gy0624ww** [sequelpro/sequelpro#3070] opened 2018-06-04 02:12 UTC
An error occured while trying to add the password to your Keychain. Repairing your Keychain might resolve this, but if it doesn't please report it to the Sequel Pro team, supplying the error code -25293.

i can't save my db password

**Comment by dmoagx** [comment] 2018-06-04 21:08
Have you tried restarting your Mac?

**Comment by dmoagx** [comment] 2018-07-06 20:28
Duplicate of #2900

**Closed by dmoagx** 2018-07-06 20:28 UTC
Labels: WaitingOnUser
