### ISSUE TITLE
Foreign keys in UI table not jumping correctly

### ISSUE THREAD

**Issue by pjebs** [sequelpro/sequelpro#3411] opened 2019-03-14 01:48 UTC
Build: 5438(664)

In the UI table for a particular DB Table, I have a foreign key. I can see the little grey jump arrow.
When I click on the arrow, it goes to the correct UI table but doesn't jump to the correct row.

The official stable version worked correctly.

**Comment by dmoagx** [comment] 2019-03-14 19:01
duplicate of #2792

**Closed by dmoagx** 2019-03-14 19:01 UTC
