### ISSUE TITLE
Export of utf8mb4 db/table(s) has SET NAMES utf8 which corrupts data on import

### ISSUE THREAD

**Issue by ctyler-liquidfish** [sequelpro/sequelpro#3142] opened 2018-08-23 16:20 UTC
In Sequel Pro 1.1.2, when I export my database or a table, importing again loses some emoji data. After investigation I solved the issue by changing the line
`/*!40101 SET NAMES utf8 */;`
to
`/*!40101 SET NAMES utf8mb4 */;`
but I haven't found a way to make Sequel Pro do this automatically, which means I have to remember to edit all my database backups or else potentially lose data.

Is this a bug or a setting issue?

**Comment by dmoagx** [comment] 2018-09-11 20:54
This is closely related to #2321 so I'll mark it as duplicate.

Duplicate of #2321

**Closed by dmoagx** 2018-09-11 20:54 UTC
