### ISSUE TITLE
Mac 10.14 system crashed

### ISSUE THREAD

**Issue by pengleelove** [sequelpro/sequelpro#3269] opened 2018-11-01 03:39 UTC
Mac OS 10.14. Open multiple TAB tabs and crash when closed. Please check

**Comment by tang2606** [comment] 2018-11-01 07:35
me too .

**Comment by larsjanssen6** [comment] 2018-11-01 08:45
me too.

**Comment by jbrooksuk** [comment] 2018-11-01 08:49
You can confirm this by:

1. Open multiple tabs
2. Close one of the tabs
3. See crash

**Comment by mitoop** [comment] 2018-11-01 09:31
The build version with last commit slove this problem. 
Also , the sequel official at last build in the [Nightly Builds](https://sequelpro.com/test-builds)

**Comment by phmunhoz** [comment] 2018-11-01 14:52
This issue is a duplicate of #3116. Someone may close it?

**Closed** 2018-11-01 16:40 UTC
