### ISSUE TITLE
Duplicating Row Causes Down-Scroll

### ISSUE THREAD

**Issue by ultracasual** [sequelpro/sequelpro#2525] opened 2016-06-27 06:13 UTC
Duplicating a row and then clicking on any other entry will cause the cursor to automatically select the final entry on table.

**Comment by dmoagx** [comment] 2016-07-12 20:20
Can't reproduce with 1.1.2.

**Comment by dmoagx** [comment] 2016-09-11 03:26
Closing after no feedback from user.

**Closed by dmoagx** 2016-09-11 03:26 UTC
Labels: WaitingOnUser
