### ISSUE TITLE
Cannot connect with user using sha2 authentication plugin.

### ISSUE THREAD

**Issue by dannick223** [sequelpro/sequelpro#3152] opened 2018-09-07 13:52 UTC
I'm using Laravels php artisan to migrate my tables, and therefore I have to use sha2 authentication otherwise it throws me the following error: MySQL error 2006: mysql server has gone away. However when I am using sha2, I cant connect to my user using Sequel Pro (I did try using socket, same results though).
<img width="452" alt="screen shot 2018-09-07 at 15 41 59" src="https://user-images.githubusercontent.com/40644972/45222346-9ba5ec80-b2b4-11e8-84a5-f4ea67177bbe.png">

<img width="422" alt="screen shot 2018-09-07 at 15 40 20" src="https://user-images.githubusercontent.com/40644972/45222270-5f728c00-b2b4-11e8-828b-b055e42d9924.png">

When I change my user to mysql_native_password I am able to login using Sequel Pro and select any database, insert data and everything else, however when I try msqli_ping() on my laravel project, all it returns is shown below and as expected am unable to migrate using the specified user. 
<img width="670" alt="screen shot 2018-09-07 at 15 47 00" src="https://user-images.githubusercontent.com/40644972/45222600-48806980-b2b5-11e8-911d-6cc719f3bd2e.png">
The only temporary fix I see possible, would be to have 2 mysql accounts to handle 1. Sequel Pro and 2. the migrations from the Laravel project. 

EDIT: I am using Sequel Pro test build & mysql  Ver 8.0.12 for osx10.13 on x86_64 (Homebrew), 
<img width="195" alt="screen shot 2018-09-07 at 15 54 39" src="https://user-images.githubusercontent.com/40644972/45223014-5a164100-b2b6-11e8-818f-e3cdeb166dc7.png">

**Comment by dmoagx** [comment] 2018-09-07 15:12
Duplicate of #3037

**Closed by dmoagx** 2018-09-07 15:12 UTC
