### ISSUE TITLE
When there is multiple tabs, the app crash when I close a tab.

### ISSUE THREAD

**Issue by detectiveHLH** [sequelpro/sequelpro#3456] opened 2019-04-25 08:07 UTC
- Sequel Pro Version:  Sequal Pro 1.1.2 build 4541(602e11a)
- macOS Version:  Mojave 10.14.44(18E226)
- MySQL Version: 5.6

**Description**
When I create multiple tabs and then I close any tab, the app will crash

**Steps To Reproduce**
1. Create multiple tabs.
2. Close anyone, the app will crash.

**Expected Behaviour**
The tab should be closed normally.

**Additional Context**
none

![Screen Shot 2019-04-25 at 4 06 53 PM](https://user-images.githubusercontent.com/24632081/56719886-2cfa9e00-6774-11e9-83a6-5e5861447517.png)

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff7213a6a9 objc_msgSend + 41
1   com.apple.AppKit              	0x00007fff44c4203c -[NSTableView _uncachedNumberOfRows] + 105
2   com.apple.AppKit              	0x00007fff44c41f3f -[_NSTableRowHeightStorage numberOfRows] + 62
3   com.apple.AppKit              	0x00007fff44c496ff -[NSTableView _totalHeightOfTableView] + 282
4   com.apple.AppKit              	0x00007fff44c48bff -[NSTableView _minimumFrameSize] + 77
5   com.apple.AppKit              	0x00007fff44c481c7 -[NSTableView tile] + 438
6   com.apple.AppKit              	0x00007fff44c74739 -[NSTableView bounds] + 122
7   com.apple.AppKit              	0x00007fff44f305c8 tableViewFocusRingType + 119
8   com.apple.AppKit              	0x00007fff44dd27b4 -[NSTableView(NSTableViewNonARC) designatedFocusRingView] + 99
9   com.apple.AppKit              	0x00007fff44cd55b3 -[NSView noteFocusRingMaskChanged] + 31
10  com.apple.AppKit              	0x00007fff44bcad51 -[NSView setNeedsDisplayInRect:] + 701
11  com.apple.WebKitLegacy        	0x00007fff55aebbb6 -[NSView(WebSetNeedsDisplayInRect) _web_setNeedsDisplayInRect:] + 486
12  com.apple.AppKit              	0x00007fff44bca981 -[NSView setNeedsDisplay:] + 79
13  com.apple.AppKit              	0x00007fff44bcc2ec -[NSView(NSInternal) _invalidateEffectiveVibrantBlendingStyle] + 119
14  com.apple.AppKit              	0x00007fff44c549b4 -[NSTableView _removeBackgroundView] + 156
15  com.apple.AppKit              	0x00007fff44c548ff -[NSTableView viewWillMoveToSuperview:] + 64
16  com.apple.AppKit              	0x00007fff44bfaf64 -[NSView _setSuperview:] + 213
17  com.apple.AppKit              	0x00007fff44d51588 -[NSTableView _setSuperview:] + 324
18  com.apple.AppKit              	0x00007fff44bfe72f -[NSView removeFromSuperview] + 146
19  com.apple.AppKit              	0x00007fff44ce5083 -[NSView removeFromSuperviewWithoutNeedingDisplay] + 36
20  com.apple.AppKit              	0x00007fff44c8339b -[NSView _finalize] + 1056
21  com.apple.AppKit              	0x00007fff44c82df4 -[NSView dealloc] + 209
22  com.apple.AppKit              	0x00007fff44d59883 -[NSClipView dealloc] + 164
23  libobjc.A.dylib               	0x00007fff721420c8 objc_object::sidetable_release(bool) + 268
24  libobjc.A.dylib               	0x00007fff7213d47c (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 710
25  com.apple.CoreFoundation      	0x00007fff474d160a _CFAutoreleasePoolPop + 22
26  com.apple.Foundation          	0x00007fff4976de02 -[NSAutoreleasePool drain] + 144
27  com.apple.AppKit              	0x00007fff44b7df1f -[NSApplication run] + 810
28  com.apple.AppKit              	0x00007fff44b6d3f0 NSApplicationMain + 777
29  com.sequelpro.SequelPro       	0x0000000100002454 start + 52

**Comment by ckissi** [comment] 2019-04-25 09:46
experiencing the exactly same issue

**Comment by anup4ranium** [comment] 2019-04-25 10:44
Same issue from many months now :(

**Comment by sekrantz** [comment] 2019-04-25 15:19
Before a contributor closes this for being off-topic (which it is, see #3116 ), can they clarify where we can update to more recent stable releases for Mac OS?  Currently I've been using https://sequelpro.com/test-builds is that correct or are those still just nightly/test builds?

**Comment by dmhendricks** [comment] 2019-04-25 17:31
Agree with @sekrantz re: note in the readme - it may help reduce the dupes (?). For anyone stumbling across this, it looks like this was fixed back in 3477d22387, but I can verify that it is fixed in the latest build (664a46cd7c at the time of this post): https://sequelpro.com/test-builds

Tested on three different Mojave installs.

**Comment by dmoagx** [comment] 2019-04-25 19:21
So you are saying the issue template mentioning this crash as the very first thing when you try to create a new issue is not enough?
<img width="781" alt="Bildschirmfoto 2019-04-25 um 21 06 46 087" src="https://user-images.githubusercontent.com/5793864/56761664-37ca2880-679e-11e9-846e-1d9e64d9e2e4.png">

Or the issue homepage mentioning it in a huge box right at the top?
<img width="715" alt="Bildschirmfoto 2019-04-25 um 21 11 20 158" src="https://user-images.githubusercontent.com/5793864/56761887-c2128c80-679e-11e9-8bb4-bb60d2b3467f.png">

Or it being the top message on Twatter?
<img width="897" alt="Bildschirmfoto 2019-04-25 um 21 12 20 889" src="https://user-images.githubusercontent.com/5793864/56761941-e8d0c300-679e-11e9-9cbe-a8c5a3533725.png">

Honestly, everyone who creates duplicates at this point is either a literal illiterate or incapable of even following the most basic issue tracker etiquette. I'm sick of this!

@sekrantz The most recent "stable release" is 1.1.2. Test builds are exactly what their name suggests.
What you want to use depends on what makes you personally feel better. Neither comes with any guarantee of any kind.
The only thing I can say is that the test builds have - **at this very moment in time when I'm writing these lines** - much less bugs than the release. But in the future anything can happen…

Also Duplicate of #3116

**Closed by dmoagx** 2019-04-25 19:21 UTC

**Comment by detectiveHLH** [comment] 2019-04-26 01:46
@dmoagx My bad. Actually, I have searched the keyword 'crash' in issues before I created this, but it looks like I have only searched in the open issue. 

And after that, I use XCode to rebuild the app. It will solve the problem.
