### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zhangmiaowater** [sequelpro/sequelpro#3047] opened 2018-05-08 01:21 UTC
sequel pro will crash when connect to mysql8.0.11, mac OSX 10.13.4

**Comment by Kinjinc** [comment] 2018-05-08 10:54
the same problem

NSInvalidArgumentException

-[_NSInlineData isEqualToString:]: unrecognized selector sent to instance 0x6040004583f0

(
	0   CoreFoundation                      0x00007fff4bd9f00b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff72986c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4be37cd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff4bd153f0 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff4bd14db8 _CF_forwarding_prep_0 + 120
	5   Sequel Pro                          0x000000010002fce3 -[SPDatabaseDocument setDatabases:] + 783
	6   Sequel Pro                          0x000000010002f2a9 -[SPDatabaseDocument setConnection:] + 610
	7   Foundation                          0x00007fff4de40125 __NSThreadPerformPerform + 334
	8   CoreFoundation                      0x00007fff4bd375a1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	9   CoreFoundation                      0x00007fff4bdf135c __CFRunLoopDoSource0 + 108
	10  CoreFoundation                      0x00007fff4bd1a040 __CFRunLoopDoSources0 + 208
	11  CoreFoundation                      0x00007fff4bd194bd __CFRunLoopRun + 1293
	12  CoreFoundation                      0x00007fff4bd18d23 CFRunLoopRunSpecific + 483
	13  HIToolbox                           0x00007fff4b030e26 RunCurrentEventLoopInMode + 286
	14  HIToolbox                           0x00007fff4b030b96 ReceiveNextEventCommon + 613
	15  HIToolbox                           0x00007fff4b030914 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	16  AppKit                              0x00007fff492fbf5f _DPSNextEvent + 2085
	17  AppKit                              0x00007fff49a91b4c -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
	18  AppKit                              0x00007fff492f0d6d -[NSApplication run] + 764
	19  AppKit                              0x00007fff492bff1a NSApplicationMain + 804
	20  Sequel Pro                          0x0000000100002454 start + 52
)

**Comment by dmoagx** [comment] 2018-05-08 13:06
Duplicate of #2699

**Closed by dmoagx** 2018-05-08 13:06 UTC
