### ISSUE TITLE
Incorrect links in documentation

### ISSUE THREAD

**Issue by pseudokool** [sequelpro/sequelpro#3101] opened 2018-07-02 11:50 UTC
Local fs links active on https://sequelpro.com/docs/contribute/get-involved:

```
"check out " links to file:///Users/abhi/Downloads/www.sequelpro.com/docs/Source_Code.html
```

```
"source code" links to file:///Users/abhi/Downloads/www.sequelpro.com/docs/Source_Code.html
```

```
"chat to the developers" links to file:///Users/abhi/Downloads/www.sequelpro.com/get-involved.html#chat-to-the-developers
```

**Comment by dmoagx** [comment] 2018-07-02 19:39
Duplicate of #2715

**Closed by dmoagx** 2018-07-02 19:39 UTC
