### ISSUE TITLE
SequelPro exporter generates invalid SQL syntax and misses essential table settings

### ISSUE THREAD

**Issue by coredumperror** [sequelpro/sequelpro#3225] opened 2018-10-10 23:40 UTC
I've been having this problem on and off for a while, but I finally thought up a way to properly categorize and report it.

Here's the opening stanza of a SequalPro export of a MySQL 5.6.40 database:

```
# ************************************************************
# Sequel Pro SQL dump
# Version 4541
#
# http://www.sequelpro.com/
# https://github.com/sequelpro/sequelpro
#
# Host: REDACTED (MySQL 5.6.40-log)
# Database: REDACTED
# Generation Time: 2018-10-10 23:03:58 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table batch
# ------------------------------------------------------------

DROP TABLE IF EXISTS `batch`;

CREATE TABLE "batch" (
  "bid" int(10) unsigned NOT NULL COMMENT 'Primary Key: Unique batch ID.',
  "token" varchar(64) CHARACTER SET ascii NOT NULL COMMENT 'A string token generated against the current user''s session id and the batch id, used to ensure that only the user who submitted the batch can effectively access it.',
  "timestamp" int(11) NOT NULL COMMENT 'A Unix timestamp indicating when this batch was submitted for processing. Stale batches are purged at cron time.',
  "batch" longblob COMMENT 'A serialized array containing the processing data for the batch.',
  PRIMARY KEY ("bid"),
  KEY "token" ("token")
);
```

Here's a dump of the same database using `mysqldump`:

```
-- MySQL dump 10.13  Distrib 5.1.73, for redhat-linux-gnu (x86_64)
--
-- Host: REDACTED    Database: REDACTED
-- ------------------------------------------------------
-- Server version	5.6.40-log

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `batch`
--

DROP TABLE IF EXISTS `batch`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `batch` (
  `bid` int(10) unsigned NOT NULL COMMENT 'Primary Key: Unique batch ID.',
  `token` varchar(64) CHARACTER SET ascii NOT NULL COMMENT 'A string token generated against the current user''s session id and the batch id, used to ensure that only the user who submitted the batch can effectively access it.',
  `timestamp` int(11) NOT NULL COMMENT 'A Unix timestamp indicating when this batch was submitted for processing. Stale batches are purged at cron time.',
  `batch` longblob COMMENT 'A serialized array containing the processing data for the batch.',
  PRIMARY KEY (`bid`),
  KEY `token` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Stores details about batches (processes that run in…';
/*!40101 SET character_set_client = @saved_cs_client */;
```

The first one gives me this error when I try to load it into my dev database (it's complaining about those quotation marks around the table and key names. Remove them and the SQL runs fine):

```
[ERROR in query 9] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"batch" (
  "bid" int(10) unsigned NOT NULL COMMENT 'Primary Key: Unique batch I' at line 1
Import cancelled!
```

The second SQL dump works just fine. Also note that only the second one sets the `Engine` and `DEFAULT CHARSET` settings, which are _pretty important_.

What could be causing SequelPro to screw up the quotes and miss those essential table settings? It's quite baffling, especially since it doesn't happen to every database I export from. Only this particular one, as well as a few others that I haven't exported from in a while, and are now gone, so I can't retest them.

I'm using the exporter's default settings.

**Comment by dmoagx** [comment] 2018-10-11 09:33
Duplicate of #2955 

> What could be causing SequelPro to screw up the quotes and miss those essential table settings? 

The SQL Mode of the server is set to a crappy default value.

**Closed by dmoagx** 2018-10-11 09:33 UTC

**Comment by coredumperror** [comment] 2018-10-11 18:46
Oh wow, I have no memory of posting that issue. Thanks for the reminder. :)
