### ISSUE TITLE
Cannot login as root to remote ssh host

### ISSUE THREAD

**Issue by fulldecent** [sequelpro/sequelpro#2495] opened 2016-05-04 19:46 UTC
The error is:

> MySQL said: Access denied for user 'root'@'localhost' (using password: NO)

However, I am able to ssh into the host and run `mysql` from the command line to access the server.

**Comment by dmoagx** [comment] 2016-05-04 21:37
Essentially a duplicate of #2466 (and others before that...)

**Closed by dmoagx** 2016-05-04 21:37 UTC

**Comment by fulldecent** [comment] 2016-05-04 21:57
Thanks for the clarification, I have updated the wording.

Please reopen the issue so I can create a bounty using Bountysource.

**Comment by dmoagx** [comment] 2016-05-04 22:40
I don't like that idea.

Starting an SSH client from Sequel Pro is one thing – implementing SFTP to try and read a file is a whole different world of pain.
This would require a lot of code, which would (given our experience with SSH) probably have a lot of compatibility issues until it really works and in the end only be useful to very very few users.

**Comment by abhibeckert** [comment] 2016-05-09 06:26
I agree with dmoagx - we're not going to update sequel pro to read config files on the server to determine the password. It's excessively complicated and slow and too specific to how your server has been setup.

Please don't try to crowdsource this, since we probably would not accept the pull request anyway.
