### ISSUE TITLE
User is too long error with 32 char long users

### ISSUE THREAD

**Issue by carbontwelve** [sequelpro/sequelpro#3196] opened 2018-10-02 09:35 UTC
I have an application that creates users and databases with 32 character long names. MySQL is happy to oblige with the task and Sequel Pro will open the databases and work fine with them.

However when I click the Users button I initially get a popup saying "user is too long.":

![image](https://user-images.githubusercontent.com/464699/46340788-6465f980-c62e-11e8-8bbb-ef12d8ff5bcc.png)

Clicking ok then displays another popup saying "Multiple validation errors occurred.":

![image](https://user-images.githubusercontent.com/464699/46340842-865f7c00-c62e-11e8-8609-43622a7a590c.png)

This second popup displays a number of times, each time clicking ok opens another identical popup; after a number of clicks the Users pane opens but nothing can be done with clicking the apply button resulting in the following error popup:

![image](https://user-images.githubusercontent.com/464699/46340918-c888bd80-c62e-11e8-8c9f-ab53d0d5be69.png)

This is happening in 1.1.2 build 4541:

![image](https://user-images.githubusercontent.com/464699/46340959-eb1ad680-c62e-11e8-9ca5-01aa1cd7cd40.png)

**Comment by stuconnolly** [comment] 2018-10-02 09:46
Duplicate of #2198

**Closed by stuconnolly** 2018-10-02 09:46 UTC

**Comment by carbontwelve** [comment] 2018-10-02 10:13
For anyone else finding this issue its fixed in snapshot build available from https://sequelpro.com/test-builds. At time of writing thats build 5224.
