### ISSUE TITLE
Can't connect to local database

### ISSUE THREAD

**Issue by nmoncur** [sequelpro/sequelpro#3106] opened 2018-07-05 21:05 UTC
Thought I'd create my own issue, but same bug as  https://github.com/sequelpro/sequelpro/issues/3104

Sequel Pro 1.1.2 on Mac Version 10.13.5. Can't connect to any of my local databases. Also running Sql Version 8.0.11 via Homebrew

![image](https://user-images.githubusercontent.com/21003466/42347923-a83d8656-8064-11e8-9595-826c5f1d1483.png)

**Comment by nmoncur** [comment] 2018-07-05 21:05
I am also unable to submit the feedback form, with or without notes & an email address. It times out

**Comment by dmoagx** [comment] 2018-07-06 08:22
There is zero necessity to open a new issue when you know it is a duplicate of another issue.
Especially not when you know that the other issue report is without any value because it contains no details we could use to fix it and you still post something equally lacking!

All this does is creating administrative work for us which means less time will be spent on fixing issues.

Duplicate of #3104

**Closed by dmoagx** 2018-07-06 08:22 UTC
