### ISSUE TITLE
List of favourite / frequently used tables

### ISSUE THREAD

**Issue by aramkarapetian** [sequelpro/sequelpro#2822] opened 2017-06-18 15:27 UTC
hi guys,
would be great to have favourites in table list. will check and see if I can code this feature.
cheers

**Comment by artaex** [comment] 2017-06-20 08:36
What's wrong with the alphabetical order?

**Comment by parangdae** [comment] 2017-06-20 08:44
If there are many tables, it is hard to find the table. and more scroll, more search

**Comment by elincyar** [comment] 2017-08-08 14:50
I agree that this would be a very useful feature. When you are working with only a few tables in a database of over 400 tables it would be great to easily switch between a couple of tables without constantly searching for the table you need.

**Comment by stuconnolly** [comment] 2018-10-08 22:29
Duplicate of #1391

**Closed by stuconnolly** 2018-10-08 22:29 UTC
Labels: Enhancement
