### ISSUE TITLE
Sort when searching databases

### ISSUE THREAD

**Issue by HongbinZhu** [sequelpro/sequelpro#3156] opened 2018-09-10 21:09 UTC
Hey team, love sequelpro, awesome work! Just a little thing that I think could improve user experience ;) In our use case, we have a lot of databases(1000+), when we switch databases, we will use Shift+Cmd+D to search for databases. It works fine, one thing is when I type the whole database name, it's not showing that database in high priority. For example, we have "aabb" and "ab" databases, when I type "ab", it's showing "aabb" as the first one, since it also has all the characters "a", and "b", and "aa" prefix comes first. I know it's not a bug, but I would prefer when searching, we should give those whole matches a high priority. What do you think guys? Still, awesome work!

**Comment by dmoagx** [comment] 2018-09-11 09:05
Duplicate of #2344

**Closed by dmoagx** 2018-09-11 09:05 UTC
