### ISSUE TITLE
Sequel Pro crashes everytime i close a tab

### ISSUE THREAD

**Issue by tsndr** [sequelpro/sequelpro#3359] opened 2019-01-17 07:48 UTC
It's been almost 4 months since the release of macOS Mojave and still there is no update for Sequel Pro. I'm using this software on a daily basis, i also donated a while ago because i love using it. But those crashes are super annoying, please fix it.

**Comment by dmoagx** [comment] 2019-01-17 08:06
Duplicate of #3116 
Also #3034

**Closed by dmoagx** 2019-01-17 08:06 UTC

**Comment by tsndr** [comment] 2019-01-17 08:08
Then fix it already.
