### ISSUE TITLE
Sequel pro is too slow in performance

### ISSUE THREAD

**Issue by rbncha** [sequelpro/sequelpro#2990] opened 2018-03-02 05:26 UTC
Hi,

Recently Sequel Pro is way slow opening the app, selecting db, tables, moving around tabs of table, querying. Am I only one facing this ? Here is screen record to show how it is : https://www.useloom.com/share/02f5c762217b4dbf865832d06a3a09da

Thanks

**Comment by dmoagx** [comment] 2018-03-02 06:13
You most likely have a huge query in your query history. Try clearing it.

**Comment by rbncha** [comment] 2018-03-02 10:14
Yeah! clearing history made it faster again. But I wished those query history be there.

Thankx @dmoagx

**Comment by dmoagx** [comment] 2018-03-02 19:28
Duplicate of #687

**Closed by dmoagx** 2018-03-02 19:29 UTC
Labels: WaitingOnUser
