### ISSUE TITLE
Se cerro inesperadamente

### ISSUE THREAD

**Issue by xxtochoxx** [sequelpro/sequelpro#3258] opened 2018-10-26 15:35 UTC
Process:               Sequel Pro [2459]
Path:                  /Applications/Sequel Pro.app/Contents/MacOS/Sequel Pro
Identifier:            com.sequelpro.SequelPro
Version:               1.1.2 (4541)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Sequel Pro [2459]
User ID:               1595600033

Date/Time:             2018-10-26 10:33:57.953 -0500
OS Version:            Mac OS X 10.14 (18A391)
Report Version:        12
Anonymous UUID:        AD20EA00-54A9-31E3-33EB-5E2161B5004F
<img width="968" alt="captura de pantalla 2018-10-26 a la s 10 35 33" src="https://user-images.githubusercontent.com/7839541/47576764-e6ce9a00-d90a-11e8-9efe-dfa9af08b208.png">

**Comment by dmoagx** [comment] 2018-10-26 21:19
English only please.

**Comment by kylex** [comment] 2018-10-28 18:19
I too am seeing this issue of Sequel Pro closing unexpectedly since upgrading my Mac to 10.14
It happens frequently.

Sometimes it is random, but it happens consistently whenever I close a tab (the whole thing shuts down and produces an error). It doesn't matter whether I click on the 'x' to close the tab, or use cmd+W. Unexpected closure happens.

**Comment by stuconnolly** [comment] 2018-10-28 21:56
Duplicate of #3116

**Closed by stuconnolly** 2018-10-28 21:56 UTC
Labels: WaitingOnUser
