### ISSUE TITLE
Empty passwords in Mysql 5.7

### ISSUE THREAD

**Issue by natrim** [sequelpro/sequelpro#2571] opened 2016-09-22 09:15 UTC
Hello,

after i installed new server i noticed that SequelPro no longer sees paswords and is unable to change them.

Seems like mysql 5.7 changed syntax for SET PASSWORD.

**Comment by dmoagx** [comment] 2016-09-22 15:55
Duplicate of #2418

**Closed by dmoagx** 2016-09-22 15:55 UTC
