### ISSUE TITLE
Icon issue on retina display

### ISSUE THREAD

**Issue by lamberttraccard** [sequelpro/sequelpro#2656] opened 2017-01-14 13:56 UTC
There is an issue with the icon on retina display.

<img width="158" alt="capture d ecran 2017-01-14 a 14 53 11" src="https://cloud.githubusercontent.com/assets/4272598/21955335/7e682e6e-da69-11e6-9116-334dc709945d.png">

**Comment by stuconnolly** [comment] 2017-01-14 18:35
Duplicate of #2623

**Closed by stuconnolly** 2017-01-14 18:35 UTC
Labels: Duplicate
