### ISSUE TITLE
ui going to a mistake status after using desktop management software like Mosaic

### ISSUE THREAD

**Issue by xiangbohua** [sequelpro/sequelpro#3394] opened 2019-02-25 05:45 UTC
- Sequel Pro Version: Build 5438
- macOS Version: 10.14.3
- MySQL Version:any version

**Description**
I'm using some desktop management software like Mosaic. After i was drag Sequel from a external monitor to other the UI was going to a worry state. The detail panel was just like been scrolled and been covered by the top panel.
I'm going to find other app.
So said.

**Steps To Reproduce**
1.open app
2.connect to a database
3.drag app form a big monitor to build in monitor or a small one
4.trigger the resize of UI
5.done. you will find the detail panel will be covered by the top panel

**Expected Behaviour**
all ui be normal

**Additional Context**
none

Please see the image.the left window was the worry state and the right one was the normal state
![default](https://user-images.githubusercontent.com/10529889/53317254-e4ef0480-3905-11e9-9d93-71d302099f36.png)

**Comment by dmoagx** [comment] 2019-02-26 23:56
Duplicate of #3091

**Closed by dmoagx** 2019-02-26 23:56 UTC
