### ISSUE TITLE
Sequel Pro keeps craching and cannot submit the report

### ISSUE THREAD

**Issue by dvlancer** [sequelpro/sequelpro#3436] opened 2019-04-02 01:31 UTC
Sending crash report times out each time after Sequel Pro crashes and attempts to send the report

https://monosnap.com/file/JaZ844ZlKRcdI48t8oYysVFpwHNoN4

v Sequel Pro 1.1.2 - MacOS 10.14.3

**Comment by dmoagx** [comment] 2019-04-02 19:04
Duplicate of #3226

**Closed by dmoagx** 2019-04-02 19:04 UTC
