### ISSUE TITLE
Closing the window when a connection is lost is not intuitive or helpful

### ISSUE THREAD

**Issue by Phrohdoh** [sequelpro/sequelpro#2821] opened 2017-06-17 11:44 UTC
When a connection is lost you get the dialog stating so and can click "close connection".

Doing so closes the current Sequel Pro window which means your queries are lost too unless you saved them beforehand.

Ideally you could still edit the text area but not execute the queries.

**Comment by dmoagx** [comment] 2017-06-29 20:22
Duplicate of #1158

**Closed by dmoagx** 2017-06-29 20:22 UTC
